"""Deutsche Wortlisten fuer das Data Poisoning (siehe browser/decoy.py)."""

CITIES = [
    "berlin", "hamburg", "münchen", "köln", "frankfurt", "stuttgart", "düsseldorf",
    "leipzig", "dortmund", "essen", "bremen", "dresden", "hannover", "nürnberg",
    "duisburg", "bochum", "wuppertal", "bielefeld", "bonn", "münster", "karlsruhe",
    "mannheim", "augsburg", "wiesbaden", "gelsenkirchen", "mönchengladbach", "braunschweig",
    "chemnitz", "kiel", "aachen", "halle", "magdeburg", "freiburg", "krefeld",
    "lübeck", "oberhausen", "erfurt", "mainz", "rostock", "kassel", "hagen",
    "hamm", "saarbrücken", "mülheim", "potsdam", "ludwigshafen", "oldenburg",
    "leverkusen", "osnabrück", "solingen", "heidelberg", "herne", "neuss", "darmstadt",
    "paderborn", "regensburg", "ingolstadt", "würzburg", "fürth", "wolfsburg",
    "offenbach", "ulm", "heilbronn", "pforzheim", "göttingen", "bottrop", "trier",
    "recklinghausen", "bremerhaven", "koblenz", "bergisch gladbach", "erlangen",
    "remscheid", "siegen", "hildesheim", "jena", "salzgitter", "cottbus", "gütersloh",
    "kaiserslautern", "schwerin", "zwickau", "gera", "iserlohn", "düren", "memmingen",
    "kempten", "konstanz", "passau", "bamberg", "bayreuth", "landshut", "rosenheim",
    "straubing", "ansbach", "coburg", "aschaffenburg", "schweinfurt",
    "wien", "graz", "linz", "salzburg", "innsbruck", "klagenfurt", "villach",
    "wels", "st. pölten", "dornbirn", "steyr", "feldkirch", "bregenz", "leonding",
    "klosterneuburg", "leoben", "krems", "traun", "amstetten", "lustenau",
    "zürich", "genf", "basel", "bern", "lausanne", "winterthur", "luzern",
    "st. gallen", "lugano", "biel", "thun", "köniz", "la chaux-de-fonds",
    "schaffhausen", "fribourg", "chur", "vernier", "neuchâtel", "uster", "sion",
    "emmen", "zug", "kriens", "rapperswil", "arbon", "frenkendorf",
    "paris", "lyon", "marseille", "toulouse", "nizza", "nantes", "strasbourg",
    "montpellier", "bordeaux", "lille", "rennes", "reims", "le havre", "grenoble",
    "dijon", "angers", "nîmes", "villeurbanne", "saint-étienne", "toulon",
    "london", "manchester", "birmingham", "liverpool", "leeds", "glasgow",
    "sheffield", "edinburgh", "bristol", "cardiff", "belfast", "nottingham",
    "leicester", "coventry", "bradford", "newcastle", "sunderland", "oxford",
    "cambridge", "brighton", "exeter", "york", "plymouth", "aberdeen",
    "madrid", "barcelona", "sevilla", "valencia", "bilbao", "málaga", "murcia",
    "palma", "alicante", "valladolid", "vigo", "gijón", "zaragoza",
    "rom", "mailand", "neapel", "turin", "palermo", "genua", "bologna",
    "florenz", "venedig", "catania", "bari", "verona", "messina", "padova",
    "triest", "brescia", "parma", "livorno", "cagliari", "ferrara", "pisa",
    "amsterdam", "rotterdam", "den haag", "utrecht", "eindhoven", "groningen",
    "tilburg", "almere", "breda", "nijmegen", "arnhem", "haarlem", "zaandam",
    "brüssel", "antwerpen", "gent", "lüttich", "brügge", "namur", "mons",
    "warschau", "krakau", "lodz", "breslau", "posen", "danzig", "kattowitz",
    "lublin", "bialystok", "bydgoszcz", "torun", "rzeszow", "opole",
    "prag", "brünn", "ostrava", "pilsen", "liberec", "olomouc", "ceske budejovice",
    "budapest", "bratislava", "bukarest", "sofia", "zagreb", "belgrad",
    "laibach", "sarajevo", "skopje", "tirana", "podgorica", "pristina",
    "stockholm", "göteborg", "malmö", "uppsala", "västerås", "örebro",
    "linköping", "helsingborg", "norrköping", "jönköping", "umeå", "lund",
    "kopenhagen", "aarhus", "odense", "aalborg", "esbjerg", "randers", "kolding",
    "oslo", "bergen", "trondheim", "stavanger", "drammen", "fredrikstad", "tromsø",
    "helsinki", "tampere", "turku", "espoo", "vantaa", "oulu", "lahti",
    "reykjavik", "lissabon", "porto", "braga", "coimbra", "funchal", "setúbal",
    "moskau", "st. petersburg", "nowosibirsk", "jekaterinburg", "nischni nowgorod",
    "kazan", "tscheljabinsk", "omsk", "samara", "ufa", "krasnojarsk",
    "kiew", "charkiw", "dnipro", "odessa", "lwiw", "mykolajiw", "donezk",
    "istanbul", "ankara", "izmir", "bursa", "adana", "konya", "antalya", "gaziantep",
    "athen", "thessaloniki", "patras", "heraklion", "larissa",
    "new york", "los angeles", "chicago", "houston", "phoenix", "philadelphia",
    "san antonio", "san diego", "dallas", "san jose", "austin", "jacksonville",
    "san francisco", "columbus", "charlotte", "indianapolis", "seattle", "denver",
    "washington", "boston", "nashville", "baltimore", "louisville", "portland",
    "las vegas", "memphis", "atlanta", "miami", "minneapolis", "new orleans",
    "toronto", "montreal", "vancouver", "calgary", "edmonton", "ottawa",
    "winnipeg", "quebec", "saskatoon", "kitchener",
    "mexiko-stadt", "guadalajara", "monterrey", "puebla", "tijuana",
    "buenos aires", "córdoba", "rosario", "mendoza", "tucumán",
    "santiago", "valparaíso", "concepción",
    "são paulo", "rio de janeiro", "brasília", "salvador", "fortaleza",
    "belo horizonte", "manaus", "curitiba", "recife", "porto alegre",
    "bogotá", "medellín", "cali", "barranquilla", "cartagena",
    "lima", "arequipa", "trujillo", "chiclayo",
    "caracas", "maracaibo", "quito", "guayaquil",
    "kairo", "alexandria", "gizeh", "shubra el-kheima",
    "casablanca", "rabat", "fes", "marrakesch", "tanger",
    "tunis", "algier", "tripolis", "khartum", "addis abeba",
    "lagos", "kano", "ibadan", "abuja", "port harcourt",
    "kinshasa", "lubumbashi", "nairobi", "mombasa", "kampala",
    "daressalam", "johannesburg", "kapstadt", "durban", "pretoria",
    "akkra", "dakar", "abidjan", "bamako", "ouagadougou", "lomé", "conakry",
    "dubai", "abu dhabi", "riad", "dschidda", "mekka", "medina", "kuwait-stadt",
    "doha", "manama", "muskat", "teheran", "isfahan", "mashhad", "täbris",
    "bagdad", "basra", "mossul", "amman", "beirut", "damaskus", "aleppo",
    "tel aviv", "jerusalem", "haifa",
    "karatschi", "lahore", "faisalabad", "rawalpindi", "islamabad", "multan",
    "neu-delhi", "mumbai", "bengaluru", "kolkata", "chennai", "hyderabad",
    "pune", "ahmedabad", "surat", "jaipur", "lucknow", "kanpur", "nagpur",
    "indore", "bhopal", "ludhiana", "agra", "nashik", "varanasi",
    "dhaka", "chittagong", "sylhet",
    "kathmandu", "colombo", "yangon", "mandalay",
    "bangkok", "chiang mai", "pattaya", "phuket",
    "singapur", "kuala lumpur", "penang", "johor bahru",
    "jakarta", "surabaya", "bandung", "medan", "semarang", "makassar",
    "manila", "quezon city", "davao", "cebu",
    "ho-chi-minh-stadt", "hanoi", "haiphong", "da nang",
    "phnom penh", "vientiane", "naypyidaw",
    "peking", "shanghai", "guangzhou", "shenzhen", "chengdu", "chongqing",
    "tianjin", "wuhan", "xi'an", "hangzhou", "suzhou", "nanjing",
    "harbin", "shenyang", "qingdao", "zhengzhou", "dongguan", "foshan",
    "hongkong", "macau", "taipeh", "kaohsiung", "taichung", "tainan",
    "seoul", "busan", "incheon", "daegu", "daejeon", "gwangju",
    "tokio", "osaka", "nagoya", "sapporo", "fukuoka", "kobe", "kyoto",
    "kawasaki", "saitama", "hiroshima", "sendai", "kitakyushu",
    "ulaan-baatar", "pjöngjang",
    "sydney", "melbourne", "brisbane", "perth", "adelaide", "gold coast",
    "canberra", "wollongong", "hobart", "darwin",
    "auckland", "wellington", "christchurch", "hamilton",
    "port moresby", "suva", "nuku'alofa", "apia",
    "havanna", "santo domingo", "san juan", "port-au-prince", "kingston",
    "panama-stadt", "tegucigalda", "managua", "guatemala-stadt",
    "san salvador",
    "accra", "lome", "cotonou", "niamey", "ndjamena", "bangui",
    "libreville", "brazzaville", "luanda", "lusaka", "harare",
    "antananarivo", "maputo", "lilongwe", "gaborone", "windhoek",
    "maseru", "mbabane", "djibouti", "mogadischu", "asmara",
    "valletta", "tiflis", "eriwan", "baku",
    "taschkent", "almaty", "bishkek", "duschanbe", "aschgabat",
    "nur-sultan", "minsk", "riga", "tallinn", "vilnius",
    "kischinau", "chisinau",
]

TEMPLATES = [
    "wetter {}",
    "wetter {} heute",
    "wetter {} morgen",
    "wetter {} wochenende",
    "wetter {} 7 tage",
    "wetter {} aktuell",
    "wetter {} nächste woche",
    "wetter {} übermorgen",
    "temperatur {} heute",
    "niederschlag {} morgen",
    "hotels {} günstig",
    "hotels {} zentrum",
    "hotels {} mit frühstück",
    "hotels {} letzte minute",
    "hotel {} buchen",
    "hostel {}",
    "ferienwohnung {} mieten",
    "airbnb {}",
    "unterkunft {} günstig",
    "pension {}",
    "camping {} umgebung",
    "restaurants {}",
    "beste restaurants {}",
    "günstige restaurants {}",
    "vegane restaurants {}",
    "restaurant {} innenstadt",
    "pizza {} liefern",
    "sushi {} empfehlung",
    "brunch {} sonntag",
    "frühstück {}",
    "türkisches restaurant {}",
    "italienisches restaurant {}",
    "griechisches restaurant {}",
    "asiatisches restaurant {}",
    "burger {} gut",
    "ramen {} empfehlung",
    "café {}",
    "café {} mit wlan",
    "bäckerei {}",
    "eiscreme {}",
    "flüge nach {} günstig",
    "flüge {} buchen",
    "billigflüge {}",
    "zug nach {} preis",
    "zugverbindung {}",
    "bahnfahrt nach {}",
    "bus nach {} kosten",
    "fernbus {}",
    "mietwagen {}",
    "auto mieten {}",
    "parkplätze {} innenstadt",
    "parken {} kostenlos",
    "öffentliche verkehrsmittel {}",
    "u-bahn {}",
    "tram {} linien",
    "stadtbus {}",
    "fahrplan {}",
    "flughafen {} terminal",
    "taxi {} bestellen",
    "uber {}",
    "sehenswürdigkeiten {}",
    "top sehenswürdigkeiten {}",
    "museen {}",
    "museum {} öffnungszeiten",
    "stadtführung {}",
    "parks {}",
    "strände {} schönste",
    "wandern {} umgebung",
    "ausflugsziele {} umgebung",
    "natur {} erkunden",
    "burg {}",
    "schloss {}",
    "altstadt {} bilder",
    "turm {}",
    "zoo {}",
    "aquarium {}",
    "events {} heute",
    "events {} wochenende",
    "konzerte {} dieses wochenende",
    "konzert {} tickets",
    "festival {}",
    "festivals {} sommer 2026",
    "veranstaltungen {} august",
    "flomarkt {}",
    "weihnachtsmarkt {}",
    "stadtfest {}",
    "kino {} programm heute",
    "theater {} spielplan",
    "oper {} karten",
    "nightlife {}",
    "bars {}",
    "beste bars {}",
    "clubs {}",
    "club {} eintritt",
    "cocktailbar {}",
    "biergarten {}",
    "rooftopbar {}",
    "pub {} empfehlung",
    "wohnung mieten {}",
    "wohnung kaufen {}",
    "immobilien {}",
    "mietwohnung {} zentrum",
    "haus kaufen {} umgebung",
    "wg-zimmer {}",
    "wohnungssuche {} tipps",
    "mietpreise {} 2026",
    "jobs {}",
    "stellenangebote {}",
    "arbeit suchen {}",
    "ausbildung {}",
    "praktikum {}",
    "uni {}",
    "universität {} bewerbung",
    "hochschule {}",
    "studium {} kosten",
    "schule {}",
    "gymnasium {}",
    "kindergarten {} platz",
    "kita {} kosten",
    "arzt {}",
    "zahnarzt {}",
    "krankenhaus {}",
    "notaufnahme {}",
    "apotheke {} geöffnet",
    "apotheke {} notdienst",
    "tierarzt {}",
    "fitnessstudio {} preis",
    "gym {} angebot",
    "schwimmbad {}",
    "hallenbad {}",
    "freibad {}",
    "yoga {}",
    "crossfit {}",
    "coworking space {}",
    "coworking {} preis",
    "bibliothek {} öffnungszeiten",
    "stadtbibliothek {}",
    "einwohnerzahl {}",
    "bevölkerung {}",
    "stadtplan {}",
    "postleitzahl {}",
    "bezirke {}",
    "geschichte {}",
    "sehenswert {}",
    "urlaub {} tipps",
    "urlaub {} 2026",
    "reise {} günstig",
    "reisebericht {}",
    "reiseziel {}",
    "{} tourismus",
    "{} reiseführer",
    "{} empfehlungen tourist",
    "{} insider tipps",
    "{} reisetipps",
    "{} urlaub mit kindern",
    "{} sehenswürdigkeiten kostenlos",
    "{} einkaufen",
    "{} shopping zentrum",
    "{} outlet",
    "{} markt wochenmarkt",
    "{} flohmarkt wann",
    "{} straßenbahn",
    "{} stau aktuell",
    "{} webcam",
    "{} bilder fotos",
    "{} karte lageplan",
    "{} umzug kosten",
    "umzug nach {} erfahrungen",
    "leben in {} erfahrungen",
    "wohnen in {} vor und nachteile",
    "wohnkosten {}",
    "lebenshaltungskosten {}",
    "beste stadtviertel {} zum wohnen",
    "sicherheit {}",
    "kriminalitätsrate {}",
    "{} sprache einheimische",
    "{} trinkwasser leitungswasser",
    "{} klima wann beste reisezeit",
    "{} beste reisezeit",
    "{} sehenswürdigkeiten top 10",
    "{} umgebung tagesausflug",
    "{} tipps für einen tag",
    "{} was muss man gesehen haben",
    "günstig essen {} tipps",
    "street food {}",
    "lokale spezialitäten {}",
    "starbucks {}",
    "mcdonalds {} geöffnet",
    "lidl {} filiale",
    "aldi {} in der nähe",
    "ikea {} öffnungszeiten",
    "mediamarkt {}",
    "saturn {}",
    "dm {} filiale",
    "tankstelle {} offen",
    "ladestationen elektroauto {}",
    "fahrrad leihen {}",
    "e-scooter {}",
    "bootsverleih {}",
    "kajakverleih {}",
    "reisebüro {}",
    "fremdenverkehrsamt {}",
    "touristinfo {}",
    "stadtbesichtigung {} mit guide",
    "{} fotospots instagram",
    "{} abends was tun",
    "{} familienfreundlich tipps",
    "{} hundefreundlich restaurants",
    "{} barrierefreiheit info",
    "{} regenwetter was tun",
    "{} bei hitze was tun",
    "{} mit dem fahrrad erkunden",
    "{} walking tour kostenlos",
    "tagesausflug von münchen nach {}",
    "tagesausflug von berlin nach {}",
    "tagesausflug von zürich nach {}",
    "entfernung berlin {}",
    "entfernung münchen {}",
    "entfernung zürich {}",
    "wie weit ist {} von berlin",
    "anreise {} mit dem auto",
    "anreise {} mit dem zug",
    "{} besuchen lohnt sich",
    "{} wert für geld urlaub",
    "{} budget urlaub möglich",
    "{} luxushotels top",
    "{} boutique hotel",
    "{} jugendherberge preis",
    "{} wlan überall verfügbar",
    "{} sim karte kaufen",
    "{} tipps für studenten",
    "{} tipps für alleinreisende",
    "{} romantisch wochenendtrip",
    "{} junggesellenabschied ideen",
    "{} team event firmenausflug",
    "{} veranstaltungshalle konzerte",
    "{} football stadium",
    "{} fussballstadion tour",
    "{} laufstrecke park",
    "{} radweg",
    "bahn {} stau",
    "flug {} verspätung",
    "{} stadteil empfehlenswert",
    "{} hipster viertel",
    "{} günstig schlafen",
    "airbnb {} tipps",
    "{} co living",
    "{} hostel bestes",
    "{} nightbus plan",
    "{} fernbahnhof adresse",
    "{} zentralbahnhof parken",
    "{} flughafen parkgebühren",
]

STANDALONE = [
    "python liste sortieren",
    "python dictionary comprehension",
    "python for schleife beispiel",
    "python klasse erstellen",
    "python try except",
    "python string formatierung",
    "python virtualenv einrichten",
    "python requests library tutorial",
    "python pandas dataframe filtern",
    "python matplotlib diagramm erstellen",
    "python csv datei lesen",
    "python json parsen",
    "python regex beispiel",
    "python generator funktion",
    "python async await erklärung",
    "python unittest tutorial",
    "python pip pakete installieren",
    "python requirements.txt erstellen",
    "javascript fetch api tutorial",
    "javascript promises erklärt",
    "javascript array methoden",
    "javascript es6 features",
    "typescript generics beispiel",
    "react hooks tutorial",
    "react usestate erklärung",
    "react router dom v6",
    "next.js tutorial 2026",
    "vue.js anfänger guide",
    "node.js express server erstellen",
    "css flexbox guide",
    "css grid layout tutorial",
    "css dark mode implementieren",
    "html semantische elemente",
    "git branch zusammenführen",
    "git rebase vs merge",
    "git konflikt lösen",
    "linux befehle anfänger",
    "linux permissions erklärung",
    "linux cron job einrichten",
    "linux bash script beispiel",
    "linux prozess beenden",
    "linux netzwerk prüfen",
    "docker container erstellen",
    "docker compose tutorial",
    "docker image bauen",
    "kubernetes grundlagen",
    "postgresql abfragen tutorial",
    "mysql tabelle erstellen",
    "sqlite datenbank python",
    "mongodb grundlagen",
    "rest api design best practices",
    "graphql vs rest vergleich",
    "websocket tutorial",
    "ssh key erstellen",
    "nginx konfigurieren",
    "raspberry pi projekt ideen",
    "arduino anfänger projekt",
    "esp32 wifi verbinden",
    "3d drucker kaufen empfehlung 2026",
    "3d druck filament vergleich",
    "cura slicer einstellungen",
    "solidworks tutorial deutsch",
    "fusion 360 grundlagen",
    "bestes smartphone 2026",
    "samsung galaxy s25 test",
    "iphone 17 vergleich",
    "pixel 9 pro erfahrungen",
    "smartphone akku verbessern tipps",
    "smartphone kamera vergleich 2026",
    "laptop kaufen empfehlung 2026",
    "laptop für studenten günstig",
    "gaming laptop test 2026",
    "macbook air m3 test",
    "ultrabook vergleich 2026",
    "externe festplatte kaufen",
    "nas server heimnetz",
    "wlan router test 2026",
    "mesh wlan system vergleich",
    "monitor kaufen 2026",
    "4k monitor empfehlung",
    "gaming monitor 144hz",
    "mechanische tastatur vergleich",
    "gaming maus test",
    "gaming headset empfehlung 2026",
    "kopfhörer kaufen empfehlung",
    "noise cancelling kopfhörer test",
    "bluetooth lautsprecher vergleich",
    "smart tv kaufen 2026",
    "oled tv empfehlung",
    "soundbar test 2026",
    "e-reader vergleich 2026",
    "tablet kaufen 2026",
    "smartwatch empfehlung 2026",
    "fitness tracker vergleich",
    "e-bike kaufen 2026",
    "e-bike test günstig",
    "elektroauto kaufen 2026",
    "elektroauto reichweite vergleich",
    "ladenetz deutschland ausbau",
    "tesla model 3 erfahrungen",
    "vw id.4 test 2026",
    "solaranlage balkon kosten",
    "photovoltaik anlage kosten 2026",
    "wärmepumpe kosten installation",
    "wallbox installieren kosten",
    "brot selber backen anfänger",
    "sauerteig brot rezept",
    "pasta selber machen",
    "risotto grundrezept",
    "kimchi selber machen",
    "ramen selber kochen",
    "hummus rezept",
    "granola selber machen",
    "vegane ernährung anfänger",
    "proteinreiche rezepte muskelaufbau",
    "abnehmen mit intervallfasten tipps",
    "kalorien berechnen täglich",
    "makros berechnen fitness",
    "smoothie rezepte gesund",
    "fermentieren einsteiger",
    "batch cooking woche vorbereiten",
    "meal prep ideen einfach",
    "gefrier-tipps lebensmittel",
    "welche lebensmittel nicht einfrieren",
    "gewürze kombinieren guide",
    "wie lange hält joghurt",
    "frittieren ohne friteuse",
    "sous vide einstieg",
    "rückenübungen zuhause",
    "bauchmuskelübungen anfänger",
    "krafttraining zuhause plan",
    "ganzkörpertraining ohne geräte",
    "dehnübungen morgens",
    "yoga für anfänger",
    "meditation einstieg tipps",
    "schlaf verbessern tipps",
    "schlafdauer optimal",
    "einschlafen schneller tipps",
    "bluthochdruck senken tipps",
    "cholesterin senken ernährung",
    "rückenschmerzen lindern tipps",
    "kopfschmerzen ursachen",
    "vitamin d mangel symptome",
    "magnesium wofür wichtig",
    "omega 3 quellen vegan",
    "immunsystem stärken hausmittel",
    "erkältung schnell loswerden",
    "burnout symptome erkennen",
    "stress abbauen techniken",
    "angst bewältigen techniken",
    "konzentration verbessern tipps",
    "produktivität erhöhen methoden",
    "pomodoro technik erklärung",
    "gtd methode einführung",
    "habit tracking app empfehlung",
    "journaling anfangen tipps",
    "bücher für mehr produktivität",
    "beste bücher 2026 empfehlung",
    "hörbücher kostenlos deutsch",
    "podcast empfehlungen deutsch 2026",
    "netflix neue serien 2026",
    "netflix serie empfehlung",
    "amazon prime serien empfehlung",
    "disney plus serie 2026",
    "beste kinofilme 2026",
    "action film empfehlung 2026",
    "thriller serie empfehlung",
    "sci-fi serie deutsch empfehlung",
    "dokumentation netflix empfehlung",
    "anime anfänger empfehlung",
    "manga lesen kostenlos legal",
    "spotify playlist rock deutsch",
    "neue musik entdecken 2026",
    "gitarre lernen anfänger",
    "gitarren app kostenlos",
    "ukulele lernen tipps",
    "klavier lernen app",
    "beatmaking software anfänger",
    "fotografie anfänger tipps",
    "kamera einstellungen verstehen",
    "compositing tipps lightroom",
    "bildbearbeitung kostenlos",
    "instagram foto tipps",
    "youtube kanal starten 2026",
    "video schneiden anfänger",
    "davinci resolve tutorial deutsch",
    "obs studio einrichten",
    "podcast aufnehmen ausrüstung",
    "zeichnen lernen anfänger",
    "digitales zeichnen tablet empfehlung",
    "procreate tutorial deutsch",
    "blender 3d tutorial anfänger",
    "gaming pc zusammenstellen 2026",
    "beste spiele 2026 pc",
    "elden ring tipps anfänger",
    "minecraft server erstellen",
    "minecraft modpack installieren",
    "steam spiele günstig kaufen",
    "best free to play spiele 2026",
    "fps verbessern pc tipps",
    "controller auf pc verwenden",
    "brettspiel empfehlung familienabend",
    "brettspiele für erwachsene 2026",
    "kartenspiel regeln erklärt",
    "aktien anfänger deutschland",
    "etf investieren anfänger",
    "depot eröffnen vergleich",
    "bitcoin kaufen sicher",
    "kryptowährungen 2026 trend",
    "inflation absichern investment",
    "steuererklärung selbst machen",
    "steuern sparen tipps arbeitnehmer",
    "elster steuererklärung tutorial",
    "riester rente sinnvoll 2026",
    "betriebliche altersvorsorge erklärung",
    "rentenversicherung punkte berechnen",
    "haushaltsbuch führen app",
    "sparen tipps für alltag",
    "energiekosten senken zuhause",
    "strom sparen haushalt tipps",
    "heizung richtig einstellen sparen",
    "kredit aufnehmen tipps",
    "zinsen vergleichen kredit",
    "mietrecht mieter rechte",
    "mietvertrag prüfen worauf achten",
    "nebenkostenabrechnung prüfen",
    "versicherungen welche brauche ich",
    "haftpflichtversicherung vergleich",
    "berufsunfähigkeit versicherung sinnvoll",
    "krankenkasse wechseln tipps",
    "private krankenversicherung vergleich",
    "auslandskrankenversicherung test",
    "pflanzen pflegen anfänger",
    "zimmerpflanzen wenig licht",
    "zimmerpflanzen luftreinigend",
    "sukkulenten pflegen tipps",
    "balkongarten anlegen",
    "hochbeet anlegen anleitung",
    "kompost anlegen richtig",
    "regenwasser sammeln anleitung",
    "garten winterfest machen",
    "rasenpflege tipps",
    "unkraut entfernen ohne chemie",
    "möbel restaurieren anleitung",
    "tapete entfernen tipps",
    "wand streichen richtig",
    "laminat verlegen anleitung",
    "fliesen kleben anleitung",
    "ikea möbel umbauen ideen",
    "wohnung einrichten tipps klein",
    "kleine wohnung optimieren",
    "aufbewahrungssystem zuhause tipps",
    "kleiderschrank organisieren",
    "haushalt putzen plan",
    "putzmittel selber machen",
    "flecken entfernen tipps",
    "waschmaschine reinigen",
    "spülmaschine richtig einräumen",
    "kühlschrank richtig organisieren",
    "mikrowelle reinigen einfach",
    "schimmel bekämpfen hausmittel",
    "beziehung kommunikation verbessern",
    "konflikt lösen beziehung tipps",
    "freundschaften pflegen tipps",
    "soziale angst überwinden",
    "selbstbewusstsein aufbauen",
    "grenzen setzen lernen",
    "gewohnheiten ändern wissenschaft",
    "dopamin fasten was ist das",
    "glücklicher leben tipps",
    "dankbarkeit üben tipps",
    "akzeptanz und commitment therapie",
    "stoizismus alltag anwenden",
    "philosophie einsteiger bücher",
    "quantenphysik einfach erklärt",
    "klimawandel fakten 2026",
    "erneuerbare energien deutschland 2026",
    "weltall neuigkeiten 2026",
    "mars mission aktuell",
    "james webb teleskop entdeckungen",
    "schwarzes loch erklärt einfach",
    "evolution theorie zusammenfassung",
    "dinosaurier neueste forschung",
    "wikinger geschichte zusammenfassung",
    "zweiter weltkrieg ursachen",
    "kalter krieg zusammenfassung",
    "antikes rom zusammenfassung",
    "ägypten pyramiden geheimnisse",
    "sprache lernen schnell tipps",
    "englisch verbessern tipps",
    "spanisch lernen app",
    "japanisch lernen anfänger",
    "anki flashcards guide",
    "sprachkurs empfehlung 2026",
    "duolingo alternativen",
    "auslandsjahr planen tipps",
    "au pair werden informationen",
    "freiwilliges soziales jahr ausland",
    "bundeswehr bewerbung ablauf",
    "zivildienst informationen",
    "ausbildung oder studium vergleich",
    "duales studium vorteile nachteile",
    "bachelor master unterschied",
    "bafög berechnen antrag stellen",
    "studentenjobs bestbezahlt",
    "nebenjob als schüler tipps",
    "freelance starten tipps deutschland",
    "kleingewerbe anmelden kosten",
    "selbstständig machen schritt für schritt",
    "wie lange dauert lieferung amazon",
    "amazon retoure einleiten",
    "paypal käuferschutz nutzen",
    "phishing mail erkennen",
    "online sicherheit tipps 2026",
    "vpn sinnvoll 2026",
    "passwort manager empfehlung",
    "2-faktor authentifizierung einrichten",
    "datenschutz internet verbessern",
    "browser extension empfehlung datenschutz",
    "ad blocker empfehlung 2026",
    "linux distro vergleich anfänger",
    "ubuntu vs fedora unterschied",
    "windows 11 tipps tricks",
    "macos tipps produktivität",
    "icloud speicher voll was tun",
    "google fotos alternative",
    "obsidian notizen app tutorial",
    "notion tipps anfänger",
    "chatgpt tipps besser nutzen",
    "ki tools produktivität 2026",
    "midjourney prompts deutsch",
    "stable diffusion lokal installieren",
    "llm lokal betreiben",
    "ollama tutorial",
    "wie macht man sauerteig starter",
    "warum schlafen wir überhaupt",
    "was hilft gegen prokrastination",
    "wie funktioniert eine wärmepumpe",
    "warum ist der himmel blau",
    "wie entsteht ein gewitter",
    "warum werden wir älter",
    "was ist das grundeinkommen",
    "wie funktioniert das internet",
    "was ist machine learning einfach",
    "wie sicher ist cloud storage",
    "bester zeitpunkt aktien kaufen",
    "passives einkommen ideen 2026",
    "dividendenstrategie erklärung",
    "gold kaufen sinnvoll",
]
