"""Zusaetzliche deutsche Staedtenamen fuer das Data Poisoning."""

CITIES = [
    "berlin",
    "hamburg",
    "münchen",
    "köln",
    "frankfurt am main",
    "stuttgart",
    "düsseldorf",
    "dortmund",
    "essen",
    "leipzig",
    "bremen",
    "dresden",
    "hannover",
    "nürnberg",
    "duisburg",
    "bochum",
    "wuppertal",
    "bielefeld",
    "bonn",
    "münster",
    "karlsruhe",
    "mannheim",
    "augsburg",
    "wiesbaden",
    "gelsenkirchen",
    "mönchengladbach",
    "braunschweig",
    "chemnitz",
    "kiel",
    "aachen",
    "halle",
    "magdeburg",
    "freiburg im breisgau",
    "krefeld",
    "lübeck",
    "oberhausen",
    "erfurt",
    "mainz",
    "rostock",
    "kassel",
    "hagen",
    "hamm",
    "saarbrücken",
    "mülheim an der ruhr",
    "potsdam",
    "ludwigshafen",
    "oldenburg",
    "leverkusen",
    "osnabrück",
    "solingen",
    "heidelberg",
    "herne",
    "neuss",
    "darmstadt",
    "paderborn",
    "regensburg",
    "ingolstadt",
    "würzburg",
    "fürth",
    "wolfsburg",
    "offenbach",
    "ulm",
    "heilbronn",
    "göttingen",
    "pforzheim",
    "bottrop",
    "trier",
    "recklinghausen",
    "bremerhaven",
    "reutlingen",
    "koblenz",
    "bergisch gladbach",
    "erlangen",
    "moers",
    "siegen",
    "hildesheim",
    "salzgitter",
    "cottbus",
    "kaiserslautern",
    "gütersloh",
    "schwerin",
    "witten",
    "iserlohn",
    "düren",
    "zwickau",
    "wilhelmshaven",
    "ratingen",
    "hanau",
    "velbert",
    "gladbeck",
    "jena",
    "minden",
    "marl",
    "lünen",
    "remscheid",
    "dessau",
    "hameln",
    "troisdorf",
    "flensburg",
    "bamberg",
    "bayreuth",
    "aschaffenburg",
    "landshut",
    "rosenheim",
    "kempten",
    "memmingen",
    "straubing",
    "passau",
    "weiden",
    "amberg",
    "coburg",
    "hof",
    "schweinfurt",
    "ansbach",
    "neustadt an der weinstraße",
    "speyer",
    "worms",
    "frankenthal",
    "zweibrücken",
    "pirmasens",
    "bad kreuznach",
    "andernach",
    "bingen am rhein",
    "ingelheim",
    "bad homburg",
    "dillenburg",
    "gießen",
    "fulda",
    "marburg",
    "lahn",
    "limburg",
    "wetzlar",
    "friedberg",
    "viernheim",
    "langen",
    "rüsselsheim",
    "mörfelden-walldorf",
    "dietzenbach",
    "dreieich",
    "rödermark",
    "seligenstadt",
    "schwäbisch hall",
    "ellwangen",
    "aalen",
    "göppingen",
    "geislingen",
    "heidenheim an der brenz",
    "biberach",
    "ravensburg",
    "friedrichshafen",
    "konstanz",
    "villingen-schwenningen",
    "rottweil",
    "tuttlingen",
    "singen",
    "offenburg",
    "lahr",
    "freiburg",
    "rheinfelden",
    "lörrach",
    "weil am rhein",
    "achern",
    "bühl",
    "rastatt",
    "bruchsal",
    "ettlingen",
    "waiblingen",
    "schorndorf",
    "schwäbisch gmünd",
    "esslingen",
    "nürtingen",
    "kirchheim unter teck",
    "metzingen",
    "balingen",
    "horb am neckar",
    "calw",
    "mühlacker",
    "vaihingen an der enz",
    "bietigheim-bissingen",
    "ludwigsburg",
    "neckarsulm",
    "öhringen",
    "crailsheim",
    "mosbach",
    "eberbach",
    "sinsheim",
    "wiesloch",
    "leimen",
    "schwetzingen",
    "hockenheim",
    "homburg",
    "saarlouis",
    "merzig",
    "neunkirchen",
    "sulzbach",
    "völklingen",
    "dillingen",
    "blieskastel",
    "st. wendel",
    "ottweiler",
    "illingen",
    "schiffweiler",
    "saarwellingen",
    "beckingen",
    "rehlingen-siersburg",
    "konz",
    "saarburg",
    "bernkastel-kues",
    "wittlich",
    "bitburg",
    "prüm",
    "daun",
    "cochem",
    "mayen",
    "neuwied",
    "lahnstein",
    "bad ems",
    "nassau",
    "montabaur",
    "westerburg",
    "altenkirchen",
    "betzdorf",
    "olpe",
    "attendorn",
    "meschede",
    "brilon",
    "marsberg",
    "lippstadt",
    "soest",
    "arnsberg",
    "menden",
    "fröndenberg",
    "unna",
    "datteln",
    "castrop-rauxel",
    "wanne-eickel",
    "hattingen",
    "sprockhövel",
    "ennepetal",
    "gevelsberg",
    "schwelm",
    "wetter",
    "herdecke",
    "overath",
    "rösrath",
    "siegburg",
    "much",
    "gummersbach",
    "wiehl",
    "radevormwald",
    "hückeswagen",
    "wermelskirchen",
    "burscheid",
    "langenfeld",
    "monheim",
    "hilden",
    "haan",
    "mettmann",
    "erkrath",
    "wülfrath",
    "heiligenhaus",
    "dorsten",
    "haltern",
    "dülmen",
    "coesfeld",
    "ahlen",
    "oelde",
    "warendorf",
    "beckum",
    "herford",
    "bad oeynhausen",
    "bünde",
    "löhne",
    "porta westfalica",
    "rinteln",
    "holzminden",
    "einbeck",
    "northeim",
    "hann. münden",
    "baunatal",
    "hofgeismar",
    "bad karlshafen",
    "diemelstadt",
    "detmold",
    "lemgo",
    "horn-bad meinberg",
    "bad lippspringe",
    "lichtenfels",
    "ludwigsstadt",
    "sonneberg",
    "hildburghausen",
    "meiningen",
    "bad salzungen",
    "eisenach",
    "gotha",
    "weimar",
    "apolda",
    "gera",
    "altenburg",
    "schmölln",
    "greiz",
    "zeulenroda",
    "saalfeld",
    "rudolstadt",
    "ilmenau",
    "arnstadt",
    "nordhausen",
    "mühlhausen",
    "bad langensalza",
    "leinefelde",
    "heiligenstadt",
    "halberstadt",
    "quedlinburg",
    "wernigerode",
    "blankenburg",
    "thale",
    "aschersleben",
    "bernburg",
    "köthen",
    "wittenberg",
    "bitterfeld",
    "zerbst",
    "stendal",
    "gardelegen",
    "burg",
    "genthin",
    "schönebeck",
    "staßfurt",
    "sangerhausen",
    "merseburg",
    "weißenfels",
    "naumburg",
    "zeitz",
    "hohenmölsen",
    "borna",
    "zwenkau",
    "markkleeberg",
    "delitzsch",
    "torgau",
    "eilenburg",
    "grimma",
    "döbeln",
    "meißen",
    "riesa",
    "großenhain",
    "radebeul",
    "pirna",
    "heidenau",
    "freital",
    "freiberg",
    "brand-erbisdorf",
    "plauen",
    "reichenbach",
    "auerbach",
    "annaberg-buchholz",
    "glauchau",
    "meerane",
    "bautzen",
    "görlitz",
    "löbau",
    "zittau",
    "hoyerswerda",
    "guben",
    "forst",
    "spremberg",
    "lübben",
    "senftenberg",
    "frankfurt an der oder",
    "eisenhüttenstadt",
    "fürstenwalde",
    "strausberg",
    "eberswalde",
    "bernau",
    "oranienburg",
    "ludwigsfelde",
    "teltow",
    "zossen",
    "jüterbog",
    "luckenwalde",
    "rathenow",
    "nauen",
    "falkensee",
    "neuruppin",
    "prenzlau",
    "angermünde",
    "schwedt",
    "neustrelitz",
    "neubrandenburg",
    "stralsund",
    "greifswald",
    "anklam",
    "demmin",
    "waren",
    "güstrow",
    "wismar",
    "ludwigslust",
    "boizenburg",
    "lüneburg",
    "buxtehude",
    "stade",
    "cuxhaven",
    "delmenhorst",
    "emden",
    "papenburg",
    "lingen",
    "nordhorn",
    "rheine",
    "ibbenbüren",
    "greven",
    "gronau",
    "ahaus",
    "borken",
    "bocholt",
    "wesel",
    "xanten",
    "kleve",
    "viersen",
    "kempen",
    "grevenbroich",
    "erkelenz",
    "heinsberg",
    "geilenkirchen",
    "jülich",
    "alsdorf",
    "baesweiler",
    "eschweiler",
    "würselen",
    "stolberg",
    "herzogenrath",
    "wien",
    "graz",
    "linz",
    "salzburg",
    "innsbruck",
    "klagenfurt",
    "villach",
    "wels",
    "st. pölten",
    "dornbirn",
    "steyr",
    "wiener neustadt",
    "feldkirch",
    "bregenz",
    "leonding",
    "klosterneuburg",
    "traun",
    "leoben",
    "wolfsberg",
    "krems an der donau",
    "amstetten",
    "wr. neustadt",
    "mödling",
    "kapfenberg",
    "bruck an der mur",
    "schwechat",
    "perchtoldsdorf",
    "hallein",
    "wörgl",
    "kufstein",
    "schwaz",
    "telfs",
    "hall in tirol",
    "imst",
    "lienz",
    "zell am see",
    "bischofshofen",
    "st. veit an der glan",
    "völkermarkt",
    "spittal an der drau",
    "hermagor",
    "eisenstadt",
    "rust",
    "neusiedl am see",
    "oberpullendorf",
    "mattersburg",
    "jennersdorf",
    "güssing",
    "bad radkersburg",
    "weiz",
    "hartberg",
    "fürstenfeld",
    "feldbach",
    "gleisdorf",
    "voitsberg",
    "judenburg",
    "knittelfeld",
    "mürzzuschlag",
    "zürich",
    "genf",
    "basel",
    "lausanne",
    "bern",
    "winterthur",
    "luzern",
    "st. gallen",
    "lugano",
    "biel",
    "thun",
    "köniz",
    "la chaux-de-fonds",
    "schaffhausen",
    "fribourg",
    "chur",
    "vernier",
    "neuchâtel",
    "uster",
    "sion",
    "emmen",
    "zug",
    "yverdon-les-bains",
    "dübendorf",
    "kriens",
    "aarau",
    "arbon",
    "arlesheim",
    "arth",
    "arosa",
    "altdorf",
    "bellinzona",
    "locarno",
    "mendrisio",
    "kloten",
    "opfikon",
    "illnau-effretikon",
    "volketswil",
    "dietikon",
    "schlieren",
    "urdorf",
    "birmensdorf",
    "spreitenbach",
    "wettingen",
    "brugg",
    "kaiseraugst",
    "allschwil",
    "binningen",
    "muttenz",
    "pratteln",
    "liestal",
    "sissach",
    "olten",
    "solothurn",
    "grenchen",
    "bettlach",
    "lengnau",
    "langenthal",
    "burgdorf",
    "biel/bienne",
    "nidau",
    "münchenbuchsee",
    "ostermundigen",
    "muri bei bern",
    "gümligen",
    "bolligen",
    "worb",
    "belp",
    "steffisburg",
    "spiez",
    "interlaken",
    "brienz",
    "meiringen",
    "grindelwald",
    "lauterbrunnen",
    "wengen",
    "murten",
    "avenches",
    "payerne",
    "moudon",
    "romont",
    "bulle",
    "broc",
    "gruyères",
    "châtel-saint-denis",
    "vevey",
    "montreux",
    "villeneuve",
    "aigle",
    "bex",
    "monthey",
    "martigny",
    "saxon",
    "riddes",
    "leuk",
    "visp",
    "brig",
    "zermatt",
    "saas-fee",
    "andermatt",
    "airolo",
    "biasca",
    "acquarossa",
    "olivone",
    "ilanz",
    "disentis",
    "flims",
    "davos",
    "klosters",
    "thusis",
    "tiefencastel",
    "silvaplana",
    "st. moritz",
    "pontresina",
    "poschiavo",
    "brusio",
    "roveredo",
    "mesocco",
    "promontogno",
    "stampa",
    "chiavenna",
    "paris",
    "lyon",
    "marseille",
    "toulouse",
    "nice",
    "nantes",
    "strasbourg",
    "montpellier",
    "bordeaux",
    "lille",
    "rennes",
    "reims",
    "le havre",
    "saint-étienne",
    "toulon",
    "grenoble",
    "dijon",
    "angers",
    "nîmes",
    "clermont-ferrand",
    "le mans",
    "aix-en-provence",
    "brest",
    "tours",
    "amiens",
    "caen",
    "rouen",
    "perpignan",
    "nancy",
    "metz",
    "orléans",
    "valenciennes",
    "dunkerque",
    "mérignac",
    "mulhouse",
    "besançon",
    "avignon",
    "pau",
    "cannes",
    "antibes",
    "nizza",
    "narbonne",
    "béziers",
    "sète",
    "arles",
    "orange",
    "carpentras",
    "apt",
    "manosque",
    "digne-les-bains",
    "gap",
    "briançon",
    "embrun",
    "sisteron",
    "london",
    "birmingham",
    "manchester",
    "glasgow",
    "leeds",
    "liverpool",
    "newcastle",
    "sheffield",
    "bristol",
    "edinburgh",
    "cardiff",
    "belfast",
    "leicester",
    "nottingham",
    "coventry",
    "hull",
    "bradford",
    "stoke-on-trent",
    "wolverhampton",
    "derby",
    "sunderland",
    "plymouth",
    "reading",
    "southampton",
    "oxford",
    "cambridge",
    "bath",
    "york",
    "exeter",
    "norwich",
    "ipswich",
    "peterborough",
    "luton",
    "milton keynes",
    "brighton",
    "portsmouth",
    "swansea",
    "middlesbrough",
    "bolton",
    "blackpool",
    "dundee",
    "aberdeen",
    "inverness",
    "amsterdam",
    "rotterdam",
    "haag",
    "utrecht",
    "eindhoven",
    "tilburg",
    "groningen",
    "almere",
    "breda",
    "nijmegen",
    "apeldoorn",
    "haarlem",
    "arnhem",
    "zaanstad",
    "s-hertogenbosch",
    "amersfoort",
    "delft",
    "leiden",
    "dordrecht",
    "zwolle",
    "enschede",
    "deventer",
    "maastricht",
    "leeuwarden",
    "venlo",
    "alkmaar",
    "brüssel",
    "gent",
    "antwerpen",
    "lüttich",
    "brügge",
    "namur",
    "mechelen",
    "leuven",
    "hasselt",
    "kortrijk",
    "charleroi",
    "mons",
    "roeselare",
    "turnhout",
    "aalst",
    "ostende",
    "genk",
    "madrid",
    "barcelona",
    "valencia",
    "sevilla",
    "zaragoza",
    "málaga",
    "murcia",
    "palma de mallorca",
    "bilbao",
    "alicante",
    "valladolid",
    "córdoba",
    "vigo",
    "gijón",
    "hospitalet de llobregat",
    "la coruña",
    "granada",
    "vitoria-gasteiz",
    "elche",
    "oviedo",
    "badalona",
    "cartagena",
    "terrassa",
    "jerez de la frontera",
    "sabadell",
    "santa cruz de tenerife",
    "pamplona",
    "almería",
    "fuenlabrada",
    "leganés",
    "san sebastián",
    "burgos",
    "salamanca",
    "alcalá de henares",
    "albacete",
    "alcorcón",
    "getafe",
    "rom",
    "mailand",
    "neapel",
    "turin",
    "palermo",
    "genua",
    "bologna",
    "florenz",
    "bari",
    "catania",
    "venedig",
    "verona",
    "messina",
    "padua",
    "trieste",
    "brescia",
    "taranto",
    "prato",
    "reggio calabria",
    "modena",
    "reggio emilia",
    "perugia",
    "ravenna",
    "livorno",
    "cagliari",
    "foggia",
    "rimini",
    "salerno",
    "ferrara",
    "sassari",
    "siracusa",
    "bergamo",
    "monza",
    "vicenza",
    "andria",
    "udine",
    "parma",
    "piacenza",
    "ancona",
    "la spezia",
    "forli",
    "trento",
    "pesaro",
    "treviso",
    "lecce",
    "novara",
    "pisa",
    "como",
    "lissabon",
    "porto",
    "vila nova de gaia",
    "amadora",
    "braga",
    "almada",
    "coimbra",
    "funchal",
    "setúbal",
    "agualva-cacém",
    "aveiro",
    "guimarães",
    "viseu",
    "évora",
    "faro",
    "leiria",
    "portimão",
    "lagos",
    "albufeira",
    "athen",
    "thessaloniki",
    "patras",
    "heraklion",
    "larissa",
    "volos",
    "ioannina",
    "chania",
    "kavala",
    "serres",
    "drama",
    "komotini",
    "xanthi",
    "alexandroupoli",
    "korfu",
    "rhodos",
    "warschau",
    "krakau",
    "lodz",
    "breslau",
    "posen",
    "danzig",
    "stettin",
    "bydgoszcz",
    "lublin",
    "katowice",
    "białystok",
    "gdynia",
    "częstochowa",
    "radom",
    "sosnowiec",
    "toruń",
    "kielce",
    "gliwice",
    "rzeszów",
    "zabrze",
    "olsztyn",
    "bielsko-biała",
    "bytom",
    "zielona góra",
    "rybnik",
    "ruda śląska",
    "tychy",
    "dąbrowa górnicza",
    "opole",
    "elbląg",
    "płock",
    "wałbrzych",
    "wrocław",
    "prag",
    "brünn",
    "ostrava",
    "pilsen",
    "liberec",
    "olmütz",
    "ústí nad labem",
    "hradec králové",
    "české budějovice",
    "pardubice",
    "zlín",
    "havirov",
    "kladno",
    "most",
    "opava",
    "frydek-mistek",
    "budapest",
    "debrecen",
    "miskolc",
    "szeged",
    "pécs",
    "győr",
    "nyíregyháza",
    "kecskemét",
    "székesfehérvár",
    "szombathely",
    "szolnok",
    "tatabánya",
    "kaposvár",
    "eger",
    "veszprém",
    "zalaegerszeg",
    "bukarest",
    "cluj-napoca",
    "timișoara",
    "iași",
    "constanța",
    "craiova",
    "brașov",
    "galați",
    "ploiești",
    "oradea",
    "brăila",
    "arad",
    "pitești",
    "sibiu",
    "bacău",
    "târgu mureș",
    "baia mare",
    "buzău",
    "satu mare",
    "râmnicu vâlcea",
    "belgrad",
    "novi sad",
    "niš",
    "kragujevac",
    "subotica",
    "zrenjanin",
    "pančevo",
    "čačak",
    "kruševac",
    "novi pazar",
    "sofia",
    "plowdiw",
    "warna",
    "burgas",
    "ruse",
    "stara zagora",
    "pleven",
    "sliven",
    "dobrich",
    "schumen",
    "zagreb",
    "split",
    "rijeka",
    "osijek",
    "zadar",
    "slavonski brod",
    "pula",
    "šibenik",
    "dubrovnik",
    "koprivnica",
    "laibach",
    "maribor",
    "celje",
    "kranj",
    "koper",
    "velenje",
    "novo mesto",
    "ptuj",
    "tschechische",
    "bratislava",
    "košice",
    "prešov",
    "žilina",
    "banská bystrica",
    "nitra",
    "trnava",
    "martin",
    "trenčín",
    "poprad",
    "helsinki",
    "espoo",
    "tampere",
    "vantaa",
    "oulu",
    "turku",
    "jyväskylä",
    "lahti",
    "kuopio",
    "pori",
    "joensuu",
    "lappeenranta",
    "hämeenlinna",
    "vaasa",
    "seinäjoki",
    "rovaniemi",
    "mikkeli",
    "stockholm",
    "göteborg",
    "malmö",
    "uppsala",
    "linköping",
    "örebro",
    "västerås",
    "helsingborg",
    "jönköping",
    "norrköping",
    "lund",
    "umeå",
    "gävle",
    "borås",
    "eskilstuna",
    "södertälje",
    "karlstad",
    "täby",
    "sundsvall",
    "oslo",
    "bergen",
    "stavanger",
    "trondheim",
    "drammen",
    "fredrikstad",
    "porsgrunn",
    "skien",
    "kristiansand",
    "ålesund",
    "tønsberg",
    "haugesund",
    "kopenhagen",
    "aarhus",
    "odense",
    "aalborg",
    "esbjerg",
    "randers",
    "kolding",
    "horsens",
    "vejle",
    "roskilde",
    "helsingør",
    "naestved",
    "fredericia",
    "silkeborg",
    "viborg",
    "reykjavik",
    "moskau",
    "st. petersburg",
    "nowosibirsk",
    "jekaterinburg",
    "kasan",
    "nischni nowgorod",
    "samara",
    "omsk",
    "tscheljabinsk",
    "rostow am don",
    "ufa",
    "krasnodar",
    "perm",
    "wolgagrad",
    "woronesch",
    "saratow",
    "irkutsk",
    "krasnojarsk",
    "uljanowsk",
    "togliatti",
    "toljatti",
    "ischjewsk",
    "tjumen",
    "chabarowsk",
    "tschita",
    "nowokusnezk",
    "barnaul",
    "wladiwostok",
    "jaroslawl",
    "machatschkala",
    "chasawjurt",
    "derbent",
    "odessa",
    "kiew",
    "charkiw",
    "dnipro",
    "donezk",
    "lwiw",
    "saporischschja",
    "krywyi rih",
    "mykolajiw",
    "mariupol",
    "luhansk",
    "winnyzja",
    "makijiwka",
    "sewastopol",
    "simferopol",
    "cherson",
    "khmelnyzkyj",
    "tschernihiw",
    "sumy",
    "poltawa",
    "tscherkassy",
    "kirowograd",
    "schytomyr",
    "riwne",
    "ternopil",
    "iwano-frankiwsk",
    "uschhorod",
    "tiflis",
    "eriwan",
    "baku",
    "taschkent",
    "almaty",
    "bischkek",
    "aschgabat",
    "duschanbe",
    "istanbul",
    "ankara",
    "izmir",
    "bursa",
    "adana",
    "gaziantep",
    "konya",
    "antalya",
    "diyarbakır",
    "mersin",
    "kayseri",
    "eskişehir",
    "samsun",
    "trabzon",
    "kahramanmaraş",
    "malatya",
    "erzurum",
    "van",
    "denizli",
    "şanlıurfa",
    "sivas",
    "edirne",
    "karabük",
    "teheran",
    "mashhad",
    "isfahan",
    "tabriz",
    "karaj",
    "shiraz",
    "ahvaz",
    "qom",
    "kermanshah",
    "urmia",
    "rasht",
    "zahedan",
    "bagdad",
    "basra",
    "mossul",
    "erbil",
    "sulaymaniyah",
    "kairo",
    "alexandrien",
    "gizeh",
    "shubrā al khaymah",
    "port said",
    "suez",
    "luxor",
    "mansoura",
    "tanta",
    "assiut",
    "kafr el sheikh",
    "damanhur",
    "hurghada",
    "casablanca",
    "rabat",
    "fez",
    "marrakesch",
    "meknes",
    "tanger",
    "agadir",
    "oujda",
    "tetouan",
    "sale",
    "kenitra",
    "tunis",
    "sfax",
    "sousse",
    "kairouan",
    "bizerte",
    "gabes",
    "ariana",
    "gafsa",
    "algier",
    "oran",
    "konstantine",
    "annaba",
    "blida",
    "batna",
    "djelfa",
    "sétif",
    "sidi bel abbès",
    "biskra",
    "tlemcen",
    "tizi ouzou",
    "tripolis",
    "bengasi",
    "misrata",
    "tarhuna",
    "zawiya",
    "al-khums",
    "harare",
    "bulawayo",
    "johannesburg",
    "kapstadt",
    "durban",
    "pretoria",
    "port elizabeth",
    "bloemfontein",
    "soweto",
    "benoni",
    "tembisa",
    "vereeniging",
    "east london",
    "pietermaritzburg",
    "boksburg",
    "cape town",
    "nairobi",
    "mombasa",
    "kisumu",
    "nakuru",
    "eldoret",
    "dar es salaam",
    "dodoma",
    "arusha",
    "mwanza",
    "mbeya",
    "kampala",
    "gulu",
    "mbarara",
    "kigali",
    "butare",
    "gitarama",
    "addis abeba",
    "dire dawa",
    "mekelle",
    "gondar",
    "bahir dar",
    "jimma",
    "khartum",
    "omdurman",
    "port sudan",
    "kassala",
    "el-obeid",
    "wad medani",
    "abuja",
    "kano",
    "ibadan",
    "kaduna",
    "port harcourt",
    "benin city",
    "maiduguri",
    "zaria",
    "aba",
    "jos",
    "ilorin",
    "oyo",
    "enugu",
    "abeokuta",
    "accra",
    "kumasi",
    "tamale",
    "sekondi-takoradi",
    "cape coast",
    "dakar",
    "thiès",
    "kaolack",
    "abidjan",
    "yamoussoukro",
    "bouaké",
    "korhogo",
    "san-pédro",
    "bamako",
    "sikasso",
    "mopti",
    "ouagadougou",
    "bobo-dioulasso",
    "bangui",
    "kinshasa",
    "lubumbashi",
    "mbuji-mayi",
    "kananga",
    "kisangani",
    "kolwezi",
    "brazzaville",
    "pointe-noire",
    "luanda",
    "huambo",
    "lobito",
    "benguela",
    "lusaka",
    "ndola",
    "kitwe",
    "kabwe",
    "lilongwe",
    "blantyre",
    "maputo",
    "beira",
    "nampula",
    "antananarivo",
    "toamasina",
    "antsirabe",
    "fianarantsoa",
    "windhoek",
    "walvis bay",
    "gaborone",
    "francistown",
    "maseru",
    "mbabane",
    "peking",
    "schanghai",
    "kanton",
    "tianjin",
    "chengdu",
    "wuhan",
    "chongqing",
    "xi'an",
    "suzhou",
    "nanjing",
    "shenzhen",
    "hangzhou",
    "shenyang",
    "dongguan",
    "harbin",
    "foshan",
    "jinan",
    "qingdao",
    "zhengzhou",
    "changsha",
    "dalian",
    "kunming",
    "ningbo",
    "wenzhou",
    "nanchang",
    "hefei",
    "changchun",
    "guiyang",
    "nanning",
    "urümqi",
    "xining",
    "lhasa",
    "hongkong",
    "macau",
    "taipeh",
    "kaohsiung",
    "taichung",
    "tainan",
    "hsinchu",
    "tokio",
    "osaka",
    "nagoya",
    "sapporo",
    "fukuoka",
    "kobe",
    "kyoto",
    "kawasaki",
    "saitama",
    "hiroshima",
    "sendai",
    "kitakyushu",
    "chiba",
    "sakai",
    "niigata",
    "hamamatsu",
    "kumamoto",
    "okayama",
    "sagamihara",
    "shizuoka",
    "kagoshima",
    "funabashi",
    "hachioji",
    "higashiosaka",
    "seoul",
    "busan",
    "incheon",
    "daegu",
    "daejeon",
    "gwangju",
    "suwon",
    "ulsan",
    "changwon",
    "seongnam",
    "bucheon",
    "goyang",
    "pjöngjang",
    "hamhung",
    "chongjin",
    "nampo",
    "wonsan",
    "singapur",
    "kuala lumpur",
    "george town",
    "ipoh",
    "johor bahru",
    "petaling jaya",
    "shah alam",
    "subang jaya",
    "klang",
    "kota kinabalu",
    "kuching",
    "jakarta",
    "surabaya",
    "bandung",
    "medan",
    "semarang",
    "makassar",
    "palembang",
    "tangerang",
    "depok",
    "bogor",
    "batam",
    "pekanbaru",
    "bandar lampung",
    "padang",
    "malang",
    "samarinda",
    "manado",
    "manila",
    "quezon city",
    "caloocan",
    "davao",
    "cebu",
    "zamboanga",
    "antipolo",
    "pasig",
    "cagayan de oro",
    "paranaque",
    "taguig",
    "valenzuela",
    "dasmariñas",
    "bangkok",
    "nonthaburi",
    "pak kret",
    "hat yai",
    "chiang mai",
    "udon thani",
    "nakhon ratchasima",
    "phnom penh",
    "siem reap",
    "vientiane",
    "naypyidaw",
    "yangon",
    "mandalay",
    "dhaka",
    "chittagong",
    "comilla",
    "rajshahi",
    "sylhet",
    "khulna",
    "neu-delhi",
    "mumbai",
    "kolkata",
    "chennai",
    "bengaluru",
    "hyderabad",
    "ahmedabad",
    "pune",
    "surat",
    "jaipur",
    "lucknow",
    "kanpur",
    "nagpur",
    "indore",
    "thane",
    "bhopal",
    "visakhapatnam",
    "pimpri-chinchwad",
    "patna",
    "vadodara",
    "ghaziabad",
    "ludhiana",
    "agra",
    "nashik",
    "faridabad",
    "meerut",
    "rajkot",
    "varanasi",
    "srinagar",
    "aurangabad",
    "dhanbad",
    "amritsar",
    "allahabad",
    "ranchi",
    "howrah",
    "guwahati",
    "jabalpur",
    "coimbatore",
    "vijayawada",
    "jodhpur",
    "raipur",
    "madurai",
    "kota",
    "chandigarh",
    "islamabad",
    "karachi",
    "lahore",
    "faisalabad",
    "rawalpindi",
    "gujranwala",
    "peshawar",
    "multan",
    "quetta",
    "bahawalpur",
    "sargodha",
    "sialkot",
    "kathmandu",
    "pokhara",
    "patan",
    "biratnagar",
    "birgunj",
    "colombo",
    "dehiwala",
    "moratuwa",
    "jaffna",
    "kabul",
    "kandahar",
    "herat",
    "mazar-e-sharif",
    "riad",
    "dschidda",
    "mekka",
    "medina",
    "taif",
    "dammam",
    "abu dhabi",
    "dubai",
    "sharjah",
    "ajman",
    "muskat",
    "manama",
    "kuwait city",
    "amman",
    "irbid",
    "zarqa",
    "beirut",
    "sidon",
    "damaskus",
    "aleppo",
    "homs",
    "hama",
    "latakia",
    "deir ez-zor",
    "jerusalem",
    "tel aviv",
    "haifa",
    "rishon lezion",
    "petah tikva",
    "ashdod",
    "ashkelon",
    "netanya",
    "beer sheva",
    "bnei brak",
    "holon",
    "bat yam",
    "sanaa",
    "aden",
    "taiz",
    "al-hudaydah",
    "new york",
    "los angeles",
    "chicago",
    "houston",
    "phoenix",
    "philadelphia",
    "san antonio",
    "san diego",
    "dallas",
    "san jose",
    "austin",
    "jacksonville",
    "fort worth",
    "columbus",
    "charlotte",
    "indianapolis",
    "san francisco",
    "seattle",
    "denver",
    "nashville",
    "oklahoma city",
    "el paso",
    "washington",
    "boston",
    "las vegas",
    "portland",
    "louisville",
    "memphis",
    "baltimore",
    "milwaukee",
    "albuquerque",
    "tucson",
    "fresno",
    "sacramento",
    "mesa",
    "kansas city",
    "atlanta",
    "omaha",
    "colorado springs",
    "raleigh",
    "long beach",
    "virginia beach",
    "miami",
    "minneapolis",
    "new orleans",
    "honolulu",
    "anchorage",
    "tampa",
    "orlando",
    "pittsburgh",
    "cincinnati",
    "st. louis",
    "cleveland",
    "detroit",
    "buffalo",
    "richmond",
    "salt lake city",
    "hartford",
    "baton rouge",
    "little rock",
    "sioux falls",
    "boise",
    "spokane",
    "tacoma",
    "madison",
    "des moines",
    "jackson",
    "fayetteville",
    "cheyenne",
    "montgomery",
    "bismarck",
    "helena",
    "juneau",
    "dover",
    "concord",
    "montpelier",
    "toronto",
    "montreal",
    "vancouver",
    "calgary",
    "edmonton",
    "ottawa",
    "winnipeg",
    "quebec city",
    "hamilton",
    "kitchener",
    "victoria",
    "halifax",
    "oshawa",
    "windsor",
    "saskatoon",
    "regina",
    "st. john's",
    "kelowna",
    "abbotsford",
    "mexico city",
    "guadalajara",
    "monterrey",
    "puebla",
    "toluca",
    "tijuana",
    "juárez",
    "León",
    "zapopan",
    "nezahualcóyotl",
    "ecatepec",
    "chihuahua",
    "naucalpan",
    "mérida",
    "san luis potosí",
    "aguascalientes",
    "morelia",
    "culiacán",
    "hermosillo",
    "saltillo",
    "tlaquepaque",
    "cancún",
    "acapulco",
    "veracruz",
    "san salvador",
    "guatemala city",
    "tegucigalpa",
    "managua",
    "san josé",
    "panama city",
    "havanna",
    "santo domingo",
    "san juan",
    "port-au-prince",
    "kingston",
    "bogotá",
    "medellín",
    "cali",
    "barranquilla",
    "cúcuta",
    "bucaramanga",
    "pereira",
    "santa marta",
    "ibagué",
    "caracas",
    "maracaibo",
    "barquisimeto",
    "maracay",
    "lima",
    "arequipa",
    "callao",
    "trujillo",
    "chiclayo",
    "piura",
    "iquitos",
    "cusco",
    "quito",
    "guayaquil",
    "cuenca",
    "la paz",
    "santa cruz de la sierra",
    "cochabamba",
    "sucre",
    "asunción",
    "ciudad del este",
    "encarnación",
    "santiago",
    "valparaíso",
    "concepción",
    "antofagasta",
    "viña del mar",
    "temuco",
    "rancagua",
    "talca",
    "arica",
    "chillán",
    "buenos aires",
    "rosario",
    "mendoza",
    "tucumán",
    "la plata",
    "mar del plata",
    "quilmes",
    "lanús",
    "salta",
    "santa fe",
    "resistencia",
    "santiago del estero",
    "corrientes",
    "río cuarto",
    "posadas",
    "neuquén",
    "bahía blanca",
    "rio de janeiro",
    "são paulo",
    "brasília",
    "salvador",
    "fortaleza",
    "belo horizonte",
    "manaus",
    "curitiba",
    "recife",
    "porto alegre",
    "belém",
    "goiânia",
    "guarulhos",
    "campinas",
    "são luís",
    "maceió",
    "natal",
    "teresina",
    "campo grande",
    "joão pessoa",
    "osasco",
    "santo andré",
    "são bernardo do campo",
    "jaboatão dos guararapes",
    "contagem",
    "uberlândia",
    "sorocaba",
    "aracaju",
    "feira de santana",
    "cuiabá",
    "juiz de fora",
    "londrina",
    "joinville",
    "aparecida de goiânia",
    "sydney",
    "melbourne",
    "brisbane",
    "perth",
    "adelaide",
    "gold coast",
    "canberra",
    "sunshine coast",
    "wollongong",
    "hobart",
    "darwin",
    "geelong",
    "townsville",
    "cairns",
    "auckland",
    "wellington",
    "christchurch",
    "tauranga",
    "napier-hastings",
    "dunedin",
    "palmerston north",
    "suva",
    "port moresby",
    "honiara",
    "nuku'alofa",
    "apia",
    "tahiti",
    "papeete",
    "noumea",
    "badoehl",
    "achim",
    "adendorf",
    "adorf",
    "ahrensburg",
    "alfeld",
    "altena",
    "altötting",
    "alzey",
    "asbach-bäumenheim",
    "auma-weidatal",
    "babelsberg",
    "backnang",
    "bad berleburg",
    "bad bevensen",
    "bad cannstatt",
    "bad driburg",
    "bad dürkheim",
    "bad frankenhausen",
    "bad gandersheim",
    "bad hersfeld",
    "bad kissingen",
    "bad königshofen",
    "bad lauterberg",
    "bad neustadt",
    "bad orb",
    "bad pyrmont",
    "bad reichenhall",
    "bad rodach",
    "bad salzdetfurth",
    "bad schwartau",
    "bad segeberg",
    "bad sooden-allendorf",
    "bad tölz",
    "bad urach",
    "bad wildungen",
    "bad wimpfen",
    "bärnau",
    "barsinghausen",
    "bensheim",
    "berching",
    "bergheim",
    "bergkamen",
    "bestwig",
    "beverungen",
    "biberach an der riß",
    "blaubeuren",
    "blomberg",
    "bobingen",
    "böblingen",
    "boppard",
    "bornheim",
    "brackenheim",
    "bramsche",
    "breisach",
    "bretten",
    "büdingen",
    "burglengenfeld",
    "burghausen",
    "butzbach",
    "calau",
    "celle",
    "clausthal-zellerfeld",
    "cloppenburg",
    "dachau",
    "deggendorf",
    "diepholz",
    "dillingen an der donau",
    "dinslaken",
    "donaueschingen",
    "donauwörth",
    "donzdorf",
    "dormagen",
    "eichstätt",
    "eisleben",
    "emmendingen",
    "engen",
    "erding",
    "eschborn",
    "eschwege",
    "esens",
    "ettenheim",
    "euskirchen",
    "eutin",
    "feuchtwangen",
    "filderstadt",
    "forchheim",
    "freudenstadt",
    "friedrichsdorf",
    "fritzlar",
    "frondenberg",
    "fürstenfeldbruck",
    "garmisch-partenkirchen",
    "geislingen an der steige",
    "gengenbach",
    "germersheim",
    "gersthofen",
    "gifhorn",
    "goch",
    "goslar",
    "grafenau",
    "großräschen",
    "guenzburg",
    "hagenow",
    "haltern am see",
    "hassfurt",
    "haßloch",
    "hattersheim",
    "herzberg am harz",
    "höxter",
    "husum",
    "illertissen",
    "isny im allgäu",
    "kirchheimbolanden",
    "kulmbach",
    "landau",
    "landsberg am lech",
    "langenzenn",
    "lauingen",
    "leer",
    "lengerich",
    "leonberg",
    "leutkirch",
    "lüdenscheid",
    "marktoberdorf",
    "marktheidenfeld",
    "mühldorf",
    "murrhardt",
    "nagold",
    "neu-ulm",
    "neuburg an der donau",
    "neumarkt in der oberpfalz",
    "neustadt an der aisch",
    "nördlingen",
    "nordenham",
    "osterholz-scharmbeck",
    "plattling",
    "plochingen",
    "pocking",
    "radolfzell",
    "ratzeburg",
    "regen",
    "rheinbach",
    "roding",
    "rothenburg ob der tauber",
    "rottenburg am neckar",
    "schrobenhausen",
    "sonthofen",
    "staffelstein",
    "sulingen",
    "traunstein",
    "tübingen",
    "uelzen",
    "velburg",
    "verden",
    "vilshofen",
    "vohenstrauss",
    "warburg",
    "werdohl",
    "weißenburg in bayern",
    "weißwasser",
    "wertheim",
    "wiedenbrück",
    "wildbad",
    "wolfratshausen",
    "wunsiedel",
    "zirndorf",
]
