"""Zusaetzliche deutsche Orts-Suchvorlagen ('{}' = Stadt) fuer das Data Poisoning."""

TEMPLATES = [
    # Wetter
    "wetter {}",
    "wetter {} heute",
    "wetter {} morgen",
    "wetter {} wochenende",
    "wetter {} 7 tage",
    "wetter {} 14 tage",
    "wetter {} aktuell",
    "wetter {} vorhersage",
    "wetter {} nächste woche",
    "wetter {} dezember",
    "wetter {} januar",
    "wetter {} februar",
    "wetter {} märz",
    "wetter {} april",
    "wetter {} mai",
    "wetter {} juni",
    "wetter {} juli",
    "wetter {} august",
    "wetter {} september",
    "wetter {} oktober",
    "wetter {} november",
    "wetter {} sommer",
    "wetter {} winter",
    "wetter {} frühling",
    "wetter {} herbst",
    "{} temperatur heute",
    "{} regenwahrscheinlichkeit morgen",
    "{} schnee vorhersage",
    "{} gewitter warnung",
    "{} wetterradar",

    # Unterkunft allgemein
    "hotels in {}",
    "günstige hotels {}",
    "hotel {} buchen",
    "hotel {} last minute",
    "hotel {} mit pool",
    "hotel {} zentrum",
    "hotel {} nähe bahnhof",
    "hotel {} nähe flughafen",
    "hotel {} bewertungen",
    "hotel {} 3 sterne",
    "hotel {} 4 sterne",
    "hotel {} 5 sterne",
    "hotel {} familienzimmer",
    "hotel {} haustiere erlaubt",
    "hotel {} parken kostenlos",
    "hotel {} frühstück inklusive",
    "hostel {}",
    "hostel {} günstig",
    "hostel {} zentrum",
    "jugendherberge {}",
    "pension {}",
    "ferienwohnung {}",
    "ferienwohnung {} buchen",
    "ferienwohnung {} günstig",
    "airbnb {}",
    "airbnb {} günstig",
    "unterkunft {} günstig",
    "unterkunft {} buchen",
    "übernachtung {}",
    "übernachtung {} günstig",
    "camping {}",
    "campingplatz {}",
    "campingplatz {} am see",
    "campingplatz {} mit strom",
    "wohnmobil stellplatz {}",
    "bed and breakfast {}",
    "apartment {} mieten kurzzeit",
    "boutique hotel {}",
    "designhotel {}",
    "{} unterkunft empfehlung",
    "{} wo übernachten",
    "{} billige unterkunft",

    # Restaurants
    "restaurant {}",
    "beste restaurants {}",
    "günstig essen {}",
    "restaurants {} bewertungen",
    "restaurants {} empfehlung",
    "restaurants {} innenstadt",
    "restaurant {} reservierung",
    "restaurants {} heute geöffnet",
    "vegan restaurant {}",
    "vegetarisch restaurant {}",
    "veganes restaurant {}",
    "vegetarisches restaurant {}",
    "sushi {} bestellen",
    "sushi restaurant {}",
    "pizza {} liefern",
    "pizza restaurant {}",
    "beste pizza {}",
    "burger restaurant {}",
    "burger {} empfehlung",
    "italienisches restaurant {}",
    "asiatisches restaurant {}",
    "chinesisches restaurant {}",
    "indisches restaurant {}",
    "türkisches restaurant {}",
    "griechisches restaurant {}",
    "mexikanisches restaurant {}",
    "japanisches restaurant {}",
    "thai restaurant {}",
    "vietnamesisches restaurant {}",
    "steakhouse {}",
    "fischrestaurant {}",
    "meeresfrüchte {}",
    "frühstück {} restaurant",
    "brunch {}",
    "brunch {} am wochenende",
    "brunchen {} wo",
    "mittagessen {} günstig",
    "lunch {} angebot",
    "abendessen {} romantisch",
    "fine dining {}",
    "streetfood {}",
    "food market {}",
    "food truck {}",
    "döner {}",
    "kebab {}",
    "schnitzel {} restaurant",
    "bayerisches restaurant {}",
    "restaurant {} terrasse",
    "restaurant {} mit garten",
    "restaurant {} am wasser",
    "restaurant {} am see",
    "restaurant {} am fluss",
    "glutenfrei restaurant {}",
    "halal restaurant {}",
    "kosher restaurant {}",

    # Cafés
    "café {}",
    "cafés {}",
    "beste cafés {}",
    "café {} zentrum",
    "café {} gemütlich",
    "café {} mit kuchen",
    "café {} frühstück",
    "kaffee {} spezialitäten",
    "third wave coffee {}",
    "specialty coffee {}",
    "café {} laptop arbeiten",
    "café {} wlan",
    "café {} cozy",
    "café {} am see",
    "eiscafé {}",
    "konditorei {}",
    "bäckerei {} frühstück",
    "bäckerei {} empfehlung",
    "patisserie {}",
    "café {} hipster",
    "café {} instagrammable",

    # Bars und Nightlife
    "bar {}",
    "bars {}",
    "beste bars {}",
    "cocktailbar {}",
    "rooftop bar {}",
    "weinbar {}",
    "bierbar {}",
    "craftbeer {}",
    "brauerei {}",
    "brauerei {} besichtigung",
    "club {}",
    "clubs {}",
    "nightlife {}",
    "disco {}",
    "ausgehen {}",
    "tanzbar {}",
    "bar {} geöffnet",
    "bar {} zentrum",
    "happy hour {}",
    "bar {} mit terrasse",
    "pub {}",
    "irish pub {}",
    "sportbar {}",
    "karaoke bar {}",
    "jazz bar {}",
    "live musik {}",
    "konzert {} heute",
    "konzert {} heute abend",

    # Verkehr – Flüge
    "flug nach {}",
    "flüge nach {}",
    "billigflug {}",
    "billigflüge {}",
    "flug {} günstig",
    "flug {} buchen",
    "flug {} wann am günstigsten",
    "flüge {} last minute",
    "direktflug {}",
    "flug {} ryanair",
    "flug {} easyjet",
    "flug {} lufthansa",
    "flughafen {}",
    "flughafen {} anfahrt",
    "flughafen {} parken",
    "flughafen {} terminals",
    "flughafen {} abflug",
    "flughafen {} ankunft",
    "flughafen {} hotel",
    "ab {} fliegen wohin günstig",

    # Verkehr – Zug / Bahn
    "zug nach {}",
    "bahn nach {}",
    "zugverbindung {}",
    "db {} fahrplan",
    "ic nach {}",
    "ice nach {}",
    "nachtzug {}",
    "bahnhof {}",
    "bahnhof {} adresse",
    "bahnhof {} öffnungszeiten",
    "bahnhof {} parken",
    "bahnhof {} locker",
    "regionalbahn {}",
    "s-bahn {}",
    "bahncard {} sparen",
    "zugticket {} kaufen",

    # Verkehr – Bus / Fernbus
    "fernbus nach {}",
    "flixbus nach {}",
    "flixbus {} buchen",
    "busverbindung {}",
    "bus {} fahrplan",
    "reisebus {}",

    # Verkehr – Fähre / Schiff
    "fähre nach {}",
    "fähre {} buchen",
    "fähre {} fahrplan",
    "schiffsverbindung {}",

    # Verkehr – Mietwagen / Taxi
    "mietwagen {}",
    "mietwagen {} günstig",
    "mietwagen {} vergleich",
    "auto mieten {}",
    "carsharing {}",
    "taxi {}",
    "taxi {} bestellen",
    "taxi {} preise",
    "uber {}",
    "lyft {}",
    "ridesharing {}",

    # Öffentlicher Nahverkehr
    "öpnv {}",
    "u-bahn {}",
    "u-bahn {} fahrplan",
    "u-bahn {} karte",
    "straßenbahn {}",
    "bus {} linie",
    "tageskarte {} preis",
    "wochenkarte {}",
    "monatsticket {}",
    "öffentliche verkehrsmittel {}",
    "nahverkehr {}",
    "ticket {} kaufen",
    "{} vom flughafen in die stadt",
    "{} innenstadt parken",
    "parken {} kostenlos",
    "parkhaus {} zentrum",
    "parkplatz {} günstig",
    "stau {} aktuell",
    "fahrradverleih {}",
    "fahrrad mieten {}",
    "e-scooter {}",
    "fahrradweg {}",

    # Sehenswürdigkeiten
    "{} sehenswürdigkeiten",
    "{} sehenswürdigkeiten top 10",
    "{} must see",
    "{} highlights",
    "{} tourismus",
    "{} tipps",
    "{} tipps insider",
    "{} reisetipps",
    "{} was besichtigen",
    "{} was unternehmen",
    "{} touristenattraktion",
    "museum {}",
    "museen {}",
    "museen {} kostenlos",
    "kunstmuseum {}",
    "kunstgalerie {}",
    "galerie {}",
    "ausstellung {}",
    "ausstellung {} aktuell",
    "historisches museum {}",
    "naturkundemuseum {}",
    "technikmuseum {}",
    "stadtmuseum {}",
    "schloss {}",
    "burg {}",
    "kirche {} besichtigung",
    "kathedrale {}",
    "dom {}",
    "altstadt {}",
    "{} altstadt spaziergang",
    "park {}",
    "parks {}",
    "botanischer garten {}",
    "zoo {}",
    "tierpark {}",
    "aquarium {}",
    "strand {}",
    "strände {}",
    "strand {} sauber",
    "strandbar {}",
    "wandern {} umgebung",
    "wanderweg {}",
    "wanderung {} empfehlung",
    "aussichtspunkt {}",
    "aussichtspunkte {}",
    "beste aussicht {}",
    "turm {}",
    "fernsehturm {}",
    "brücke {}",
    "{} wahrzeichen",
    "denkmal {}",
    "skulptur {} bekannt",
    "platz {} bekannt",
    "marktplatz {}",
    "hafenviertel {}",
    "hafen {} spaziergang",
    "altes rathaus {}",
    "stadtbibliothek {}",
    "oper {}",
    "theater {}",
    "philharmonie {}",
    "kino {}",
    "kino {} programm heute",

    # Events und Veranstaltungen
    "events {}",
    "events {} heute",
    "events {} dieses wochenende",
    "events {} nächste woche",
    "veranstaltungen {}",
    "veranstaltungen {} heute",
    "konzerte {}",
    "konzert {} tickets",
    "festival {}",
    "festivals {} sommer",
    "musikfestival {}",
    "stadtfest {}",
    "weihnachtsmarkt {}",
    "flohmarkt {}",
    "flohmarkt {} wann",
    "markt {} wochenmarkt",
    "bauernmarkt {}",
    "wochenmarkt {} wo",
    "kunstmesse {}",
    "buchmesse {}",
    "messe {}",
    "theatervorstellung {}",
    "kinder event {} wochenende",
    "open air {} sommer",
    "street art {} tour",

    # Shopping
    "shopping {}",
    "einkaufen {}",
    "einkaufszentrum {}",
    "einkaufszentren {}",
    "shopping mall {}",
    "outlet {}",
    "outlet center {}",
    "flohmarkt {} kaufen",
    "secondhand {}",
    "vintage shop {}",
    "designerläden {}",
    "lokale geschäfte {}",
    "souvenirs {} kaufen",
    "souvenirs {} günstig",
    "bücher kaufen {}",
    "buchhandlung {}",
    "antikmarkt {}",
    "markt {} günstig",
    "supermarkt {} öffnungszeiten",
    "lebensmittel {} liefern",

    # Wohnen und Immobilien
    "wohnung mieten {}",
    "wohnung mieten {} günstig",
    "wohnung {} 2-zimmer",
    "wohnung {} 3-zimmer",
    "1-zimmer-wohnung {}",
    "studio wohnung mieten {}",
    "wg {} zimmer frei",
    "wg-zimmer {} suche",
    "wohnung kaufen {}",
    "haus kaufen {}",
    "immobilien {}",
    "immobilienpreise {}",
    "mietspiegel {}",
    "durchschnittliche miete {}",
    "miete {} pro m²",
    "immobilien {} investieren",
    "neubau {} wohnungen",
    "eigentumswohnung {} preis",
    "haus {} bauen kosten",
    "makler {}",
    "immobilienmakler {}",

    # Jobs und Karriere
    "jobs {}",
    "stellenangebote {}",
    "arbeit {} suchen",
    "job {} finden",
    "gehalt {} durchschnitt",
    "gehalt {} vergleich",
    "arbeitgeber {} top",
    "jobbörse {}",
    "praktikum {}",
    "ausbildung {} stellen",
    "lehrstelle {}",
    "werkstudent {}",
    "freelancer {} netzwerk",
    "startup {} szene",
    "karriere {}",

    # Bildung
    "universität {}",
    "uni {} studiengänge",
    "hochschule {}",
    "fachhochschule {}",
    "studieren {} kosten",
    "studentenwohnheim {}",
    "sprachschule {}",
    "deutschkurs {}",
    "englischkurs {}",
    "schule {} empfehlung",
    "gymnasium {}",
    "grundschule {}",
    "kindergarten {}",
    "kita {}",
    "weiterbildung {}",
    "online kurs {} lokal",

    # Gesundheit
    "arzt {}",
    "hausarzt {}",
    "arzt {} suchen",
    "arzt {} empfehlung",
    "facharzt {}",
    "zahnarzt {}",
    "zahnarzt {} günstig",
    "zahnarzt {} notfall",
    "krankenhaus {}",
    "klinik {}",
    "notaufnahme {}",
    "apotheke {}",
    "apotheke {} geöffnet",
    "apotheke {} nacht",
    "apotheke {} 24h",
    "tierarzt {}",
    "tierarzt {} notfall",
    "physiotherapie {}",
    "psychologe {}",
    "heilpraktiker {}",

    # Sport und Fitness
    "fitnessstudio {}",
    "fitnessstudio {} günstig",
    "fitnessstudio {} probe",
    "gym {}",
    "yoga {}",
    "yogastudio {}",
    "pilates {}",
    "schwimmbad {}",
    "schwimmbad {} öffnungszeiten",
    "freibad {}",
    "hallenbad {}",
    "sauna {}",
    "spa {}",
    "wellnesscenter {}",
    "kletteranlage {}",
    "kletterhalle {}",
    "laufstrecke {}",
    "joggen {} wo",
    "fahrradtour {} umgebung",
    "sportzentrum {}",
    "sportverein {}",
    "stadion {}",
    "fußballspiel {} tickets",
    "tennis {}",
    "golfplatz {}",
    "surf schule {}",
    "skateboard park {}",

    # Coworking und Remote Work
    "coworking space {}",
    "coworking {} günstig",
    "coworking {} tagespass",
    "coworking {} monatspass",
    "büro mieten {}",
    "schreibtisch mieten {}",
    "café mit wlan {}",
    "café {} arbeiten",
    "bibliothek {} wlan",
    "business center {}",

    # Stadtinfos
    "{} einwohnerzahl",
    "{} bevölkerung",
    "{} geschichte",
    "{} stadtplan",
    "{} karte",
    "{} postleitzahl",
    "{} vorwahl",
    "{} zeitzone",
    "{} höhe über meeresspiegel",
    "{} klimazone",
    "{} lage",
    "{} bundesland",
    "{} bürgermeister",
    "{} stadtgebiet",
    "{} stadtteile",
    "{} bezirke",
    "{} statistik",
    "{} wiki",
    "{} wikipedia",
    "{} offiziell webseite",
    "{} stadtrat",

    # Reiseplanung
    "beste reisezeit {}",
    "{} urlaub planen",
    "{} reiseführer",
    "{} reisebericht",
    "{} reiseblog",
    "{} backpacking tipps",
    "{} solo reisen",
    "{} mit kindern",
    "{} mit hund",
    "tagesausflug ab {}",
    "ausflug ab {}",
    "ausflugsziele {} umgebung",
    "ausflugsziele ab {} 1 stunde",
    "{} wochendtrip",
    "{} 3 tage plan",
    "{} kurzurlaub ideen",
    "{} budget reise",
    "{} luxusreise",
    "fotospots {}",
    "instagram {} highlights",
    "sonnenuntergang {} wo",
    "romantisch {} pärchen",
    "honeymoon {}",
    "geführte tour {}",
    "stadtführung {}",
    "free walking tour {}",
    "fahrradtour {} geführt",
    "bootstour {}",
    "kayak {}",
    "kanu mieten {}",

    # Währung und Praktisches
    "währung {}",
    "trinkgeld {} üblich",
    "sprache {}",
    "visa {} einreise",
    "einreise {} deutschland",
    "reisepass nötig {}",
    "sicherheit {} für touristen",
    "kriminalitätsrate {}",
    "notruf {}",
    "polizei {}",
    "botschaft {} berlin",
    "wlan {} kostenlos",
    "simkarte {}",
    "steckdose {} typ",

    # Lebenshaltungskosten
    "lebenshaltungskosten {}",
    "kosten {} leben",
    "wie teuer ist {}",
    "preisniveau {}",
    "wie viel geld {} urlaub",
    "budget {} pro tag",
    "günstig reisen {}",
    "sparen {}",
    "trinkgeldkultur {}",

    # Gastronomie speziell
    "frühstück {} günstig",
    "frühstück {} täglich",
    "frühstücksrestaurant {}",
    "mittagsmenü {} unter 10 euro",
    "lunch {} günstig",
    "take away {}",
    "lieferdienst {}",
    "essen bestellen {}",
    "lieferando {}",
    "wolt {}",
    "essen {} mitnehmen",
    "snack {} günstig",
    "imbiss {}",
    "currywurst {}",
    "pommes {}",
    "bäcker {} günstig",

    # Kinder und Familie
    "{} mit kindern sehenswürdigkeiten",
    "kinderfreundliche hotels {}",
    "kinderrestaurant {}",
    "kinderspielplatz {}",
    "spielplatz {}",
    "freizeitpark {}",
    "kinderprogramm {}",
    "babysitter {}",
    "kinderarzt {}",
    "kinder aktivitäten {}",
    "familienausflug {}",
    "familienhotel {}",

    # Haustiere
    "hundefreundlich {}",
    "hundefreundliche hotels {}",
    "hund mitnehmen {}",
    "hundepark {}",
    "tierheim {}",
    "tierhandlung {}",
    "hundesalon {}",

    # Barrierefreiheit
    "barrierefrei {}",
    "rollstuhlgerecht {}",
    "barrierefreie hotels {}",
    "rollstuhl {}",

    # Webcam und Live
    "webcam {}",
    "livecam {}",
    "webcam {} aktuell",
    "webcam {} strand",
    "webcam {} innenstadt",

    # Weitere nützliche Suchphrasen
    "{} blogbeitrag",
    "{} youtube tour",
    "ferienwohnung {} last minute",
    "hotel {} gutschein",
    "{} gratis sehenswürdigkeiten",
    "{} kostenlos",
    "gratis aktivitäten {}",
    "{} essen gehen empfehlung",
    "{} karte pdf",
    "{} audioguide",
    "führerschein umschreiben {}",
    "bürgeramt {}",
    "standesamt {}",
    "einwohnermeldeamt {}",
    "anmelden wohnsitz {}",
    "müllentsorgung {}",
    "recyclinghof {}",
    "stromanbieterwechsel {}",
    "internet anbieter {}",
    "gas anbieter {}",
    "steuerberater {}",
    "notar {}",
    "rechtsanwalt {}",
    "bank {} filiale",
    "geldautomat {}",
    "post {} öffnungszeiten",
    "paketshop {}",
    "friseur {}",
    "friseur {} günstig",
    "kosmetik {}",
    "nagelstudio {}",
    "tattoostudio {}",
    "wäscherei {}",
    "reinigung {}",
    "schlüsseldienst {}",
    "elektriker {}",
    "klempner {}",
    "umzugsunternehmen {}",
    "lagerraum mieten {}",
    "self storage {}",
    "autopflege {}",
    "autowerkstatt {}",
    "reifenwechsel {}",
    "tankstelle {}",
    "tankstelle {} günstig",
    "e-ladestelle {}",
    "e-auto laden {}",
    "fahrschule {}",
    "führerschein {} kosten",
    "hundebetreuung {}",
    "katzenbetreuung {}",
    "blumengeschäft {}",
    "apotheke {} homöopathie",
    "gesundheitsamt {}",
    "impfzentrum {}",
    "corona test {}",
    "covid test {}",
    "spielothek {}",
    "spielcasino {}",
    "escape room {}",
    "lasertag {}",
    "bowling {}",
    "minigolf {}",
    "kart {}",
    "go-kart {}",
    "paintball {}",
    "trampolin park {}",
    "indoorspielplatz {}",
    "badepark {}",
    "wasserpark {}",
    "eislaufen {}",
    "eisstadion {}",
    "ski {} lift",
    "skigebiet {} nähe",
    "wanderkarte {}",
    "bergwanderung {} einfach",
    "mountainbike trail {}",
    "fahrrad tour {} anfänger",
    "segway tour {}",
    "reiten {}",
    "reitschule {}",
    "paragliding {}",
    "fallschirmspringen {}",
    "tauchen {}",
    "tauchschule {}",
    "kitesurfing {}",
    "surfen {}",
    "wellness {} tageskarte",
    "thermalbad {}",
    "heilbad {}",
    "kurort {}",
    "naturheilmittel {}",
    "reformhaus {}",
    "bio supermarkt {}",
    "bio markt {}",
    "demeter hof {}",
    "obst und gemüse {}",
    "asia supermarkt {}",
    "türkischer supermarkt {}",
    "halal supermarkt {}",
    "kosher supermarkt {}",
    "weinkauf {}",
    "weinhandlung {}",
    "whisky shop {}",
    "rum shop {}",
    "feinkost {}",
    "delicatessen {}",
    "chocolaterie {}",
    "pralinenhersteller {}",
    "käserei {}",
    "metzgerei {}",
    "fischmarkt {}",
    "frischfisch {}",
    "wochenmarkt {} samstag",
    "farmer's market {}",
    "gemüsebox {}",
    "lieferkiste {}",
    "musik kaufen {}",
    "plattenladen {}",
    "gitarre kaufen {}",
    "musikschule {}",
    "kunstschule {}",
    "kunstatelier {}",
    "töpfern {}",
    "kochkurs {}",
    "backworkshop {}",
    "weinkurs {}",
    "bierkurs {}",
    "cocktailkurs {}",
    "yoga retreat {}",
    "meditation {}",
    "meditationskurs {}",
    "achtsamkeit {}",
    "buddhismus {}",
    "kirche {} gottesdienst",
    "moschee {}",
    "synagoge {}",
    "tempel {}",
    "friedhof {} bedeutend",
    "kriegsgräber {}",
    "memorial {}",
    "mahnmal {}",
    "gedenkstätte {}",
    "stadtspaziergang {}",
    "stadtviertel {} empfehlung",
    "gentrifizierung {}",
    "hipster viertel {}",
    "studentenviertel {}",
    "bahnhofsviertel {}",
    "lateinisches viertel {}",
    "chinatown {}",
    "straßenkunst {} galerie",
    "street art tour {}",
    "graffiti {}",
    "architektur {} tour",
    "moderne architektur {}",
    "jugendstil {}",
    "bauhaus {}",
    "industriekultur {}",
    "fabrik {} kultur",
    "kreativzentrum {}",
    "kulturzentrum {}",
    "kulturpalast {}",
    "congress center {}",
    "messe {} aussteller",
    "trade fair {}",
    "konferenz {}",
    "tagungshotel {}",
    "businesshotel {}",
    "airporthotel {}",
    "kapsule hotel {}",
    "baumhaushotel {}",
    "hausboot mieten {}",
    "hausboot {} urlaub",
    "wohnwagen {}",
    "naturcamping {}",
    "glamping {}",
    "{} natur highlights",
    "{} naturpark",
    "nationalpark {}",
    "biosphärenreservat {}",
    "vogelbeobachtung {}",
    "sternenhimmel {} wo beobachten",
    "planetarium {}",
    "sternwarte {}",
    "observatorium {}",
    "wissenschaftszentrum {}",
    "science center {}",
    "kinder museum {}",
    "mitmachmuseum {}",
    "erlebnispädagogik {}",
    "schulausflug {} ideen",
    "bachelor party {}",
    "junggesellenabschied {}",
    "geburtstag feiern {}",
    "hochzeitslocation {}",
    "hochzeit {}",
    "event location {}",
    "location mieten {}",
    "firmenfeier {}",
    "teambuilding {}",
    "seminarzentrum {}",
    "workation {}",
    "digital nomad {}",
    "expat {}",
    "expats {} community",
    "austausch {} studenten",
    "erasmus {}",
    "welcome center {}",
    "integration {}",
    "sprachbarriere {}",
    "dolmetscher {}",
    "{} auf englisch",
    "{} englischsprachig",
    "international community {}",
    "nachbarschaft {} aktiv",
    "verein {} beitreten",
    "ehrenamt {}",
    "volunteering {}",
    "foodbank {}",
    "kleiderspende {}",
    "tauschbörse {}",
    "repair café {}",
    "upcycling {}",
    "nachhaltigkeit {}",
    "zero waste {}",
    "klimaschutz {}",
    "fahrradfreundlich {}",
    "fußgängerzone {}",
    "parkanlage {}",
    "grünanlagen {}",
    "freizeit {} natur",
    "{} dorf oder stadt",
    "kleinstadt {} leben",
    "großstadt {} zuzug",
    "zuzug {} tipps",
    "umzug nach {}",
    "nach {} ziehen",
    "{} lebensqualität",
    "{} ranking lebensqualität",
    "{} platz zum leben",
    "{} für familien",
    "{} für singles",
    "{} für rentner",
    "{} für studenten",
    "{} fürs alter",
    "pension {} beantragen",
    "rentenamt {}",
    "sozialamt {}",
    "jobcenter {}",
    "arbeitsamt {}",
    "finanzamt {}",
    "gemeindeverwaltung {}",
    "stadtamt {}",
    "kreisamt {}",
    "landkreis {}",
    "bürgerservice {}",
    "online bürgerportal {}",
    "personalausweis {}",
    "reisepass beantragen {}",
    "führerschein {} umschreiben",
    "auto ummelden {}",
    "kfz zulassungsstelle {}",
    "hundesteuer {}",
    "kirchensteuer {}",
    "grundsteuer {}",
    "müllgebühren {}",
    "friedhof {} beerdigung",
    "bestattung {}",
    "bestattungsunternehmen {}",
    "krematorium {}",
    "urnenbeisetzung {}",
    "seestattung ab {}",
    "friedwald {}",
    "grabpflege {}",
    "seniorenheim {}",
    "pflegeheim {}",
    "altersresidenz {}",
    "betreutes wohnen {}",
    "pflege zuhause {}",
    "haushaltshilfe {}",
    "kinderbetreuung {}",
    "tagesmutter {}",
    "hort {}",
    "ganztagsschule {}",
    "nachhilfe {}",
    "lernhilfe {}",
    "ergotherapie {}",
    "logopädie {}",
    "frühförderung {}",
    "inklusionsschule {}",
    "berufsschule {}",
    "berufsberatung {}",
    "agentur für arbeit {}",
    "ivk {}",
    "beratungsstelle {}",
    "drogenberatung {}",
    "suchtberatung {}",
    "krisentelefon {}",
    "frauenhaus {}",
    "männerberatung {}",
    "jugendamt {}",
    "soziale einrichtungen {}",
    "ngo {}",
    "wohltätigkeitsorganisation {}",
    "kulturelle integration {}",
    "interkulturelles zentrum {}",
    "migrationsberatung {}",
    "geflüchtete hilfe {}",
    "flüchtlingshilfe {}",
    "sprachkurs geflüchtete {}",
    "bildungsberatung {}",
    "anerkennungsberatung {}",
    "studienberatung {}",
    "auslandsamt {}",
    "bafög {}",
    "stipendium {}",
    "bildungsgutschein {}",
    "elterngeld {}",
    "kindergeld {}",
    "wohngeld {}",
    "wohnungslosenhilfe {}",
    "obdachlose {}",
    "tafel {}",
    "lebensmittelspende {}",
    "kleiderkammer {}",
    "sozialkaufhaus {}",
    "drogerie {} angebote",
    "dm {}",
    "rossmann {}",
    "rewe {}",
    "edeka {}",
    "aldi {}",
    "lidl {}",
    "penny {}",
    "netto {}",
    "kaufland {}",
    "real {}",
    "ikea {}",
    "möbel {}",
    "möbelhaus {}",
    "möbel gebraucht {}",
    "kleinanzeigen {}",
    "ebay kleinanzeigen {}",
    "gebrauchtwaren {}",
    "trödelmarkt {}",
    "kfz händler {}",
    "gebrauchtwagen {}",
    "auto kaufen {}",
    "motorrad kaufen {}",
    "fahrrad kaufen {}",
    "e-bike kaufen {}",
    "elektroauto kaufen {}",
    "e-auto {} laden",
    "photovoltaik {}",
    "solaranlage {}",
    "wärmepumpe {}",
    "energieberatung {}",
    "sanitär {}",
    "heizung {}",
    "dachdecker {}",
    "maurer {}",
    "zimmermann {}",
    "innenausbau {}",
    "küche kaufen {}",
    "badezimmer renovation {}",
    "bad renovation {}",
    "gartengestaltung {}",
    "landschaftsgärtner {}",
    "gartenpflege {}",
    "gartencenter {}",
    "pflanzen kaufen {}",
    "baumschulen {}",
    "gartenmarkt {}",
    "baumarkt {}",
    "hornbach {}",
    "obi {}",
    "hagebaumarkt {}",
    "elektrohändler {}",
    "mediamarkt {}",
    "saturn {}",
    "laptop kaufen {}",
    "handy kaufen {}",
    "computerreparatur {}",
    "handyreparatur {}",
    "drucker kaufen {}",
    "fotograf {}",
    "fotostudio {}",
    "fotos entwickeln {}",
    "optiker {}",
    "brille kaufen {}",
    "hörakustiker {}",
    "orthopäde {}",
    "orthopädieschuhmacher {}",
    "sportartikel {}",
    "sportgeschäft {}",
    "outdoor ausrüstung {}",
    "bergsport {}",
    "tauchen ausrüstung {}",
    "angeln {}",
    "angelschein {}",
    "jagd {}",
    "jagdschein {}",
    "kfz versicherung {}",
    "hausratversicherung {}",
    "krankenversicherung {}",
    "rentenversicherung {}",
    "versicherungsberater {}",
    "versicherungsmakler {}",
    "bank {} konto eröffnen",
    "direktbank {} konto",
    "sparkasse {}",
    "volksbank {}",
    "commerzbank {}",
    "deutsche bank {}",
    "ing {}",
    "finanzberater {}",
    "investment {}",
    "aktien {}",
    "etf {}",
    "immobilien investition {}",
    "rendite {}",
    "immobilienfonds {}",
    "erbschaft {}",
    "testamentberatung {}",
    "scheidungsanwalt {}",
    "familienrecht {}",
    "erbrecht {}",
    "arbeitsrecht {}",
    "mietrecht {}",
    "verbraucherrecht {}",
    "verbraucherzentrale {}",
    "bürgerrechte {}",
    "demokratie {}",
    "wahlen {}",
    "parteibüro {}",
    "bürgerinitiative {}",
    "stadtentwicklung {}",
    "stadtplanung {}",
    "neubaugebiet {}",
    "bebauungsplan {}",
    "baugenehmigung {}",
    "gastronomiegenehmigung {}",
    "gewerbe anmelden {}",
    "existenzgründung {}",
    "gründerzentrum {}",
    "inkubator {}",
    "startup {}",
    "co-founder {}",
    "netzwerkveranstaltung {}",
    "businessplan beratung {}",
    "kammer {} ihk",
    "handelskammer {}",
    "handwerkskammer {}",
    "berufsverband {}",
    "gewerkschaft {}",
    "betriebsrat {}",
    "hr {}",
    "recruiting {}",
    "headhunter {}",
    "personal agentur {}",
    "zeitarbeit {}",
    "minijob {}",
    "nebenjob {}",
    "home office {}",
    "remote job {}",
    "telearbeit {}",
    "freelance {}",
    "selbstständig {}",
    "gewerbe {}",
    "buchhalter {}",
    "bilanzbuchhalter {}",
    "wirtschaftsprüfer {}",
    "inkasso {}",
    "schuldenberatung {}",
    "privatinsolvenz {}",
    "pfändung {}",
    "insolvenzverwalter {}",
    "sanierung {}",
    "konkurs {}",
    "pleite {}",
    "liquidation {}",
    "immobilienversteigerung {}",
    "zwangsversteigerung {}",
    "auktion {}",
    "kunst auktion {}",
    "auto auktion {}",
]
