"""English word lists for data poisoning (see browser/decoy.py)."""

CITIES = [
    "new york",     "los angeles",     "chicago",     "houston",     "phoenix",     "philadelphia",
    "san antonio",     "san diego",     "dallas",     "san jose",     "austin",     "jacksonville",
    "fort worth",     "columbus",     "charlotte",     "indianapolis",     "san francisco",     "seattle",
    "denver",     "nashville",     "oklahoma city",     "el paso",     "washington",     "las vegas",
    "louisville",     "memphis",     "portland",     "baltimore",     "milwaukee",     "albuquerque",
    "tucson",     "fresno",     "mesa",     "kansas city",     "atlanta",     "omaha",
    "colorado springs",     "raleigh",     "long beach",     "virginia beach",     "minneapolis",     "tampa",
    "new orleans",     "arlington",     "wichita",     "aurora",     "bakersfield",     "anaheim",
    "santa ana",     "corpus christi",     "riverside",     "st. louis",     "lexington",     "pittsburgh",
    "anchorage",     "stockton",     "cincinnati",     "st. paul",     "toledo",     "greensboro",
    "newark",     "plano",     "henderson",     "lincoln",     "buffalo",     "fort wayne",
    "jersey city",     "chula vista",     "orlando",     "st. petersburg",     "norfolk",     "chandler",
    "laredo",     "madison",     "durham",     "lubbock",     "winston-salem",     "garland",
    "glendale",     "hialeah",     "reno",     "baton rouge",     "irvine",     "chesapeake",
    "scottsdale",     "north las vegas",     "fremont",     "gilbert",     "san bernardino",     "birmingham",
    "rochester",     "richmond",     "spokane",     "des moines",     "montgomery",     "modesto",
    "fayetteville",     "tacoma",     "shreveport",     "frisco",     "akron",     "yonkers",
    "huntington beach",     "salt lake city",     "grand rapids",     "tallahassee",     "huntsville",     "worcester",
    "knoxville",     "providence",     "brownsville",     "santa clarita",     "garden grove",     "fort lauderdale",
    "chattanooga",     "oceanside",     "rancho cucamonga",     "santa rosa",     "tempe",     "cape coral",
    "oxnard",     "ontario",     "elk grove",     "eugene",     "peoria",     "salem",
    "corona",     "springfield",     "fort collins",     "jackson",     "alexandria",     "hayward",
    "lancaster",     "salinas",     "palmdale",     "sunnyvale",     "pomona",     "escondido",
    "torrance",     "pasadena",     "paterson",     "savannah",     "metairie",     "surprise",
    "roseville",     "macon",     "dayton",     "bridgeport",     "clarksville",     "syracuse",
    "mcallen",     "lakewood",     "hollywood",     "murfreesboro",     "columbia",     "athens",
    "mobile",     "little rock",     "amarillo",     "grand prairie",     "overland park",     "cedar rapids",
    "sioux falls",     "erie",     "cary",     "coral springs",     "west palm beach",     "rockford",
    "clearwater",     "topeka",     "vallejo",     "sterling heights",     "ann arbor",     "thousand oaks",
    "visalia",     "concord",     "hartford",     "denton",     "lansing",     "killeen",
    "beaumont",     "flint",     "santa clara",     "elgin",     "round rock",     "miramar",
    "mesquite",     "waco",     "olathe",     "mckinney",     "london",     "manchester",
    "glasgow",     "liverpool",     "leeds",     "sheffield",     "edinburgh",     "bristol",
    "leicester",     "coventry",     "bradford",     "nottingham",     "cardiff",     "belfast",
    "hull",     "stoke-on-trent",     "wolverhampton",     "plymouth",     "southampton",     "reading",
    "derby",     "middlesbrough",     "luton",     "swindon",     "newcastle",     "portsmouth",
    "brighton",     "oxford",     "cambridge",     "toronto",     "montreal",     "vancouver",
    "calgary",     "edmonton",     "ottawa",     "winnipeg",     "quebec city",     "hamilton",
    "kitchener",     "victoria",     "halifax",     "saskatoon",     "regina",     "kelowna",
    "abbotsford",     "barrie",     "sydney",     "melbourne",     "brisbane",     "perth",
    "adelaide",     "gold coast",     "canberra",     "sunshine coast",     "wollongong",     "geelong",
    "hobart",     "townsville",     "cairns",     "toowoomba",     "darwin",     "ballarat",
    "bendigo",     "paris",     "berlin",     "madrid",     "rome",     "vienna",
    "amsterdam",     "brussels",     "prague",     "budapest",     "warsaw",     "bucharest",
    "stockholm",     "copenhagen",     "oslo",     "helsinki",     "lisbon",     "zurich",
    "geneva",     "basel",     "munich",     "hamburg",     "cologne",     "frankfurt",
    "stuttgart",     "dusseldorf",     "milan",     "florence",     "venice",     "naples",
    "turin",     "bologna",     "genoa",     "barcelona",     "seville",     "bilbao",
    "valencia",     "malaga",     "zaragoza",     "rotterdam",     "the hague",     "utrecht",
    "antwerp",     "ghent",     "bruges",     "lyon",     "marseille",     "toulouse",
    "nice",     "nantes",     "strasbourg",     "bordeaux",     "lausanne",     "bern",
    "lucerne",     "lugano",     "st gallen",     "graz",     "salzburg",     "innsbruck",
    "linz",     "klagenfurt",     "moscow",     "novosibirsk",     "yekaterinburg",     "kazan",
    "nizhny novgorod",     "chelyabinsk",     "samara",     "omsk",     "rostov-on-don",     "beijing",
    "shanghai",     "guangzhou",     "shenzhen",     "chengdu",     "chongqing",     "wuhan",
    "xian",     "hangzhou",     "nanjing",     "tianjin",     "shenyang",     "harbin",
    "qingdao",     "zhengzhou",     "jinan",     "changsha",     "dalian",     "tokyo",
    "osaka",     "yokohama",     "nagoya",     "sapporo",     "kobe",     "kyoto",
    "fukuoka",     "kawasaki",     "saitama",     "hiroshima",     "sendai",     "kitakyushu",
    "seoul",     "busan",     "incheon",     "daegu",     "daejeon",     "gwangju",
    "suwon",     "delhi",     "mumbai",     "bangalore",     "hyderabad",     "ahmedabad",
    "chennai",     "kolkata",     "surat",     "pune",     "jaipur",     "lucknow",
    "kanpur",     "nagpur",     "indore",     "thane",     "bhopal",     "visakhapatnam",
    "patna",     "vadodara",     "jakarta",     "surabaya",     "bandung",     "medan",
    "semarang",     "palembang",     "makassar",     "tangerang",     "depok",     "south tangerang",
    "manila",     "quezon city",     "davao",     "caloocan",     "cebu",     "zamboanga",
    "kuala lumpur",     "george town",     "ipoh",     "johor bahru",     "petaling jaya",     "singapore",
    "bangkok",     "chiang mai",     "pattaya",     "phuket",     "hat yai",     "ho chi minh city",
    "hanoi",     "da nang",     "hai phong",     "can tho",     "taipei",     "kaohsiung",
    "taichung",     "tainan",     "new taipei",     "hong kong",     "macau",     "dubai",
    "abu dhabi",     "sharjah",     "doha",     "riyadh",     "jeddah",     "mecca",
    "medina",     "kuwait city",     "manama",     "muscat",     "tehran",     "istanbul",
    "ankara",     "izmir",     "bursa",     "antalya",     "konya",     "tel aviv",
    "jerusalem",     "haifa",     "beirut",     "amman",     "baghdad",     "cairo",
    "giza",     "casablanca",     "rabat",     "marrakech",     "tunis",     "algiers",
    "tripoli",     "accra",     "lagos",     "abuja",     "ibadan",     "nairobi",
    "mombasa",     "dar es salaam",     "kampala",     "addis ababa",     "cape town",     "johannesburg",
    "durban",     "pretoria",     "port elizabeth",     "harare",     "lusaka",     "maputo",
    "luanda",     "kinshasa",     "dakar",     "abidjan",     "khartoum",     "antananarivo",
    "mogadishu",     "mexico city",     "guadalajara",     "monterrey",     "puebla",     "tijuana",
    "leon",     "juarez",     "zapopan",     "nezahualcoyotl",     "chihuahua",     "sao paulo",
    "rio de janeiro",     "brasilia",     "salvador",     "fortaleza",     "belo horizonte",     "manaus",
    "curitiba",     "recife",     "porto alegre",     "buenos aires",     "cordoba",     "rosario",
    "mendoza",     "san miguel de tucuman",     "bogota",     "medellin",     "cali",     "barranquilla",
    "cartagena",     "bucaramanga",     "lima",     "arequipa",     "trujillo",     "chiclayo",
    "santiago",     "valparaiso",     "concepcion",     "antofagasta",     "caracas",     "maracaibo",
    "barquisimeto",     "quito",     "guayaquil",     "cuenca",     "montevideo",     "asuncion",
    "la paz",     "santa cruz",     "cochabamba",     "havana",     "panama city",     "santo domingo",
    "san juan",     "kingston",     "port-au-prince",     "guatemala city",     "tegucigalpa",     "managua",
    "san salvador",     "reykjavik",     "valletta",     "nicosia",     "tirana",     "skopje",
    "sarajevo",     "podgorica",     "belgrade",     "zagreb",     "ljubljana",     "bratislava",
    "vilnius",     "riga",     "tallinn",     "chisinau",     "minsk",     "sofia",
    "tbilisi",     "yerevan",     "baku",     "almaty",     "tashkent",     "bishkek",
    "ashgabat",     "kabul",     "islamabad",     "karachi",     "lahore",     "faisalabad",
    "kathmandu",     "colombo",     "dhaka",     "chittagong",     "yangon",     "naypyidaw",
    "phnom penh",     "vientiane",     "ulaanbaatar",     "pyongyang",     "auckland",     "wellington",
    "christchurch",     "honolulu",     "juneau",     "fairbanks",     "sitka",     "miami",
    "pensacola",     "daytona beach",     "fort myers",     "boise",     "billings",     "cheyenne",
    "helena",     "fargo",     "rapid city",     "bismarck",     "pierre",     "casper",
    "missoula",     "great falls",     "pocatello",     "twin falls",     "green bay",     "eau claire",
    "appleton",     "oshkosh",     "traverse city",     "kalamazoo",     "saginaw",     "duluth",
    "st cloud",     "mankato",     "iowa city",     "waterloo",     "ames",     "council bluffs",
    "manhattan",     "lawrence",     "salina",     "hutchinson",     "tulsa",     "norman",
    "broken arrow",     "edmond",     "springdale",     "jonesboro",     "fort smith",     "pine bluff",
    "gulfport",     "biloxi",     "hattiesburg",     "meridian",     "greenville",     "spartanburg",
    "rock hill",     "asheville",     "wilmington",     "high point",     "huntington",     "morgantown",
    "parkersburg",     "wheeling",     "bowling green",     "owensboro",     "paducah",     "frankfort",
    "augusta",     "warner robins",     "valdosta",     "pompano beach",     "ogden",     "provo",
    "st george",     "orem",     "carson city",     "sparks",     "flagstaff",     "yuma",
    "prescott",     "santa fe",     "las cruces",     "roswell",     "clovis",     "abilene",
    "midland",     "tyler",     "lake charles",     "monroe",     "joplin",     "cape girardeau",
    "bozeman",     "butte",     "grand island",     "north platte",     "bellevue",     "aberdeen",
    "brookings",     "grand forks",     "minot",     "rochester mn",     "st cloud mn",     "brainerd",
    "sierra vista",     "porto",     "funchal",     "setubal",     "coimbra",     "granada",
    "salamanca",     "alicante",     "catania",     "palermo",     "bari",     "reggio calabria",
    "eindhoven",     "tilburg",     "groningen",     "arnhem",     "liege",     "namur",
    "charleroi",     "leuven",     "nuremberg",     "augsburg",     "mannheim",     "karlsruhe",
    "aarhus",     "odense",     "aalborg",     "esbjerg",     "gothenburg",     "malmo",
    "uppsala",     "linkoping",     "tampere",     "oulu",     "turku",     "jyvaskyla",
    "bergen",     "trondheim",     "stavanger",     "tromsoe",     "wroclaw",     "krakow",
    "lodz",     "poznan",     "debrecen",     "miskolc",     "pecs",     "gyor",
    "timisoara",     "cluj-napoca",     "iasi",     "constanta",     "varna",     "plovdiv",
    "ruse",     "burgas",     "thessaloniki",     "patras",     "heraklion",     "larissa",
    "kaunas",     "klaipeda",     "siauliai",     "panevezys",     "tartu",     "narva",
    "parnu",     "viljandi",     "daugavpils",     "liepaja",     "jelgava",     "jurmala",
    "kharkiv",     "odessa",     "dnipro",     "donetsk",     "grodno",     "gomel",
    "brest",     "fez",     "tangier",     "agadir",     "sfax",     "sousse",
    "bizerte",     "oran",     "constantine",     "annaba",     "tlemcen",     "kisumu",
    "nakuru",     "entebbe",     "jinja",     "gulu",     "kumasi",     "tamale",
    "cape coast",     "bouake",     "yamoussoukro",     "korhogo",     "thies",     "kaolack",
    "ziguinchor",     "conakry",     "freetown",     "monrovia",     "port harcourt",     "kano",
    "benin city",     "dire dawa",     "gondar",     "mekelle",     "kigali",     "butare",
    "gisenyi",     "musanze",     "ndola",     "kitwe",     "livingstone",     "bulawayo",
    "mutare",     "gweru",     "matola",     "beira",     "nampula",     "toamasina",
    "antsirabe",     "fianarantsoa",     "east london",     "bloemfontein",     "nelspruit",     "windhoek",
    "walvis bay",     "swakopmund",     "rundu",     "gaborone",     "francistown",     "maun",
    "kasane",     "al rayyan",     "al wakrah",     "dukhan",     "salalah",     "sohar",
    "nizwa",     "salmiya",     "hawalli",     "al ahmadi",     "riffa",     "muharraq",
    "hamad",     "gyumri",     "vanadzor",     "vagharshapat",     "kutaisi",     "batumi",
    "rustavi",     "ganja",     "sumgait",     "nakhchivan",     "samarkand",     "bukhara",
    "namangan",     "osh",     "jalal-abad",     "karakol",     "dushanbe",     "khujand",
    "kulob",     "qurghonteppa",     "turkmenabat",     "mary",     "dashoguz",     "pokhara",
    "lalitpur",     "bharatpur",     "kandy",     "galle",     "jaffna",     "khulna",
    "rajshahi",     "mandalay",     "bago",     "siem reap",     "sihanoukville",     "battambang",
    "luang prabang",     "savannakhet",     "pakse",     "suva",     "nadi",     "lautoka",
    "labasa",     "port moresby",     "lae",     "mount hagen",     "madang",     "honiara",
    "apia",     "nuku alofa",     "port vila",
]

TEMPLATES = [
    "weather {} today",
    "weather {} tomorrow",
    "weather {} this weekend",
    "weather {} forecast 10 days",
    "weather {} right now",
    "current temperature {}",
    "is it raining in {} today",
    "best hotels in {}",
    "cheap hotels in {}",
    "luxury hotels in {}",
    "boutique hotels in {}",
    "hotels near downtown {}",
    "airbnb {} city center",
    "hostel {} best rated",
    "bed and breakfast {}",
    "motels in {} cheap",
    "best restaurants in {}",
    "cheap eats in {}",
    "fine dining {}",
    "vegan restaurants {}",
    "vegetarian food {}",
    "best pizza in {}",
    "best sushi {}",
    "best ramen {}",
    "best tacos {}",
    "best burgers {}",
    "best brunch {}",
    "best breakfast spots {}",
    "best coffee shops {}",
    "best bakeries {}",
    "best seafood restaurants {}",
    "romantic restaurants {}",
    "rooftop restaurants {}",
    "late night food {}",
    "food delivery {}",
    "things to do in {}",
    "top attractions {}",
    "must see places {}",
    "tourist spots {}",
    "hidden gems {}",
    "museums in {}",
    "art galleries {}",
    "parks in {}",
    "best beaches near {}",
    "hiking trails near {}",
    "nature walks {}",
    "botanical garden {}",
    "zoo {}",
    "aquarium {}",
    "things to do in {} with kids",
    "free things to do {}",
    "weekend activities {}",
    "day trips from {}",
    "flights to {}",
    "cheap flights to {}",
    "direct flights to {} from london",
    "flights from new york to {}",
    "train to {}",
    "bus to {}",
    "car rental {}",
    "parking in {}",
    "public transport {}",
    "metro map {}",
    "uber {} available",
    "taxi {} price",
    "airport transfer {}",
    "how to get from airport to {} center",
    "events in {} this weekend",
    "concerts in {} tonight",
    "festivals {} 2026",
    "live music {}",
    "comedy shows {}",
    "theater {}",
    "opera {}",
    "exhibitions {}",
    "sports events {}",
    "nightlife {}",
    "best bars in {}",
    "best clubs {}",
    "rooftop bars {}",
    "craft beer {}",
    "wine bars {}",
    "cocktail bars {}",
    "gay bars {}",
    "karaoke {}",
    "shopping in {}",
    "best shopping malls {}",
    "flea market {}",
    "farmers market {}",
    "vintage shops {}",
    "outlet stores near {}",
    "souvenirs {}",
    "apartment for rent {}",
    "studio apartment rent {}",
    "furnished apartment {}",
    "short term rental {}",
    "house for sale {}",
    "condo for sale {}",
    "real estate {} prices",
    "average rent {}",
    "cost of living {}",
    "jobs in {}",
    "hiring {} 2026",
    "remote jobs {}",
    "it jobs {}",
    "engineering jobs {}",
    "graduate jobs {}",
    "internship {}",
    "universities in {}",
    "best universities {}",
    "colleges {}",
    "schools {}",
    "language schools {}",
    "coworking spaces {}",
    "best coworking {}",
    "cafe with wifi {}",
    "library {} open hours",
    "gym membership {}",
    "best gyms {}",
    "yoga studios {}",
    "pilates {}",
    "swimming pool {}",
    "doctor {}",
    "dentist {}",
    "hospital {}",
    "pharmacy {}",
    "urgent care {}",
    "population of {}",
    "history of {}",
    "map of {}",
    "zip code {}",
    "area code {}",
    "time zone {}",
    "currency used in {}",
    "is {} safe to visit",
    "safety tips {}",
    "visa requirements {}",
    "best time to visit {}",
    "how many days in {}",
    "{} travel guide",
    "{} itinerary 3 days",
    "{} itinerary 5 days",
    "what to pack for {}",
    "language spoken in {}",
    "best neighborhoods in {}",
    "how to get around {}",
    "{} city center",
    "is {} expensive",
    "{} budget travel tips",
    "{} for solo travel",
    "{} backpacker guide",
    "expat life {}",
    "moving to {}",
    "living in {} pros and cons",
    "{} digital nomad",
    "best vpn for {}",
    "sim card {}",
    "internet speed {}",
    "public holidays {} 2026",
    "sunrise sunset {}",
    "best viewpoints {}",
    "castle in {}",
    "cathedral {}",
    "old town {}",
    "waterfront {}",
    "botanical gardens {}",
    "national park near {}",
    "camping near {}",
    "kayaking near {}",
    "cycling routes {}",
    "scuba diving near {}",
    "surf lessons {}",
    "ski resort near {}",
    "spa hotels {}",
    "wellness retreat {}",
    "pet friendly hotels {}",
    "{} travel blog",
    "{} travel vlog youtube",
    "reddit {} travel tips",
    "tripadvisor {}",
    "best instagram spots {}",
    "photography spots {}",
    "{} street food guide",
    "local food {} must try",
    "traditional food {}",
    "best markets {}",
    "night market {}",
    "street art {}",
    "graffiti tour {}",
    "architecture {}",
    "film locations {}",
    "walking tour {}",
    "free walking tour {}",
    "bike tour {}",
    "boat tour {}",
    "helicopter tour {}",
    "car hire {}",
    "electric scooter rental {}",
    "airport lounge {}",
    "best airport {}",
    "terminal {} departures",
    "arrivals {}",
    "cruise port {}",
    "ferry to {}",
    "train station {}",
    "bus station {}",
    "drive from london to {}",
    "road trip {}",
    "rv park {}",
    "dog friendly {}",
    "accessible travel {}",
    "wheelchair friendly {}",
    "solo female travel {}",
    "lgbt friendly {}",
    "best month to go to {}",
    "rainy season {}",
    "temperature {} in july",
    "temperature {} in december",
    "does it snow in {}",
    "humidity {} in summer",
    "earthquake risk {}",
    "crime rate {}",
    "pollution {} air quality",
    "tap water safe {}",
    "mosquito risk {}",
    "local emergency number {}",
    "embassy in {}",
    "consulate {}",
    "covid entry requirements {}",
    "customs rules {}",
    "tipping culture {}",
    "drinking age {}",
    "dress code {}",
    "etiquette {}",
    "best travel insurance for {}",
    "travel adapter {}",
    "atm fees {}",
    "credit cards accepted {}",
    "cash or card {}",
    "exchange rate {}",
    "money changers {}",
    "cheap flights {} to bangkok",
    "how far is {} from london",
    "distance {} to paris",
    "{} vs london comparison",
    "salary in {}",
    "average wage {}",
    "tax rate {}",
    "startups {}",
    "tech scene {}",
    "best tech companies {}",
    "networking events {}",
    "conferences {} 2026",
    "meetup events {}",
]

STANDALONE = [
    "how to learn python in 2026",
    "best programming languages 2026",
    "python vs javascript which to learn first",
    "how to become a software developer",
    "free coding courses online",
    "best laptops for programming 2026",
    "mechanical keyboard recommendation 2026",
    "best monitor for developers",
    "standing desk benefits",
    "how to set up a home office",
    "best noise cancelling headphones 2026",
    "rtx 5090 review",
    "amd ryzen 9800x3d benchmark",
    "best gaming cpu 2026",
    "nvidia vs amd gpu comparison",
    "how to build a pc step by step",
    "best budget gaming pc 2026",
    "gaming pc under 1000",
    "is 32gb ram enough for gaming",
    "best nvme ssd 2026",
    "pcie 5.0 ssd worth it",
    "how to overclock cpu safely",
    "best gaming mouse 2026",
    "best gaming headset 2026",
    "ultrawide monitor worth it",
    "4k vs 1440p gaming 2026",
    "240hz monitor difference noticeable",
    "how to reduce input lag",
    "best fps settings valorant",
    "how to improve aim in fps games",
    "best minecraft mods 2026",
    "minecraft shader pack performance",
    "how to set up a minecraft server",
    "best survival games 2026",
    "best open world games 2026",
    "elden ring tips for beginners",
    "how to get better at chess",
    "chess openings for beginners",
    "best chess app 2026",
    "how to start learning guitar",
    "best acoustic guitar for beginners",
    "guitar chord chart printable",
    "how long to learn guitar",
    "fingerpicking vs strumming guitar",
    "best guitar learning app 2026",
    "how to read guitar tabs",
    "music theory basics for guitarists",
    "best daw software 2026",
    "how to make beats at home",
    "mixing and mastering tips",
    "best microphone for home recording",
    "audio interface for beginners",
    "how to start photography",
    "best camera for beginners 2026",
    "mirrorless vs dslr which is better",
    "best camera lens for portraits",
    "photo editing tutorial lightroom",
    "lightroom vs photoshop comparison",
    "how to shoot in raw format",
    "street photography tips",
    "night photography settings",
    "best photo editing software free",
    "how to start a youtube channel",
    "video editing software 2026",
    "best laptop for video editing",
    "final cut pro vs premiere pro",
    "davinci resolve tutorial for beginners",
    "how to grow on youtube",
    "best microphone for podcast",
    "how to start a podcast 2026",
    "podcast hosting platform comparison",
    "how to monetize a blog",
    "best website builder 2026",
    "wordpress vs squarespace",
    "how to start a website for free",
    "best hosting for wordpress 2026",
    "seo tips for beginners 2026",
    "how to write good meta descriptions",
    "keyword research tools free",
    "google analytics tutorial",
    "how to do email marketing",
    "best email marketing platform 2026",
    "mailchimp vs convertkit comparison",
    "passive income ideas online 2026",
    "how to invest in index funds",
    "etf vs index fund difference",
    "best broker for beginners 2026",
    "how to start investing at 20",
    "compound interest calculator",
    "how much to save per month",
    "emergency fund how much",
    "budgeting methods comparison",
    "50/30/20 rule explained",
    "how to pay off student loans fast",
    "credit card debt strategy",
    "best credit card cashback 2026",
    "how to improve credit score fast",
    "tax deductions self employed",
    "how to file taxes online",
    "tax software comparison 2026",
    "capital gains tax explained",
    "crypto tax 2026",
    "is bitcoin a good investment 2026",
    "ethereum price prediction",
    "best crypto to buy 2026",
    "how to buy bitcoin safely",
    "hardware wallet best 2026",
    "defi explained simply",
    "stock market basics for beginners",
    "how to read a balance sheet",
    "dividend investing strategy",
    "value investing principles",
    "best books about investing",
    "warren buffett investment advice",
    "real estate investing for beginners",
    "how to buy your first house",
    "mortgage calculator 2026",
    "down payment assistance programs",
    "renting vs buying house comparison",
    "how to negotiate salary",
    "freelancing tips for beginners",
    "best freelance platforms 2026",
    "upwork vs fiverr comparison",
    "how to write a resume 2026",
    "best resume templates 2026",
    "cover letter tips",
    "linkedin profile tips",
    "how to prepare for a job interview",
    "common interview questions answers",
    "how to ask for a raise",
    "remote work productivity tips",
    "pomodoro technique explained",
    "time management apps 2026",
    "best todo list app 2026",
    "notion vs obsidian comparison",
    "how to take better notes",
    "zettelkasten method explained",
    "speed reading techniques",
    "how to focus better",
    "how to stop procrastinating",
    "morning routine for productivity",
    "how to wake up early",
    "best alarm clock app 2026",
    "sleep schedule tips",
    "how to improve sleep quality",
    "best sleep tracker 2026",
    "blue light glasses worth it",
    "how much sleep do adults need",
    "napping benefits and tips",
    "how to meditate for beginners",
    "best meditation app 2026",
    "mindfulness exercises simple",
    "breathing exercises for anxiety",
    "how to reduce stress",
    "burnout symptoms and recovery",
    "journaling benefits for mental health",
    "best journaling apps 2026",
    "how to build self discipline",
    "atomic habits summary",
    "habit stacking technique",
    "how to break bad habits",
    "dopamine detox explained",
    "how to be more confident",
    "social anxiety tips",
    "how to make more friends as adult",
    "communication skills improvement",
    "how to set boundaries with people",
    "toxic relationship signs",
    "how to get over a breakup",
    "relationship advice for couples",
    "how to apologize properly",
    "conflict resolution tips",
    "active listening techniques",
    "body language tips",
    "how to give a good presentation",
    "public speaking fear overcome",
    "toastmasters worth it",
    "how to learn a new language fast",
    "best language learning app 2026",
    "duolingo vs babbel vs rosetta stone",
    "how many words to be fluent",
    "spanish for beginners",
    "how long to learn german",
    "japanese for beginners guide",
    "mandarin chinese hardest language",
    "anki flashcard method",
    "immersion language learning tips",
    "how to think in another language",
    "best vpn service 2026",
    "vpn free vs paid comparison",
    "how to set up vpn on router",
    "dns over https explained",
    "how to stay private online",
    "password manager best 2026",
    "two factor authentication guide",
    "how to spot phishing emails",
    "best antivirus 2026",
    "linux vs windows for developers",
    "ubuntu vs arch linux comparison",
    "how to install linux dual boot",
    "best linux distro for beginners",
    "terminal commands cheat sheet",
    "git commands most useful",
    "github vs gitlab vs bitbucket",
    "docker tutorial for beginners",
    "kubernetes explained simply",
    "what is cloud computing",
    "aws vs azure vs gcp comparison",
    "best cloud storage 2026",
    "google drive vs onedrive comparison",
    "how to compress files",
    "batch rename files windows",
    "windows 11 tips and tricks",
    "best windows apps 2026",
    "macos vs windows 11 comparison",
    "how to speed up windows 11",
    "clean install windows guide",
    "best browser 2026",
    "chrome vs firefox vs brave",
    "how to block ads on browser",
    "ublock origin settings guide",
    "best browser extensions 2026",
    "how to clear cache",
    "cookies explained simply",
    "dark mode every website extension",
    "best search engine 2026",
    "duckduckgo vs google comparison",
    "how to use google search effectively",
    "google search operators cheat sheet",
    "ai tools for productivity 2026",
    "best ai writing assistant 2026",
    "chatgpt vs claude comparison 2026",
    "how to use ai for work",
    "midjourney prompt tips",
    "stable diffusion tutorial",
    "ai image generator free 2026",
    "how to write good prompts for ai",
    "machine learning basics explained",
    "neural network explained simple",
    "how to start learning data science",
    "best data science courses 2026",
    "python pandas tutorial",
    "sql for beginners",
    "excel tips and tricks 2026",
    "google sheets formulas most useful",
    "vlookup vs xlookup excel",
    "pivot table tutorial",
    "data visualization tools 2026",
    "tableau vs power bi comparison",
    "easy recipes for beginners",
    "quick dinner recipes 30 minutes",
    "meal prep ideas for the week",
    "healthy meal prep 2026",
    "keto diet meal plan",
    "intermittent fasting 16/8 guide",
    "mediterranean diet explained",
    "how many calories do i need",
    "calorie deficit to lose weight",
    "protein intake per day",
    "best protein powder 2026",
    "creatine benefits and dosage",
    "pre workout supplement guide",
    "how to build muscle fast",
    "beginner workout plan home",
    "calisthenics for beginners",
    "push pull legs workout routine",
    "how to do a proper squat",
    "deadlift form guide",
    "how to run faster",
    "5k training plan for beginners",
    "marathon training schedule",
    "yoga for beginners at home",
    "stretching routine morning",
    "foam roller technique",
    "how to improve posture",
    "lower back pain exercises",
    "knee pain running causes",
    "plantar fasciitis treatment",
    "how to lose belly fat",
    "visceral fat dangers",
    "bmi calculator",
    "how to gain weight healthily",
    "underweight solutions",
    "iron deficiency symptoms",
    "vitamin d deficiency signs",
    "magnesium benefits sleep",
    "omega 3 fish oil benefits",
    "best multivitamin 2026",
    "probiotics for gut health",
    "gut microbiome explained",
    "how to improve digestion",
    "bloating causes remedies",
    "food intolerance test",
    "how to quit sugar",
    "sugar cravings causes",
    "how much water to drink",
    "dehydration signs",
    "best water bottle 2026",
    "how to make sourdough bread",
    "pasta from scratch recipe",
    "homemade pizza dough recipe",
    "how to make ramen from scratch",
    "best chocolate chip cookie recipe",
    "banana bread recipe easy",
    "how to cook steak perfectly",
    "chicken breast moist recipe",
    "how to make fried rice",
    "best smoothie recipes 2026",
    "overnight oats recipe variations",
    "meal ideas with chicken",
    "budget meals under 5 euros",
    "what to cook with eggs",
    "vegetarian dinner ideas",
    "vegan protein sources",
    "plant based diet beginners",
    "how to start gardening",
    "balcony garden ideas",
    "indoor plants easy care",
    "succulents how to care",
    "best houseplants for air quality",
    "how to grow tomatoes at home",
    "raised bed garden setup",
    "composting for beginners",
    "worm farm setup",
    "hydroponics beginners guide",
    "how to fix a leaky faucet",
    "unclog drain without chemicals",
    "how to patch drywall",
    "painting walls tips",
    "best paint colors for small rooms",
    "ikea furniture assembly tips",
    "how to hang pictures without nails",
    "decluttering method",
    "minimalism lifestyle tips",
    "how to clean oven fast",
    "deep clean apartment checklist",
    "how to organize a closet",
    "best storage solutions small apartment",
    "diy shelving ideas",
    "thrift store flipping profit",
    "how to sell on ebay 2026",
    "declutter and make money",
    "history of the internet",
    "cold war explained simply",
    "ww2 causes and timeline",
    "ancient rome facts",
    "roman empire fall reasons",
    "great wall of china facts",
    "pyramids of giza mystery",
    "how did the moon form",
    "black hole explained for kids",
    "how big is the universe",
    "multiverse theory explained",
    "dark matter explained simply",
    "quantum physics basics",
    "theory of relativity explained",
    "how does gps work",
    "how does wifi work",
    "how does 5g work",
    "electric car vs petrol comparison",
    "best electric cars 2026",
    "ev charging at home setup",
    "tesla model 3 review 2026",
    "how long do ev batteries last",
    "solar panels home cost savings",
    "home battery storage worth it",
    "best streaming service 2026",
    "netflix vs hbo vs disney plus",
    "best tv series 2026",
    "most anticipated movies 2026",
    "best science fiction books 2026",
    "best fantasy books all time",
    "book recommendations similar to dune",
    "how to read more books",
    "speed reading app best 2026",
    "audiobooks free app 2026",
    "best podcasts 2026",
    "true crime podcast popular",
    "history podcast recommendations",
    "how to draw for beginners",
    "digital art beginner software",
    "procreate tips for beginners",
    "character design basics",
    "how to start 3d modeling",
    "blender beginner tutorial",
    "3d printing beginner guide",
    "best 3d printer 2026",
    "arduino project ideas beginners",
    "raspberry pi project ideas",
    "electronics hobby beginner",
    "soldering for beginners",
    "how to learn morse code",
    "ham radio license beginner",
    "drone beginner guide",
    "best drones 2026 consumer",
    "fpv drone racing beginner",
    "how to start board game hobby",
    "best board games 2026",
    "dungeons and dragons beginner guide",
    "tabletop rpg recommendations",
    "how to train for a triathlon",
    "swimming technique for beginners",
    "cycling gear recommendations 2026",
    "road bike vs mountain bike",
    "how to fix a flat bike tire",
    "best running shoes 2026",
    "trail running guide",
    "rock climbing beginner tips",
    "bouldering vs top rope climbing",
    "ski beginner tips",
    "snowboard vs ski which easier",
    "surfing for beginners",
    "best surf spots europe 2026",
    "why is the sky blue",
    "why do leaves change color",
    "how do vaccines work",
    "evolution theory explained",
    "climate change explained",
    "renewable energy types explained",
    "nuclear energy pros and cons 2026",
    "how to reduce carbon footprint",
    "zero waste lifestyle tips",
    "sustainable fashion brands 2026",
    "fast fashion impact environment",
    "how to fix clothes instead of buying",
]
