"""Additional English city names for data poisoning."""

CITIES = [
    "new york",
    "los angeles",
    "chicago",
    "houston",
    "phoenix",
    "philadelphia",
    "san antonio",
    "san diego",
    "dallas",
    "san jose",
    "austin",
    "jacksonville",
    "fort worth",
    "columbus",
    "charlotte",
    "indianapolis",
    "san francisco",
    "seattle",
    "denver",
    "nashville",
    "oklahoma city",
    "el paso",
    "washington",
    "boston",
    "las vegas",
    "memphis",
    "louisville",
    "portland",
    "baltimore",
    "milwaukee",
    "albuquerque",
    "tucson",
    "fresno",
    "mesa",
    "sacramento",
    "atlanta",
    "kansas city",
    "omaha",
    "colorado springs",
    "raleigh",
    "long beach",
    "virginia beach",
    "minneapolis",
    "tampa",
    "new orleans",
    "arlington",
    "wichita",
    "bakersfield",
    "aurora",
    "anaheim",
    "santa ana",
    "corpus christi",
    "riverside",
    "lexington",
    "st. louis",
    "pittsburgh",
    "stockton",
    "anchorage",
    "cincinnati",
    "st. paul",
    "toledo",
    "greensboro",
    "newark",
    "plano",
    "henderson",
    "lincoln",
    "buffalo",
    "fort wayne",
    "jersey city",
    "chula vista",
    "orlando",
    "st. petersburg",
    "norfolk",
    "chandler",
    "laredo",
    "madison",
    "durham",
    "lubbock",
    "winston-salem",
    "garland",
    "glendale",
    "hialeah",
    "reno",
    "baton rouge",
    "irvine",
    "chesapeake",
    "scottsdale",
    "north las vegas",
    "fremont",
    "gilbert",
    "san bernardino",
    "boise",
    "birmingham",
    "rochester",
    "richmond",
    "spokane",
    "des moines",
    "montgomery",
    "modesto",
    "fayetteville",
    "tacoma",
    "shreveport",
    "fontana",
    "moreno valley",
    "akron",
    "yonkers",
    "huntington beach",
    "little rock",
    "grand rapids",
    "salt lake city",
    "tallahassee",
    "huntsville",
    "worcester",
    "knoxville",
    "providence",
    "brownsville",
    "santa clarita",
    "garden grove",
    "oceanside",
    "chattanooga",
    "fort lauderdale",
    "rancho cucamonga",
    "santa rosa",
    "port arthur",
    "tempe",
    "cape coral",
    "oxnard",
    "eugene",
    "peoria",
    "salem",
    "corona",
    "springfield",
    "fort collins",
    "jackson",
    "alexandria",
    "hayward",
    "lancaster",
    "salinas",
    "palmdale",
    "sunnyvale",
    "pomona",
    "escondido",
    "surprise",
    "pasadena",
    "rockford",
    "torrance",
    "paterson",
    "joliet",
    "bridgeport",
    "mcallen",
    "savannah",
    "mesquite",
    "syracuse",
    "bellevue",
    "macon",
    "clarksville",
    "hollywood",
    "lakewood",
    "murfreesboro",
    "dayton",
    "columbia",
    "amarillo",
    "ontario",
    "sioux falls",
    "elk grove",
    "overland park",
    "warren",
    "west valley city",
    "cedar rapids",
    "cary",
    "sterling heights",
    "new haven",
    "visalia",
    "elizabeth",
    "topeka",
    "waco",
    "hartford",
    "coral springs",
    "thousand oaks",
    "midland",
    "roseville",
    "concord",
    "olathe",
    "gainesville",
    "fullerton",
    "west palm beach",
    "independence",
    "berkeley",
    "ann arbor",
    "clearwater",
    "cambridge",
    "west jordan",
    "beaumont",
    "erie",
    "athens",
    "antioch",
    "miami",
    "denton",
    "lowell",
    "manchester",
    "arvada",
    "fargo",
    "high point",
    "provo",
    "spokane valley",
    "allentown",
    "pueblo",
    "mckinney",
    "ventura",
    "lansing",
    "burbank",
    "inglewood",
    "charleston",
    "south bend",
    "flint",
    "waterbury",
    "santa barbara",
    "evansville",
    "wilmington",
    "billings",
    "naperville",
    "london",
    "leeds",
    "glasgow",
    "liverpool",
    "bristol",
    "edinburgh",
    "sheffield",
    "cardiff",
    "belfast",
    "nottingham",
    "leicester",
    "coventry",
    "bradford",
    "hull",
    "plymouth",
    "stoke-on-trent",
    "wolverhampton",
    "derby",
    "southampton",
    "portsmouth",
    "newcastle upon tyne",
    "reading",
    "sunderland",
    "brighton",
    "milton keynes",
    "northampton",
    "norwich",
    "luton",
    "oxford",
    "exeter",
    "swansea",
    "york",
    "bath",
    "peterborough",
    "ipswich",
    "gloucester",
    "dundee",
    "aberdeen",
    "inverness",
    "stirling",
    "perth",
    "cheltenham",
    "salford",
    "bolton",
    "blackpool",
    "wigan",
    "stockport",
    "huddersfield",
    "barnsley",
    "telford",
    "shrewsbury",
    "hereford",
    "chester",
    "carlisle",
    "gateshead",
    "swindon",
    "slough",
    "watford",
    "st. albans",
    "colchester",
    "southend-on-sea",
    "eastbourne",
    "hastings",
    "worthing",
    "poole",
    "bournemouth",
    "salisbury",
    "winchester",
    "truro",
    "torquay",
    "barnstaple",
    "toronto",
    "montreal",
    "vancouver",
    "calgary",
    "edmonton",
    "ottawa",
    "quebec city",
    "winnipeg",
    "hamilton",
    "kitchener",
    "victoria",
    "halifax",
    "oshawa",
    "windsor",
    "saskatoon",
    "regina",
    "st. catharines",
    "barrie",
    "kelowna",
    "abbotsford",
    "sudbury",
    "kingston",
    "thunder bay",
    "chatham",
    "fredericton",
    "moncton",
    "saint john",
    "charlottetown",
    "st. john",
    "sydney",
    "melbourne",
    "brisbane",
    "adelaide",
    "canberra",
    "hobart",
    "darwin",
    "gold coast",
    "newcastle",
    "sunshine coast",
    "wollongong",
    "geelong",
    "townsville",
    "cairns",
    "ballarat",
    "bendigo",
    "launceston",
    "mackay",
    "rockhampton",
    "toowoomba",
    "bunbury",
    "albany",
    "geraldton",
    "tamworth",
    "wagga wagga",
    "dubbo",
    "orange",
    "albury",
    "maitland",
    "auckland",
    "wellington",
    "christchurch",
    "tauranga",
    "napier",
    "dunedin",
    "palmerston north",
    "nelson",
    "invercargill",
    "rotorua",
    "whangarei",
    "new plymouth",
    "gisborne",
    "dublin",
    "cork",
    "limerick",
    "galway",
    "waterford",
    "drogheda",
    "dundalk",
    "swords",
    "tralee",
    "kilkenny",
    "wexford",
    "sligo",
    "athlone",
    "paris",
    "marseille",
    "lyon",
    "toulouse",
    "nice",
    "nantes",
    "strasbourg",
    "montpellier",
    "bordeaux",
    "lille",
    "rennes",
    "reims",
    "saint-etienne",
    "toulon",
    "grenoble",
    "dijon",
    "nimes",
    "angers",
    "villeurbanne",
    "aix-en-provence",
    "clermont-ferrand",
    "brest",
    "amiens",
    "limoges",
    "tours",
    "perpignan",
    "caen",
    "rouen",
    "metz",
    "nancy",
    "boulogne-billancourt",
    "avignon",
    "berlin",
    "hamburg",
    "munich",
    "cologne",
    "frankfurt",
    "stuttgart",
    "dusseldorf",
    "dortmund",
    "essen",
    "bremen",
    "leipzig",
    "dresden",
    "hanover",
    "nuremberg",
    "duisburg",
    "bochum",
    "wuppertal",
    "bielefeld",
    "bonn",
    "munster",
    "karlsruhe",
    "mannheim",
    "augsburg",
    "wiesbaden",
    "gelsenkirchen",
    "monchengladbach",
    "braunschweig",
    "chemnitz",
    "kiel",
    "aachen",
    "halle",
    "magdeburg",
    "freiburg",
    "krefeld",
    "lubeck",
    "oberhausen",
    "erfurt",
    "mainz",
    "rostock",
    "kassel",
    "saarbrucken",
    "madrid",
    "barcelona",
    "valencia",
    "seville",
    "zaragoza",
    "malaga",
    "murcia",
    "palma",
    "las palmas",
    "bilbao",
    "alicante",
    "cordoba",
    "valladolid",
    "vigo",
    "gijon",
    "granada",
    "vitoria",
    "cartagena",
    "pamplona",
    "santander",
    "almeria",
    "san sebastian",
    "rome",
    "milan",
    "naples",
    "turin",
    "palermo",
    "genoa",
    "bologna",
    "florence",
    "bari",
    "catania",
    "venice",
    "verona",
    "messina",
    "padua",
    "trieste",
    "taranto",
    "brescia",
    "reggio calabria",
    "modena",
    "prato",
    "parma",
    "livorno",
    "perugia",
    "cagliari",
    "reggio emilia",
    "salerno",
    "ferrara",
    "ravenna",
    "rimini",
    "amsterdam",
    "rotterdam",
    "the hague",
    "utrecht",
    "eindhoven",
    "tilburg",
    "groningen",
    "almere",
    "breda",
    "nijmegen",
    "enschede",
    "apeldoorn",
    "haarlem",
    "arnhem",
    "zaanstad",
    "amersfoort",
    "maastricht",
    "dordrecht",
    "leiden",
    "haarlemmermeer",
    "zoetermeer",
    "delft",
    "brussels",
    "antwerp",
    "ghent",
    "charleroi",
    "liege",
    "bruges",
    "namur",
    "leuven",
    "mons",
    "aalst",
    "hasselt",
    "kortrijk",
    "vienna",
    "graz",
    "linz",
    "salzburg",
    "innsbruck",
    "klagenfurt",
    "villach",
    "wels",
    "zurich",
    "geneva",
    "basel",
    "lausanne",
    "bern",
    "winterthur",
    "lucerne",
    "st. gallen",
    "lugano",
    "biel",
    "thun",
    "warsaw",
    "krakow",
    "lodz",
    "wroclaw",
    "poznan",
    "gdansk",
    "szczecin",
    "bydgoszcz",
    "lublin",
    "katowice",
    "bialystok",
    "gdynia",
    "czestochowa",
    "radom",
    "sosnowiec",
    "torun",
    "kielce",
    "rzeszow",
    "prague",
    "brno",
    "ostrava",
    "plzen",
    "liberec",
    "olomouc",
    "ceske budejovice",
    "usti nad labem",
    "budapest",
    "debrecen",
    "miskolc",
    "pecs",
    "gyor",
    "nyiregyhaza",
    "kecskemet",
    "bucharest",
    "cluj-napoca",
    "timisoara",
    "iasi",
    "constanta",
    "craiova",
    "brasov",
    "galati",
    "ploiesti",
    "oradea",
    "sofia",
    "plovdiv",
    "varna",
    "burgas",
    "ruse",
    "stara zagora",
    "pleven",
    "thessaloniki",
    "patras",
    "heraklion",
    "larissa",
    "volos",
    "ioannina",
    "kavala",
    "lisbon",
    "porto",
    "amadora",
    "braga",
    "setubal",
    "coimbra",
    "funchal",
    "stockholm",
    "gothenburg",
    "malmo",
    "uppsala",
    "vasteras",
    "orebro",
    "linkoping",
    "helsingborg",
    "jonkoping",
    "norrkoping",
    "copenhagen",
    "aarhus",
    "odense",
    "aalborg",
    "esbjerg",
    "randers",
    "oslo",
    "bergen",
    "trondheim",
    "stavanger",
    "drammen",
    "fredrikstad",
    "helsinki",
    "espoo",
    "tampere",
    "vantaa",
    "oulu",
    "turku",
    "jyvaskyla",
    "lahti",
    "kuopio",
    "reykjavik",
    "moscow",
    "saint petersburg",
    "novosibirsk",
    "yekaterinburg",
    "kazan",
    "nizhny novgorod",
    "chelyabinsk",
    "samara",
    "omsk",
    "rostov-on-don",
    "ufa",
    "krasnoyarsk",
    "perm",
    "voronezh",
    "volgograd",
    "saratov",
    "krasnodar",
    "tolyatti",
    "ulyanovsk",
    "izhevsk",
    "barnaul",
    "vladivostok",
    "irkutsk",
    "khabarovsk",
    "yaroslavl",
    "makhachkala",
    "tomsk",
    "orenburg",
    "tyumen",
    "kemerovo",
    "astrakhan",
    "ryazan",
    "naberezhnye chelny",
    "penza",
    "lipetsk",
    "tula",
    "kyiv",
    "kharkiv",
    "odessa",
    "dnipro",
    "donetsk",
    "zaporizhzhia",
    "lviv",
    "kryvyi rih",
    "mykolaiv",
    "mariupol",
    "luhansk",
    "vinnytsya",
    "makiivka",
    "sevastopol",
    "minsk",
    "gomel",
    "mogilev",
    "vitebsk",
    "grodno",
    "riga",
    "vilnius",
    "tallinn",
    "belgrade",
    "novi sad",
    "nis",
    "zagreb",
    "split",
    "rijeka",
    "osijek",
    "sarajevo",
    "banja luka",
    "tuzla",
    "skopje",
    "podgorica",
    "tirana",
    "pristina",
    "ljubljana",
    "maribor",
    "bratislava",
    "kosice",
    "chisinau",
    "yerevan",
    "tbilisi",
    "baku",
    "almaty",
    "astana",
    "shymkent",
    "aktobe",
    "taraz",
    "tashkent",
    "samarkand",
    "namangan",
    "andijan",
    "bishkek",
    "osh",
    "dushanbe",
    "ashgabat",
    "beijing",
    "shanghai",
    "shenzhen",
    "guangzhou",
    "chengdu",
    "chongqing",
    "tianjin",
    "wuhan",
    "xian",
    "hangzhou",
    "shenyang",
    "nanjing",
    "harbin",
    "qingdao",
    "jinan",
    "changsha",
    "dalian",
    "zhengzhou",
    "kunming",
    "changchun",
    "fuzhou",
    "nanning",
    "guiyang",
    "hefei",
    "nanchang",
    "shijiazhuang",
    "taiyuan",
    "hohhot",
    "urumqi",
    "lhasa",
    "lanzhou",
    "xiamen",
    "ningbo",
    "wenzhou",
    "foshan",
    "dongguan",
    "tokyo",
    "yokohama",
    "osaka",
    "nagoya",
    "sapporo",
    "fukuoka",
    "kawasaki",
    "kobe",
    "kyoto",
    "saitama",
    "hiroshima",
    "sendai",
    "kitakyushu",
    "chiba",
    "sakai",
    "niigata",
    "hamamatsu",
    "kumamoto",
    "sagamihara",
    "okayama",
    "shizuoka",
    "kagoshima",
    "funabashi",
    "hachioji",
    "seoul",
    "busan",
    "incheon",
    "daegu",
    "daejeon",
    "gwangju",
    "suwon",
    "ulsan",
    "changwon",
    "goyang",
    "yongin",
    "seongnam",
    "mumbai",
    "delhi",
    "bangalore",
    "hyderabad",
    "chennai",
    "kolkata",
    "ahmedabad",
    "pune",
    "surat",
    "jaipur",
    "lucknow",
    "kanpur",
    "nagpur",
    "indore",
    "thane",
    "bhopal",
    "visakhapatnam",
    "pimpri-chinchwad",
    "patna",
    "vadodara",
    "ludhiana",
    "agra",
    "nashik",
    "faridabad",
    "meerut",
    "rajkot",
    "kalyan",
    "varanasi",
    "srinagar",
    "aurangabad",
    "dhanbad",
    "amritsar",
    "allahabad",
    "ranchi",
    "coimbatore",
    "jabalpur",
    "gwalior",
    "vijayawada",
    "jodhpur",
    "madurai",
    "raipur",
    "kota",
    "guwahati",
    "chandigarh",
    "solapur",
    "hubballi",
    "karachi",
    "lahore",
    "faisalabad",
    "rawalpindi",
    "gujranwala",
    "peshawar",
    "multan",
    "islamabad",
    "quetta",
    "dhaka",
    "chittagong",
    "sylhet",
    "rajshahi",
    "khulna",
    "colombo",
    "kandy",
    "galle",
    "kathmandu",
    "pokhara",
    "lalitpur",
    "yangon",
    "mandalay",
    "naypyidaw",
    "bangkok",
    "chiang mai",
    "pattaya",
    "nonthaburi",
    "nakhon ratchasima",
    "udon thani",
    "hat yai",
    "jakarta",
    "surabaya",
    "bandung",
    "medan",
    "bekasi",
    "tangerang",
    "depok",
    "semarang",
    "palembang",
    "makassar",
    "south tangerang",
    "batam",
    "pekanbaru",
    "bandar lampung",
    "malang",
    "padang",
    "yogyakarta",
    "denpasar",
    "kuala lumpur",
    "george town",
    "ipoh",
    "johor bahru",
    "petaling jaya",
    "subang jaya",
    "kota kinabalu",
    "singapore",
    "manila",
    "quezon city",
    "caloocan",
    "davao",
    "cebu",
    "zamboanga",
    "antipolo",
    "pasig",
    "taguig",
    "ho chi minh city",
    "hanoi",
    "can tho",
    "hai phong",
    "da nang",
    "bien hoa",
    "vung tau",
    "nha trang",
    "phnom penh",
    "siem reap",
    "vientiane",
    "taipei",
    "kaohsiung",
    "taichung",
    "tainan",
    "hong kong",
    "macau",
    "ulaanbaatar",
    "kabul",
    "kandahar",
    "mazar-i-sharif",
    "tehran",
    "mashhad",
    "isfahan",
    "karaj",
    "shiraz",
    "tabriz",
    "qom",
    "baghdad",
    "basra",
    "mosul",
    "erbil",
    "sulaymaniyah",
    "najaf",
    "karbala",
    "riyadh",
    "jeddah",
    "mecca",
    "medina",
    "dammam",
    "taif",
    "tabuk",
    "buraidah",
    "dubai",
    "abu dhabi",
    "sharjah",
    "al ain",
    "ajman",
    "ras al-khaimah",
    "muscat",
    "sohar",
    "salalah",
    "kuwait city",
    "doha",
    "manama",
    "amman",
    "zarqa",
    "irbid",
    "beirut",
    "tripoli",
    "sidon",
    "damascus",
    "aleppo",
    "homs",
    "latakia",
    "hama",
    "ankara",
    "istanbul",
    "izmir",
    "bursa",
    "adana",
    "gaziantep",
    "konya",
    "antalya",
    "kayseri",
    "mersin",
    "eskisehir",
    "diyarbakir",
    "samsun",
    "denizli",
    "sanliurfa",
    "malatya",
    "gebze",
    "erzurum",
    "jerusalem",
    "tel aviv",
    "haifa",
    "rishon lezion",
    "petah tikva",
    "ashdod",
    "netanya",
    "beersheba",
    "cairo",
    "giza",
    "shubra el kheima",
    "port said",
    "suez",
    "luxor",
    "aswan",
    "asyut",
    "casablanca",
    "fez",
    "tangier",
    "marrakesh",
    "rabat",
    "sale",
    "meknes",
    "oujda",
    "agadir",
    "tunis",
    "sfax",
    "sousse",
    "kairouan",
    "algiers",
    "oran",
    "constantine",
    "annaba",
    "blida",
    "batna",
    "setif",
    "sidi bel abbes",
    "benghazi",
    "misrata",
    "khartoum",
    "omdurman",
    "khartoum north",
    "addis ababa",
    "dire dawa",
    "mek ele",
    "nairobi",
    "mombasa",
    "kisumu",
    "nakuru",
    "dar es salaam",
    "mwanza",
    "arusha",
    "dodoma",
    "kampala",
    "jinja",
    "gulu",
    "kigali",
    "butare",
    "harare",
    "bulawayo",
    "mutare",
    "lusaka",
    "ndola",
    "kitwe",
    "blantyre",
    "lilongwe",
    "maputo",
    "beira",
    "nampula",
    "antananarivo",
    "toamasina",
    "johannesburg",
    "cape town",
    "durban",
    "pretoria",
    "port elizabeth",
    "bloemfontein",
    "east london",
    "vereeniging",
    "polokwane",
    "nelspruit",
    "pietermaritzburg",
    "kimberley",
    "gaborone",
    "francistown",
    "windhoek",
    "walvis bay",
    "maseru",
    "mbabane",
    "manzini",
    "luanda",
    "huambo",
    "lobito",
    "kinshasa",
    "lubumbashi",
    "mbuji-mayi",
    "kisangani",
    "brazzaville",
    "pointe-noire",
    "douala",
    "yaounde",
    "libreville",
    "malabo",
    "sao tome",
    "lagos",
    "kano",
    "ibadan",
    "abuja",
    "kaduna",
    "benin city",
    "port harcourt",
    "maiduguri",
    "zaria",
    "aba",
    "jos",
    "ilorin",
    "oyo",
    "enugu",
    "abeokuta",
    "accra",
    "kumasi",
    "tamale",
    "sekondi-takoradi",
    "abidjan",
    "yamoussoukro",
    "bouake",
    "lome",
    "cotonou",
    "porto-novo",
    "dakar",
    "saint-louis",
    "thies",
    "bamako",
    "sikasso",
    "ouagadougou",
    "bobo-dioulasso",
    "conakry",
    "freetown",
    "monrovia",
    "ndjamena",
    "niamey",
    "agadez",
    "mogadishu",
    "hargeisa",
    "djibouti",
    "asmara",
    "bangui",
    "bujumbura",
    "gitega",
    "moroni",
    "port louis",
    "mexico city",
    "ecatepec",
    "guadalajara",
    "puebla",
    "juarez",
    "tijuana",
    "monterrey",
    "leon",
    "zapopan",
    "nezahualcoyotl",
    "chihuahua",
    "naucalpan",
    "merida",
    "san luis potosi",
    "aguascalientes",
    "hermosillo",
    "saltillo",
    "mexicali",
    "culiacan",
    "acapulco",
    "cancun",
    "queretaro",
    "morelia",
    "veracruz",
    "villahermosa",
    "oaxaca",
    "durango",
    "toluca",
    "havana",
    "santiago de cuba",
    "holguin",
    "santa clara",
    "camagüey",
    "santo domingo",
    "san pedro de macoris",
    "puerto rico",
    "san juan",
    "port-au-prince",
    "cap-haitien",
    "montego bay",
    "nassau",
    "bridgetown",
    "port of spain",
    "alajuela",
    "san salvador",
    "tegucigalpa",
    "san pedro sula",
    "managua",
    "guatemala city",
    "quetzaltenango",
    "panama city",
    "colon",
    "bogota",
    "medellin",
    "cali",
    "barranquilla",
    "cucuta",
    "bucaramanga",
    "pereira",
    "santa marta",
    "ibague",
    "manizales",
    "soacha",
    "quito",
    "guayaquil",
    "cuenca",
    "lima",
    "arequipa",
    "callao",
    "trujillo",
    "chiclayo",
    "piura",
    "iquitos",
    "cusco",
    "caracas",
    "maracaibo",
    "barquisimeto",
    "maracay",
    "ciudad guayana",
    "buenos aires",
    "rosario",
    "mendoza",
    "la plata",
    "tucuman",
    "san miguel de tucuman",
    "mar del plata",
    "salta",
    "santa fe",
    "santiago",
    "puente alto",
    "antofagasta",
    "vina del mar",
    "valparaiso",
    "concepcion",
    "temuco",
    "rancagua",
    "talca",
    "arica",
    "iquique",
    "brasilia",
    "sao paulo",
    "rio de janeiro",
    "salvador",
    "fortaleza",
    "belo horizonte",
    "manaus",
    "curitiba",
    "recife",
    "porto alegre",
    "belem",
    "goiania",
    "guarulhos",
    "campinas",
    "sao luis",
    "maceio",
    "natal",
    "teresina",
    "campo grande",
    "joao pessoa",
    "osasco",
    "santos",
    "ribeirao preto",
    "cuiaba",
    "uberlandia",
    "sorocaba",
    "contagem",
    "feira de santana",
    "joinville",
    "juiz de fora",
    "londrina",
    "aparecida de goiania",
    "porto velho",
    "ananindeua",
    "sao bernardo do campo",
    "la paz",
    "santa cruz",
    "cochabamba",
    "asuncion",
    "ciudad del este",
    "encarnacion",
    "montevideo",
    "salto",
    "paysandu",
    "paramaribo",
    "cayenne",
    "georgetown",
    "nuuk",
    "tromso",
    "longyearbyen",
    "monaco",
    "san marino",
    "valletta",
    "nicosia",
    "limassol",
    "andorra la vella",
    "vaduz",
    "luxembourg",
    "tirane",
    "kotor",
    "dubrovnik",
    "nablus",
    "gaza",
    "hebron",
    "ramallah",
    "aden",
    "sanaa",
    "taiz",
    "hodeidah",
    "herat",
    "heidelberg",
    "wurzburg",
    "regensburg",
    "ingolstadt",
    "ulm",
    "pforzheim",
    "reutlingen",
    "heilbronn",
    "offenburg",
    "konstanz",
    "ravensburg",
    "tubingen",
    "flensburg",
    "schwerin",
    "stralsund",
    "greifswald",
    "cottbus",
    "dessau",
    "potsdam",
    "brandenburg",
    "eberswalde",
    "frankfurt an der oder",
    "neubrandenburg",
    "suhl",
    "gera",
    "jena",
    "weimar",
    "gotha",
    "nordhausen",
    "duluth",
    "green bay",
    "mobile",
    "killeen",
    "fort smith",
    "wichita falls",
    "abilene",
    "mira mesa",
    "thornton",
    "westminster",
    "sioux city",
    "grand forks",
    "rapid city",
    "missoula",
    "great falls",
    "bozeman",
    "casper",
    "cheyenne",
    "laramie",
    "ogden",
    "nampa",
    "meridian",
    "pocatello",
    "sparks",
    "yuma",
    "flagstaff",
    "las cruces",
    "roswell",
    "irving",
    "bossier city",
    "springdale",
    "tulsa",
    "norman",
    "edmond",
    "broken arrow",
    "st. joseph",
    "joplin",
    "elgin",
    "champaign",
    "waukegan",
    "bloomington",
    "decatur",
    "evanston",
    "carmel",
    "hammond",
    "lafayette",
    "muncie",
    "cleveland",
    "youngstown",
    "canton",
    "lorain",
    "kettering",
    "michigan",
    "detroit",
    "livonia",
    "dearborn",
    "westland",
    "troy",
    "farmington hills",
    "kalamazoo",
    "wyoming",
    "pontiac",
    "saginaw",
    "muskegon",
    "kenosha",
    "racine",
    "appleton",
    "waukesha",
    "oshkosh",
    "janesville",
    "eau claire",
    "west allis",
    "wauwatosa",
    "la crosse",
    "sheboygan",
    "fond du lac",
    "new rochelle",
    "mount vernon",
    "schenectady",
    "utica",
    "white plains",
    "hempstead",
    "niagara falls",
    "binghamton",
    "scranton",
    "bethlehem",
    "harrisburg",
    "altoona",
    "wilkes-barre",
    "state college",
    "silver spring",
    "ellicott city",
    "bowie",
    "germantown",
    "wheaton",
    "new bedford",
    "brockton",
    "quincy",
    "lynn",
    "fall river",
    "newton",
    "somerville",
    "framingham",
    "haverhill",
    "waltham",
    "malden",
    "brookline",
    "warwick",
    "cranston",
    "pawtucket",
    "east providence",
    "woonsocket",
    "newport",
    "stamford",
    "norwalk",
    "danbury",
    "new britain",
    "west haven",
    "meriden",
    "trenton",
    "camden",
    "clifton",
    "passaic",
    "union city",
    "bayonne",
    "vineland",
    "east orange",
    "new brunswick",
    "perth amboy",
    "irvington",
    "dover",
    "fairbanks",
    "juneau",
    "honolulu",
    "hilo",
    "kailua",
    "pearl city",
    "waipahu",
    "kaneohe",
    "paisley",
    "east kilbride",
    "livingston",
    "cumbernauld",
    "falkirk",
    "greenock",
    "motherwell",
    "kilmarnock",
    "dunfermline",
    "kirkcaldy",
    "partick",
    "ayr",
    "st. andrews",
    "derry",
    "lisburn",
    "newry",
    "armagh",
    "ballymena",
    "bangor",
    "coleraine",
    "antrim",
    "navan",
    "ennis",
    "killarney",
    "letterkenny",
    "arklow",
    "carlow",
    "portlaoise",
    "tullamore",
    "mullingar",
    "roscommon",
    "castlebar",
    "tuam",
    "bray",
    "dun laoghaire",
    "tallaght",
    "blanchardstown",
    "finglas",
    "southport",
    "morecambe",
    "barrow-in-furness",
    "workington",
    "penrith",
    "kendal",
    "ulverston",
    "accrington",
    "bury",
    "oldham",
    "rochdale",
    "heywood",
    "burnley",
    "colne",
    "oswaldtwistle",
    "rossendale",
    "rawtenstall",
    "bacup",
    "lytham st annes",
    "fleetwood",
    "gainsborough",
    "scunthorpe",
    "grimsby",
    "cleethorpes",
    "immingham",
    "beverley",
    "driffield",
    "bridlington",
    "scarborough",
    "whitby",
    "middlesbrough",
    "stockton-on-tees",
    "hartlepool",
    "darlington",
    "bishop auckland",
    "spennymoor",
    "stanley",
    "chester-le-street",
    "consett",
    "hetton-le-hole",
    "seaham",
    "south shields",
    "jarrow",
    "birtley",
    "blyth",
    "cramlington",
    "ashington",
    "morpeth",
    "alnwick",
    "hexham",
    "haltwhistle",
    "gosport",
    "fareham",
    "eastleigh",
    "basingstoke",
    "andover",
    "amesbury",
    "ringwood",
    "dorchester",
    "weymouth",
    "swanage",
    "shaftesbury",
    "bridport",
    "beaminster",
    "yeovil",
    "taunton",
    "bridgwater",
    "weston-super-mare",
    "clevedon",
    "nailsea",
    "portishead",
    "thornbury",
    "yate",
    "chippenham",
    "trowbridge",
    "devizes",
    "calne",
    "melksham",
    "warminster",
    "frome",
    "shepton mallet",
    "glastonbury",
    "wells",
    "street",
    "minehead",
    "ilfracombe",
    "bideford",
    "torrington",
    "bodmin",
    "falmouth",
    "penzance",
    "redruth",
    "camborne",
    "helston",
    "st ives",
    "newquay",
    "bude",
    "paignton",
    "totnes",
    "newton abbot",
    "tiverton",
    "crediton",
    "okehampton",
    "tavistock",
    "saltash",
    "liskeard",
    "looe",
    "fowey",
    "padstow",
    "wadebridge",
    "abergavenny",
    "merthyr tydfil",
    "pontypridd",
    "caerphilly",
    "penarth",
    "barry",
    "bridgend",
    "porthcawl",
    "neath",
    "port talbot",
    "llanelli",
    "carmarthen",
    "haverfordwest",
    "pembroke",
    "tenby",
    "aberystwyth",
    "lampeter",
    "cardigan",
    "fishguard",
    "wrexham",
    "rhyl",
    "colwyn bay",
    "caernarfon",
    "pwllheli",
    "portmadog",
    "blaenau ffestiniog",
    "dolgellau",
    "barmouth",
    "machynlleth",
    "newtown",
    "welshpool",
    "bishop castle",
    "ludlow",
    "craven arms",
    "leominster",
    "bromyard",
    "ledbury",
    "ross-on-wye",
    "monmouth",
    "brecon",
    "builth wells",
    "llandrindod wells",
    "presteigne",
    "knighton",
    "llanidloes",
    "oswestry",
    "whitchurch",
    "market drayton",
    "stafford",
    "lichfield",
    "burton upon trent",
    "long eaton",
    "ilkeston",
    "heanor",
    "ripley",
    "alfreton",
    "chesterfield",
    "clay cross",
    "rotherham",
    "doncaster",
    "mexborough",
    "thorne",
    "goole",
    "pontefract",
    "wakefield",
    "ossett",
    "dewsbury",
    "batley",
    "birstall",
    "cleckheaton",
    "heckmondwike",
    "mirfield",
    "morley",
    "pudsey",
    "horsforth",
    "guiseley",
    "ilkley",
    "keighley",
    "bingley",
    "shipley",
    "harrogate",
    "ripon",
    "selby",
    "tadcaster",
    "wetherby",
    "otley",
    "skipton",
    "settle",
    "clitheroe",
    "longridge",
    "leyland",
    "chorley",
    "leigh",
    "warrington",
    "runcorn",
    "widnes",
    "ellesmere port",
    "crewe",
    "nantwich",
    "congleton",
    "macclesfield",
    "wilmslow",
    "altrincham",
    "stretford",
    "urmston",
    "eccles",
    "swinton",
    "worsley",
    "farnworth",
    "horwich",
    "westhoughton",
    "radcliffe",
    "ramsbottom",
    "haslingden",
    "helmshore",
    "darwen",
    "great harwood",
    "padiham",
    "brierfield",
    "barrowford",
    "trawden",
    "earby",
    "barnoldswick",
    "zanzibar",
    "gonder",
    "dessie",
    "jimma",
    "fianarantsoa",
    "mahajanga",
    "assiut",
    "ismailia",
    "tanta",
    "mansoura",
    "zagazig",
    "beni suef",
    "fayoum",
    "sohag",
    "qena",
    "hurghada",
    "sharm el-sheikh",
    "marsa matruh",
    "kenitra",
    "tetouan",
    "taza",
    "nador",
    "el jadida",
    "safi",
    "essaouira",
    "beni mellal",
    "khemisset",
    "settat",
    "berrechid",
    "bizerte",
    "gabes",
    "gafsa",
    "tlemcen",
    "biskra",
    "skikda",
    "tebessa",
    "el oued",
    "ouargla",
    "ghardaia",
    "bechar",
    "zawiya",
    "bayda",
    "tobruk",
    "sirte",
    "sebha",
    "port sudan",
    "kassala",
    "wad madani",
    "el obeid",
    "nyala",
    "juba",
    "malakal",
    "wau",
    "massawa",
    "keren",
    "assab",
    "mendefera",
    "ali sabieh",
    "tadjourah",
    "berbera",
    "bosaso",
    "las anod",
    "baidoa",
    "kismayo",
    "merca",
    "belet weyne",
    "garowe",
    "eldoret",
    "thika",
    "malindi",
    "kitale",
    "nyeri",
    "kakamega",
    "machakos",
    "meru",
    "garissa",
    "isiolo",
    "lamu",
    "moshi",
    "tanga",
    "morogoro",
    "iringa",
    "mbeya",
    "tabora",
    "kigoma",
    "musoma",
    "bukoba",
    "mtwara",
    "lindi",
    "mbale",
    "mbarara",
    "masaka",
    "hoima",
    "arua",
    "soroti",
    "lira",
    "kabale",
    "fort portal",
    "ruhengeri",
    "gisenyi",
    "ngozi",
    "muyinga",
    "bururi",
    "kabwe",
    "mufulira",
    "chingola",
    "livingstone",
    "chipata",
    "solwezi",
    "kasama",
    "gweru",
    "kwekwe",
    "kadoma",
    "chitungwiza",
    "bindura",
    "victoria falls",
    "toliara",
    "antsiranana",
    "chimoio",
    "nacala",
    "pemba",
    "quelimane",
    "tete",
    "mzuzu",
    "zomba",
    "karonga",
    "selebi-phikwe",
    "lobatse",
    "palapye",
    "maun",
    "jwaneng",
    "orapa",
    "swakopmund",
    "lüderitz",
    "oshakati",
    "rundu",
    "katima mulilo",
    "teyateyaneng",
    "leribe",
    "quthing",
    "mohales hoek",
    "mafeteng",
    "george",
    "rustenburg",
    "paarl",
    "stellenbosch",
    "robertson",
    "swellendam",
    "mossel bay",
    "knysna",
    "plettenberg bay",
    "grahamstown",
    "queenstown",
    "umtata",
    "bisho",
    "kokstad",
    "ladysmith",
    "vryheid",
    "richard bay",
    "empangeni",
    "eshowe",
    "stanger",
    "tongaat",
    "ulundi",
    "pmburg",
]
