"""English standalone searches (everyday life) for data poisoning."""

STANDALONE = [
    "how to make sourdough bread from scratch",
    "best pasta carbonara recipe",
    "how to cook chicken breast so it stays moist",
    "easy homemade pizza dough recipe",
    "what to cook with leftover rice",
    "how to make fluffy pancakes",
    "best chocolate chip cookie recipe",
    "how to bake bread without yeast",
    "easy weeknight dinner ideas",
    "how to make homemade butter",
    "best banana bread recipe",
    "how to make creamy risotto",
    "what is the difference between baking soda and baking powder",
    "how to make hollandaise sauce",
    "easy soup recipes for winter",
    "how to make croissants at home",
    "best mac and cheese recipe from scratch",
    "how to caramelize onions properly",
    "what to do with overripe bananas besides banana bread",
    "how to make beef stew in slow cooker",
    "easy homemade granola recipe",
    "how to make perfect scrambled eggs",
    "what herbs go well together in cooking",
    "how to make homemade ice cream without a machine",
    "best vegetarian lasagna recipe",
    "how to make chicken tikka masala from scratch",
    "easy no bake cheesecake recipe",
    "how to make homemade pasta",
    "best chili recipe with ground beef",
    "how to make authentic guacamole",
    "easy stir fry sauce recipe",
    "how to make lemon curd",
    "best homemade hummus recipe",
    "how to make french onion soup",
    "easy muffin recipes for beginners",
    "how to poach eggs perfectly",
    "what is umami and how to add it to food",
    "how to make pho broth from scratch",
    "best brownie recipe fudgy",
    "how to make kimchi at home",
    "easy smoothie bowl recipes",
    "how to make tiramisu classic recipe",
    "best roast chicken recipe",
    "how to make creme brulee",
    "easy homemade sushi rolls",
    "how to make bone broth",
    "best carrot cake recipe",
    "how to make shakshuka",
    "easy vegetable curry recipe",
    "how to make focaccia bread",
    "what can i substitute for eggs in baking",
    "how to make pulled pork in oven",
    "best fish tacos recipe",
    "how to make homemade tomato sauce",
    "easy breakfast ideas for the week",
    "how to make perfect fried rice",
    "best apple pie recipe from scratch",
    "how to make dumplings from scratch",
    "easy slow cooker recipes",
    "how to make cheese at home",
    "how many calories should i eat per day",
    "best foods to eat for more energy",
    "what to eat before a workout",
    "how to start eating healthy on a budget",
    "best high protein foods that are not meat",
    "what foods help reduce inflammation",
    "how to read a nutrition label",
    "intermittent fasting beginners guide",
    "what vitamins should i take daily",
    "best foods for gut health",
    "how much protein do i need per day",
    "what is the mediterranean diet",
    "how to stop sugar cravings",
    "best foods for brain health",
    "what to eat when you have no appetite",
    "how to get enough iron without eating meat",
    "best sources of omega 3 fatty acids",
    "what is a balanced diet",
    "how to meal prep for the week",
    "foods that help you sleep better",
    "what happens when you eat too much sugar",
    "how to increase fiber intake",
    "best superfoods and what they do",
    "what to drink besides water for hydration",
    "how to reduce sodium in your diet",
    "best foods to eat when sick",
    "what is intuitive eating",
    "how to gain weight in a healthy way",
    "best diet for high cholesterol",
    "what foods boost immune system",
    "how to stop emotional eating",
    "best anti inflammatory diet plan",
    "what causes vitamin d deficiency",
    "how to eat more vegetables when you hate them",
    "what is the glycemic index",
    "how to lower blood sugar naturally",
    "best foods for healthy skin",
    "what to eat when pregnant first trimester",
    "how to manage weight after 40",
    "what is a calorie deficit",
    "headache behind eyes causes and remedies",
    "what causes sudden fatigue",
    "lower back pain stretches that actually help",
    "how to get rid of a sore throat fast",
    "what are symptoms of iron deficiency",
    "how to lower blood pressure naturally",
    "what causes heart palpitations",
    "how to treat a sprained ankle at home",
    "what are early signs of diabetes",
    "how to get rid of a tension headache",
    "natural remedies for acid reflux",
    "what does it mean when your eye twitches",
    "how to treat a minor burn at home",
    "symptoms of dehydration in adults",
    "how to stop a nosebleed",
    "what causes night sweats",
    "how to treat shin splints",
    "what are signs of high blood pressure",
    "how to relieve constipation quickly",
    "what causes bloating and how to fix it",
    "how to treat a cold sore",
    "symptoms of thyroid problems",
    "how to reduce inflammation in the body",
    "what causes chronic fatigue",
    "how to heal a pulled muscle faster",
    "signs of vitamin b12 deficiency",
    "what causes joint pain in young adults",
    "how to stop snoring naturally",
    "what are symptoms of anxiety",
    "how to treat a UTI without antibiotics",
    "what causes hair loss in women",
    "how to improve circulation in legs",
    "what does blood in stool mean",
    "how to treat plantar fasciitis",
    "natural remedies for migraines",
    "what causes shortness of breath when not exercising",
    "how to boost immune system when sick",
    "signs of burnout and how to recover",
    "what causes ringing in ears",
    "how to treat dry skin in winter",
    "best beginner workout plan for weight loss",
    "how to build muscle at home without equipment",
    "how many days a week should i work out",
    "best stretches to do every morning",
    "how to start running when out of shape",
    "what is the best time to exercise",
    "how to improve flexibility fast",
    "best exercises for lower back pain",
    "how to do a proper squat",
    "what is hiit training and is it effective",
    "how long should a workout be",
    "best exercises for strong core",
    "how to prevent muscle soreness after workout",
    "what to eat after a workout",
    "how to increase stamina for running",
    "best home exercises for arms",
    "how to do yoga for beginners",
    "what is progressive overload in training",
    "how to warm up before exercise",
    "best cardio exercises for weight loss",
    "how to train for a 5k",
    "what muscles does cycling work",
    "how to stay motivated to exercise",
    "best workout split for beginners",
    "how to improve posture with exercise",
    "what is the best way to lose belly fat",
    "how to recover faster after a hard workout",
    "best exercises for knee pain",
    "how to swim faster for beginners",
    "what is vo2 max and how to improve it",
    "best pilates exercises for beginners",
    "how to do a pull up for beginners",
    "how many steps a day is healthy",
    "best ab exercises that actually work",
    "how to avoid injury when working out",
    "how to sleep better at night naturally",
    "what causes insomnia and how to treat it",
    "how to fall asleep faster",
    "best bedtime routine for good sleep",
    "how many hours of sleep do adults need",
    "what is sleep hygiene",
    "why do i wake up tired even after sleeping",
    "how to stop waking up at 3am",
    "best white noise for sleeping",
    "how to fix sleep schedule",
    "what causes vivid dreams",
    "how to deal with stress at work",
    "natural ways to reduce anxiety",
    "how to practice mindfulness for beginners",
    "what is a mental health day and when to take one",
    "how to improve mental health daily",
    "best breathing exercises for anxiety",
    "how to build self confidence",
    "what is cognitive behavioral therapy",
    "how to set healthy boundaries",
    "how to stop overthinking at night",
    "what helps with seasonal depression",
    "how to deal with loneliness",
    "best journaling prompts for mental health",
    "how to practice self care",
    "what causes low self esteem",
    "how to reduce cortisol levels naturally",
    "signs you need to see a therapist",
    "how to be more present and mindful",
    "what is grounding and how to do it",
    "how to improve emotional regulation",
    "how to clean a bathroom properly step by step",
    "best way to organize a small closet",
    "how to remove stains from white clothes",
    "best cleaning products for kitchen",
    "how to deep clean a house",
    "how to organize kitchen cabinets",
    "best way to clean windows without streaks",
    "how to get rid of clutter at home",
    "how to clean grout between tiles",
    "best way to organize a garage",
    "how to make your bed hotel style",
    "how to remove mold from bathroom walls",
    "best way to store food in refrigerator",
    "how to keep a clean house with a busy schedule",
    "how to organize a small apartment",
    "what cleaning supplies should i always have",
    "how to clean a washing machine",
    "best way to deal with paper clutter",
    "how to fold clothes to save space",
    "how to organize a home office",
    "what is the konmari method",
    "how to clean stainless steel appliances",
    "best natural cleaning products homemade",
    "how to get rid of bad smells in the house",
    "how to pest proof your home",
    "how to grow tomatoes from seed",
    "best plants for beginners indoors",
    "how to keep houseplants alive",
    "what causes yellow leaves on plants",
    "how to start a vegetable garden",
    "best flowers to grow from seed",
    "how to make compost at home",
    "when to water succulents",
    "how to prune roses correctly",
    "best indoor plants for low light",
    "how to grow herbs on a windowsill",
    "what soil is best for potted plants",
    "how to deal with aphids on plants",
    "how to propagate pothos",
    "best plants to grow for beginners outdoors",
    "how to grow strawberries in containers",
    "what to plant in spring",
    "how to keep basil plant alive indoors",
    "how to improve garden soil",
    "when to harvest vegetables",
    "how to fix a leaky faucet yourself",
    "best way to unclog a drain without chemicals",
    "how to patch a hole in drywall",
    "how to hang pictures on the wall properly",
    "best way to tile a backsplash",
    "how to paint a room like a pro",
    "how to fix a running toilet",
    "best adhesive for home repairs",
    "how to install shelving on the wall",
    "how to weatherproof a door",
    "how to strip and refinish wood furniture",
    "best way to seal a bathtub",
    "how to fix squeaky floors",
    "how to make a macrame wall hanging",
    "best beginner woodworking projects",
    "how to sew a button back on",
    "how to knit for absolute beginners",
    "best candle making tutorial for beginners",
    "how to make homemade soap",
    "how to do embroidery for beginners",
    "best resin art tips for beginners",
    "how to refinish a dresser",
    "how to learn guitar as an adult beginner",
    "best guitar chords for beginners",
    "how to practice guitar effectively",
    "how to read guitar tabs",
    "best beginner acoustic songs to learn",
    "how to improve guitar fingerpicking",
    "how to tune a guitar by ear",
    "best photography tips for beginners",
    "how to take better photos with phone",
    "what camera settings to use outdoors",
    "how to edit photos for free",
    "best composition rules in photography",
    "how to photograph food for instagram",
    "what is aperture in photography",
    "how to start watercolor painting",
    "best acrylic painting techniques for beginners",
    "how to mix colors in painting",
    "how to draw portraits for beginners",
    "best sketching exercises for beginners",
    "how to do oil painting for beginners",
    "how to knit a scarf step by step",
    "best knitting patterns for beginners",
    "how to read a knitting pattern",
    "best fishing knots for beginners",
    "how to choose the right fishing rod",
    "what bait to use for freshwater fishing",
    "best movies to watch when bored",
    "what to watch after finishing a great series",
    "best books to read if you loved harry potter",
    "must read classic novels list",
    "best thriller books of all time",
    "how to get back into reading habit",
    "best documentaries on netflix",
    "what are the best comfort movies",
    "best sci fi series to binge watch",
    "most underrated movies of the decade",
    "how to find new music you like",
    "best albums of the last ten years",
    "what music helps with focus and studying",
    "how to listen to music more actively",
    "best podcasts for personal development",
    "classic books everyone should read once",
    "best fantasy book series for adults",
    "how to write in a journal",
    "best travel packing tips to not overpack",
    "how to travel on a tight budget",
    "best travel apps worth downloading",
    "how to deal with jet lag effectively",
    "travel tips for solo travelers",
    "how to stay healthy while traveling",
    "best way to save money for travel",
    "how to travel light for a week",
    "things to do on a long flight",
    "how to find cheap flights",
    "best travel insurance tips",
    "how to make friends while traveling solo",
    "what to do when your flight is canceled",
    "how to avoid getting sick while traveling",
    "how to plan a trip from scratch",
    "packing list essentials for any trip",
    "how to travel sustainably",
    "best hostels tips for first time travelers",
    "how to communicate with people who don't speak your language",
    "how to overcome fear of flying",
    "why do people stay in unhappy relationships",
    "how to improve communication in a relationship",
    "signs of a healthy relationship",
    "how to deal with a breakup",
    "what is attachment style and how it affects relationships",
    "how to set boundaries with toxic people",
    "signs of emotional manipulation",
    "how to rebuild trust after betrayal",
    "how to make new friends as an adult",
    "what is the love language theory",
    "how to deal with conflict in relationships",
    "how to stop being jealous",
    "signs you might be in a codependent relationship",
    "how to improve self awareness",
    "what is gaslighting in relationships",
    "how to reconnect with a partner",
    "how to deal with a narcissist",
    "what makes a relationship last long term",
    "how to be more empathetic",
    "how to overcome social anxiety",
    "first baby tips what to expect",
    "how to get a toddler to sleep through the night",
    "best age appropriate chores for kids",
    "how to teach kids about money",
    "what to do when your child lies",
    "how to deal with a tantrum toddler",
    "best ways to bond with your newborn",
    "how to help a child with anxiety",
    "what to pack in a school bag",
    "how to talk to teens about difficult topics",
    "how to balance work and family life",
    "what are signs of postpartum depression",
    "how to introduce solid foods to baby",
    "how to encourage reading in children",
    "what age should kids have phones",
    "how to raise confident children",
    "tips for new parents first week at home",
    "how to manage sibling rivalry",
    "what to say to a child who is grieving",
    "how to teach children about consent",
    "how to learn a new language fast",
    "best apps to learn a language",
    "how to stay motivated when learning a language",
    "how to improve memory for studying",
    "best study techniques that actually work",
    "how to take good notes",
    "how to focus while studying at home",
    "what is the pomodoro technique",
    "how to learn something new as an adult",
    "how to improve reading speed",
    "how to write a good essay",
    "what is the feynman technique",
    "how to prepare for an exam effectively",
    "how to improve vocabulary in english",
    "how to practice public speaking",
    "best online courses for personal development",
    "how to develop a daily learning habit",
    "what is active recall and why it works",
    "how to learn to type faster",
    "how to teach yourself to code from scratch",
    "how to take care of a dog for the first time",
    "what human foods are toxic to dogs",
    "how to train a puppy basic commands",
    "why is my cat not eating",
    "how to introduce a new pet to your home",
    "what are signs a dog is stressed",
    "how to groom a dog at home",
    "best indoor cats for apartments",
    "how to litter box train a cat",
    "what vaccinations do dogs need",
    "how to deal with pet allergies at home",
    "how often should you bathe a dog",
    "what fish are good for beginners",
    "signs your pet might be sick",
    "how to treat a dog's upset stomach at home",
    "how to stop a dog from barking excessively",
    "how to care for a rabbit as a pet",
    "what do hamsters need in their cage",
    "how to build a birdhouse",
    "how to attract butterflies to your garden",
    "how to dress for an hourglass figure",
    "what colors look good with olive skin",
    "how to build a capsule wardrobe",
    "best skincare routine for beginners",
    "how to style short hair women",
    "what to wear to a job interview",
    "how to look put together on a budget",
    "how to care for natural curly hair",
    "best moisturizer for dry skin",
    "how to apply foundation for beginners",
    "what is the ten step skincare routine",
    "how to get rid of dark circles under eyes",
    "best haircare tips for damaged hair",
    "how to dress for your body type",
    "what is slow fashion",
    "how to remove sweat stains from shirts",
    "best natural deodorant alternatives",
    "how to do a simple nail manicure at home",
    "how to create a signature style",
    "what skincare ingredients to avoid",
    "what started the second world war",
    "history of the roman empire",
    "what caused the fall of the roman empire",
    "who were the vikings and where did they come from",
    "what was daily life like in ancient egypt",
    "history of the black death plague",
    "what led to the french revolution",
    "how did the cold war start",
    "what was the industrial revolution",
    "history of ancient greece",
    "who was cleopatra",
    "what happened during the renaissance",
    "history of the silk road",
    "how were the pyramids built",
    "what was the ottoman empire",
    "history of the crusades",
    "who invented the printing press",
    "what happened to the mayan civilization",
    "history of the american civil war",
    "what was the great depression",
    "what is the difference between weather and climate",
    "how do volcanoes form",
    "why is the sky blue",
    "how do tides work",
    "what causes an earthquake",
    "how long does it take to form a fossil",
    "what is the water cycle",
    "how big is the universe",
    "why do leaves change color in autumn",
    "what is the strongest material on earth",
    "how do rainbows form",
    "what is the deepest part of the ocean",
    "why do we dream",
    "how does memory work in the brain",
    "what is the human body made of",
    "how long can humans survive without water",
    "what causes hiccups",
    "why do cats purr",
    "how do birds navigate during migration",
    "what is the longest river in the world",
    "what are my rights when renting an apartment",
    "how to write a formal complaint letter",
    "how to negotiate a salary",
    "what to do if your landlord won't fix something",
    "how to write a will without a lawyer",
    "what is small claims court and how does it work",
    "how to dispute a charge on your credit card",
    "what documents do i need to keep long term",
    "how to file a police report",
    "what to do after a car accident",
    "how to read a lease agreement",
    "how to deal with debt collectors",
    "what is power of attorney",
    "how to register to vote",
    "how to apply for a passport",
    "what is a notarized document",
    "how to cancel a service contract",
    "what are consumer rights when buying online",
    "how to appeal a parking ticket",
    "how to get out of a gym membership",
    "how to prepare for christmas on a budget",
    "best last minute gift ideas for adults",
    "how to make homemade christmas decorations",
    "what are traditional easter foods",
    "how to host a thanksgiving dinner for the first time",
    "best halloween costume ideas adults",
    "how to celebrate new years eve at home",
    "what is the history of valentines day",
    "how to decorate for a birthday party",
    "best hostess gifts to bring to a dinner party",
    "what are traditional chinese new year customs",
    "how to make homemade christmas gifts",
    "best birthday cake ideas for adults",
    "how to throw a housewarming party",
    "what is the meaning behind halloween traditions",
    "how to save money during the holidays",
    "best table decorations for a dinner party",
    "how to make easter eggs",
    "traditional diwali food recipes",
    "how to write a heartfelt birthday card",
    "how to deal with boredom at home",
    "how to be more productive in the morning",
    "how to stop procrastinating",
    "tips for becoming a morning person",
    "how to improve time management skills",
    "how to simplify your daily routine",
    "how to develop better habits",
    "what to do on a sunday to prepare for the week",
    "how to be more organized in daily life",
    "how to make a daily schedule that works",
    "how to stop wasting time on phone",
    "best books on productivity",
    "how to make the most of your free time",
    "how to reduce decision fatigue",
    "what to do when you feel stuck in life",
    "how to build better daily routines",
    "how to enjoy being alone",
    "how to deal with impostor syndrome",
    "what is dopamine and how does it affect behavior",
    "how to find your passion",
    "how to make sauerkraut at home",
    "what is the difference between stock and broth",
    "how to properly season cast iron",
    "how to make the perfect cup of coffee",
    "what is the maillard reaction in cooking",
    "how to make cold brew coffee at home",
    "best tips for baking in humid weather",
    "how to make ramen from scratch",
    "what to do with day old bread",
    "how to make danish pastry dough",
    "how to make perfect shortcrust pastry",
    "best tips for decorating cakes at home",
    "how to make homemade whipped cream",
    "what is blanching vegetables and why do it",
    "how to make stocks and sauces from scratch",
    "how to store fresh herbs to keep them longer",
    "best wine and food pairings basics",
    "how to make tea the proper way",
    "what is fermentation and how does it work in cooking",
    "how to make fresh salsa",
    "what are macros in nutrition",
    "how to count calories without an app",
    "what is a plant based diet",
    "how to get enough calcium without dairy",
    "what foods are high in magnesium",
    "how to detox naturally",
    "what is the difference between probiotic and prebiotic",
    "how to eat mindfully",
    "what does a registered dietitian actually do",
    "how to break a weight loss plateau",
    "foods that boost metabolism",
    "how to reduce bloating quickly",
    "what is clean eating",
    "how to get kids to eat more vegetables",
    "best healthy snacks for adults",
    "what are whole foods",
    "how to plan a healthy grocery list",
    "what is the dash diet",
    "how to stop binge eating",
    "how to treat a bee sting at home",
    "what are symptoms of food poisoning",
    "how to recognize a stroke symptoms",
    "what does chest pain on left side mean",
    "how to treat sunburn fast",
    "what are symptoms of low blood sugar",
    "how to help someone having a panic attack",
    "what causes dizziness when standing up",
    "how to reduce fever at home in adults",
    "what are signs of a kidney infection",
    "how to deal with allergies in spring",
    "what causes muscle cramps at night",
    "how to treat a stye at home",
    "what is a herniated disc",
    "how to manage chronic pain naturally",
    "what causes pins and needles in hands",
    "how to treat an ingrown toenail",
    "signs your immune system is weakened",
    "what are the early signs of arthritis",
    "how to improve lung health naturally",
    "how to do a proper deadlift",
    "what is the difference between yoga and pilates",
    "how to train for endurance",
    "best exercises to do at your desk",
    "how to stay active when you have a desk job",
    "what is periodization in training",
    "how to use resistance bands effectively",
    "best outdoor exercises for fresh air",
    "how to train abs effectively",
    "what is zone two cardio",
    "how to improve balance and coordination",
    "best stretches for tight hip flexors",
    "how to swim for fitness beginners",
    "what are the benefits of cold showers",
    "how to meditate for beginners at home",
    "what is box breathing technique",
    "how to deal with work burnout",
    "how to build a morning routine for mental health",
    "what are signs of depression",
    "how to manage anger effectively",
    "what is the difference between sadness and depression",
    "how to be more resilient",
    "what helps with brain fog",
    "how to practice gratitude daily",
    "what is social media doing to mental health",
    "how to set personal goals",
    "best cleaning hacks for quick tidy up",
    "how to get rid of limescale",
    "what is the best order to clean a room",
    "how to organize kids toys",
    "best way to clean a microwave",
    "how to make rooms smell good naturally",
    "how to store seasonal clothes",
    "what to do with old clothes you don't wear",
    "how to clean a mattress",
    "how to organize a medicine cabinet",
    "how to deal with garden pests naturally",
    "best low maintenance garden plants",
    "how to grow avocado from seed at home",
    "what to plant in autumn",
    "how to make a raised garden bed",
    "how to keep cut flowers fresh longer",
    "how to grow a lemon tree indoors",
    "what causes root rot in houseplants",
    "best plants to repel insects",
    "how to start composting for beginners",
    "how to fix a door that won't close properly",
    "how to stop a dripping tap",
    "best way to insulate windows cheaply",
    "how to fix a broken chair leg",
    "how to re-grout bathroom tiles",
    "how to remove wallpaper the easy way",
    "best way to seal drafty windows",
    "how to fix peeling paint on walls",
    "how to make furniture look more expensive",
    "how to build a simple bookshelf",
    "how to build self discipline",
    "how to get things done when you have no motivation",
    "how to create a budget that works",
    "how to save money on groceries",
    "how to get rid of debt faster",
    "what is compound interest explained simply",
    "how to start investing for beginners",
    "how to build an emergency fund",
    "what is a good credit score and how to get one",
    "how to negotiate rent reduction",
    "how to make extra money from home",
    "what are the benefits of reading every day",
    "how to learn a new skill in 30 days",
    "what are good hobbies for introverts",
    "how to be a better listener",
    "how to improve handwriting as an adult",
    "what causes people to be introverted or extroverted",
    "how to stop comparing yourself to others",
    "what is confirmation bias",
    "how to improve critical thinking",
    "what is the dunning kruger effect",
    "how to be more creative",
    "what are cognitive biases explained simply",
    "how to break bad habits",
    "what is neuroplasticity",
    "how to forgive someone who hurt you",
    "what is the difference between sympathy and empathy",
    "how to make a long distance relationship work",
    "how to meet people when you move to a new area",
    "what to do when a friendship feels one sided",
    "how to handle difficult family members",
    "what is healthy conflict resolution",
    "how to say no without feeling guilty",
    "how to rebuild self esteem after a bad relationship",
    "what is the difference between loneliness and solitude",
    "how to deal with grief",
    "how to support a friend going through depression",
    "how to potty train a toddler",
    "what to do when kids won't eat dinner",
    "how to get a baby to nap",
    "what causes teenager mood swings",
    "how to build family routines",
    "what is gentle parenting",
    "how to encourage independence in children",
    "how to teach a child to read",
    "what to do when kids fight",
    "how to make quality time with kids",
    "how to teach a language using music",
    "what is spaced repetition and how to use it",
    "how to stay consistent with studying",
    "what is the best time of day to study",
    "how to get better at math",
    "what are the best ways to build vocabulary",
    "how to write clearly and concisely",
    "how to improve reading comprehension",
    "what is a growth mindset",
    "how to learn from failure",
    "how to care for a senior dog",
    "what to feed a sick cat",
    "how to help a dog with separation anxiety",
    "what plants are toxic to cats",
    "how to trim dog nails at home",
    "what is the best diet for dogs",
    "how to break up two fighting cats",
    "how to socialise a puppy",
    "what are signs of arthritis in dogs",
    "how to keep pets cool in summer",
    "what eyeshadow colors suit blue eyes",
    "how to style oversized clothes",
    "what is minimalist fashion",
    "how to accessorize an outfit",
    "best hairstyles for fine hair",
    "how to get a natural no makeup look",
    "what are the basics of skincare",
    "how to fade acne scars naturally",
    "best lip care routine for dry lips",
    "how to keep white clothes white",
    "who was napoleon and what did he do",
    "what was feudalism in medieval europe",
    "how did ancient rome fall",
    "history of the british empire",
    "what caused the great famine in ireland",
    "history of the islamic golden age",
    "who were the samurai in japan",
    "what happened during the cold war",
    "history of the berlin wall",
    "what is manifest destiny in american history",
    "why is the ocean salty",
    "how do glaciers form",
    "what causes the northern lights",
    "how big is the sahara desert",
    "what is biodiversity and why does it matter",
    "how do hurricanes form",
    "what is the ozone layer",
    "why do we have seasons",
    "what is the biggest animal that ever lived",
    "how deep can you dig into the earth",
    "what to do if you get a parking ticket",
    "how to write a professional email",
    "what is the difference between a will and a trust",
    "how to apply for social benefits",
    "how to write a resignation letter",
    "how to dispute an incorrect bill",
    "what rights do tenants have",
    "how to prepare for a job interview",
    "what is a credit score and how is it calculated",
    "how to apply for a name change",
    "best ways to decorate on a budget",
    "how to make christmas more meaningful",
    "what are typical new years resolutions that actually work",
    "how to give better gifts",
    "what is the history of halloween",
    "how to celebrate a birthday alone and enjoy it",
    "best games to play at a family gathering",
    "how to write a toast speech",
    "what to cook for a dinner party",
    "how to create family traditions",
    "what are good conversation topics for a first date",
    "how to find balance between work and personal life",
    "what to do when you feel overwhelmed",
    "how to create a comfortable home environment",
    "what makes people happy according to psychology",
    "how to stop seeking external validation",
    "how to deal with perfectionism",
    "what are signs you need a break",
    "how to find meaning in everyday life",
    "how to be more content with what you have",
    "what is hedonic adaptation",
    "how to stay grounded when things are chaotic",
    "how to make conversation with anyone",
    "how to be less negative",
    "what is stoicism and how to apply it",
    "how to embrace uncertainty",
    "how to let go of things you can not control",
    "what does it mean to live authentically",
    "how to become a better version of yourself",
    "how to discover your values",
]
