"""Additional English location search templates ('{}' = city) for data poisoning."""

TEMPLATES = [
    "weather {}",
    "weather in {} today",
    "weather {} tomorrow",
    "weather {} this weekend",
    "weather {} next week",
    "weather {} 10 day forecast",
    "weather {} 14 day forecast",
    "weather {} hourly",
    "weather {} right now",
    "weather {} monday",
    "weather {} tuesday",
    "weather {} wednesday",
    "weather {} thursday",
    "weather {} friday",
    "weather {} saturday",
    "weather {} sunday",
    "weather {} january",
    "weather {} february",
    "weather {} march",
    "weather {} april",
    "weather {} may",
    "weather {} june",
    "weather {} july",
    "weather {} august",
    "weather {} september",
    "weather {} october",
    "weather {} november",
    "weather {} december",
    "current temperature {}",
    "temperature {} today",
    "rain {} today",
    "snow {} forecast",
    "humidity {} today",
    "wind speed {}",
    "uv index {}",
    "sunrise sunset {}",
    "hotels in {}",
    "best hotels {}",
    "cheap hotels {}",
    "luxury hotels {}",
    "hotel deals {}",
    "hotels {} tonight",
    "hotels {} this weekend",
    "5 star hotels {}",
    "4 star hotels {}",
    "3 star hotels {}",
    "budget hotels {}",
    "hostels in {}",
    "best hostels {}",
    "cheap hostels {}",
    "airbnb {}",
    "airbnb rentals {}",
    "vacation rentals {}",
    "holiday apartments {}",
    "short term rentals {}",
    "camping {}",
    "campsites {}",
    "campgrounds near {}",
    "glamping {}",
    "bed and breakfast {}",
    "guesthouses {}",
    "motels {}",
    "boutique hotels {}",
    "hotels near {} city center",
    "hotels {} with pool",
    "hotels {} with parking",
    "hotels {} pet friendly",
    "hotels {} near airport",
    "where to stay {}",
    "accommodation {}",
    "restaurants in {}",
    "best restaurants {}",
    "cheap restaurants {}",
    "restaurants {} open now",
    "restaurants {} open late",
    "restaurants {} near me",
    "fine dining {}",
    "vegan restaurants {}",
    "vegetarian restaurants {}",
    "vegan food {}",
    "vegetarian food {}",
    "gluten free restaurants {}",
    "halal restaurants {}",
    "kosher restaurants {}",
    "breakfast places {}",
    "best breakfast {}",
    "brunch {}",
    "best brunch {}",
    "lunch spots {}",
    "dinner restaurants {}",
    "pizza {} best",
    "best pizza in {}",
    "pizza delivery {}",
    "burger {}",
    "best burgers {}",
    "sushi {}",
    "best sushi {}",
    "ramen {}",
    "italian restaurants {}",
    "chinese restaurants {}",
    "indian restaurants {}",
    "thai restaurants {}",
    "mexican restaurants {}",
    "japanese restaurants {}",
    "korean restaurants {}",
    "vietnamese restaurants {}",
    "greek restaurants {}",
    "spanish restaurants {}",
    "french restaurants {}",
    "turkish restaurants {}",
    "lebanese restaurants {}",
    "ethiopian restaurants {}",
    "american food {}",
    "asian food {}",
    "middle eastern food {}",
    "seafood restaurants {}",
    "steak restaurants {}",
    "bbq {}",
    "barbecue {}",
    "tapas {}",
    "dim sum {}",
    "street food {}",
    "food trucks {}",
    "fast food {}",
    "food markets {}",
    "local food {}",
    "traditional food {}",
    "rooftop restaurants {}",
    "restaurants with view {}",
    "restaurants {} with outdoor seating",
    "michelin star restaurants {}",
    "cafes {}",
    "coffee shops {}",
    "best coffee {}",
    "specialty coffee {}",
    "third wave coffee {}",
    "cafes with wifi {}",
    "cozy cafes {}",
    "cafes {} open early",
    "bakeries {}",
    "patisseries {}",
    "dessert places {}",
    "ice cream {}",
    "bubble tea {}",
    "juice bars {}",
    "bars {}",
    "best bars {}",
    "cocktail bars {}",
    "wine bars {}",
    "craft beer {}",
    "breweries {}",
    "pubs {}",
    "sports bars {}",
    "rooftop bars {}",
    "bars {} open late",
    "bars {} open now",
    "nightlife {}",
    "clubs {}",
    "nightclubs {}",
    "best clubs {}",
    "things to do in {}",
    "things to do {} this weekend",
    "activities in {}",
    "attractions {}",
    "{} attractions",
    "top attractions {}",
    "must see {}",
    "sightseeing {}",
    "tourist spots {}",
    "what to do in {}",
    "places to visit {}",
    "best places to visit {}",
    "hidden gems {}",
    "museums {}",
    "best museums {}",
    "art museums {}",
    "history museums {}",
    "science museums {}",
    "natural history museum {}",
    "art galleries {}",
    "contemporary art {}",
    "parks {}",
    "national parks near {}",
    "best parks {}",
    "botanical garden {}",
    "gardens {}",
    "zoo {}",
    "aquarium {}",
    "beaches {}",
    "best beaches near {}",
    "swimming beaches {}",
    "hiking near {}",
    "hiking trails {}",
    "hiking {} beginner",
    "hiking {} advanced",
    "nature walks {}",
    "waterfalls near {}",
    "viewpoints {}",
    "scenic viewpoints {}",
    "best views {}",
    "observation deck {}",
    "old town {}",
    "{} old town",
    "historic sites {}",
    "landmarks {}",
    "{} castle",
    "castles near {}",
    "monuments {}",
    "ruins near {}",
    "cathedrals {}",
    "churches {}",
    "temples {}",
    "mosques {}",
    "synagogues {}",
    "markets {}",
    "local markets {}",
    "flea market {}",
    "antique market {}",
    "souvenir shops {}",
    "shopping {}",
    "shopping malls {}",
    "best shopping {}",
    "outlet shopping {}",
    "boutique shops {}",
    "street shopping {}",
    "department stores {}",
    "bookshops {}",
    "record stores {}",
    "thrift stores {}",
    "vintage shops {}",
    "events in {} today",
    "events {} this weekend",
    "concerts {}",
    "live music {}",
    "festivals {}",
    "festivals {} summer",
    "festivals {} winter",
    "events {} this month",
    "upcoming events {}",
    "markets {} this weekend",
    "christmas market {}",
    "food festival {}",
    "street festival {}",
    "cultural events {}",
    "free events {}",
    "sports events {}",
    "flights to {}",
    "cheap flights to {}",
    "flights from {}",
    "cheap flights from {}",
    "direct flights to {}",
    "flights {} one way",
    "flights {} round trip",
    "airline tickets {}",
    "train to {}",
    "trains from {}",
    "train tickets {}",
    "bus to {}",
    "buses from {}",
    "bus tickets {}",
    "ferry to {}",
    "ferries from {}",
    "car rental {}",
    "rent a car {}",
    "cheap car rental {}",
    "taxi {}",
    "taxi from {} airport",
    "taxi to {}",
    "uber {}",
    "rideshare {}",
    "airport transfer {}",
    "how to get to {}",
    "how to get from {} to",
    "getting around {}",
    "public transport {}",
    "metro {}",
    "{} metro map",
    "{} subway map",
    "bus map {}",
    "tram {}",
    "public transport card {}",
    "transport pass {}",
    "bike rental {}",
    "cycling {}",
    "scooter rental {}",
    "e-scooter {}",
    "parking {}",
    "parking near {}",
    "free parking {}",
    "cheap parking {}",
    "traffic {} today",
    "{} traffic now",
    "traffic jams {}",
    "road conditions {}",
    "airport {}",
    "{} airport",
    "{} airport terminal",
    "{} airport transfers",
    "{} airport bus",
    "{} airport taxi",
    "{} airport hotel",
    "apartment rent {}",
    "apartments for rent {}",
    "rent apartment {}",
    "rental prices {}",
    "average rent {}",
    "studio apartment {}",
    "one bedroom apartment {}",
    "two bedroom apartment {}",
    "flats for rent {}",
    "houses for rent {}",
    "property for sale {}",
    "houses for sale {}",
    "apartments for sale {}",
    "property prices {}",
    "real estate {}",
    "house prices {}",
    "cost of living {}",
    "living costs {}",
    "cost of living {} compared to",
    "is {} expensive",
    "how expensive is {}",
    "average salary {}",
    "salary {}",
    "jobs {}",
    "job vacancies {}",
    "hiring {}",
    "work in {}",
    "working in {}",
    "jobs {} remote",
    "it jobs {}",
    "engineering jobs {}",
    "healthcare jobs {}",
    "teaching jobs {}",
    "internships {}",
    "universities {}",
    "best universities {}",
    "colleges {}",
    "university {}",
    "{} university ranking",
    "language schools {}",
    "english courses {}",
    "schools {}",
    "international schools {}",
    "private schools {}",
    "kindergarten {}",
    "daycare {}",
    "map of {}",
    "{} map",
    "{} city map",
    "{} neighborhood map",
    "zip code {}",
    "{} zip code",
    "postal code {}",
    "{} postal code",
    "area code {}",
    "{} area code",
    "population {}",
    "{} population",
    "{} population 2024",
    "history of {}",
    "{} history",
    "{} wiki",
    "{} wikipedia",
    "time zone {}",
    "{} time zone",
    "current time {}",
    "elevation {}",
    "{} elevation above sea level",
    "coordinates {}",
    "latitude longitude {}",
    "{} gps coordinates",
    "best time to visit {}",
    "when to visit {}",
    "peak season {}",
    "off season {}",
    "avoid crowds {}",
    "doctor {}",
    "doctors {}",
    "hospital {}",
    "hospitals {}",
    "emergency hospital {}",
    "pharmacy {}",
    "pharmacies {}",
    "dentist {}",
    "eye doctor {}",
    "clinic {}",
    "urgent care {}",
    "health insurance {}",
    "gym {}",
    "gyms {}",
    "fitness center {}",
    "yoga {}",
    "yoga studio {}",
    "crossfit {}",
    "swimming pool {}",
    "public pool {}",
    "spa {}",
    "wellness {}",
    "sauna {}",
    "coworking {}",
    "coworking space {}",
    "coworking spaces {}",
    "shared office {}",
    "cafe with wifi {}",
    "wifi {} cafe",
    "internet cafe {}",
    "work remotely {}",
    "digital nomad {}",
    "nomad friendly {}",
    "dog friendly {}",
    "dog friendly restaurants {}",
    "dog friendly hotels {}",
    "dog friendly beaches {}",
    "pet friendly {}",
    "kid friendly {}",
    "family friendly {}",
    "family activities {}",
    "things to do with kids {}",
    "playground {}",
    "children museum {}",
    "water park {}",
    "amusement park {}",
    "theme park {}",
    "wheelchair accessible {}",
    "disabled access {}",
    "accessible hotels {}",
    "accessibility {}",
    "safety {}",
    "is {} safe",
    "crime rate {}",
    "{} crime rate",
    "safe neighborhoods {}",
    "travel safety {}",
    "safety tips {}",
    "webcam {}",
    "{} live webcam",
    "live camera {}",
    "live stream {}",
    "{} language",
    "what language spoken {}",
    "do people speak english {}",
    "currency {}",
    "{} currency",
    "exchange rate {}",
    "money {}",
    "atm {}",
    "day trips from {}",
    "day trip {}",
    "excursions from {}",
    "nearby cities {}",
    "nearby towns {}",
    "places near {}",
    "weekend trip from {}",
    "{} itinerary",
    "itinerary {}",
    "3 days in {}",
    "2 days in {}",
    "one week in {}",
    "travel guide {}",
    "{} travel guide",
    "guide to {}",
    "visiting {}",
    "first time {}",
    "travel tips {}",
    "expat {}",
    "expats in {}",
    "moving to {}",
    "relocating to {}",
    "visa {}",
    "{} visa requirements",
    "passport requirements {}",
    "driving license {}",
    "driving in {}",
    "speed limits {}",
    "fuel prices {}",
    "gas stations {}",
    "electric vehicle charging {}",
    "ev charging {}",
    "tapwater {}",
    "is tapwater safe {}",
    "drinking water {}",
    "recycling {}",
    "waste disposal {}",
    "sustainability {}",
    "eco friendly {}",
    "green spaces {}",
    "air quality {}",
    "{} air quality index",
    "pollution {}",
    "noise levels {}",
    "new year events {}",
    "new years eve {}",
    "halloween {}",
    "christmas events {}",
    "easter events {}",
    "public holidays {}",
    "{} public holidays",
    "bank holidays {}",
    "opening hours {}",
    "shops open sunday {}",
    "stores open {}",
    "supermarkets {}",
    "grocery stores {}",
    "farmers market {}",
    "organic food {}",
    "health food stores {}",
    "food delivery {}",
    "delivery apps {}",
    "food apps {}",
    "uber eats {}",
    "post office {}",
    "police station {}",
    "embassy {}",
    "consulate {}",
    "tourist information {}",
    "tourist office {}",
    "visitor center {}",
    "sim card {}",
    "mobile data {}",
    "phone plan {}",
    "bank {}",
    "banks {}",
    "open bank account {}",
    "tax {}",
    "tax rates {}",
    "income tax {}",
    "vat {}",
    "retirement {}",
    "retire in {}",
    "studying in {}",
    "student life {}",
    "student accommodation {}",
    "nightlife {} for students",
    "free things to do {}",
    "free attractions {}",
    "free museums {}",
    "cheap things to do {}",
    "budget travel {}",
    "budget guide {}",
    "tipping culture {}",
    "tipping {}",
    "tips {}",
    "local customs {}",
    "etiquette {}",
    "dress code {}",
    "culture {}",
    "{} culture",
    "local culture {}",
    "religion {}",
    "architecture {}",
    "{} architecture",
    "street art {}",
    "graffiti {}",
    "music scene {}",
    "live music venues {}",
    "jazz clubs {}",
    "comedy clubs {}",
    "theater {}",
    "theatre {}",
    "opera {}",
    "ballet {}",
    "cinema {}",
    "cinemas {}",
    "movie theaters {}",
    "sports {}",
    "football {}",
    "soccer {}",
    "basketball {}",
    "tennis {}",
    "running {}",
    "marathon {}",
    "cycling routes {}",
    "surfing {}",
    "skiing {}",
    "ski resorts near {}",
    "snowboarding {}",
    "swimming {}",
    "water sports {}",
    "sailing {}",
    "kayaking {}",
    "rock climbing {}",
    "bouldering {}",
    "golf {}",
    "golf courses {}",
    "bowling {}",
    "escape rooms {}",
    "laser tag {}",
    "paintball {}",
    "karting {}",
    "climbing walls {}",
    "trampoline park {}",
    "virtual reality {}",
    "arcades {}",
    "gaming cafes {}",
    "board game cafes {}",
    "karaoke {}",
    "casinos {}",
    "photography {}",
    "instagram spots {}",
    "best photo spots {}",
    "sunset spots {}",
    "sunrise spots {}",
    "rooftop views {}",
    "panoramic views {}",
    "lookout points {}",
    "state parks near {}",
    "forest {}",
    "lakes near {}",
    "rivers {}",
    "mountains near {}",
    "valleys {}",
    "hot springs {}",
    "thermal baths {}",
    "caves near {}",
    "volcanoes near {}",
    "islands near {}",
    "peninsulas {}",
    "countryside {}",
    "rural areas near {}",
    "vineyards {}",
    "wineries {}",
    "wine tasting {}",
    "distilleries {}",
    "whiskey {}",
    "craft cocktails {}",
    "tea rooms {}",
    "afternoon tea {}",
    "high tea {}",
    "food tours {}",
    "walking tours {}",
    "bike tours {}",
    "boat tours {}",
    "bus tours {}",
    "helicopter tours {}",
    "guided tours {}",
    "self guided tours {}",
    "audio guides {}",
    "city pass {}",
    "tourist pass {}",
    "discount card {}",
    "train pass {}",
    "beach clubs {}",
    "pool bars {}",
    "beach bars {}",
    "waterfront {}",
    "harbor {}",
    "{} harbor",
    "marina {}",
    "pier {}",
    "promenade {}",
    "boardwalk {}",
    "riverfront {}",
    "lakefront {}",
    "waterpark {}",
    "sports stadium {}",
    "football stadium {}",
    "concert venue {}",
    "arenas {}",
    "convention center {}",
    "conference center {}",
    "wedding venues {}",
    "event spaces {}",
    "rooftop venues {}",
    "outdoor venues {}",
    "photo studios {}",
    "recording studios {}",
    "art studios {}",
    "craft workshops {}",
    "pottery classes {}",
    "cooking classes {}",
    "dance classes {}",
    "yoga classes {}",
    "language classes {}",
    "german classes {}",
    "spanish classes {}",
    "french classes {}",
    "language exchange {}",
    "tutoring {}",
    "libraries {}",
    "public libraries {}",
    "reading cafes {}",
    "study spaces {}",
    "quiet cafes {}",
    "remote work {}",
    "work spaces {}",
    "hot desks {}",
    "meeting rooms {}",
    "printing services {}",
    "laundry {}",
    "laundromat {}",
    "dry cleaning {}",
    "haircut {}",
    "barbers {}",
    "hair salons {}",
    "nail salons {}",
    "beauty salons {}",
    "tattoo shops {}",
    "piercing {}",
    "massage {}",
    "massage therapy {}",
    "physiotherapy {}",
    "chiropractor {}",
    "optician {}",
    "vet {}",
    "veterinary {}",
    "dog grooming {}",
    "pet stores {}",
    "hardware stores {}",
    "ikea {}",
    "furniture stores {}",
    "electronics stores {}",
    "phone repair {}",
    "computer repair {}",
    "car repair {}",
    "mechanic {}",
    "car wash {}",
    "petrol station {}",
    "camping gear {}",
    "outdoor stores {}",
    "sports stores {}",
    "bicycle shops {}",
    "skateboard shops {}",
    "surf shops {}",
    "second hand shops {}",
    "charity shops {}",
    "pawn shops {}",
    "toy stores {}",
    "kids shops {}",
    "baby stores {}",
    "maternity {}",
    "pharmacy delivery {}",
    "24 hour pharmacy {}",
    "covid testing {}",
    "vaccination {}",
    "mental health {}",
    "therapy {}",
    "psychologist {}",
    "counseling {}",
    "addiction help {}",
    "animal shelter {}",
    "volunteer {}",
    "volunteering {}",
    "charities {}",
    "community center {}",
    "social clubs {}",
    "sports clubs {}",
    "running clubs {}",
    "chess clubs {}",
    "book clubs {}",
    "expat community {}",
    "english speakers {}",
    "facebook groups {}",
    "meetup {}",
    "networking events {}",
    "startup scene {}",
    "tech scene {}",
    "startups {}",
    "innovation hub {}",
    "accelerators {}",
    "incubators {}",
    "venture capital {}",
    "investment {}",
    "business {}",
    "doing business {}",
    "business registration {}",
    "freelance {}",
    "freelancing {}",
    "tax advisor {}",
    "accountant {}",
    "lawyer {}",
    "legal advice {}",
    "notary {}",
    "translation services {}",
    "interpreter {}",
    "shipping {}",
    "postal services {}",
    "courier {}",
    "package delivery {}",
    "customs {}",
    "import regulations {}",
    "night markets {}",
    "food stalls {}",
    "hawker centers {}",
    "cafeteria {}",
    "canteen {}",
    "food court {}",
    "eating out {} cheaply",
    "all you can eat {}",
    "buffet {}",
    "fondue {}",
    "shabu shabu {}",
    "hot pot {}",
    "teppanyaki {}",
    "omakase {}",
    "tapas bar {}",
    "pintxos {}",
    "mezze {}",
    "smorgasbord {}",
    "brunch menu {}",
    "bottomless brunch {}",
    "happy hour {}",
    "happy hour bars {}",
    "two for one drinks {}",
    "cocktail menu {}",
    "mocktail {}",
    "non alcoholic bars {}",
    "sober bars {}",
    "sports bar {} with screens",
    "watch football {}",
    "watch game {}",
    "live sport {}",
    "trivia night {}",
    "pub quiz {}",
    "open mic {}",
    "stand up comedy {}",
    "drag shows {}",
    "lgbtq bars {}",
    "gay bars {}",
    "queer friendly {}",
    "inclusive venues {}",
    "sunset cruise {}",
    "dinner cruise {}",
    "river cruise {}",
    "canal tour {}",
    "gondola {}",
    "cable car {}",
    "funicular {}",
    "tuk tuk {}",
    "rickshaw {}",
    "horse carriage {}",
    "helicopter ride {}",
    "hot air balloon {}",
    "paragliding {}",
    "skydiving {}",
    "bungee jumping {}",
    "zip line {}",
    "white water rafting {}",
    "snorkeling {}",
    "scuba diving {}",
    "surfing lessons {}",
    "kitesurfing {}",
    "windsurfing {}",
    "paddleboarding {}",
    "canoeing {}",
    "fishing {}",
    "fishing trips {}",
    "horseback riding {}",
    "cycling tour {}",
    "e-bike rental {}",
    "quad biking {}",
    "off road {}",
    "jeep tour {}",
    "safari near {}",
    "wildlife watching {}",
    "birdwatching {}",
    "whale watching {}",
    "dolphin watching {}",
    "seal watching {}",
    "swimming with dolphins {}",
    "night safari {}",
    "stargazing {}",
    "astronomy {}",
    "dark sky {}",
    "northern lights {}",
    "aurora {}",
    "rainy day activities {}",
    "indoor activities {}",
    "indoor climbing {}",
    "bowling alley {}",
    "mini golf {}",
    "crazy golf {}",
    "pool hall {}",
    "billiards {}",
    "darts {}",
    "retro arcade {}",
    "museum pass {}",
    "gallery free entry {}",
    "open house {}",
    "architecture tour {}",
    "ghost tour {}",
    "street food tour {}",
    "bar crawl {}",
    "pub crawl {}",
    "wine tour {}",
    "beer tour {}",
    "chocolate tour {}",
    "cheese tasting {}",
    "olive oil tasting {}",
    "truffle hunting {}",
    "mushroom foraging {}",
    "foraging tour {}",
    "cooking school {}",
    "sushi class {}",
    "pasta making class {}",
    "bread baking {}",
    "coffee cupping {}",
    "barista course {}",
    "cocktail making {}",
    "mixology {}",
    "perfume making {}",
    "glass blowing {}",
    "ceramic workshop {}",
    "painting class {}",
    "drawing class {}",
    "photography tour {}",
    "photo walk {}",
    "film locations {}",
    "movie locations {}",
    "tv show locations {}",
    "literary tours {}",
    "book tour {}",
    "music tour {}",
    "beatle tour {}",
    "historical walk {}",
    "jewish quarter {}",
    "roman ruins {}",
    "medieval town {}",
    "renaissance {}",
    "baroque architecture {}",
    "art nouveau {}",
    "modernist architecture {}",
    "brutalist buildings {}",
    "contemporary architecture {}",
    "skyline {}",
    "{} skyline",
    "city tour {}",
    "hop on hop off {}",
    "open top bus {}",
    "panorama bus {}",
    "free walking tour {}",
    "pay what you want {}",
    "museum free day {}",
    "student discounts {}",
    "senior discounts {}",
    "family tickets {}",
    "group discount {}",
    "early bird {}",
    "last minute {}",
    "skip the queue {}",
    "timed entry {}",
    "booking required {}",
    "reservations {}",
    "table booking {}",
    "reservation system {}",
    "online booking {}",
    "travel insurance {}",
    "insurance {}",
    "emergency services {}",
    "emergency number {}",
    "{} emergency number",
    "lost passport {}",
    "embassy {} contact",
    "crime {}",
    "pickpocket {}",
    "scams {}",
    "tourist traps {}",
    "overrated {}",
    "{} overrated",
    "underrated {}",
    "hidden {}",
    "secret spots {}",
    "locals only {}",
    "off the beaten path {}",
    "unusual {}",
    "weird things {}",
    "quirky {}",
    "unique experiences {}",
    "only in {}",
    "typical {}",
    "iconic {}",
    "most famous {}",
    "photo worthy {}",
    "aesthetic {}",
    "trendy {}",
    "hipster {}",
    "gentrified {}",
    "bohemian {}",
    "artsy {}",
    "upscale {}",
    "posh {}",
    "rough areas {}",
    "dangerous areas {}",
    "best neighborhoods {}",
    "best areas to stay {}",
    "where to live {}",
    "residential areas {}",
    "suburbs {}",
    "outskirts {}",
    "city center {}",
    "downtown {}",
    "old quarter {}",
    "new town {}",
    "historic center {}",
    "financial district {}",
    "business district {}",
    "embassy district {}",
    "expat areas {}",
    "international community {}",
    "nightlife district {}",
    "red light district {}",
    "lgbtq district {}",
    "chinatown {}",
    "little italy {}",
    "arts district {}",
    "museum district {}",
    "student area {}",
    "university district {}",
    "market district {}",
    "harbour area {}",
    "beach area {}",
    "mountain area {}",
    "lakes area {}",
    "size of {}",
    "{} size",
    "area {}",
    "{} facts",
    "interesting facts {}",
    "fun facts {}",
    "{} nickname",
    "known for {}",
    "{} known for",
    "famous people from {}",
    "{} famous people",
    "celebrities from {}",
    "born in {}",
    "founded {}",
    "when was {} founded",
    "age of {}",
    "oldest part {}",
    "city center {} map",
    "street map {}",
    "walking distance {}",
    "walkable {}",
    "walkability score {}",
    "livability {}",
    "livability score {}",
    "quality of life {}",
    "happiness index {}",
    "standard of living {}",
    "infrastructure {}",
    "utilities {}",
    "water quality {}",
    "internet speed {}",
    "broadband {}",
    "5g {}",
    "technology {}",
    "smart city {}",
    "startup {}",
    "innovation {}",
    "gdp {}",
    "economy {}",
    "economic growth {}",
    "poverty rate {}",
    "unemployment {}",
    "income inequality {}",
    "minimum wage {}",
    "average income {}",
    "household income {}",
    "median salary {}",
    "buying power {}",
    "affordability {}",
    "cheap to live {}",
    "expensive to live {}",
    "tax free {}",
    "low tax {}",
    "high tax {}",
    "pension {}",
    "social security {}",
    "healthcare system {}",
    "free healthcare {}",
    "private healthcare {}",
    "insurance costs {}",
    "education system {}",
    "free education {}",
    "school fees {}",
    "university fees {}",
    "student visa {}",
    "work visa {}",
    "digital nomad visa {}",
    "citizenship {}",
    "naturalization {}",
    "permanent residency {}",
    "green card {}",
    "immigration {}",
    "expat guide {}",
    "retire abroad {}",
    "best places retire {}",
    "climate {}",
    "{} climate",
    "average temperature {}",
    "rainy season {}",
    "dry season {}",
    "monsoon {}",
    "hurricane season {}",
    "tornado risk {}",
    "earthquake risk {}",
    "flood risk {}",
    "natural disasters {}",
    "emergency preparedness {}",
    "civil defense {}",
    "blackout {}",
    "power cuts {}",
    "street noise {}",
    "light pollution {}",
    "green city {}",
    "cycling city {}",
    "pedestrian friendly {}",
    "family friendly city {}",
    "retirement friendly {}",
    "senior friendly {}",
    "student friendly {}",
    "night owl {}",
    "early riser {}",
    "24 hour city {}",
    "city that never sleeps {}",
    "quiet city {}",
    "busy city {}",
    "crowded {}",
    "tourist season {}",
    "high season {}",
    "low season {}",
    "shoulder season {}",
    "best month {}",
    "cheapest month {}",
    "most visited {}",
    "tourist numbers {}",
    "overtourism {}",
    "locals vs tourists {}",
]
