"""Listas de palabras en espanol para el data poisoning (ver browser/decoy.py)."""

CITIES = [
    "madrid",
    "barcelona",
    "valencia",
    "sevilla",
    "zaragoza",
    "málaga",
    "murcia",
    "palma",
    "las palmas de gran canaria",
    "bilbao",
    "alicante",
    "córdoba",
    "valladolid",
    "vigo",
    "gijón",
    "hospitalet de llobregat",
    "vitoria",
    "granada",
    "elche",
    "oviedo",
    "badalona",
    "cartagena",
    "terrassa",
    "jerez de la frontera",
    "sabadell",
    "santa cruz de tenerife",
    "pamplona",
    "almería",
    "fuenlabrada",
    "leganés",
    "san sebastián",
    "getafe",
    "burgos",
    "albacete",
    "santander",
    "castellón de la plana",
    "alcalá de henares",
    "logroño",
    "badajoz",
    "salamanca",
    "huelva",
    "marbella",
    "lleida",
    "tarragona",
    "dos hermanas",
    "parla",
    "torrejón de ardoz",
    "mataró",
    "santa coloma de gramenet",
    "jaén",
    "algeciras",
    "cádiz",
    "reus",
    "tenerife",
    "girona",
    "lugo",
    "ourense",
    "pontevedra",
    "toledo",
    "cáceres",
    "mérida",
    "cuenca",
    "segovia",
    "ávila",
    "soria",
    "guadalajara",
    "ciudad real",
    "teruel",
    "huesca",
    "lérida",
    "santiago de compostela",
    "a coruña",
    "ferrol",
    "León",
    "palencia",
    "zamora",
    "ciudad de méxico",
    "guadalajara jalisco",
    "monterrey",
    "puebla",
    "tijuana",
    "toluca",
    "juárez",
    "mérida yucatán",
    "cancún",
    "querétaro",
    "san luis potosí",
    "aguascalientes",
    "acapulco",
    "hermosillo",
    "saltillo",
    "morelia",
    "culiacán",
    "veracruz",
    "oaxaca",
    "chihuahua",
    "torreón",
    "durango",
    "tepic",
    "colima",
    "cuernavaca",
    "tuxtla gutiérrez",
    "villahermosa",
    "campeche",
    "chetumal",
    "playa del carmen",
    "buenos aires",
    "córdoba argentina",
    "rosario",
    "mendoza",
    "tucumán",
    "la plata",
    "mar del plata",
    "salta",
    "santa fe",
    "san juan",
    "resistencia",
    "neuquén",
    "corrientes",
    "posadas",
    "bahía blanca",
    "santiago",
    "valparaíso",
    "concepción",
    "antofagasta",
    "viña del mar",
    "temuco",
    "iquique",
    "rancagua",
    "talca",
    "arica",
    "bogotá",
    "medellín",
    "cali",
    "barranquilla",
    "cartagena de indias",
    "cúcuta",
    "bucaramanga",
    "pereira",
    "santa marta",
    "manizales",
    "lima",
    "arequipa",
    "trujillo",
    "chiclayo",
    "piura",
    "iquitos",
    "cusco",
    "tacna",
    "caracas",
    "maracaibo",
    "valencia venezuela",
    "barquisimeto",
    "maracay",
    "quito",
    "guayaquil",
    "cuenca ecuador",
    "santo domingo",
    "santiago de los caballeros",
    "san pedro de macorís",
    "la habana",
    "santiago de cuba",
    "san josé",
    "heredia",
    "cartago",
    "panama",
    "colón",
    "managua",
    "león",
    "tegucigalpa",
    "san pedro sula",
    "san salvador",
    "santa ana",
    "ciudad de guatemala",
    "quetzaltenango",
    "asunción",
    "ciudad del este",
    "montevideo",
    "salto",
    "la paz",
    "santa cruz de la sierra",
    "cochabamba",
    "sucre",
    "oruro",
    "potosí",
    "trinidad",
    "puerto príncipe",
    "san juan de puerto rico",
    "ponce",
    "nueva york",
    "los ángeles",
    "miami",
    "chicago",
    "houston",
    "dallas",
    "san francisco",
    "washington",
    "boston",
    "seattle",
    "atlanta",
    "las vegas",
    "denver",
    "orlando",
    "toronto",
    "montreal",
    "vancouver",
    "ottawa",
    "calgary",
    "edimburgo",
    "glasgow",
    "mánchester",
    "birmingham",
    "leeds",
    "liverpool",
    "bristol",
    "cardiff",
    "bruselas",
    "amberes",
    "gante",
    "lieja",
    "amsterdam",
    "róterdam",
    "la haya",
    "utrecht",
    "eindhoven",
    "múnich",
    "berlín",
    "hamburgo",
    "fráncfort",
    "colonia",
    "stuttgart",
    "düsseldorf",
    "dresde",
    "leipzig",
    "hanóver",
    "nuremberg",
    "viena",
    "graz",
    "linz",
    "salzburgo",
    "innsbruck",
    "zúrich",
    "ginebra",
    "basilea",
    "berna",
    "lausana",
    "milán",
    "roma",
    "nápoles",
    "turín",
    "florencia",
    "venecia",
    "bolonia",
    "génova",
    "palermo",
    "bari",
    "catania",
    "verona",
    "trento",
    "trieste",
    "parís",
    "lyon",
    "marsella",
    "toulouse",
    "niza",
    "burdeos",
    "estrasburgo",
    "nantes",
    "lille",
    "montpellier",
    "rennes",
    "brest",
    "grenoble",
    "lisboa",
    "oporto",
    "braga",
    "coímbra",
    "funchal",
    "moscú",
    "san petersburgo",
    "ekaterimburgo",
    "novosibirsk",
    "kazán",
    "varsovia",
    "cracovia",
    "lodz",
    "gdansk",
    "breslavia",
    "poznan",
    "praga",
    "brno",
    "ostrava",
    "bratislava",
    "budapest",
    "debrecen",
    "bucarest",
    "cluj",
    "sofía",
    "plovdiv",
    "belgrade",
    "zagreb",
    "liubliana",
    "sarajevo",
    "skopie",
    "tirana",
    "atenas",
    "tesalónica",
    "heraclión",
    "estambul",
    "ankara",
    "esmirna",
    "estocolmo",
    "gotemburgo",
    "malmö",
    "upsala",
    "copenhague",
    "aarhus",
    "odense",
    "oslo",
    "bergen",
    "trondheim",
    "helsinki",
    "tampere",
    "turku",
    "reikiavik",
    "dublín",
    "cork",
    "galway",
    "riga",
    "tallin",
    "vilna",
    "chisinau",
    "kiev",
    "kharkiv",
    "odesa",
    "minsk",
    "tiflis",
    "ereván",
    "bakú",
    "almaty",
    "astana",
    "tashkent",
    "tehérán",
    "mashhad",
    "isfahan",
    "bagdad",
    "mosul",
    "damasco",
    "alepo",
    "amán",
    "beirut",
    "tel aviv",
    "jerusalén",
    "dubái",
    "abu dabi",
    "doha",
    "kuwait",
    "riad",
    "jeddah",
    "karachi",
    "lahore",
    "islamabad",
    "delhi",
    "mumbai",
    "bangalore",
    "chennai",
    "kolkata",
    "hyderabad",
    "pune",
    "ahmedabad",
    "jaipur",
    "lucknow",
    "surat",
    "katmandú",
    "colombo",
    "daca",
    "chittagong",
    "rangún",
    "bangkok",
    "chiang mai",
    "pattaya",
    "kuala lumpur",
    "penang",
    "singapur",
    "yakarta",
    "surabaya",
    "bandung",
    "bali",
    "manila",
    "cebú",
    "davao",
    "hanói",
    "ciudad ho chi minh",
    "da nang",
    "nom pen",
    "vientiane",
    "tokio",
    "osaka",
    "kioto",
    "yokohama",
    "nagoya",
    "hiroshima",
    "fukuoka",
    "saporo",
    "seúl",
    "busan",
    "incheon",
    "pekín",
    "shanghái",
    "cantón",
    "shenzhen",
    "chengdu",
    "wuhan",
    "tianjín",
    "xian",
    "chongqing",
    "nanjing",
    "hangzhou",
    "hong kong",
    "macao",
    "taipéi",
    "ulán bator",
    "sídney",
    "melbourne",
    "brisbane",
    "perth",
    "adelaida",
    "auckland",
    "wellington",
    "christchurch",
    "el cairo",
    "alejandría",
    "casablanca",
    "rabat",
    "marrakech",
    "fez",
    "tánger",
    "argel",
    "orán",
    "túnez",
    "trípoli",
    "lagos",
    "abuya",
    "accra",
    "dakar",
    "abiyán",
    "nairobi",
    "mombasa",
    "addis abeba",
    "kampala",
    "dar es salam",
    "ciudad del cabo",
    "johannesburgo",
    "durban",
    "pretoria",
    "harare",
    "lusaka",
    "maputo",
    "antananarivo",
    "luanda",
    "kinshasa",
    "brazzaville",
    "yaundé",
    "lomé",
    "uagadugú",
    "niamey",
    "bamako",
    "conakri",
    "freetown",
    "monrovia",
    "asmara",
    "mogadiscio",
    "yibuti",
    "jartum",
    "porto alegre",
    "belo horizonte",
    "brasilia",
    "río de janeiro",
    "sao paulo",
    "salvador",
    "fortaleza",
    "manaos",
    "recife",
    "belém",
    "florianópolis",
    "curitiba",
    "goiania",
    "campo grande",
    "natal",
    "maceió",
    "reykjavik",
    "luxemburgo",
    "mónaco",
    "andorra la vella",
    "valletta",
    "nicosia",
    "san marino",
    "vaduz",
    "londres",
]

TEMPLATES = [
    "tiempo en {} hoy",
    "tiempo en {} mañana",
    "tiempo en {} este fin de semana",
    "pronóstico del tiempo {} esta semana",
    "lluvia en {} esta tarde",
    "temperatura en {} ahora",
    "hoteles baratos en {}",
    "mejores hoteles en {}",
    "hostales en {} centro",
    "apartamentos en {} por noche",
    "alojamiento económico en {}",
    "airbnb en {}",
    "hoteles con piscina en {}",
    "hotel boutique en {}",
    "hoteles con desayuno incluido en {}",
    "hotel cerca del aeropuerto de {}",
    "mejores restaurantes en {}",
    "restaurantes baratos en {}",
    "restaurante vegetariano en {}",
    "desayuno brunch en {}",
    "sushi en {}",
    "pizza en {}",
    "tapas en {}",
    "comida típica de {}",
    "restaurante romántico en {}",
    "restaurante para grupos en {}",
    "dónde comer en {} barato",
    "vuelos baratos a {}",
    "vuelos desde madrid a {}",
    "vuelos desde barcelona a {}",
    "vuelos desde {} a canarias",
    "ofertas de vuelo a {}",
    "tren a {} desde madrid",
    "bus a {} precio",
    "cómo llegar a {}",
    "alquiler de coche en {}",
    "taxi aeropuerto {}",
    "qué ver en {}",
    "qué hacer en {} con niños",
    "lugares imprescindibles en {}",
    "visitas turísticas en {}",
    "museos en {}",
    "parques y jardines en {}",
    "playas cerca de {}",
    "rutas de senderismo en {}",
    "excursiones desde {}",
    "guía turística {}",
    "monumentos históricos en {}",
    "turismo en {}",
    "atracciones gratuitas en {}",
    "mejor época para visitar {}",
    "eventos en {} este fin de semana",
    "conciertos en {} este mes",
    "festivales en {} 2026",
    "qué hay hoy en {}",
    "agenda cultural de {}",
    "exposiciones en {}",
    "teatro en {}",
    "cine en {}",
    "vida nocturna en {}",
    "bares de copas en {}",
    "discotecas en {}",
    "bares de vinos en {}",
    "coctelería en {}",
    "compras en {}",
    "mercados en {}",
    "mercadillo en {}",
    "centro comercial en {}",
    "tiendas de ropa en {}",
    "tiendas vintage en {}",
    "souvenirs en {}",
    "piso en alquiler en {}",
    "alquiler de apartamento en {}",
    "comprar piso en {}",
    "precio vivienda en {}",
    "inmobiliaria en {}",
    "habitación compartida en {}",
    "oferta de trabajo en {}",
    "empleo en {}",
    "trabajar en {}",
    "colegios en {}",
    "universidades en {}",
    "guardería en {}",
    "academia de idiomas en {}",
    "clases particulares en {}",
    "transporte público en {}",
    "metro en {}",
    "autobús urbano en {}",
    "bicicleta pública en {}",
    "aparcamiento en {} gratuito",
    "tráfico en {} ahora",
    "cómo moverse por {} sin coche",
    "uber en {}",
    "cabify en {}",
    "médico de cabecera en {}",
    "hospital en {}",
    "farmacia 24 horas en {}",
    "urgencias en {}",
    "dentista en {}",
    "médico privado en {}",
    "gimnasio en {}",
    "yoga en {}",
    "pilates en {}",
    "spa en {}",
    "peluquería en {}",
    "coworking en {}",
    "cafetería con wifi en {}",
    "biblioteca en {}",
    "piscina municipal en {}",
    "polideportivo en {}",
    "supermercado en {}",
    "mercado de abastos en {}",
    "tienda de segunda mano en {}",
    "ferretería en {}",
    "notario en {}",
    "abogado en {}",
    "asesoría fiscal en {}",
    "bancos en {}",
    "cajero automático en {}",
    "oficina de correos en {}",
    "historia de {}",
    "mapa de {}",
    "código postal {}",
    "zona horaria {}",
    "población de {}",
    "clima de {} en agosto",
    "clima de {} en diciembre",
    "clima de {} en verano",
    "qué idioma se habla en {}",
    "moneda en {}",
    "seguridad en {}",
    "barrios de {}",
    "barrio más bonito de {}",
    "dónde dormir en {} con poco dinero",
    "mejores cafeterías en {}",
    "brunch en {}",
    "desayuno en {}",
    "bar de tapas en {}",
    "heladería en {}",
    "pastelería en {}",
    "panaderías en {}",
    "precio de la cerveza en {}",
    "vino de {}",
    "gastronomía típica de {}",
    "recetas de {}",
    "plato típico de {}",
    "festival de comida en {}",
    "mercado de navidad en {}",
    "qué comprar en {}",
    "artesanía en {}",
    "{} para familias",
    "{} en pareja viaje romántico",
    "{} guía de viaje 2026",
    "{} qué ver en un día",
    "{} fin de semana",
    "{} itinerario 3 días",
    "{} itinerario 5 días",
    "{} viaje barato",
    "{} turismo de aventura",
    "{} turismo de naturaleza",
    "{} ruta en bici",
    "{} ruta a pie",
    "{} visita virtual",
    "{} mapa turístico",
    "qué llevar a {}",
    "idioma oficial de {}",
    "visa para {}",
    "pasaporte necesario para {}",
    "seguro de viaje {}",
    "presupuesto viaje a {}",
    "cuánto cuesta vivir en {}",
    "vivir en {} como expatriado",
    "mudarse a {}",
    "costo de vida en {}",
    "salario medio en {}",
    "impuestos en {}",
    "sanidad pública en {}",
    "requisitos para trabajar en {}",
    "estudiar en {}",
    "beca para estudiar en {}",
    "mascotas permitidas en hoteles en {}",
    "veterinario en {}",
    "parques para perros en {}",
    "actividades con niños en {}",
    "parque de atracciones en {}",
    "acuario en {}",
    "zoológico en {}",
    "camping cerca de {}",
    "glamping en {}",
    "ruta en coche desde {}",
    "alquiler de moto en {}",
    "surf en {}",
    "esquí cerca de {}",
    "submarinismo en {}",
    "kayak en {}",
    "tirolina en {}",
    "paintball en {}",
    "escape room en {}",
    "karting en {}",
    "bolera en {}",
    "exposición de arte en {}",
    "galería de arte en {}",
    "mercado de antigüedades en {}",
    "feria de artesanía en {}",
    "música en vivo en {}",
    "jazz bar en {}",
    "flamenco en {}",
    "salsa en {}",
    "clases de baile en {}",
    "correr en {} rutas",
    "maratón en {} 2026",
    "triatlón en {} 2026",
    "campo de golf en {}",
    "padel en {}",
    "tenis en {}",
    "pádel clubs en {}",
    "restaurante con vistas al mar en {}",
    "restaurante con vistas a la montaña en {}",
    "terraza de moda en {}",
    "rooftop bar en {}",
    "brunch dominical en {}",
    "menú del día en {}",
    "cena romántica en {}",
    "restaurante de mariscos en {}",
    "restaurante japonés en {}",
    "restaurante italiano en {}",
    "restaurante chino en {}",
    "restaurante mexicano en {}",
    "restaurante árabe en {}",
    "restaurante indio en {}",
    "hamburguesería en {}",
    "cervecería artesanal en {}",
    "cócteles sin alcohol en {}",
    "cafés de especialidad en {}",
    "sidrería en {}",
    "marisquería en {}",
    "churrería en {}",
    "chocolatería en {}",
]

STANDALONE = [
    "cómo instalar ubuntu 24.04 paso a paso",
    "diferencia entre ram ddr4 y ddr5",
    "mejor tarjeta gráfica para gaming 2026",
    "python para principiantes tutorial gratis",
    "cómo aprender javascript desde cero",
    "qué es la inteligencia artificial explicado fácil",
    "chatgpt vs gemini comparativa 2026",
    "cómo usar git y github tutorial",
    "mejores extensiones de vs code 2026",
    "cómo hacer una página web gratis",
    "linux vs windows cuál es mejor para programar",
    "ssd nvme vs sata diferencias",
    "cómo montar un pc gaming paso a paso",
    "mejores monitores gaming 2026",
    "auriculares inalámbricos con anc baratos",
    "mejor smartphone android 2026 comparativa",
    "iphone vs samsung cuál comprar",
    "smartwatch con mejor batería 2026",
    "mejor portátil para estudiantes 2026",
    "portátil gaming menos de 1000 euros",
    "tablet para dibujar digital recomendaciones",
    "impresora 3d para principiantes 2026",
    "cómo limpiar el ordenador por dentro",
    "qué es vpn y para qué sirve",
    "cómo configurar una vpn gratis",
    "cómo proteger tu privacidad en internet",
    "gestor de contraseñas cuál es mejor",
    "antivirus gratis 2026 comparativa",
    "cómo hacer copia de seguridad del móvil",
    "recuperar fotos borradas android",
    "cómo descargar música de spotify gratis",
    "cómo descargar videos de youtube",
    "cómo editar fotos gratis en el móvil",
    "mejores apps de edición de vídeo android",
    "cómo hacer un vídeo de youtube paso a paso",
    "cómo ganar dinero con youtube 2026",
    "cómo monetizar instagram en 2026",
    "marketing digital cursos gratis",
    "diseño gráfico canva tutorial",
    "mejores cursos online gratis 2026",
    "udemy cursos en oferta",
    "cómo aprender inglés rápido desde casa",
    "alemán para principiantes frases básicas",
    "francés nivel b1 recursos gratuitos",
    "duolingo o babbel cuál es mejor",
    "cómo mejorar el vocabulario en inglés",
    "traductor de inglés a español",
    "receta de paella valenciana auténtica",
    "cómo hacer tortilla española perfecta",
    "receta de gazpacho casero",
    "masa de pizza casera receta fácil",
    "receta de pasta carbonara auténtica",
    "cómo hacer sushi en casa paso a paso",
    "receta de curry de pollo fácil",
    "receta de tiramisú sin horno",
    "tarta de queso la viña receta original",
    "bizcocho esponjoso receta básica",
    "receta de pan casero con levadura",
    "cómo hacer mermelada casera",
    "receta de granola casera saludable",
    "batidos proteicos para desayuno",
    "receta de hummus casero",
    "ensalada césar receta original",
    "receta de ramen japonés casero",
    "cómo hacer leche de avena casera",
    "receta de kombucha casera",
    "cómo fermentar verduras en casa",
    "alimentos ricos en proteínas lista",
    "dieta mediterránea beneficios y alimentos",
    "cómo perder peso de forma saludable 2026",
    "ejercicios para quemar grasa en casa",
    "rutina de entrenamiento sin material",
    "yoga para principiantes en casa",
    "meditación para reducir el estrés",
    "cómo dormir mejor consejos",
    "cuántas horas hay que dormir",
    "insomnio remedios naturales efectivos",
    "cómo reducir la ansiedad de forma natural",
    "técnicas de respiración para la ansiedad",
    "mindfulness qué es y cómo practicarlo",
    "suplementos deportivos cuáles son seguros",
    "creatina para qué sirve y cómo tomarla",
    "proteína de suero o vegetal comparativa",
    "cómo ganar músculo en casa sin pesas",
    "rutina de running para principiantes",
    "cómo prepararse un maratón plan entrenamiento",
    "errores comunes al empezar a correr",
    "ciclismo de montaña ruta fácil cerca",
    "senderismo con niños consejos",
    "escalada en roca para principiantes",
    "natación técnica de crawl mejorar",
    "pilates en casa para espalda",
    "estiramientos para después de correr",
    "cómo ahorrar dinero con sueldo bajo",
    "cómo hacer una declaración de la renta 2026",
    "deducciones fiscales autónomo 2026",
    "cuenta bancaria sin comisiones 2026",
    "mejor banco online españa 2026",
    "invertir en bolsa desde cero guía",
    "fondos indexados qué son y cómo funciona",
    "etf para principiantes explicado",
    "criptomonedas vale la pena invertir 2026",
    "bitcoin precio predicción 2026",
    "plan de pensiones o cuenta ahorro",
    "hipoteca fija vs variable 2026",
    "cómo mejorar el historial crediticio",
    "tarjeta de crédito sin comisiones comparativa",
    "cómo conseguir financiación para un negocio",
    "montar un negocio online sin dinero",
    "cómo hacerse autónomo en españa 2026",
    "factura electrónica cómo hacerla",
    "iva trimestral autónomos guía",
    "cómo pagar menos impuestos legalmente",
    "derechos del trabajador españa 2026",
    "despido improcedente cómo reclamar",
    "excedencia laboral cuánto se cobra",
    "baja por enfermedad cuánto cobra",
    "prestación por desempleo cuánto tiempo",
    "cómo pedir una hipoteca paso a paso",
    "gastos al comprar una casa lista completa",
    "cómo negociar el precio de un piso",
    "contrato de arrendamiento modelo",
    "derechos del inquilino españa",
    "cómo reclamar la fianza al casero",
    "cómo tocar guitarra para principiantes",
    "acordes básicos de guitarra acústica",
    "cómo leer partituras musicales",
    "piano digital para principiantes recomendaciones",
    "aprender a tocar el ukulele desde cero",
    "fotografía para principiantes ajustes básicos",
    "cómo usar modo manual de la cámara",
    "mejores cámaras sin espejo 2026",
    "edición de fotos en lightroom tutorial",
    "composición fotográfica regla de tercios",
    "fotografía nocturna consejos y ajustes",
    "cómo hacer fotografía de retrato",
    "drone para fotografía cuál comprar 2026",
    "videojuegos más vendidos 2026",
    "mejor juego de rol 2026 pc",
    "cómo mejorar en fortnite consejos",
    "los mejores juegos de estrategia pc",
    "mejores juegos multijugador gratis 2026",
    "gaming sillas recomendadas para largas horas",
    "cómo hacer streaming en twitch guía",
    "configuración obs studio para streaming",
    "cómo cultivar tomates en maceta",
    "jardinería urbana para principiantes",
    "plantas de interior fáciles de cuidar",
    "cómo hacer compost en casa",
    "huerto en terraza consejos",
    "qué flores plantar en primavera",
    "bonsái cuidados básicos principiante",
    "suculentas cómo regarlas y cuidarlas",
    "cómo podar rosales correctamente",
    "bricolaje reparar grietas en la pared",
    "cómo pintar una habitación sin manchar",
    "parquet flotante cómo colocarlo solo",
    "instalar un enchufe eléctrico paso a paso",
    "cómo cambiar un grifo gotando",
    "instalar estanterías a la pared correctamente",
    "cómo desatascar un lavabo sin productos",
    "decoración minimalista ideas para el hogar",
    "cómo organizar una cocina pequeña",
    "ikea hacks ideas creativas 2026",
    "feng shui habitación cómo aplicarlo",
    "mejores aspiradoras robot 2026",
    "cómo limpiar el baño rápidamente",
    "truco para limpiar la vitrocerámica",
    "quitar manchas de vino de la ropa",
    "lavar ropa de lana sin encoger",
    "cómo doblar ropa método konmari",
    "sistema solar planetas y características",
    "agujero negro cómo se forma",
    "teoría del big bang explicada",
    "misión artemisa luna 2026 noticias",
    "SpaceX starship lanzamiento 2026",
    "satélites de elon musk starlink",
    "fusión nuclear última hora 2026",
    "cambio climático efectos en europa",
    "energía solar cuánto cuesta instalar paneles",
    "coche eléctrico merece la pena 2026",
    "autonomía coches eléctricos comparativa",
    "cargadores coche eléctrico en casa",
    "impuesto matriculación coches eléctricos",
    "batería coche eléctrico duración",
    "moto eléctrica recomendaciones 2026",
    "bicicleta eléctrica cuál comprar 2026",
    "historia de la segunda guerra mundial resumen",
    "revolución industrial causas y consecuencias",
    "guerra fría resumen para bachillerato",
    "caída del muro de berlín historia",
    "imperio romano caída causas",
    "la edad media en europa características",
    "renacimiento artistas más importantes",
    "ilustración francesa pensadores clave",
    "revolución francesa resumen fácil",
    "guerra civil española causas resumen",
    "transición española a la democracia",
    "constitución española 1978 derechos básicos",
    "mejores series netflix 2026",
    "mejores películas de 2026 recomendadas",
    "oscar 2026 ganadores lista",
    "mejores documentales de naturaleza 2026",
    "anime más popular 2026 lista",
    "top álbumes música 2026",
    "artistas musicales nuevos 2026",
    "reggaeton últimos éxitos 2026",
    "flamenco fusión artistas actuales",
    "podcasts en español recomendados 2026",
    "audiolibros gratis español descarga",
    "libros más vendidos en español 2026",
    "novela histórica recomendada en español",
    "ciencia ficción libros esenciales lista",
    "gabriel garcía márquez mejores libros",
    "mario vargas llosa obras principales",
    "isabel allende libros recomendados",
    "javier cercas últimas novelas",
    "almudena grandes libros imprescindibles",
    "premio planeta 2025 ganador",
    "liga española clasificación 2026",
    "champions league cuartos de final 2026",
    "fichajes de verano 2026 rumores",
    "real madrid plantilla 2026",
    "barcelona fc noticias hoy",
    "selección española de fútbol 2026",
    "eurocopa 2028 selección",
    "fórmula 1 clasificación mundial 2026",
    "tenis masters madrid 2026",
    "rafa nadal últimas noticias",
    "baloncesto euroliga resultados",
    "acb liga baloncesto clasificación",
    "ciclismo tour de france 2026",
    "olimpiadas 2028 los ángeles deportes",
    "videojuego elden ring análisis",
    "minecraft trucos y construcciones",
    "cómo hacer una granja de trigo en minecraft",
    "zelda tears of the kingdom guía",
    "gta vi fecha de salida confirmada",
    "mejor procesador para gaming 2026",
    "rtx 5090 precio y disponibilidad",
    "ram 32gb ddr5 mejores opciones",
    "fuente de alimentación modular 850w recomendada",
    "refrigeración líquida vs aire torre comparativa",
    "disco duro vs ssd velocidad diferencia",
    "nas casero cómo montar uno",
    "raspberry pi proyectos fáciles para casa",
    "arduino guía para principiantes español",
    "impresión 3d filamento pla o petg",
    "inteligencia artificial en medicina 2026",
    "chatbot cómo funciona por dentro",
    "prompts para chatgpt productividad",
    "cómo usar copilot en windows 11",
    "windows 11 trucos y atajos de teclado",
    "cómo acelerar windows 11 pc lento",
    "macos sequoia novedades",
    "android 16 funciones nuevas",
    "ios 19 novedades principales",
    "aplicación para dormir mejor iphone",
    "app de meditación gratis android",
    "cómo configurar google home en casa",
    "domótica barata para casa inteligente",
    "bombillas inteligentes cuáles comprar",
    "cámara de vigilancia ip exterior",
    "cerradura inteligente sin llave opiniones",
    "psicología positiva técnicas prácticas",
    "cómo superar la procrastinación",
    "hábitos de personas exitosas libro resumen",
    "inteligencia emocional cómo desarrollarla",
    "técnica pomodoro para estudiar",
    "cómo concentrarse mejor en el trabajo",
    "burnout síntomas y cómo recuperarse",
    "relaciones tóxicas señales de alarma",
    "cómo mejorar la comunicación en pareja",
    "terapia cognitivo conductual qué es",
    "psicólogo online precio y cómo funciona",
    "autoestima cómo trabajarla día a día",
    "asertividad qué es y cómo practicarla",
    "cómo hacer amigos de adulto",
    "comunicación no violenta ejemplos prácticos",
    "trabajo en equipo habilidades clave",
    "cv moderno 2026 ejemplos y plantillas",
    "carta de presentación cómo escribirla",
    "entrevista de trabajo preguntas y respuestas",
    "linkedin cómo optimizar el perfil 2026",
    "teletrabajo cómo ser más productivo",
    "freelance cómo conseguir clientes",
    "emprendimiento social qué es y ejemplos",
    "startup ideas innovadoras 2026",
    "cómo hacer un plan de negocio sencillo",
    "marketing de contenidos qué es",
    "seo posicionamiento web guía básica",
    "google ads cómo funciona para pequeños negocios",
    "redes sociales para empresas cuál usar",
    "tiktok para negocios estrategia 2026",
    "email marketing herramientas gratuitas",
    "copywriting técnicas básicas para vender",
    "cómo hacer una presentación powerpoint impactante",
    "excel tablas dinámicas tutorial básico",
    "google sheets fórmulas más útiles",
    "notas de voz en whatsapp trucos",
    "cómo recuperar mensajes eliminados whatsapp",
    "privacidad en whatsapp cómo mejorarla",
    "correo electrónico profesional cómo redactarlo",
    "gestión del tiempo técnicas eficaces",
    "bullet journal cómo empezar",
    "notion plantillas gratis para estudiantes",
    "obsidian cómo tomar notas conectadas",
    "anki cómo usarlo para memorizar",
    "método de estudio más eficaz ciencia",
    "cómo estudiar oposiciones desde cero",
    "oposiciones bombero temario y preparación",
    "oposiciones policía local 2026",
    "oposiciones administrativo 2026 convocatorias",
    "fórmula para calcular el imc",
    "tensión arterial normal por edades",
    "colesterol bueno y malo diferencias",
    "vitamina d deficiencia síntomas",
    "hierro deficiencia síntomas y alimentos",
    "cómo bajar la tensión arterial naturalmente",
    "cómo regular el azúcar en sangre",
    "diabetes tipo 2 prevención y dieta",
    "migraña causas y remedios caseros",
    "dolor de espalda lumbar ejercicios",
    "hernia de disco síntomas y tratamiento",
    "contractura cervical cómo aliviarla",
    "intolerancia al gluten síntomas",
    "intolerancia a la lactosa qué comer",
    "veganismo guía para principiantes",
    "dieta keto para qué sirve realmente",
    "ayuno intermitente 16 8 cómo empezar",
    "aceite de oliva virgen extra beneficios",
    "alimentos probióticos lista completa",
    "cúrcuma propiedades y cómo consumirla",
    "jengibre beneficios y recetas",
    "semillas de chía cómo tomarlas",
    "omega 3 alimentos fuente natural",
    "magnesio para qué sirve y dónde está",
]
