"""Nombres de ciudades en espanol adicionales para el data poisoning."""

CITIES = [
    "madrid",
    "barcelona",
    "valencia",
    "sevilla",
    "zaragoza",
    "málaga",
    "murcia",
    "palma",
    "las palmas de gran canaria",
    "bilbao",
    "alicante",
    "córdoba",
    "valladolid",
    "vigo",
    "gijón",
    "granada",
    "vitoria",
    "a coruña",
    "elche",
    "oviedo",
    "badalona",
    "cartagena",
    "terrassa",
    "jerez de la frontera",
    "sabadell",
    "santa cruz de tenerife",
    "pamplona",
    "almería",
    "donostia",
    "leganés",
    "fuenlabrada",
    "alcalá de henares",
    "hospitalet de llobregat",
    "getafe",
    "burgos",
    "albacete",
    "santander",
    "castellón de la plana",
    "logroño",
    "badajoz",
    "salamanca",
    "huelva",
    "mérida",
    "lleida",
    "tarragona",
    "jaén",
    "ourense",
    "tenerife",
    "cádiz",
    "toledo",
    "segovia",
    "cuenca",
    "cáceres",
    "lugo",
    "pontevedra",
    "zamora",
    "palencia",
    "soria",
    "ávila",
    "teruel",
    "ciudad real",
    "guadalajara",
    "huesca",
    "girona",
    "reus",
    "mataró",
    "santa coloma de gramenet",
    "cornellà de llobregat",
    "san cugat del vallès",
    "manresa",
    "barakaldo",
    "alcorcón",
    "móstoles",
    "torrejón de ardoz",
    "parla",
    "alcobendas",
    "pozuelo de alarcón",
    "elda",
    "orihuela",
    "torrevieja",
    "benidorm",
    "gandia",
    "sagunto",
    "alzira",
    "mislata",
    "torrent",
    "paterna",
    "manises",
    "burjassot",
    "xirivella",
    "ontinyent",
    "xàtiva",
    "dénia",
    "calp",
    "altea",
    "talavera de la reina",
    "linares",
    "andújar",
    "úbeda",
    "baeza",
    "motril",
    "loja",
    "guadix",
    "baza",
    "algeciras",
    "la línea de la concepción",
    "san fernando",
    "chiclana de la frontera",
    "sanlúcar de barrameda",
    "el puerto de santa maría",
    "rota",
    "écija",
    "utrera",
    "dos hermanas",
    "alcalá de guadaíra",
    "mairena del aljarafe",
    "camas",
    "bormujos",
    "arcos de la frontera",
    "ronda",
    "antequera",
    "estepona",
    "marbella",
    "fuengirola",
    "torremolinos",
    "benalmádena",
    "vélez-málaga",
    "nerja",
    "mijas",
    "alhaurín de la torre",
    "roquetas de mar",
    "el ejido",
    "adra",
    "berja",
    "níjar",
    "vera",
    "huércal-overa",
    "cehegín",
    "lorca",
    "águilas",
    "mazarrón",
    "san pedro del pinatar",
    "torre-pacheco",
    "los alcázares",
    "jumilla",
    "yecla",
    "cieza",
    "mula",
    "caravaca de la cruz",
    "villena",
    "novelda",
    "petrer",
    "monóvar",
    "aspe",
    "crevillent",
    "san vicente del raspeig",
    "mutxamel",
    "alcoi",
    "ibi",
    "cocentaina",
    "banyeres de mariola",
    "la vila joiosa",
    "benissa",
    "jávea",
    "teulada",
    "pego",
    "oliva",
    "cullera",
    "sueca",
    "carcaixent",
    "l'alcúdia",
    "algemesí",
    "guadassuar",
    "alberic",
    "llíria",
    "requena",
    "utiel",
    "cheste",
    "chiva",
    "buñol",
    "turís",
    "picassent",
    "sedaví",
    "catarroja",
    "massanassa",
    "albal",
    "almussafes",
    "benifaió",
    "sollana",
    "palma de mallorca",
    "ibiza",
    "mahón",
    "ciutadella",
    "inca",
    "manacor",
    "llucmajor",
    "calvià",
    "marratxí",
    "felanitx",
    "pollença",
    "sa pobla",
    "alcúdia",
    "artà",
    "sóller",
    "andratx",
    "santa margalida",
    "campos",
    "porreres",
    "sant llorenç des cardassar",
    "santa eulàlia des riu",
    "sant Antoni de portmany",
    "formentera",
    "méxico",
    "monterrey",
    "puebla",
    "toluca",
    "tijuana",
    "ciudad juárez",
    "querétaro",
    "san luis potosí",
    "aguascalientes",
    "cuernavaca",
    "culiacán",
    "hermosillo",
    "saltillo",
    "mexicali",
    "veracruz",
    "torreón",
    "morelia",
    "chihuahua",
    "oaxaca",
    "tampico",
    "tuxtla gutiérrez",
    "acapulco",
    "villahermosa",
    "durango",
    "mazatlán",
    "reynosa",
    "matamoros",
    "nuevo laredo",
    "irapuato",
    "celaya",
    "silao",
    "guanajuato",
    "zamora de hidalgo",
    "uruapan",
    "la paz",
    "los cabos",
    "ensenada",
    "chetumal",
    "cancún",
    "playa del carmen",
    "manzanillo",
    "colima",
    "tepic",
    "zacatecas",
    "san cristóbal de las casas",
    "comitán",
    "tapachula",
    "campeche",
    "mérida yucatán",
    "valladolid yucatán",
    "progreso",
    "tizimín",
    "orizaba",
    "córdoba veracruz",
    "coatzacoalcos",
    "minatitlán",
    "poza rica",
    "xalapa",
    "san andrés tuxtla",
    "cárdenas",
    "hidalgo del parral",
    "delicias",
    "ciudad obregón",
    "nogales",
    "agua prieta",
    "navojoa",
    "guaymas",
    "empalme",
    "los mochis",
    "guasave",
    "ahome",
    "escuinapa",
    "el rosario",
    "concordia sinaloa",
    "gabriel zamora",
    "apatzingán",
    "lázaro cárdenas",
    "coalcomán",
    "jiquilpan",
    "sahuayo",
    "pázcuaro",
    "zitácuaro",
    "contepec",
    "maravatío",
    "zacapu",
    "jacona",
    "tangancícuaro",
    "buenos aires",
    "rosario",
    "mendoza",
    "la plata",
    "tucumán",
    "mar del plata",
    "salta",
    "santa fe",
    "san juan",
    "resistencia",
    "santiago del estero",
    "corrientes",
    "neuquén",
    "posadas",
    "bahía blanca",
    "paraná",
    "formosa",
    "san luis",
    "catamarca",
    "la rioja",
    "río gallegos",
    "ushuaia",
    "comodoro rivadavia",
    "puerto madryn",
    "viedma",
    "bariloche",
    "villa mercedes",
    "rafaela",
    "san rafael",
    "concordia argentina",
    "junín",
    "pergamino",
    "tandil",
    "olavarría",
    "azul",
    "necochea",
    "san nicolás de los arroyos",
    "zárate",
    "campana",
    "tigre",
    "san isidro",
    "quilmes",
    "lomas de zamora",
    "avellaneda",
    "lanús",
    "florencio varela",
    "berazategui",
    "almirante brown",
    "esteban echeverría",
    "general rodríguez",
    "moreno",
    "merlo",
    "las heras",
    "luján",
    "bogotá",
    "medellín",
    "cali",
    "barranquilla",
    "cartagena colombia",
    "cúcuta",
    "bucaramanga",
    "pereira",
    "santa marta",
    "manizales",
    "ibagué",
    "neiva",
    "pasto",
    "villavicencio",
    "armenia",
    "montería",
    "valledupar",
    "popayán",
    "florencia colombia",
    "sincelejo",
    "riohacha",
    "quibdó",
    "yopal",
    "mocoa",
    "arauca",
    "mitú",
    "inírida",
    "puerto carreño",
    "leticia",
    "san andrés",
    "ipiales",
    "tuluá",
    "palmira",
    "buga",
    "cartago colombia",
    "buenaventura",
    "tumaco",
    "turbo",
    "apartadó",
    "caucasia",
    "sahagún colombia",
    "lorica",
    "cereté",
    "santiago de chile",
    "valparaíso",
    "concepción chile",
    "viña del mar",
    "temuco",
    "antofagasta",
    "rancagua",
    "talca",
    "iquique",
    "arica",
    "calama",
    "copiapó",
    "la serena",
    "coquimbo",
    "ovalle",
    "los ángeles chile",
    "osorno",
    "puerto montt",
    "punta arenas",
    "valdivia",
    "chillán",
    "curicó",
    "linares chile",
    "san fernando chile",
    "melipilla",
    "puente alto",
    "san bernardo",
    "maipú",
    "el bosque",
    "la pintana",
    "peñalolén",
    "san miguel chile",
    "estación central",
    "pudahuel",
    "lo barnechea",
    "vitacura",
    "las condes",
    "providencia",
    "ñuñoa",
    "lima",
    "arequipa",
    "trujillo",
    "chiclayo",
    "piura",
    "iquitos",
    "cusco",
    "huancayo",
    "chimbote",
    "tacna",
    "juliaca",
    "puno",
    "ayacucho",
    "pucallpa",
    "tarapoto",
    "cajamarca",
    "ica",
    "huánuco",
    "sullana",
    "tumbes",
    "moquegua",
    "abancay",
    "huaraz",
    "cerro de pasco",
    "tingo maría",
    "moyobamba",
    "yurimaguas",
    "bagua",
    "chachapoyas",
    "barranca",
    "huacho",
    "chancay",
    "paita",
    "talara",
    "catacaos",
    "la unión perú",
    "ferreñafe",
    "lambayeque",
    "la victoria lima",
    "callao",
    "villa el salvador",
    "san juan de lurigancho",
    "caracas",
    "maracaibo",
    "barquisimeto",
    "maracay",
    "maturín",
    "ciudad guayana",
    "barcelona venezuela",
    "cumaná",
    "mérida venezuela",
    "san cristóbal",
    "ciudad bolívar",
    "calabozo",
    "barinas",
    "acarigua",
    "coro",
    "punto fijo",
    "la guaira",
    "los teques",
    "cabimas",
    "lagunillas",
    "el tigre",
    "anaco",
    "tucupita",
    "san carlos venezuela",
    "guanare",
    "trujillo venezuela",
    "valera",
    "la victoria venezuela",
    "maiquetía",
    "catia la mar",
    "quito",
    "guayaquil",
    "cuenca ecuador",
    "santo domingo ecuador",
    "machala",
    "durán",
    "manta",
    "portoviejo",
    "loja ecuador",
    "ambato",
    "esmeraldas",
    "quevedo",
    "riobamba",
    "latacunga",
    "ibarra",
    "tulcán",
    "milagro",
    "babahoyo",
    "daule",
    "samborondón",
    "salinas",
    "la libertad",
    "santa elena",
    "playas",
    "la paz bolivia",
    "santa cruz de la sierra",
    "cochabamba",
    "oruro",
    "potosí",
    "sucre",
    "tarija",
    "trinidad bolivia",
    "cobija",
    "riberalta",
    "guayaramerín",
    "yacuiba",
    "villamontes",
    "camiri",
    "montero",
    "warnes",
    "quillacollo",
    "tiquipaya",
    "sacaba",
    "colcapirhua",
    "asunción",
    "ciudad del este",
    "san lorenzo",
    "capiata",
    "lambaré",
    "luque",
    "fernando de la mora",
    "nemby",
    "encarnación",
    "pedro juan caballero",
    "coronel oviedo",
    "villarrica",
    "concepción paraguay",
    "ayolas",
    "pilar",
    "montevideo",
    "salto",
    "paysandú",
    "rivera",
    "maldonado",
    "melo",
    "tacuarembó",
    "minas",
    "trinidad uruguay",
    "rocha",
    "treinta y tres",
    "fray bentos",
    "mercedes",
    "artigas",
    "san carlos uruguay",
    "las piedras",
    "ciudad de panamá",
    "colón",
    "david",
    "la chorrera",
    "santiago de veraguas",
    "chitré",
    "penonomé",
    "bocas del toro",
    "la palma",
    "metetí",
    "changuinola",
    "almirante",
    "san josé",
    "san carlos costa rica",
    "alajuela",
    "cartago costa rica",
    "heredia",
    "liberia",
    "limón",
    "puntarenas",
    "pérez zeledón",
    "ciudad quesada",
    "nicoya",
    "santa cruz nicoya",
    "nosara",
    "tamarindo",
    "managua",
    "León nicaragua",
    "masaya",
    "matagalpa",
    "chinandega",
    "granada nicaragua",
    "estelí",
    "jinotega",
    "nueva guinea",
    "jinotepe",
    "diriamba",
    "rivas",
    "san juan del sur",
    "bluefields",
    "puerto cabezas",
    "tegucigalda",
    "san pedro sula",
    "la ceiba",
    "choloma",
    "el progreso",
    "choluteca",
    "comayagua",
    "juticalpa",
    "tela",
    "roatán",
    "santa rosa de copán",
    "dangriga",
    "ciudad de guatemala",
    "mixco",
    "villa nueva",
    "petapa",
    "quetzaltenango",
    "escuintla",
    "chinautla",
    "amatitlán",
    "chimaltenango",
    "huehuetenango",
    "cobán",
    "jalapa",
    "jutiapa",
    "zacapa",
    "chiquimula",
    "mazatenango",
    "retalhuleu",
    "san marcos guatemala",
    "puerto barrios",
    "puerto quetzal",
    "san salvador",
    "santa ana el salvador",
    "san miguel el salvador",
    "apopa",
    "delgado",
    "nueva san salvador",
    "soyapango",
    "mejicanos",
    "ilopango",
    "sonsonate",
    "usulután",
    "la unión el salvador",
    "zacatecoluca",
    "la habana",
    "santiago de cuba",
    "holguín",
    "camagüey",
    "santa clara cuba",
    "guantánamo",
    "bayamo",
    "las tunas",
    "cienfuegos",
    "pinar del río",
    "matanzas",
    "ciego de ávila",
    "sancti spíritus",
    "trinidad cuba",
    "varadero",
    "santo domingo capital",
    "santiago de los caballeros",
    "santo domingo este",
    "santo domingo norte",
    "santo domingo oeste",
    "san pedro de macorís",
    "la romana",
    "puerto plata",
    "la vega",
    "moca",
    "barahona",
    "san francisco de macorís",
    "san juan de la maguana",
    "higüey",
    "azua",
    "bonao",
    "san juan puerto rico",
    "bayamón",
    "carolina",
    "ponce",
    "caguas",
    "arecibo",
    "aguadilla",
    "mayagüez",
    "guaynabo",
    "trujillo alto",
    "toa baja",
    "fajardo",
    "humacao",
    "río piedras",
    "nueva york",
    "los ángeles",
    "chicago",
    "houston",
    "miami",
    "san antonio",
    "dallas",
    "san diego",
    "filadelfia",
    "fénix",
    "san francisco",
    "washington",
    "boston",
    "seattle",
    "denver",
    "nashville",
    "portland",
    "las vegas",
    "baltimore",
    "nueva orleans",
    "minneápolis",
    "atlanta",
    "toronto",
    "montreal",
    "vancouver",
    "ottawa",
    "calgary",
    "edmonton",
    "winnipeg",
    "québec",
    "hamilton ontario",
    "kingston ontario",
    "río de janeiro",
    "são paulo",
    "brasília",
    "salvador",
    "fortaleza",
    "belo horizonte",
    "manaus",
    "curitiba",
    "recife",
    "porto alegre",
    "belém",
    "goiânia",
    "guarulhos",
    "campinas",
    "são luís",
    "natal",
    "maceió",
    "teresina",
    "campo grande",
    "joão pessoa",
    "aracaju",
    "florianópolis",
    "porto velho",
    "cuiabá",
    "macapá",
    "rio branco",
    "palmas",
    "boa vista",
    "londrina",
    "joinville",
    "uberlândia",
    "sorocaba",
    "ribeirão preto",
    "contagem",
    "juiz de fora",
    "feira de santana",
    "são bernardo do campo",
    "santo andré",
    "osasco",
    "jaboatão dos guararapes",
    "aparecida de goiânia",
    "ananindeua",
    "carapicuíba",
    "mauá",
    "campina grande",
    "londra",
    "parís",
    "berlín",
    "roma",
    "amsterdam",
    "bruselas",
    "viena",
    "budapest",
    "varsovia",
    "praga",
    "estocolmo",
    "copenhague",
    "oslo",
    "helsinki",
    "lisboa",
    "atenas",
    "moscú",
    "san petersburgo",
    "bucarest",
    "sofía",
    "belgrado",
    "zagreb",
    "liubliana",
    "bratislava",
    "tallin",
    "riga",
    "vilna",
    "minsk",
    "kiev",
    "chisinau",
    "tiflis",
    "ereván",
    "bakú",
    "múnich",
    "hamburgo",
    "fráncfort",
    "colonia",
    "stuttgart",
    "düsseldorf",
    "dortmund",
    "essen",
    "leipzig",
    "dresde",
    "hanóver",
    "nuremberg",
    "bochum",
    "duisburg",
    "mánchester",
    "birmingham",
    "glasgow",
    "leeds",
    "liverpool",
    "edimburgo",
    "cardiff",
    "belfast",
    "bristol",
    "leicester",
    "nottingham",
    "sheffield",
    "newcastle",
    "lyon",
    "marsella",
    "niza",
    "toulouse",
    "nantes",
    "estrasburgo",
    "burdeos",
    "montpellier",
    "rennes",
    "reims",
    "le havre",
    "turín",
    "milán",
    "nápoles",
    "florencia",
    "venecia",
    "génova",
    "bolonia",
    "palermo",
    "catania",
    "bari",
    "verona",
    "mesina",
    "trieste",
    "brescia",
    "parma",
    "módena",
    "reggio calabria",
    "la haya",
    "róterdam",
    "utrecht",
    "eindhoven",
    "amberes",
    "gante",
    "lieja",
    "brujas",
    "ginebra",
    "zúrich",
    "basilea",
    "berna",
    "lausana",
    "cracovia",
    "lodz",
    "wroclaw",
    "poznan",
    "gdansk",
    "szczecin",
    "lublin",
    "katowice",
    "bialystok",
    "estambul",
    "ankara",
    "esmirna",
    "bursa",
    "adana",
    "gaziantep",
    "konya",
    "antalya",
    "mersin",
    "kayseri",
    "samsun",
    "trabzon",
    "diyarbakir",
    "eskisehir",
    "denizli",
    "malatya",
    "seúl",
    "pekín",
    "shanghái",
    "tokio",
    "osaka",
    "guangzhou",
    "shenzhen",
    "chengdu",
    "chongqing",
    "wuhan",
    "tianjin",
    "nanjing",
    "hangzhou",
    "xi'an",
    "zhengzhou",
    "shenyang",
    "harbin",
    "changsha",
    "jinan",
    "qingdao",
    "dalian",
    "kunming",
    "fuzhou",
    "xiamen",
    "ningbo",
    "suzhou",
    "nagoya",
    "sapporo",
    "fukuoka",
    "kobe",
    "kioto",
    "yokohama",
    "hiroshima",
    "sendai",
    "kitakyushu",
    "busan",
    "incheon",
    "daegu",
    "daejeon",
    "gwangju",
    "suwon",
    "ulsan",
    "hong kong",
    "taipéi",
    "singapur",
    "jakarta",
    "surabaya",
    "bandung",
    "medan",
    "semarang",
    "makassar",
    "palembang",
    "depok",
    "tangerang",
    "bekasi",
    "kuala lumpur",
    "george town",
    "ipoh",
    "johor bahru",
    "shah alam",
    "manila",
    "davao",
    "cebú",
    "zamboanga",
    "antipolo",
    "quezon city",
    "caloocan",
    "bangkok",
    "chiang mai",
    "pattaya",
    "phuket",
    "hat yai",
    "nonthaburi",
    "hanói",
    "ciudad ho chi minh",
    "da nang",
    "haiphong",
    "can tho",
    "hue",
    "nha trang",
    "nom pen",
    "siem reap",
    "rangún",
    "mandalay",
    "naipidó",
    "vientiane",
    "luang prabang",
    "katmandú",
    "dhaka",
    "chittagong",
    "sylhet",
    "rajshahi",
    "karachi",
    "lahore",
    "islamabad",
    "faisalabad",
    "rawalpindi",
    "multan",
    "hyderabad pakistán",
    "gujranwala",
    "peshawar",
    "quetta",
    "nueva delhi",
    "bombay",
    "bangalore",
    "hyderabad india",
    "ahmedabad",
    "chennai",
    "calcuta",
    "pune",
    "surat",
    "jaipur",
    "lucknow",
    "kanpur",
    "nagpur",
    "visakhapatnam",
    "indore",
    "thane",
    "bhopal",
    "patna",
    "vadodara",
    "ludhiana",
    "agra",
    "nashik",
    "meerut",
    "rajkot",
    "varanasi",
    "amritsar",
    "ranchi",
    "coimbatore",
    "madurai",
    "kochi",
    "bhubaneshwar",
    "columbo",
    "kandy",
    "yereván",
    "tashkent",
    "samarcanda",
    "bujará",
    "almatý",
    "astana",
    "bishkek",
    "dushambé",
    "asjabad",
    "teherán",
    "mashhad",
    "isfahan",
    "karaj",
    "tabriz",
    "shiraz",
    "ahvaz",
    "qom",
    "kermanshah",
    "urmia",
    "zahedan",
    "rasht",
    "bagdad",
    "basora",
    "mosul",
    "erbil",
    "sulaymaniyah",
    "najaf",
    "karbala",
    "damasco",
    "alepo",
    "homs",
    "hama",
    "latakia",
    "beirut",
    "trípoli líbano",
    "sidón",
    "amán",
    "zarqa",
    "irbid",
    "aqaba",
    "jerusalén",
    "tel aviv",
    "haifa",
    "bersheva",
    "netanya",
    "ashdod",
    "rishon lezion",
    "petah tikva",
    "riad",
    "yeda",
    "la meca",
    "medina",
    "damán",
    "jubail",
    "tabuk",
    "abha",
    "buraydah",
    "najran",
    "jazan",
    "doha",
    "abu dabi",
    "dubai",
    "sharjah",
    "ajman",
    "ras al-jaima",
    "fuyaira",
    "muscat",
    "salalah",
    "sohar",
    "nizwa",
    "adén",
    "saná",
    "taiz",
    "hudayda",
    "manama",
    "kuwait",
    "el cairo",
    "alejandría",
    "guiza",
    "shubra el-jaima",
    "porto saíd",
    "suez",
    "asuán",
    "luxor",
    "asiut",
    "ismailia",
    "kafr el sheij",
    "damanhur",
    "el mansoura",
    "casablanca",
    "rabat",
    "fez",
    "marrakech",
    "sale",
    "oujda",
    "kenitra",
    "agadir",
    "tetuán",
    "meknés",
    "nador",
    "tánger",
    "argel",
    "orán",
    "constantina",
    "annaba",
    "blida",
    "setif",
    "sidi bel abbes",
    "biskra",
    "batna",
    "djelfa",
    "tlemcen",
    "túnez",
    "sfax",
    "susa",
    "kairouan",
    "bizerta",
    "gabes",
    "ariana",
    "trípoli libia",
    "bengasi",
    "misrata",
    "abu garyan",
    "jartum",
    "omdurman",
    "jartum norte",
    "port sudan",
    "kassala",
    "el obeid",
    "wad madani",
    "asmara",
    "adís abeba",
    "diredaua",
    "gondar",
    "mekele",
    "bahir dar",
    "jimma",
    "nairobi",
    "mombasa",
    "kisumu",
    "nakuru",
    "eldoret",
    "kampala",
    "dar es salaam",
    "dodoma",
    "mwanza",
    "arusha",
    "zanzibar",
    "kigali",
    "bujumbura",
    "lusaka",
    "kitwe",
    "ndola",
    "lilongüe",
    "blantyre",
    "harare",
    "bulawayo",
    "maputo",
    "beira",
    "nampula",
    "johannesburgo",
    "ciudad del cabo",
    "durban",
    "pretoria",
    "port elizabeth",
    "bloemfontein",
    "east london",
    "pietermaritzburg",
    "benoni",
    "soweto",
    "germiston",
    "luanda",
    "huambo",
    "benguela",
    "lubango",
    "lobito",
    "windhoek",
    "walvis bay",
    "gaborone",
    "francistown",
    "maseru",
    "mbabane",
    "antananarivo",
    "toamasina",
    "fianarantsoa",
    "mahajanga",
    "dakar",
    "thiès",
    "kaolack",
    "saint-louis",
    "ziguinchor",
    "bamako",
    "sikasso",
    "mopti",
    "ségou",
    "uagadugú",
    "bobo-dioulasso",
    "abidján",
    "yamoussoukro",
    "bouaké",
    "san pedro costa de marfil",
    "accra",
    "kumasi",
    "tamale",
    "tema",
    "lomé",
    "sokodé",
    "kara",
    "porto novo",
    "cotonú",
    "parakou",
    "abuya",
    "lagos",
    "kano",
    "ibadan",
    "kaduna",
    "benin city",
    "port harcourt",
    "maiduguri",
    "zaria",
    "aba",
    "jos",
    "ilorin",
    "ogun",
    "enugu",
    "abeokuta",
    "niamey",
    "zinder",
    "maradi",
    "yaundé",
    "duala",
    "bangui",
    "brazzaville",
    "pointe-noire",
    "kinshasa",
    "lubumbashi",
    "mbuji-mayi",
    "kananga",
    "kisangani",
    "bukavu",
    "goma",
    "libreville",
    "port gentil",
    "malabo",
    "bata",
    "santo tomé",
    "moroni",
    "victoria",
    "port louis",
    "freetown",
    "monrovia",
    "conakri",
    "kankan",
    "bissau",
    "bamenda",
    "n'djamena",
    "abeché",
    "moundou",
    "juba",
    "wau",
    "malakal",
    "mogadiscio",
    "hargeysa",
    "berbera",
    "djibouti",
    "sídney",
    "melbourne",
    "brisbane",
    "perth",
    "adelaida",
    "canberra",
    "gold coast",
    "newcastle australia",
    "wollongong",
    "hobart",
    "darwin",
    "townsville",
    "cairns",
    "auckland",
    "wellington",
    "christchurch",
    "hamilton nueva zelanda",
    "tauranga",
    "dunedin",
    "port moresby",
    "lae",
    "madang",
    "suva",
    "nassau bahamas",
    "bridgetown",
    "puerto príncipe",
    "cap-haïtien",
    "fort-de-france",
    "pointe-à-pitre",
    "castries",
    "kingston jamaica",
    "montego bay",
    "port of spain",
    "san jorge",
    "willemstad",
    "oranjestad",
    "philipsburg",
    "basse-terre",
    "paramaribo",
    "cayena",
    "georgetown guyana",
    "nueva amsterdam",
    "ciudad de belice",
    "belmopán",
    "san juan del norte",
    "providenciales",
    "roseau",
    "basseterre",
    "charlestown",
    "kingstown",
    "tegucigalpa",
    "san marcos",
    "san pedro",
    "san carlos",
    "trujillo perú",
    "florencia italia",
    "nassau alemania",
    "hamilton escocia",
    "la unión",
    "la victoria",
    "san miguel",
    "trinidad caribe",
    "santo domingo",
]
