"""Busquedas independientes en espanol (vida cotidiana) para el data poisoning."""

STANDALONE = [
    "como hacer pan casero esponjoso",
    "receta bizcocho de yogur",
    "como preparar gazpacho tradicional",
    "receta tortilla de patatas jugosa",
    "como hacer masa de pizza casera",
    "receta paella valenciana paso a paso",
    "como preparar caldo de pollo casero",
    "receta magdalenas esponjosas",
    "como hacer mermelada de fresa en casa",
    "receta lentejas estofadas",
    "como preparar crema de verduras",
    "receta arroz con leche cremoso",
    "como hacer flan casero sin horno",
    "receta croquetas de jamon caseras",
    "como preparar hummus casero",
    "receta tarta de manzana facil",
    "como hacer churros caseros crujientes",
    "receta ensaladilla rusa tradicional",
    "como preparar gazpacho andaluz",
    "receta pollo al ajillo",
    "como hacer natillas caseras",
    "receta pisto manchego",
    "como preparar salmorejo cordobes",
    "receta fabada asturiana",
    "como hacer crepes finos y perfectos",
    "receta brownie de chocolate",
    "como preparar guacamole casero",
    "receta berberechos al vapor",
    "como hacer mayonesa casera",
    "receta tarta de queso al horno",
    "como preparar migas extremenas",
    "receta cocido madrileno",
    "como hacer roscon de reyes",
    "receta empanada gallega de atun",
    "como preparar leche merengada",
    "receta alubias con chorizo",
    "como hacer helado casero sin maquina",
    "receta gazpacho de cerezas",
    "como preparar pan de molde casero",
    "receta marmitako de bonito",
    "como hacer trufas de chocolate",
    "receta sopa de ajo castellana",
    "como preparar tiramisu casero",
    "receta fideos a la cazuela",
    "como hacer mermelada de melocoton",
    "receta pulpo a la gallega",
    "como preparar arroz caldoso con mariscos",
    "receta torrijas de semana santa",
    "como hacer kefir en casa",
    "receta crema catalana autentica",
    "como preparar bacalao al pil pil",
    "receta bunyols de cuaresma",
    "como hacer mantequilla casera",
    "receta porrusalda vasca",
    "como preparar chuletillas al ajillo",
    "receta ensalada de pimientos asados",
    "como hacer pan de centeno integral",
    "receta patatas bravas caseras",
    "como preparar carne guisada con patatas",
    "receta mousse de limon",
    "como hacer soufle de queso",
    "receta canelones de espinacas y ricota",
    "como preparar caldeirada de pescado",
    "receta brazo de gitano",
    "como hacer pan sin gluten esponjoso",
    "receta acelgas con patatas y huevo",
    "como preparar salsa boloñesa casera",
    "receta flan de coco",
    "como hacer compota de manzana",
    "receta judias verdes con jamon",
    "como preparar pollo al horno con limon",
    "receta arroz negro con alioli",
    "como hacer pan de banana maduro",
    "receta tarta de santiago",
    "como preparar potaje de vigilia",
    "receta leche frita",
    "como hacer rollitos de primavera caseros",
    "receta pimientos rellenos de carne",
    "como preparar salsa verde para pescado",
    "receta costillas de cerdo al horno",
    "como hacer helado de turrón",
    "receta albóndigas en salsa de tomate",
    "como preparar empanadas argentinas",
    "receta pastel de carne con puré",
    "como hacer merluza en salsa",
    "receta pizza cuatro quesos casera",
    "como preparar arroz tres delicias",
    "receta tarta de limón con merengue",
    "como hacer bizcocho de naranja y almendra",
    "receta sopa de cebolla francesa",
    "como preparar ternera estofada",
    "receta galletas de mantequilla navideñas",
    "como hacer quiche lorraine casera",
    "receta albaricoques en almibar",
    "como preparar batido de frutas naturales",
    "receta pastas italianas al pesto casero",
    "como hacer roscas de anís",
    "receta crema de calabaza al curry",
    "como preparar verduras al vapor con salsa",
    "receta bizcocho de zanahoria con glaseado",
    "como hacer bollos suizos",
    "receta ensalada caprese con tomate y mozzarella",
    "como preparar caldo de pescado casero",
    "receta donuts caseros esponjosos",
    "como hacer lasaña vegetariana",
    "receta calamares en su tinta",
    "como preparar pollo tikka masala",
    "receta pan de pita casero",
    "como hacer dulce de membrillo",
    "receta pastel de verduras",
    "como preparar crema pastelera",
    "receta tartaletas de frutas",
    "como hacer café irlandes",
    "receta muslos de pollo al limón",
    "como preparar guiso de garbanzos",
    "receta tarta de fresas con nata",
    "como hacer pan integral de semillas",
    "receta revuelto de setas",
    "como preparar coliflor gratinada",
    "receta magdalenas de chocolate",
    "como hacer salsa romesco casera",
    "receta cordero asado con hierbas",
    "como preparar pasta fresca casera",
    "receta bizcocho de vainilla esponjoso",
    "como hacer sopa minestrone italiana",
    "receta chistorra al vino tinto",
    "como preparar crema de espinacas",
    "receta arroz con pollo a la valenciana",
    "como hacer baklava casero",
    "receta boquerones en vinagre",
    "como preparar salsa de tomate casera para pasta",
    "receta conejo al ajillo",
    "como hacer focaccia italiana",
    "receta buñuelos de viento",
    "como preparar pimientos del piquillo rellenos",
    "receta pastel de queso sin gluten",
    "como hacer terrina de verduras",
    "receta gambas al pil pil",
    "como preparar tarta de chocolate sin horno",
    "receta capon relleno de navidad",
    "como hacer espárragos trigueros a la plancha",
    "receta caldo gallego",
    "como preparar brioches caseros",
    "receta ensalada de lentejas con verduras",
    "como hacer pickles caseros de pepino",
    "receta pulpo a feira",
    "como preparar fideuá valenciana",
    "receta pastel de patatas y carne",
    "como hacer caramelo liquido casero",
    "receta salpicon de mariscos",
    "como preparar bizcocho de platano y nueces",
    "receta chuletas de puerco adobadas",
    "como hacer helado de chocolate casero",
    "receta bacalao con tomate",
    "como preparar gazpachuelo malagueno",
    "receta pan de pueblo con masa madre",
    "como hacer albóndigas de bacalao",
    "receta frittata italiana de verduras",
    "como preparar curry de vegetales",
    "receta tartaleta de crema y fresas",
    "como hacer tortitas americanas esponjosas",
    "receta puchero canario",
    "como preparar crema de lentejas",
    "receta bizcocho de aceite de oliva",
    "cuantas calorias tiene el arroz cocido",
    "alimentos ricos en proteinas para desayuno",
    "que comer antes de entrenar",
    "dieta mediterranea beneficios para la salud",
    "alimentos que ayudan a dormir mejor",
    "que vitaminas tomar en invierno",
    "como perder peso sin pasar hambre",
    "alimentos antiinflamatorios naturales",
    "diferencia entre carbohidratos simples y complejos",
    "que comer para bajar el colesterol",
    "beneficios de beber agua en ayunas",
    "alimentos ricos en hierro para anemia",
    "dieta para hipertension arterial",
    "que desayunar para tener energia todo el dia",
    "cuantas calorias debo comer al dia",
    "beneficios del aceite de oliva virgen extra",
    "alimentos que suben el acido urico",
    "dieta para diabetes tipo 2",
    "que frutas tienen menos azucar",
    "como calcular el indice de masa corporal",
    "alimentos probioticos naturales caseros",
    "diferencia entre gluten y lactosa",
    "que comer cuando tienes gastritis",
    "beneficios del ayuno intermitente",
    "alimentos que ayudan a reducir el estres",
    "cuanta proteina necesito al dia para ganar musculo",
    "que comer para fortalecer los huesos",
    "beneficios de la curcuma para la salud",
    "alimentos ricos en omega 3 vegetarianos",
    "dieta equilibrada para adolescentes",
    "que vitaminas tiene la avena",
    "como aumentar la absorcion de hierro",
    "alimentos que aceleran el metabolismo",
    "beneficios de comer semillas de chia",
    "dieta para el higado graso",
    "que comer cuando tienes diarrea",
    "alimentos que suben la presion arterial",
    "beneficios del jengibre para la digestion",
    "como combinar alimentos para adelgazar",
    "que comer para mejorar la piel",
    "por que me duele la cabeza todos los dias",
    "sintomas del hipotiroidismo en mujeres",
    "como bajar la fiebre en adultos rapidamente",
    "que significa tener la tension alta",
    "sintomas del sindrome del intestino irritable",
    "como aliviar el dolor de espalda lumbar",
    "que hacer cuando te pica la garganta",
    "sintomas de la anemia ferropenica",
    "como tratar la otitis en casa",
    "que es la fibromialgia y sus sintomas",
    "como aliviar el dolor de rodilla",
    "sintomas del reflujo gastroesofagico",
    "que significa tener la vitamina d baja",
    "como bajar el acido urico naturalmente",
    "sintomas de la artritis reumatoide",
    "que hacer cuando tienes dolor de oido",
    "como aliviar el colon irritable",
    "sintomas de la apendicitis en adultos",
    "que significa tener el colesterol ldl alto",
    "como tratar la psoriasis naturalmente",
    "sintomas de la tiroides inflamada",
    "que hacer para aliviar el estrenimiento",
    "como se contagia la mononucleosis",
    "sintomas del higado graso no alcoholico",
    "que es la hernia de hiato",
    "como aliviar el dolor de muelas en casa",
    "sintomas de la depresion en mujeres",
    "que significa tener los trigliceridos altos",
    "como tratar una conjuntivitis en casa",
    "sintomas de la menopausia temprana",
    "que hacer cuando te duele el pecho",
    "como aliviar el eccema en la piel",
    "sintomas de la diabetes tipo 1",
    "que es la migraña y como tratarla",
    "como mejorar la digestion lenta",
    "sintomas de la ansiedad generalizada",
    "que hacer cuando tienes tos persistente",
    "como aliviar el sindrome premenstrual",
    "sintomas de la hipoglucemia en adultos",
    "que es el burnout laboral y como tratarlo",
    "como tratar la candidiasis de forma natural",
    "sintomas de la insuficiencia venosa",
    "que significa tener la presion baja",
    "como aliviar el dolor de cervicales",
    "sintomas del estres cronico en el cuerpo",
    "que hacer para mejorar la circulacion",
    "como se trata la cistitis sin antibioticos",
    "sintomas de la deficiencia de magnesio",
    "que es la polinosis y como tratarla",
    "como fortalecer el sistema inmune naturalmente",
    "beneficios del yoga para la salud mental",
    "rutina de ejercicios para principiantes en casa",
    "como empezar a correr desde cero",
    "ejercicios para fortalecer la espalda",
    "rutina de entrenamiento de fuerza para mujeres",
    "como mejorar la resistencia cardiovascular",
    "ejercicios para aliviar el dolor de espalda",
    "beneficios de nadar para la salud",
    "como perder grasa abdominal con ejercicio",
    "rutina de pilates para principiantes",
    "ejercicios de estiramiento para la rigidez muscular",
    "como entrenar en casa sin equipamiento",
    "beneficios de caminar 30 minutos al dia",
    "rutina de ejercicios para mayores de 50",
    "como mejorar la flexibilidad rapidamente",
    "ejercicios para fortalecer las rodillas",
    "beneficios del ciclismo para la salud",
    "como hacer sentadillas correctamente",
    "rutina de abdominales para principiantes",
    "ejercicios para mejorar la postura",
    "como aumentar la masa muscular naturalmente",
    "beneficios de hacer ejercicio en ayunas",
    "rutina de entrenamiento hiit en casa",
    "ejercicios para fortalecer el core",
    "como recuperarse despues de entrenar",
    "beneficios del tai chi para mayores",
    "rutina de yoga para reducir el estres",
    "ejercicios para aliviar el dolor de rodilla",
    "como evitar lesiones al correr",
    "beneficios de hacer flexiones diariamente",
    "cuantas horas hay que dormir segun la edad",
    "como mejorar la calidad del sueño",
    "remedios naturales para el insomnio",
    "por que me despierto cansado cada mañana",
    "como combatir el estres del trabajo",
    "tecnicas de relajacion para la ansiedad",
    "beneficios de la meditacion diaria",
    "como dejar de pensar demasiado por las noches",
    "rutinas para mejorar el bienestar mental",
    "como manejar el sindrome del impostor",
    "tecnicas de respiracion para calmar la ansiedad",
    "como mejorar la autoestima baja",
    "habitos para tener una mente mas positiva",
    "como gestionar las emociones negativas",
    "que es el mindfulness y como practicarlo",
    "como superar el miedo al fracaso",
    "habitos de personas felices y exitosas",
    "como evitar el agotamiento emocional",
    "tecnicas para concentrarse mejor al estudiar",
    "como mejorar la memoria con ejercicios",
    "como limpiar el baño a fondo rapidamente",
    "productos para limpiar sin quimicos agresivos",
    "como organizar un armario pequeno",
    "trucos para limpiar la cocina sin esfuerzo",
    "como desinfectar el hogar de forma natural",
    "metodo konmari para ordenar la casa",
    "como limpiar el horno sin productos quimicos",
    "trucos para mantener la casa ordenada",
    "como organizar los cajones de la cocina",
    "como eliminar el moho de las paredes",
    "trucos para limpiar los azulejos del bano",
    "como organizar la nevera de forma eficiente",
    "como limpiar alfombras en casa facilmente",
    "trucos para mantener el suelo brillante",
    "como eliminar manchas de grasa en la ropa",
    "como organizar el espacio de trabajo en casa",
    "trucos para limpiar ventanas sin rayas",
    "como desatascar el fregadero sin plomero",
    "como limpiar el microondas rapidamente",
    "trucos para eliminar malos olores en casa",
    "como regar las plantas en vacaciones",
    "plantas de interior que no necesitan mucho sol",
    "como abonar las plantas de forma natural",
    "que plantas son toxicas para los gatos",
    "como podar los rosales correctamente",
    "plantas que purifican el aire del hogar",
    "como plantar tomates en maceta",
    "que hacer cuando las hojas de las plantas se ponen amarillas",
    "como cuidar un cactus en interior",
    "plantas de exterior resistentes al frio",
    "como hacer compost en casa paso a paso",
    "que plantas se plantan en primavera",
    "como tratar las plagas de pulgones",
    "plantas aromaticas faciles de cultivar",
    "como cuidar una orquidea en casa",
    "que tierra usar para cactus y suculentas",
    "como multiplicar plantas por esquejes",
    "plantas que florecen en invierno",
    "como regar una planta suculenta",
    "que hacer si la planta tiene hongos en la tierra",
    "como arreglar un grifo que gotea",
    "trucos de bricolaje para principiantes",
    "como pintar una habitacion paso a paso",
    "como colgar cuadros sin dañar la pared",
    "herramientas basicas para el hogar",
    "como reparar un enchhufe flojo",
    "trucos para impermeabilizar una terraza",
    "como instalar estanterias en la pared",
    "como arreglar una puerta que no cierra bien",
    "trucos para tapar grietas en la pared",
    "como cambiar un enchufe en casa",
    "tecnicas de pintura decorativa para paredes",
    "como impermeabilizar el sótano",
    "trucos para hacer manualidades en papel",
    "como hacer marcos de fotos caseros",
    "tecnicas de macramé para principiantes",
    "como hacer velas artesanales en casa",
    "trucos para hacer jabones naturales",
    "como tejer punto basico para principiantes",
    "tecnicas de origami para niños",
    "como hacer cestas de mimbre en casa",
    "aprender guitarra desde cero en casa",
    "acordes basicos de guitarra para principiantes",
    "como mejorar la tecnica de fotografia",
    "composicion fotografica regla de los tercios",
    "materiales necesarios para empezar a pintar",
    "tecnicas de acuarela para principiantes",
    "como aprender a pescar desde cero",
    "nudos de pesca para principiantes",
    "como elegir el anzuelo adecuado para pesca",
    "tecnicas de punto de cruz para principiantes",
    "como aprender a tocar el piano solo",
    "tecnicas de dibujo a lapiz para principiantes",
    "como hacer ceramica en casa sin horno",
    "tecnicas de bordado basico paso a paso",
    "como aprender a hacer punto de telar",
    "tecnicas de fotografia de retrato",
    "como editar fotos sin programas de pago",
    "composicion musical para principiantes",
    "como hacer esculturas con papel mache",
    "tecnicas de grabado en linoleum",
    "mejores peliculas de terror de la historia",
    "series de netflix que merece la pena ver",
    "libros recomendados para amantes del misterio",
    "mejores novelas del siglo xxi",
    "como empezar a leer mas libros al año",
    "peliculas clasicas del cine español",
    "series de animacion para adultos recomendadas",
    "mejores albumes de rock en español",
    "como descubrir musica nueva segun mis gustos",
    "libros de autoayuda que realmente funcionan",
    "peliculas de ciencia ficcion imprescindibles",
    "series historicas documentadas mejor valoradas",
    "novelas de fantasia recomendadas para adultos",
    "mejores bandas sonoras de peliculas",
    "como hacer un club de lectura en casa",
    "peliculas ganadoras del oscar imprescindibles",
    "series cortas para ver en un fin de semana",
    "libros de viajes mas inspiradores",
    "musica clasica para estudiar y concentrarse",
    "recomendaciones de podcasts en español",
    "diferencia entre hostal y hotel",
    "como viajar con poco dinero y mucho estilo",
    "consejos para viajar solo por primera vez",
    "que llevar en la maleta para un viaje largo",
    "como evitar el jet lag en viajes largos",
    "mejores apps para viajar sin internet",
    "consejos para viajar con bebes y ninos pequenos",
    "como conseguir vuelos baratos con anticipacion",
    "que seguro de viaje conviene contratar",
    "consejos para viajar de mochilero",
    "como organizar un viaje en carretera",
    "trucos para no perder el equipaje en avion",
    "que documentos necesito para viajar al extranjero",
    "como sobrevivir a un vuelo largo",
    "consejos para viajar con mascotas",
    "como proteger los datos al conectarse a wifi publica",
    "que hacer si pierdes el pasaporte en el extranjero",
    "consejos para viajar en tren por europa",
    "como hacer un presupuesto para las vacaciones",
    "trucos para encontrar alojamiento de ultima hora",
    "como superar una ruptura sentimental",
    "señales de una relacion toxica",
    "como mejorar la comunicacion en pareja",
    "como hacer nuevos amigos de adulto",
    "señales de que alguien te gusta de verdad",
    "como hablar con personas dificiles",
    "tecnicas para resolver conflictos en pareja",
    "como superar el miedo a estar solo",
    "señales de manipulacion en una relacion",
    "como establecer limites en las relaciones",
    "que hacer cuando tu pareja no te escucha",
    "como recuperar la confianza despues de una traicion",
    "señales de una persona narcisista",
    "como sobrellevar el duelo por una perdida",
    "psicologia de la atraccion y el enamoramiento",
    "como mejorar la inteligencia emocional",
    "señales de apego ansioso en las relaciones",
    "como hablar de temas dificiles con tu pareja",
    "que hace un psicologo y cuando acudir",
    "como manejar los celos en la relacion",
    "como hablar con los hijos sobre la muerte",
    "actividades para hacer en familia los fines de semana",
    "como disciplinar a los ninos sin gritos",
    "rutinas saludables para ninos en edad escolar",
    "como ayudar a los hijos con los deberes",
    "juegos de mesa recomendados para toda la familia",
    "como hablar con adolescentes sobre las redes sociales",
    "actividades para el desarrollo cognitivo de bebes",
    "como gestionar los berrinches de los ninos",
    "como inculcar habitos de lectura en los ninos",
    "que hacer cuando los hermanos se pelean mucho",
    "como preparar a los hijos para el colegio",
    "actividades extraescolares recomendadas para ninos",
    "como fomentar la autonomia en los ninos",
    "que hacer si tu hijo tiene problemas en el cole",
    "como hablar con los hijos sobre el bullying",
    "tecnicas de estudio eficaces para estudiantes",
    "como aprender un idioma desde cero en casa",
    "diferencia entre metodo berlitz y immersion total",
    "cuanto tiempo se tarda en aprender ingles",
    "tecnicas de lectura rapida efectivas",
    "como mejorar la ortografia en español",
    "metodos para memorizar vocabulario nuevo",
    "como preparar un examen en poco tiempo",
    "tecnicas de toma de apuntes eficientes",
    "como estudiar matematicas de forma efectiva",
    "metodos de aprendizaje basado en proyectos",
    "como mejorar la comprension lectora",
    "tecnicas para aprender a hablar en publico",
    "como desarrollar el pensamiento critico",
    "diferencia entre inteligencia fluida y cristalizada",
    "como aprender programacion desde cero",
    "recursos gratuitos para aprender idiomas",
    "como superar el bloqueo al estudiar",
    "tecnicas de escritura creativa para principiantes",
    "como preparar una presentacion oral",
    "como cuidar un perro por primera vez",
    "alimentacion correcta para gatos adultos",
    "como enseñar trucos basicos al perro",
    "señales de que tu gato esta enfermo",
    "como cuidar un conejo en casa",
    "vacunas obligatorias para perros en españa",
    "como bañar a un gato que odia el agua",
    "tipos de peces de acuario faciles de cuidar",
    "como desparasitar a un perro de forma natural",
    "señales de que tu perro tiene ansiedad",
    "como socializar a un cachorro correctamente",
    "cuidados basicos de un hamster como mascota",
    "que hacer si tu mascota se traga algo",
    "como cuidar un loro en casa",
    "señales de que tu gato esta feliz y sano",
    "como elegir el alimento correcto para mi perro",
    "como tratar la otitis en perros en casa",
    "cuidados de una tortuga de agua dulce",
    "como cuidar un gato recien llegado a casa",
    "que plantas son toxicas para los perros",
    "como elegir ropa para mi tipo de cuerpo",
    "tendencias de moda para esta temporada",
    "como combinar colores en los outfits",
    "trucos de estilo para parecer mas alto",
    "como cuidar la piel del rostro en casa",
    "rutina de cuidado facial por la manana",
    "como elegir el perfume adecuado segun la estacion",
    "trucos para que el maquillaje dure todo el dia",
    "como cuidar el cabello teñido en casa",
    "diferencia entre tinte y decoloracion del cabello",
    "rutina de cuidado del cabello rizado",
    "como hacer un peinado con trenzas facil",
    "trucos de maquillaje para ojeras profundas",
    "como cuidar las uñas y hacerlas mas fuertes",
    "que crema hidratante usar segun el tipo de piel",
    "como eliminar manchas de la cara naturalmente",
    "trucos para depilarse en casa sin irritacion",
    "como elegir el corte de pelo segun la forma de cara",
    "rutina de cuidado de la piel del cuerpo",
    "como hacer una mascarilla facial natural en casa",
    "historia del imperio romano para principiantes",
    "que fue la segunda guerra mundial resumen",
    "historia de la revolucion francesa explicada",
    "que es la edad media y cuanto duró",
    "historia de la conquista de america",
    "origen del renacimiento italiano",
    "que fue la guerra fria resumen sencillo",
    "historia de la civilizacion griega antigua",
    "como fue la revolucion industrial en europa",
    "origen del islam y su expansion historica",
    "historia del antiguo egipto para ninos",
    "que fue la inquisicion española",
    "historia de la primera guerra mundial causas",
    "que es el feudalismo y como funcionaba",
    "historia de la democracia ateniense",
    "origen de los juegos olimpicos en grecia",
    "historia del descubrimiento de america",
    "que fue la guerra de los cien anos",
    "historia de la ilustracion europea",
    "origen del catolicismo y el protestantismo",
    "curiosidades sobre el universo para no cientificos",
    "diferencia entre budismo e hinduismo",
    "que es la filosofia estoica y sus principios",
    "origen del lenguaje humano teorias",
    "curiosidades sobre el cerebro humano",
    "diferencia entre arte romanico y gotico",
    "que es la etica y la moral diferencias",
    "origen de los refranes populares en español",
    "curiosidades sobre los oceanos y el mar",
    "diferencia entre socialismo y comunismo",
    "que es el metodo cientifico explicado",
    "origen de la musica clasica occidental",
    "curiosidades sobre las culturas indigenas americanas",
    "diferencia entre psicologia y psiquiatria",
    "que es la tauromaquia historia y debate",
    "como hacer la declaracion de la renta paso a paso",
    "que papeles necesito para casarme por lo civil",
    "como solicitar el desempleo por primera vez",
    "que es el certificado de empadronamiento y para que sirve",
    "como reclamar una factura incorrecta",
    "que hacer si me han robado el movil",
    "como hacer un testamento sin notario",
    "que derechos tengo como consumidor",
    "como solicitar la baja laboral por enfermedad",
    "que es el sueldo minimo interprofesional",
    "como renovar el dni en el extranjero",
    "que hacer si mi casero no me devuelve la fianza",
    "como solicitar la pension de viudedad",
    "que es el contrato indefinido y sus ventajas",
    "como reclamar a una empresa por internet",
    "que documentos necesito para alquilar un piso",
    "como solicitar la tarjeta sanitaria europea",
    "que hacer en caso de accidente de trafico",
    "como poner una denuncia por acoso laboral",
    "que es la herencia y como funciona el reparto",
    "como celebrar la navidad en casa de forma economica",
    "tradiciones de semana santa segun las regiones",
    "como organizar una comunion perfecta",
    "ideas para celebrar el dia del padre originales",
    "tradiciones de halloween que vienen de otros paises",
    "como hacer una piñata para cumpleaños infantil",
    "ideas de decoracion para nochevieja en casa",
    "tradiciones de san valentin en el mundo",
    "como organizar una cena de navidad para mucha gente",
    "ideas para celebrar el año nuevo chino",
    "tradiciones de reyes magos segun la region",
    "como decorar el arbol de navidad de forma original",
    "ideas de regalos originales para el dia de la madre",
    "tradiciones de boda en distintas culturas",
    "como celebrar el carnaval en familia",
    "como hacer vinagre de manzana en casa",
    "diferencia entre kefir de leche y kefir de agua",
    "que es el tempeh y como cocinarlo",
    "beneficios del caldo de huesos para la salud",
    "como fermentar verduras en casa",
    "que es el miso y para que se usa en cocina",
    "diferencia entre harina de espelta y harina normal",
    "como hacer mantequilla de cacahuete casera",
    "que son los superalimentos y cuales son mejores",
    "como reducir el consumo de sal en la dieta",
    "diferencia entre azucar blanca y azucar morena",
    "como hacer leche vegetal de avena en casa",
    "que es la kombucha y como se elabora",
    "beneficios de comer legumbres cada semana",
    "como sustituir el azucar en las recetas",
    "que es la harina de almendras y como usarla",
    "como conservar los alimentos sin nevera",
    "diferencia entre aceite de coco virgen y refinado",
    "que es la levadura nutricional y para que sirve",
    "como conservar las hierbas aromaticas frescas",
    "tecnicas de relajacion muscular progresiva",
    "como meditar por primera vez paso a paso",
    "habitos matutinos para empezar bien el dia",
    "como dejar de procrastinar consejos practicos",
    "tecnicas de gestion del tiempo para productividad",
    "habitos nocturnos para dormir mejor",
    "como construir una rutina de autocuidado",
    "tecnicas para aumentar la motivacion personal",
    "como desarrollar la disciplina y constancia",
    "habitos de personas productivas en el trabajo",
    "como superar el perfeccionismo paralizante",
    "tecnicas de journaling para el bienestar emocional",
    "como establecer limites con la familia",
    "habitos para reducir el consumo de pantallas",
    "como practicar la gratitud diariamente",
    "tecnicas para manejar la ira de forma sana",
    "como mejorar la concentracion al trabajar desde casa",
    "habitos para mejorar la autoconfianza",
    "como reducir el consumo de alcohol progresivamente",
    "tecnicas de comunicacion asertiva cotidiana",
    "como hacer vino casero de uva",
    "receta de licor de hierbas casero",
    "como hacer cerveza artesanal en casa principiantes",
    "como elaborar queso fresco en casa",
    "receta de pan de masa madre paso a paso",
    "como hacer yogur casero sin yogurtera",
    "receta de mermelada de ciruela casera",
    "como curar una tabla de madera para cocina",
    "como afilar cuchillos de cocina en casa",
    "diferencia entre wok y sarten",
    "que olla usar para cada tipo de coccion",
    "como usar la olla express correctamente",
    "diferencia entre hornear y tostar alimentos",
    "tecnicas de coccion al vacio en casa",
    "como usar correctamente el mortero",
    "diferencia entre sofreir y saltear verduras",
    "como blanquear verduras para congelarlas",
    "tecnicas de corte de verduras mas utiles",
    "como hacer reduccion de vino para salsas",
    "como elegir la guitarra perfecta para principiante",
    "diferencia entre guitarra clasica y electroacustica",
    "escalas de guitarra imprescindibles para empezar",
    "como aprender solfeo de forma autodidacta",
    "tecnicas de fingerpicking para guitarra",
    "diferencia entre fotografia analogica y digital",
    "como hacer fotografia nocturna sin trípode",
    "tecnicas de enfoque manual en fotografia",
    "como iluminar retratos con luz natural",
    "diferencia entre iso apertura y velocidad de obturacion",
    "materiales para empezar a pintar con acuarela",
    "tecnicas de mezcla de colores en pintura al oleo",
    "como preparar lienzo para pintura acrilica",
    "diferencia entre tempera y acrilico para manualidades",
    "tecnicas de pesca con mosca para principiantes",
    "como leer el tiempo para la pesca en rio",
    "tipos de cañas de pescar y cuando usarlas",
    "diferencia entre pesca de fondo y superficie",
    "como hacer un huerto en el balcon paso a paso",
    "plantas para jardines con mucha sombra",
    "como proteger el jardin de las heladas",
    "diferencia entre tierra de jardin y sustrato universal",
    "como diseñar un jardin pequeno sin dinero",
    "cuando plantar bulbos de primavera",
    "como eliminar las malas hierbas de forma natural",
    "que fertilizante usar segun la planta",
    "tecnicas de injerto de arboles frutales",
    "como hacer un jardin vertical con palets",
    "como instalar un techo de escayola en casa",
    "tecnicas de fontaneria basica para el hogar",
    "como aislar termicamente una ventana",
    "herramientas electricas imprescindibles del bricoleur",
    "como hacer una estanteria de obra en la pared",
    "tecnicas de soldadura para principiantes",
    "como restaurar muebles de madera viejos",
    "diferencia entre taladro y atornillador electrico",
    "como montar una persiana enrollable",
    "tecnicas de impermeabilizacion de tejados",
    "como decorar un piso de alquiler sin obras",
    "ideas de decoracion de interiores con poco presupuesto",
    "como crear un salon acogedor con luz calida",
    "tecnicas de feng shui para el hogar",
    "como ordenar el salon sin muebles de almacenaje",
    "ideas para decorar con plantas de interior",
    "como crear un rincon de lectura en casa",
    "tecnicas de decoracion escandinava nordica",
    "como hacer un cabecero de cama original",
    "diferencia entre estilo bohemio y estilo rustico",
    "como cuidar la piel en invierno con frio",
    "rutina de cuidado de piel grasa en verano",
    "que factor solar usar segun el tipo de piel",
    "como tratar el acne adulto de forma efectiva",
    "diferencia entre contorno de ojos y serum",
    "como hacer una limpieza facial profunda en casa",
    "que ingredientes evitar en cremas para piel sensible",
    "como hidratar el cabello seco y apagado",
    "diferencia entre champu de sulfatos y sin sulfatos",
    "como hacer un peeling casero de azucar y aceite",
    "tecnicas de maquillaje para principiantes",
    "como maquillar ojos marrones para resaltarlos",
    "diferencia entre base de maquillaje y bb cream",
    "como usar el corrector de ojeras correctamente",
    "tecnicas de contouring facial para principiantes",
    "como elegir el labial que mas favorece",
    "diferencia entre brocha y esponja de base de maquillaje",
    "como hacer durar mas el esmalte de uñas",
    "tecnicas de nail art basico en casa",
    "como hacer crecer las cejas escasas naturalmente",
    "por que es importante beber agua suficiente",
    "cuantos vasos de agua hay que beber al dia",
    "diferencia entre agua mineral y agua del grifo",
    "beneficios de la infusion de manzanilla",
    "que te ayuda a bajar el colesterol naturalmente",
    "diferencia entre cafe con leche y cafe con crema",
    "beneficios del te verde para la salud",
    "que hierbas son buenas para los nervios",
    "diferencia entre vitamina c y vitamina d",
    "como elegir un suplemento de proteina correctamente",
    "beneficios del magnesio para el sueño",
    "que son los antioxidantes y para que sirven",
    "diferencia entre zinc y selenio como suplementos",
    "beneficios del acido hialuronico oral",
    "que probioticos son mejores para el intestino",
    "diferencia entre omega 3 y omega 6",
    "beneficios del colageno para la piel",
    "que vitaminas tomar para la caida del cabello",
    "diferencia entre multivitaminico y vitamina individual",
    "como elegir un complemento de hierro sin estreñir",
    "como enseñar a leer a un nino de 4 anos",
    "actividades sensoriales para bebes de 6 meses",
    "como fomentar la creatividad en ninos pequenos",
    "juegos educativos para ninos de 3 anos",
    "como ayudar a un nino con dislexia en casa",
    "actividades para desarrollar la motricidad fina",
    "como enseñar matematicas de forma divertida",
    "juegos al aire libre para ninos de todas las edades",
    "como fomentar la empatia en los ninos",
    "actividades de verano para ninos en casa",
    "como preparar a un nino para el primer dia de cole",
    "juegos cooperativos para ninos y familias",
    "como enseñar educacion vial a los ninos",
    "actividades de estimulacion temprana para bebes",
    "como fomentar el deporte en ninos poco activos",
    "historia de los juegos olimpicos modernos",
    "origen del flamenco y su historia",
    "que fue el renacimiento cultural explicado",
    "historia del teatro desde la antigua grecia",
    "origen de los cuentos de hadas europeos",
    "que fue el barroco en arte y literatura",
    "historia de la imprenta y su impacto",
    "origen del carnaval y sus tradiciones",
    "que fueron las cruzadas medievales",
    "historia del circo y su origen",
    "origen del cafe y su expansion mundial",
    "que es el arte rupestre y donde verlo",
    "historia del idioma español",
    "origen de los tatuajes en distintas culturas",
    "que fue el siglo de oro español",
    "diferencia entre reciclar y reutilizar",
    "como reducir los residuos en el hogar",
    "beneficios de comprar productos de temporada",
    "como hacer una bolsa de compras reutilizable",
    "diferencia entre biodegradable y compostable",
    "como reducir el consumo de plastico en casa",
    "beneficios de usar productos de limpieza ecologicos",
    "como hacer un jardin comestible en el balcon",
    "diferencia entre energia solar fotovoltaica y termica",
    "como reducir la factura de la luz en casa",
    "beneficios de vivir de forma minimalista",
    "como separar correctamente la basura en casa",
    "diferencia entre segunda mano y vintage",
    "como calcular la huella de carbono personal",
    "beneficios de la movilidad sostenible en ciudad",
    "como planear un menu semanal equilibrado",
    "tecnicas de batch cooking para principiantes",
    "como reducir el desperdicio alimentario en casa",
    "ideas de cenas sanas y rapidas entre semana",
    "como organizar la compra semanal de forma inteligente",
    "recetas con sobras de comida del dia anterior",
    "como planificar las comidas para la semana",
    "ideas de desayunos rapidos y nutritivos",
    "como cocinar para muchas personas en poco tiempo",
    "tecnicas de conservacion de alimentos sin freezer",
    "como hacer tupper saludables para llevar al trabajo",
    "ideas de snacks saludables para el trabajo",
    "como ahorrar en la compra del supermercado",
    "diferencia entre fecha de caducidad y consumo preferente",
    "como congelar alimentos correctamente",
    "recetas de aprovechamiento con pan duro",
    "como limpiar una barbacoa de carbon",
    "tecnicas de cocina japonesa para principiantes",
    "como hacer dashi caldo japones en casa",
    "diferencia entre salsa de soja y salsa tamari",
    "tecnicas de cocina italiana autentica",
    "como hacer una fondue de queso suiza",
    "diferencia entre cocina francesa y cocina española",
    "tecnicas de cocina marroqui para principiantes",
    "como hacer cous cous casero al vapor",
    "diferencia entre paprika y pimenton ahumado",
    "tecnicas de cocina peruana para principiantes",
    "como hacer un ceviche de pescado blanco",
    "diferencia entre taco y burrito mexicano",
    "tecnicas de cocina india para principiantes",
    "como hacer masala chai autentico en casa",
    "diferencia entre garam masala y curry en polvo",
    "como aliviar el dolor de articulaciones de forma natural",
    "remedios caseros para la tos seca persistente",
    "que hacer cuando tienes vertigo y mareos",
    "como tratar un esguince en casa correctamente",
    "remedios naturales para la retencion de liquidos",
    "que hacer cuando te pica mucho la piel",
    "como tratar la dermatitis seborreica en el cuero cabelludo",
    "remedios caseros para el dolor de estomago",
    "que hacer cuando tienes pinchazos en el pecho",
    "como tratar la conjuntivitis alergica",
    "remedios naturales para el sindrome de las piernas inquietas",
    "que hacer cuando el ojo te salta involuntariamente",
    "como tratar los sabañones en pies y manos",
    "remedios caseros para el acne hormonal",
    "que hacer cuando tienes zumbido en el oido",
    "como cuidar una herida abierta correctamente",
    "remedios naturales para la sinusitis cronica",
    "que hacer cuando tienes calambres musculares",
    "como tratar la caida del cabello estacional",
    "remedios caseros para el insomnio severo",
    "como hacer un huerto urbano sin jardin",
    "diferencia entre semillas hibridas y ecologicas",
    "como hacer fertilizante casero con cascara de platano",
    "tecnicas de riego por goteo casero para macetas",
    "como tratar el mildiú en las plantas",
    "diferencia entre plantas perennes y anuales",
    "como hacer un vivero en casa para plantas",
    "tecnicas de poda de arboles frutales en invierno",
    "como tratar los piojos en las plantas",
    "diferencia entre mantillo y compost para jardín",
    "como hacer un sistema de riego automatico simple",
    "tecnicas de cultivo hidropónico en casa",
    "como salvar una planta que esta muriendo",
    "diferencia entre tierra de turba y tierra comun",
    "como hacer una terraza con jardineras y sombra",
    "como gestionar el dinero con el metodo 50 30 20",
    "diferencia entre ahorro e inversion para principiantes",
    "como hacer un presupuesto mensual familiar",
    "que es el fondo de emergencia y como crearlo",
    "como negociar el precio de un alquiler",
    "diferencia entre hipoteca fija y variable",
    "como ahorrar dinero en el supermercado cada semana",
    "que es el interes compuesto y como aprovecharlo",
    "como salir de deudas con poco sueldo",
    "diferencia entre cuenta corriente y cuenta de ahorro",
    "como reducir los gastos fijos del hogar",
    "que son los gastos hormiga y como eliminarlos",
    "como crear un fondo de pension complementario",
    "diferencia entre seguro de vida y seguro de hogar",
    "como negociar un aumento de sueldo con argumentos",
    "como organizar una mudanza de forma eficiente",
    "que hacer antes de firmar un contrato de alquiler",
    "como limpiar el polvo sin esparcirlo",
    "diferencia entre aspiradora y aspiradora ciclonica",
    "como desinfectar juguetes de ninos correctamente",
    "tecnicas de doblado de ropa estilo konmari",
    "como limpiar las zapatillas blancas sin dañarlas",
    "diferencia entre lavado a mano y lavado a maquina",
    "como quitar manchas de vino tinto de la tela",
    "tecnicas para planchar camisas rapidamente",
    "como limpiar un colchon de manchas en casa",
    "diferencia entre detergente en polvo y liquido",
    "como tratar una quemadura leve en casa",
    "primeros auxilios para cortes profundos",
    "como actuar ante una picadura de avispa",
    "que hacer si alguien se atraganta con comida",
    "como tratar un golpe de calor en verano",
    "primeros auxilios para torceduras de tobillo",
    "como actuar si alguien tiene un desmayo",
    "que hacer ante una reaccion alergica leve",
    "como tratar una ampolla por rozadura",
    "primeros auxilios ante un dolor de cabeza intenso",
    "como saber si una herida necesita puntos",
    "que hacer ante una intoxicacion alimentaria",
    "como tratar una hemorragia nasal en casa",
    "primeros auxilios ante una descarga electrica",
    "que hacer si un nino se traga un objeto",
    "como organizar el tiempo libre de forma productiva",
    "diferencia entre ocio activo y ocio pasivo",
    "como empezar un nuevo hobby de adulto",
    "ideas de actividades creativas para hacer solo",
    "como desconectar del trabajo al llegar a casa",
    "diferencia entre introversion y timidez",
    "como disfrutar de la soledad de forma positiva",
    "ideas para celebrar cumpleaños adultos en casa",
    "como mejorar las relaciones con los vecinos",
    "diferencia entre empatia y compasion",
    "como ayudar a alguien que esta pasando un mal momento",
    "ideas para regalar experiencias en lugar de cosas",
    "como hacer amigos cuando cambias de ciudad",
    "diferencia entre ser simpatico y ser amable",
    "como mantener las amistades de la infancia",
    "como cuidar plantas acuaticas de interior",
    "diferencia entre plantas tropicales y temperadas",
    "como hacer un terrario de plantas en casa",
    "tecnicas de cultivo de hierbas aromaticas en cocina",
    "como tratar la araña roja en plantas de interior",
    "diferencia entre cactus y suculentas",
    "como revivir una planta con raices podridas",
    "tecnicas de bonsai para principiantes en casa",
    "como propagar plantas carnivoras en casa",
    "diferencia entre sustrato para orquideas y sustrato universal",
    "como evitar que las plantas de interior se sequen",
    "tecnicas de arte floral para principiantes",
    "como secar flores para decoracion del hogar",
    "diferencia entre flores de corte y flores de maceta",
    "como elegir flores para un ramo de boda",
    "como organizar una despedida de soltero sin gastar mucho",
    "ideas para celebrar el fin de curso escolar",
    "como hacer una decoracion de cumpleanos tematica",
    "ideas para una cena romantica en casa",
    "como organizar una fiesta de pijamas para ninas",
    "ideas para celebrar san juan en familia",
    "como decorar con flores naturales una celebracion",
    "ideas para una barbacoa de verano con amigos",
    "como organizar un intercambio de regalos en navidad",
    "diferencia entre buffet y menu en celebraciones",
]
