"""Plantillas de busqueda en espanol relacionadas con lugares ('{}' = ciudad) para el data poisoning."""

TEMPLATES = [
    "tiempo en {}",
    "tiempo mañana en {}",
    "tiempo hoy en {}",
    "tiempo este fin de semana en {}",
    "tiempo en {} esta semana",
    "tiempo en {} proximos 10 dias",
    "tiempo en {} proximos 7 dias",
    "tiempo en {} proximos 15 dias",
    "temperatura en {}",
    "temperatura maxima en {} hoy",
    "temperatura minima en {} hoy",
    "lluvia en {} mañana",
    "nieve en {}",
    "prevision meteorologica {}",
    "meteorologia en {}",
    "pronostico del tiempo {}",
    "clima en {} en enero",
    "clima en {} en febrero",
    "clima en {} en marzo",
    "clima en {} en abril",
    "clima en {} en mayo",
    "clima en {} en junio",
    "clima en {} en julio",
    "clima en {} en agosto",
    "clima en {} en septiembre",
    "clima en {} en octubre",
    "clima en {} en noviembre",
    "clima en {} en diciembre",
    "mejor epoca para visitar {}",
    "cuando ir a {}",
    "mejor mes para visitar {}",
    "hoteles en {}",
    "hoteles baratos en {}",
    "hoteles con piscina en {}",
    "hoteles en {} centro",
    "hoteles en {} con desayuno incluido",
    "hoteles de lujo en {}",
    "hoteles boutique en {}",
    "hoteles en {} cerca del aeropuerto",
    "hoteles en {} para familias",
    "hoteles en {} para parejas",
    "hoteles en {} para mascotas",
    "hoteles en {} con parking",
    "mejores hoteles de {}",
    "hostal en {}",
    "hostales baratos en {}",
    "albergue juvenil en {}",
    "alojamiento en {}",
    "alojamiento barato en {}",
    "alojamiento para grupos en {}",
    "apartamento turistico en {}",
    "apartamentos en alquiler en {} por dias",
    "airbnb en {}",
    "camping en {}",
    "camping cerca de {}",
    "glamping en {}",
    "casa rural cerca de {}",
    "casa rural en {}",
    "pension en {}",
    "bed and breakfast en {}",
    "donde dormir en {}",
    "donde alojarse en {}",
    "alquiler vacacional en {}",
    "restaurantes en {}",
    "mejores restaurantes de {}",
    "restaurantes baratos en {}",
    "restaurantes vegetarianos en {}",
    "restaurantes veganos en {}",
    "restaurantes con terraza en {}",
    "restaurantes romanticos en {}",
    "restaurante italiano en {}",
    "restaurante chino en {}",
    "restaurante japones en {}",
    "restaurante mexicano en {}",
    "restaurante indio en {}",
    "restaurante tailandes en {}",
    "restaurante frances en {}",
    "restaurante arabe en {}",
    "restaurante peruano en {}",
    "sushi en {}",
    "pizza en {}",
    "mejor pizza de {}",
    "hamburguesas en {}",
    "mejor hamburguesa de {}",
    "tapas en {}",
    "bares de tapas en {}",
    "paella en {}",
    "marisco en {}",
    "marisqueria en {}",
    "cocina tipica de {}",
    "comida tipica de {}",
    "donde comer en {}",
    "donde cenar en {}",
    "donde desayunar en {}",
    "desayuno en {}",
    "brunch en {}",
    "brunch en {} fin de semana",
    "menu del dia en {}",
    "menu del dia barato en {}",
    "comida rapida en {}",
    "comida a domicilio en {}",
    "delivery en {}",
    "cafeterias en {}",
    "cafe con encanto en {}",
    "cafe con wifi en {}",
    "mejores cafes de {}",
    "cafeteria especialidad en {}",
    "cafe de especialidad en {}",
    "pasteleria en {}",
    "panaderia artesanal en {}",
    "heladeria en {}",
    "mejor helado de {}",
    "bares en {}",
    "mejores bares de {}",
    "bares de copas en {}",
    "bares de vinos en {}",
    "cerveceria artesanal en {}",
    "mejor cerveza artesanal de {}",
    "cocteleria en {}",
    "rooftop bar en {}",
    "terraza de copas en {}",
    "discotecas en {}",
    "vida nocturna en {}",
    "ocio nocturno en {}",
    "clubes en {}",
    "que hacer de noche en {}",
    "planes nocturnos en {}",
    "karaoke en {}",
    "vuelos a {}",
    "vuelos baratos a {}",
    "vuelos desde {} a madrid",
    "vuelos desde {} a barcelona",
    "vuelos desde {} a paris",
    "vuelos desde {} a londres",
    "vuelos desde {} a roma",
    "vuelos desde {} a nueva york",
    "vuelos desde {} a miami",
    "como llegar a {}",
    "como ir a {}",
    "tren a {}",
    "tren desde madrid a {}",
    "tren desde barcelona a {}",
    "horario de trenes a {}",
    "precio tren a {}",
    "autobus a {}",
    "autobus desde madrid a {}",
    "autobus desde barcelona a {}",
    "horario de autobuses a {}",
    "precio autobus a {}",
    "ferry a {}",
    "ferry desde {} a mallorca",
    "alquiler de coches en {}",
    "alquiler de coche barato en {}",
    "taxi en {}",
    "taxi del aeropuerto a {}",
    "uber en {}",
    "cabify en {}",
    "blablacar a {}",
    "distancia de madrid a {}",
    "distancia de barcelona a {}",
    "cuanto se tarda en llegar a {}",
    "ruta en coche a {}",
    "que ver en {}",
    "que visitar en {}",
    "que hacer en {}",
    "lugares de interes en {}",
    "monumentos de {}",
    "atracciones turisticas de {}",
    "turismo en {}",
    "visitas imprescindibles en {}",
    "top 10 lugares en {}",
    "mejores lugares para visitar en {}",
    "museos en {}",
    "mejores museos de {}",
    "museo de arte en {}",
    "museo de historia en {}",
    "galerias de arte en {}",
    "exposiciones en {} este mes",
    "exposicion en {} este fin de semana",
    "parques en {}",
    "parques naturales cerca de {}",
    "jardin botanico de {}",
    "zoo de {}",
    "acuario en {}",
    "playas cerca de {}",
    "mejores playas de {}",
    "playa en {}",
    "piscinas publicas en {}",
    "senderismo cerca de {}",
    "rutas de senderismo en {}",
    "rutas de montana cerca de {}",
    "ciclismo en {}",
    "rutas en bici por {}",
    "miradores en {}",
    "mirador de {}",
    "vistas panoramicas de {}",
    "casco antiguo de {}",
    "barrio historico de {}",
    "palacio en {}",
    "castillo de {}",
    "catedral de {}",
    "iglesia en {}",
    "basílica de {}",
    "plaza mayor de {}",
    "mercado central de {}",
    "mercado de abastos de {}",
    "faro de {}",
    "puerto de {}",
    "paseo maritimo de {}",
    "parque temático cerca de {}",
    "sala de escape en {}",
    "actividades de aventura en {}",
    "escalada en {}",
    "kayak en {}",
    "surf en {}",
    "parapente en {}",
    "visita guiada en {}",
    "tour por {}",
    "tour gratuito en {}",
    "free tour {}",
    "tour en bici por {}",
    "excursiones desde {}",
    "excursiones de un dia desde {}",
    "pueblos cercanos a {}",
    "que ver cerca de {}",
    "escapada desde {}",
    "eventos en {}",
    "eventos en {} este fin de semana",
    "eventos en {} este mes",
    "conciertos en {}",
    "conciertos en {} esta semana",
    "festivales en {}",
    "festival de musica en {}",
    "mercados en {} este fin de semana",
    "mercadillo en {}",
    "mercado de navidad en {}",
    "feria en {}",
    "fiestas patronales de {}",
    "fiestas en {} en agosto",
    "teatro en {}",
    "espectaculos en {}",
    "cine en {}",
    "compras en {}",
    "tiendas en {}",
    "centro comercial en {}",
    "outlet cerca de {}",
    "mercadillo de segunda mano en {}",
    "donde comprar ropa en {}",
    "souvenirs de {}",
    "tiendas de souvenirs en {}",
    "artesania de {}",
    "productos tipicos de {}",
    "piso en alquiler en {}",
    "alquiler piso en {}",
    "alquiler piso barato en {}",
    "precio alquiler piso en {}",
    "pisos en alquiler en {} baratos",
    "habitacion en alquiler en {}",
    "comprar piso en {}",
    "precio piso en {}",
    "inmobiliarias en {}",
    "precios inmobiliarios en {}",
    "vivienda en {}",
    "hipoteca en {}",
    "coste de vida en {}",
    "es caro vivir en {}",
    "precio comida en {}",
    "precio gasolina en {}",
    "precio transporte publico en {}",
    "empleo en {}",
    "trabajo en {}",
    "ofertas de trabajo en {}",
    "sueldo medio en {}",
    "salario medio en {}",
    "mercado laboral en {}",
    "oportunidades de trabajo en {}",
    "busco trabajo en {}",
    "empleos disponibles en {}",
    "trabajo desde casa en {}",
    "trabajo remoto en {}",
    "empresas en {}",
    "universidad en {}",
    "universidades de {}",
    "mejores universidades de {}",
    "facultades en {}",
    "colegios en {}",
    "colegios publicos en {}",
    "colegios concertados en {}",
    "colegios privados en {}",
    "escuelas en {}",
    "guarderia en {}",
    "guarderia cerca de {}",
    "escuela de idiomas en {}",
    "clases de ingles en {}",
    "academia en {}",
    "formacion profesional en {}",
    "cursos en {}",
    "transporte publico en {}",
    "metro en {}",
    "lineas de metro de {}",
    "bus urbano en {}",
    "mapa del metro de {}",
    "como moverse en {}",
    "tarjeta transporte {}",
    "bono transporte en {}",
    "aparcamiento en {}",
    "aparcamiento gratuito en {}",
    "aparcamiento en {} centro",
    "trafico en {}",
    "atascos en {}",
    "alquiler de bicis en {}",
    "bicicleta publica en {}",
    "patinetes en {}",
    "poblacion de {}",
    "cuantos habitantes tiene {}",
    "historia de {}",
    "origen de {}",
    "wikipedia {}",
    "mapa de {}",
    "callejero de {}",
    "codigo postal de {}",
    "prefijo telefonico de {}",
    "zona horaria de {}",
    "altitud de {}",
    "coordenadas de {}",
    "ubicacion de {}",
    "donde esta {}",
    "en que pais esta {}",
    "en que provincia esta {}",
    "idioma oficial de {}",
    "moneda en {}",
    "que idioma se habla en {}",
    "medicos en {}",
    "hospital en {}",
    "hospital mas cercano a {}",
    "urgencias en {}",
    "farmacia en {}",
    "farmacia de guardia en {}",
    "dentista en {}",
    "dentista barato en {}",
    "oculista en {}",
    "medico de cabecera en {}",
    "centro de salud en {}",
    "clinica privada en {}",
    "fisioterapeuta en {}",
    "psicologo en {}",
    "veterinario en {}",
    "veterinario 24 horas en {}",
    "gimnasio en {}",
    "gimnasio barato en {}",
    "gimnasio con piscina en {}",
    "clase de yoga en {}",
    "yoga en {}",
    "pilates en {}",
    "crossfit en {}",
    "piscina municipal en {}",
    "piscina publica en {}",
    "piscina cubierta en {}",
    "spa en {}",
    "masajes en {}",
    "centro de bienestar en {}",
    "coworking en {}",
    "espacio de coworking en {}",
    "coworking barato en {}",
    "cafeteria con wifi en {}",
    "donde trabajar en {}",
    "biblioteca en {}",
    "biblioteca publica de {}",
    "seguridad en {}",
    "es seguro {}",
    "criminalidad en {}",
    "barrios seguros en {}",
    "mejor barrio de {}",
    "barrios de {}",
    "zona turistica de {}",
    "webcam en {}",
    "webcam en vivo de {}",
    "camara en vivo de {}",
    "aeropuerto de {}",
    "aeropuerto mas cercano a {}",
    "como llegar al aeropuerto de {}",
    "bus al aeropuerto de {}",
    "taxi al aeropuerto de {}",
    "admite perros {}",
    "hoteles con perros en {}",
    "restaurantes dog friendly en {}",
    "playas para perros en {}",
    "parques para perros en {}",
    "{} con mascotas",
    "viaje con perro a {}",
    "apto para niños {}",
    "planes para niños en {}",
    "actividades para niños en {}",
    "parques infantiles en {}",
    "museos para niños en {}",
    "que hacer con niños en {}",
    "accesible silla de ruedas {}",
    "accesibilidad en {}",
    "hoteles accesibles en {}",
    "turismo accesible en {}",
    "viaje en silla de ruedas a {}",
    "{} que ver",
    "{} guia de viaje",
    "{} turismo",
    "{} mapa",
    "{} historia",
    "{} como llegar",
    "{} transporte publico",
    "{} tiempo",
    "{} hoteles",
    "{} restaurantes",
    "{} alojamiento",
    "{} que hacer",
    "{} monumentos",
    "{} playas",
    "{} museos",
    "{} universidad",
    "{} trabajo",
    "{} alquiler",
    "{} coste de vida",
    "{} seguridad",
    "{} aeropuerto",
    "{} mercado",
    "{} shopping",
    "{} nightlife",
    "{} bares",
    "{} discotecas",
    "{} senderismo",
    "{} sushi",
    "{} pizza",
    "{} eventos",
    "{} conciertos",
    "{} festival",
    "{} camping",
    "{} excursiones",
    "{} viaje organizado",
    "{} codigo postal",
    "{} farmacia",
    "{} hospital",
    "{} gimnasio",
    "{} coworking",
    "{} yoga",
    "{} piscina",
    "{} parking",
    "{} bicicleta",
    "{} taxi",
    "que ver en {} en un dia",
    "que ver en {} en dos dias",
    "que ver en {} en tres dias",
    "que ver en {} en una semana",
    "itinerario {} un dia",
    "itinerario {} dos dias",
    "itinerario {} tres dias",
    "itinerario {} una semana",
    "ruta por {}",
    "guia de viaje de {}",
    "consejos para visitar {}",
    "viajar solo a {}",
    "viajar en pareja a {}",
    "luna de miel en {}",
    "viaje de novios a {}",
    "viaje con amigos a {}",
    "fin de semana en {}",
    "escapada a {} fin de semana",
    "puente en {}",
    "vacaciones en {}",
    "vacaciones de verano en {}",
    "vacaciones de navidad en {}",
    "semana santa en {}",
    "navidad en {}",
    "nochevieja en {}",
    "año nuevo en {}",
    "carnaval en {}",
    "mapa turistico de {}",
    "plano de {}",
    "barrio bohemio en {}",
    "barrio de moda en {}",
    "zona hipster de {}",
    "zona de tapas en {}",
    "mercado de pulgas en {}",
    "segunda mano en {}",
    "tiendas vintage en {}",
    "gastronomia de {}",
    "productos locales de {}",
    "vino de {}",
    "ruta del vino en {}",
    "bodega en {}",
    "cerveza local de {}",
    "dulces tipicos de {}",
    "postre tipico de {}",
    "ruta gastronómica en {}",
    "tour gastronómico en {}",
    "mercado gastronomico en {}",
    "food truck en {}",
    "street food en {}",
    "comida callejera en {}",
    "mercado de productores en {}",
    "mercado organico en {}",
    "tienda ecologica en {}",
    "restaurante organico en {}",
    "vegetariano en {}",
    "vegano en {}",
    "sin gluten en {}",
    "restaurante sin gluten en {}",
    "alergias alimentarias en {}",
    "halal en {}",
    "comida halal en {}",
    "kosher en {}",
    "restaurante con vistas al mar en {}",
    "chiringuito en {}",
    "merendero en {}",
    "asador en {}",
    "sidreria en {}",
    "enoteca de vinos en {}",
    "tasca en {}",
    "taberna en {}",
    "tasca tipica de {}",
    "taberna tipica de {}",
    "bar de vinos en {}",
    "enoteca en {}",
    "cerveceria en {}",
    "happy hour en {}",
    "vermut en {}",
    "aperitivo en {}",
    "tertulia en {}",
    "club de lectura en {}",
    "cinemateca de {}",
    "teatro municipal de {}",
    "opera en {}",
    "ballet en {}",
    "sala de conciertos en {}",
    "festival de cine en {}",
    "semana cultural de {}",
    "feria del libro en {}",
    "museo de bellas artes de {}",
    "museo arqueologico de {}",
    "museo etnografico de {}",
    "galeria municipal de {}",
    "palacio de exposiciones de {}",
    "centro de arte contemporaneo de {}",
    "fundacion cultural de {}",
    "patrimonio de la humanidad en {}",
    "sitio arqueologico en {}",
    "yacimiento arqueologico en {}",
    "ruinas romanas en {}",
    "castillos cerca de {}",
    "palacios en {}",
    "abadia en {}",
    "monasterio en {}",
    "convento en {}",
    "ermita en {}",
    "capilla en {}",
    "sinagoga en {}",
    "mezquita en {}",
    "templo en {}",
    "mikveh en {}",
    "necrópolis en {}",
    "cementerio historico de {}",
    "puente historico de {}",
    "acueducto de {}",
    "estadio de {}",
    "estadio de futbol en {}",
    "estadio de atletismo en {}",
    "estadio olimpico de {}",
    "pabellon deportivo de {}",
    "pista de hielo en {}",
    "bolera en {}",
    "minigolf en {}",
    "laser tag en {}",
    "paintball en {}",
    "karting en {}",
    "go kart en {}",
    "tirolina en {}",
    "toboganes acuaticos en {}",
    "parque acuatico cerca de {}",
    "parque de aventura en {}",
    "rocódromo en {}",
    "rafting en {}",
    "canoa en {}",
    "bautizo de buceo en {}",
    "buceo en {}",
    "snorkel en {}",
    "windsurf en {}",
    "kitesurf en {}",
    "esqui acuatico en {}",
    "pesca deportiva en {}",
    "cabalgata en {}",
    "equitacion en {}",
    "rutas a caballo en {}",
    "quad en {}",
    "moto de nieve en {}",
    "esqui en {}",
    "estacion de esqui cerca de {}",
    "forfait de esqui en {}",
    "snowboard en {}",
    "alquiler de esquis en {}",
    "monitor de esqui en {}",
    "clases de esqui en {}",
    "hospedaje de esqui en {}",
    "apres ski en {}",
    "golf en {}",
    "campo de golf en {}",
    "padel en {}",
    "tenis en {}",
    "pistas de padel en {}",
    "pistas de tenis en {}",
    "futbol sala en {}",
    "frontenis en {}",
    "pelota vasca en {}",
    "baloncesto en {}",
    "polideportivo en {}",
    "cicloturismo en {}",
    "mountain bike en {}",
    "ruta mtb en {}",
    "alquiler de bicicletas en {}",
    "via verde cerca de {}",
    "camino de santiago a {}",
    "camino de santiago por {}",
    "como llegar a {} en coche",
    "como llegar a {} en tren",
    "como llegar a {} en avion",
    "como llegar a {} en autobús",
    "aparcamiento gratuito cerca de {}",
    "zona azul de aparcamiento en {}",
    "zona verde de aparcamiento en {}",
    "parking disuasorio en {}",
    "estacion de autobuses de {}",
    "estacion de tren de {}",
    "terminal de autobuses de {}",
    "donde coger el tren en {}",
    "taxi desde {} al aeropuerto",
    "precio taxi en {}",
    "uber precio en {}",
    "rentalcar en {}",
    "alquiler de furgoneta en {}",
    "motorhome en {}",
    "autocaravana en {}",
    "area de autocaravanas en {}",
    "camping para autocaravanas en {}",
    "parcela en camping de {}",
    "gasolinera en {}",
    "cargador electrico en {}",
    "punto de recarga coches electricos en {}",
    "telefono de la policia de {}",
    "comisaria de {} numero de telefono",
    "bomberos de {}",
    "proteccion civil de {}",
    "ayuntamiento de {}",
    "oficina de turismo de {}",
    "consulado en {}",
    "embajada en {}",
    "notario en {}",
    "abogado en {}",
    "asesor fiscal en {}",
    "agencia de empleo en {}",
    "sepe en {}",
    "hacienda en {}",
    "registro civil de {}",
    "catastro de {}",
    "correos en {}",
    "oficina de correos en {}",
    "banco en {}",
    "cajero automatico en {}",
    "cambio de moneda en {}",
    "casa de cambio en {}",
    "supermercado en {}",
    "hipermercado en {}",
    "mercadona en {}",
    "lidl en {}",
    "carrefour en {}",
    "alcampo en {}",
    "mercado de frutas en {}",
    "fruteria en {}",
    "carniceria en {}",
    "pescaderia en {}",
    "ferreteria en {}",
    "bricolaje en {}",
    "ikea en {}",
    "mediamarkt en {}",
    "tienda de electronicos en {}",
    "fnac en {}",
    "el corte ingles en {}",
    "zara en {}",
    "mango en {}",
    "h&m en {}",
    "tienda de ropa en {}",
    "outlet de ropa en {}",
    "tienda de segunda mano en {}",
    "tienda de libros en {}",
    "libreria en {}",
    "papeleria en {}",
    "tintoreria en {}",
    "lavanderia en {}",
    "zapateria en {}",
    "relojeria en {}",
    "joyeria en {}",
    "optica en {}",
    "peluqueria en {}",
    "barberia en {}",
    "centro de estetica en {}",
    "uñas en {}",
    "micropigmentacion en {}",
    "tatuaje en {}",
    "piercing en {}",
    "dentista urgencias en {}",
    "guardia medica en {}",
    "ambulatorio en {}",
    "residencia de mayores en {}",
    "guarderia infantil en {}",
    "escuela infantil en {}",
    "ludoteca en {}",
    "parque infantil cubierto en {}",
    "clases de natacion en {}",
    "clases de danza en {}",
    "academias de musica en {}",
    "escuela de musica en {}",
    "clases de guitarra en {}",
    "clases de piano en {}",
    "academia de dibujo en {}",
    "taller de ceramica en {}",
    "taller de pintura en {}",
    "taller de fotografia en {}",
    "cursos de cocina en {}",
    "escuela de cocina en {}",
    "cursos de verano en {}",
    "actividades de verano en {}",
    "campus de verano en {}",
    "tiempo libre en {}",
    "que hacer un sabado en {}",
    "que hacer un domingo en {}",
    "planes en {} para este sabado",
    "planes en {} para este domingo",
    "agenda cultural de {}",
    "agenda de eventos de {}",
    "concierto gratuito en {}",
    "teatro gratuito en {}",
    "cine gratis en {}",
    "actividades gratuitas en {}",
    "museos gratuitos en {}",
    "dia gratis museos en {}",
    "entrada gratis en {}",
    "que hacer gratis en {}",
    "donde ir gratis en {}",
    "tematica de {} para niños",
    "parque natural de {}",
    "reserva natural cerca de {}",
    "avistamiento de aves en {}",
    "ornitologia en {}",
    "astronomia en {}",
    "observatorio cerca de {}",
    "tiempo atmosferico en {}",
    "flora y fauna de {}",
    "playas nudistas en {}",
    "playa tranquila en {}",
    "playa con bandera azul en {}",
    "playa de arena fina en {}",
    "playa familiar en {}",
    "playa de cala en {}",
    "acantilados en {}",
    "laguna en {}",
    "rio en {}",
    "lago en {}",
    "cascada cerca de {}",
    "volcán cerca de {}",
    "cuevas cerca de {}",
    "cueva turistica en {}",
    "dolmen cerca de {}",
    "megalito cerca de {}",
    "puente colgante en {}",
    "mirador de montaña en {}",
    "pico mas alto cerca de {}",
    "refugio de montaña en {}",
    "cabana de montaña en {}",
    "bodega enoturismo en {}",
    "degustacion de vinos en {}",
    "cata de vinos en {}",
    "tour de cervezas artesanas en {}",
    "como es vivir en {}",
    "vivir en {}",
    "mudarse a {}",
    "expatriados en {}",
    "comunidad extranjera en {}",
    "grupos de expatriados en {}",
    "es buena idea vivir en {}",
    "ventajas de vivir en {}",
    "inconvenientes de vivir en {}",
    "barrio tranquilo en {}",
    "barrio familiar en {}",
    "zona universitaria de {}",
    "zona de negocios de {}",
    "que barrio elegir en {}",
    "calidad de vida en {}",
    "indice de calidad de vida en {}",
    "contaminacion en {}",
    "calidad del aire en {}",
    "agua potable en {}",
    "infraestructuras de {}",
    "conexion a internet en {}",
    "fibra optica en {}",
    "operadores de telefonia en {}",
    "cobertura movil en {}",
    "comercios cerca de {} centro",
    "supermercados abiertos domingos en {}",
    "farmacias de guardia en {} hoy",
    "urgencias dentales en {}",
    "urgencias oftalmologicas en {}",
    "urgencias pediatricas en {}",
    "centros de salud en {}",
    "numero emergencias en {}",
    "linea de atencion al ciudadano en {}",
    "transporte adaptado en {}",
    "taxi adaptado en {}",
    "autobuses nocturnos en {}",
    "autobus de noche en {}",
    "metro 24 horas en {}",
    "cercanias en {}",
    "renfe en {}",
    "feve en {}",
    "bus de playa en {}",
    "bus turistico en {}",
    "tren turistico de {}",
    "visita en segway en {}",
    "tour en helicóptero en {}",
    "paseo en barco en {}",
    "crucero fluvial en {}",
    "crucero desde {}",
    "puerto de cruceros de {}",
    "porte maritimo de {}",
    "agencia de viajes en {}",
    "mayorista de viajes en {}",
    "oficina de turismo en {} telefono",
    "turismos de {}",
    "patronato de turismo de {}",
    "tarjeta turistica de {}",
    "city card de {}",
    "bono turístico de {}",
    "descuentos museos en {}",
    "pase de museos de {}",
    "guia de {} pdf",
    "foro de viajes sobre {}",
    "tripadvisor {}",
    "booking.com {}",
    "airbnb {}",
    "expedia {}",
    "viajeshalcon {}",
    "logitravel {}",
    "rumbo.es {}",
    "destinia {}",
    "skyscanner vuelos a {}",
    "kayak vuelos {}",
    "edreams vuelos {}",
    "clubmed {}",
    "viaje todo incluido a {}",
    "paquete turistico a {}",
    "oferta de viaje a {}",
    "vuelo mas hotel en {}",
    "vuelo mas coche en {}",
    "seguro de viaje para {}",
    "cuanto cuesta ir a {}",
    "presupuesto viaje a {}",
    "viaje a {} con poco dinero",
    "viaje barato a {}",
    "ahorro en viaje a {}",
    "tips para visitar {}",
    "errores al visitar {}",
    "cosas que no hacer en {}",
    "que no perderse en {}",
    "secretos de {}",
    "lugares ocultos de {}",
    "rincones secretos de {}",
    "instagram en {}",
    "fotos en {}",
    "lugares fotos bonitas en {}",
    "instagram worthy spots en {}",
    "lugares para fotos en {}",
    "atardecer en {}",
    "amanecer en {}",
    "mejor hora para visitar {}",
    "masas de agua en {}",
    "rio principal de {}",
    "lago mas grande de {}",
    "parque urbano de {}",
    "bosque urbano de {}",
    "ruta de senderismo urbana en {}",
    "sendero urbano en {}",
    "paseo fluvial de {}",
    "corredor verde de {}",
    "jardines de {} horario",
    "palacio botanico de {}",
    "vivero en {}",
    "huerto urbano en {}",
    "mercado de segunda mano en {}",
    "rastro en {}",
    "flea market en {}",
    "vintage market en {}",
    "tianguis en {}",
    "bazar en {}",
    "outlet online de {}",
    "descuentos en {} hoy",
    "liquidacion en {} tiendas",
    "ventas privadas en {}",
    "webs de descuentos en {}",
    "que pasa en {} hoy",
    "noticias de {}",
    "novedades en {}",
    "actualidad de {}",
    "periodico local de {}",
    "television local de {}",
    "radio local de {}",
    "podcast sobre {}",
    "blog de viajes sobre {}",
    "youtubers sobre {}",
    "influencers de {}",
    "comunidades vecinales en {}",
    "asociacion de vecinos de {}",
    "plataforma ciudadana de {}",
    "voluntariado en {}",
    "ong en {}",
    "grupos de meetup en {}",
    "deportes en {}",
    "equipo de futbol de {}",
    "partido de futbol en {} este fin de semana",
    "entradas futbol en {}",
    "liga local en {}",
    "eventos deportivos en {} este mes",
    "maraton de {}",
    "carrera popular en {}",
    "ciclomaraton en {}",
    "triathlon en {}",
    "piscina olimpica de {}",
    "piscina descubierta en {}",
    "palacio de deportes de {}",
    "multiusos en {}",
    "arena de {}",
    "recinto ferial de {}",
    "sala de exposiciones de {}",
    "palacio de congreso de {}",
    "sede de congreso en {}",
    "hotel de congreso en {}",
    "alojamiento para congreso en {}",
    "traslado congreso en {}",
    "alquiler sala de reuniones en {}",
    "alquiler sala de eventos en {}",
    "catering en {}",
    "empresa de catering en {}",
    "organizacion de eventos en {}",
    "wedding planner en {}",
    "lugar para celebrar boda en {}",
    "finca para eventos en {}",
    "salon de banquetes en {}",
    "celebraciones en {}",
    "cumpleaños infantil en {}",
    "comunion en {}",
    "despedida de soltera en {}",
    "despedida de soltero en {}",
    "team building en {}",
    "actividades para empresas en {}",
    "incentivos de empresa en {}",
    "hotel de empresa en {}",
    "restaurante de empresa en {}",
    "regalo tipico de {}",
    "artesania tipica de {}",
    "ceramica de {}",
    "tejidos de {}",
    "encajes de {}",
    "orfebreria de {}",
    "gastronomia tipica de {}",
    "conservas tipicas de {}",
    "embutidos de {}",
    "quesos de {}",
    "aceite de oliva de {}",
    "vino tipico de {}",
    "licor tipico de {}",
    "bebida tipica de {}",
    "dulce tradicional de {}",
    "dulce navideño de {}",
    "turron de {}",
    "mazapan de {}",
    "roscon de {}",
    "pan tipico de {}",
    "panaderia tipica de {}",
    "mercado navideño en {}",
    "belen viviente en {}",
    "luces de navidad en {}",
    "cabalgata de reyes en {}",
    "procesion de semana santa en {}",
    "cofradias de {}",
    "fiesta declarada de interes turistico en {}",
    "concurso gastronomico en {}",
    "feria gastronomica en {}",
    "semana de la gastronomia en {}",
]
