"""Listes de mots francaises pour le data poisoning (voir browser/decoy.py)."""

CITIES = [
    "paris", "marseille", "lyon", "toulouse", "nice", "nantes", "strasbourg",
    "montpellier", "bordeaux", "lille", "rennes", "reims", "saint-etienne",
    "toulon", "le havre", "grenoble", "dijon", "angers", "nimes", "villeurbanne",
    "saint-denis", "le mans", "aix-en-provence", "clermont-ferrand", "brest",
    "tours", "limoges", "amiens", "perpignan", "metz", "besancon", "boulogne-billancourt",
    "orleans", "mulhouse", "rouen", "caen", "nancy", "argenteuil", "montreuil",
    "roubaix", "dunkerque", "avignon", "poitiers", "versailles", "pau", "colombes",
    "saint-paul", "fort-de-france", "courbevoie", "vitry-sur-seine", "le tampon",
    "creil", "bourges", "tourcoing", "asnieres-sur-seine", "saint-nazaire",
    "calais", "valenciennes", "quimper", "cannes", "lorient", "antibes",
    "la rochelle", "saint-quentin", "champigny-sur-marne", "aubervilliers",
    "noisy-le-grand", "issy-les-moulineaux", "troyes", "creteil", "rueil-malmaison",
    "nanterre", "aulnay-sous-bois", "vitrolles", "levallois-perret", "la seyne-sur-mer",
    "beziers", "merignac", "hyeres", "saint-maur-des-fosses", "boulogne-sur-mer",
    "perpignan", "montrouge", "annecy", "drancy", "compiegne", "belfort", "venissieux",
    "noisiel", "cergy", "ajaccio", "pau", "bayonne", "la roche-sur-yon", "chalon-sur-saone",
    "cherbourg", "vannes", "laval", "chambery", "chartres", "valence", "sarcelles",
    "caluire-et-cuire", "evreux", "pont-a-mousson", "colmar", "thionville",
    "epinal", "saint-brieuc", "macon", "saint-malo", "frejus", "saint-nicolas-de-la-grave",
    "arras", "chalons-en-champagne", "albi", "cholet", "clichy", "montelimar",
    "villeneuve-d-ascq", "fontenay-sous-bois", "ivry-sur-seine", "saint-germain-en-laye",
    "brive-la-gaillarde", "la courneuve", "angouleme", "sartrouville", "pontoise",
    "roanne", "niort", "lorient", "albi", "tarbes", "gap", "rodez", "mende",
    "auxerre", "sens", "soissons", "saint-omer", "le puy-en-velay", "gueret",
    "tulle", "aurillac", "privas", "foix", "digne-les-bains", "moulins", "nevers",
    "vesoul", "lons-le-saunier", "bar-le-duc", "saint-lo", "laon", "beauvais",
    "coutances", "chaumont", "agen", "mont-de-marsan", "auch", "cahors", "montauban",
    "perigueux", "sarlat", "figeac", "bergerac", "marmande", "villeneuve-sur-lot",
    "biarritz", "hendaye", "saint-jean-de-luz", "arcachon", "cap-ferret",
    "saint-jean-pied-de-port", "lourdes", "luz-saint-sauveur", "cauterets",
    "bordeaux", "cognac", "rochefort", "saintes", "royan", "la tremblade",
    "ile de re", "noirmoutier", "les sables-d-olonne", "saint-gilles-croix-de-vie",
    "pornic", "saint-nazaire", "guerande", "la baule", "vittel", "epernay",
    "bar-sur-aube", "troyes", "provins", "fontainebleau", "milly-la-foret",
    "melun", "corbeil-essonnes", "evry", "cergy-pontoise", "saint-quentin-en-yvelines",
    "versailles", "rambouillet", "chartres", "dreux", "nogent-le-rotrou",
    "chateaudun", "vendome", "blois", "tours", "amboise", "chinon", "saumur",
    "angers", "cholet", "thouars", "bressuire", "parthenay", "poitiers", "chatellerault",
    "châteauroux", "issoudun", "bourges", "vierzon", "mehun-sur-yevre",
    "macon", "chalon-sur-saone", "autun", "le creusot", "montceau-les-mines",
    "dijon", "beaune", "nuits-saint-georges", "gevrey-chambertin", "cluny",
    "bourg-en-bresse", "oyonnax", "saint-claude", "gex", "ferney-voltaire",
    "thonon-les-bains", "evian-les-bains", "annecy", "chambery", "aix-les-bains",
    "grenoble", "voiron", "vienne", "valence", "romans-sur-isere", "drome",
    "montelimar", "orange", "carpentras", "apt", "pertuis", "aix-en-provence",
    "marseille", "aubagne", "cassis", "la ciotat", "toulon", "hyeres", "frejus",
    "draguignan", "brignoles", "saint-raphael", "sainte-maxime", "saint-tropez",
    "grasse", "cannes", "antibes", "nice", "menton", "monaco",
    "bastia", "corte", "calvi", "bonifacio", "porto-vecchio",
    "new york", "los angeles", "chicago", "houston", "miami", "san francisco",
    "las vegas", "seattle", "boston", "washington", "philadelphie", "denver",
    "atlanta", "dallas", "austin", "portland", "nashville", "new orleans",
    "minneapolis", "detroit", "phoenix", "san diego", "orlando", "tampa",
    "toronto", "montreal", "vancouver", "calgary", "ottawa", "quebec",
    "mexique", "guadalajara", "monterrey", "cancun", "acapulco", "puebla",
    "bogota", "medellin", "cali", "cartagene", "lima", "cusco", "arequipa",
    "buenos aires", "cordoba", "rosario", "mendoza", "santiago du chili",
    "valparaiso", "sao paulo", "rio de janeiro", "brasilia", "salvador",
    "belo horizonte", "fortaleza", "recife", "porto alegre", "manaus",
    "montevideo", "asuncion", "la paz", "quito", "caracas", "georgetown",
    "paramaribo", "cayenne", "bridgetown", "port-au-prince", "kingston",
    "la havane", "saint-domingue", "san jose", "panama", "managua",
    "tegucigalpa", "guatemala", "san salvador", "belize",
    "londres", "manchester", "birmingham", "liverpool", "leeds", "glasgow",
    "edimbourg", "cardiff", "bristol", "sheffield", "cambridge", "oxford",
    "newcastle", "nottingham", "leicester", "southampton", "brighton",
    "berlin", "munich", "hambourg", "cologne", "francfort", "stuttgart",
    "dusseldorf", "dortmund", "essen", "leipzig", "dresde", "nuremberg",
    "breme", "hanovre", "mannheim", "augsbourg", "wiesbaden", "heidelberg",
    "vienne", "salzbourg", "innsbruck", "graz", "linz", "klagenfurt",
    "zurich", "geneve", "berne", "bale", "lausanne", "lucerne", "lugano",
    "amsterdam", "rotterdam", "la haye", "utrecht", "eindhoven", "groningue",
    "bruxelles", "anvers", "gand", "bruges", "liege", "namur", "charleroi",
    "luxembourg", "madrid", "barcelone", "valence", "seville", "saragosse",
    "malaga", "murcie", "palma de majorque", "bilbao", "alicante", "cordoue",
    "valladolid", "vigo", "gijon", "grenade", "la corogne", "ibiza",
    "milan", "rome", "naples", "turin", "palerme", "genes", "florence",
    "venise", "bologne", "catane", "verone", "trieste", "bari", "padoue",
    "brescia", "modene", "reggio de calabre", "perouse", "pise", "ravenne",
    "lisbonne", "porto", "braga", "coimbra", "faro", "funchal", "setubal",
    "oslo", "bergen", "trondheim", "stavanger", "tromso",
    "stockholm", "gothenburg", "malmoe", "uppsala", "linkoping",
    "copenhague", "aarhus", "odense", "aalborg",
    "helsinki", "tampere", "turku", "espoo",
    "reykjavik", "tallinn", "riga", "vilnius",
    "varsovie", "cracovie", "gdansk", "wroclaw", "poznan", "lodz",
    "prague", "brno", "ostrava", "plzen",
    "budapest", "debrecen", "miskolc", "pecs",
    "bucarest", "cluj-napoca", "timisoara", "iasi", "constanta",
    "sofia", "plovdiv", "varna", "burgas",
    "athenes", "thessalonique", "patras", "heraklion", "rhodes",
    "zagreb", "split", "rijeka", "dubrovnik", "sarajevo", "belgrade",
    "skopje", "tirana", "podgorica", "pristina", "ljubljana",
    "bratislava", "minsk", "kiev", "kharkiv", "odessa", "lviv",
    "moscou", "saint-petersbourg", "novosibirsk", "ekaterinbourg",
    "kazan", "nijni novgorod", "tcheliabinsk", "omsk", "samara", "ростов",
    "istanbul", "ankara", "izmir", "bursa", "antalya", "konya", "adana",
    "le caire", "alexandrie", "casablanca", "rabat", "marrakech", "fes",
    "tanger", "agadir", "meknes", "tunis", "sfax", "sousse", "bizerte",
    "alger", "oran", "constantine", "annaba", "tlemcen", "blida",
    "tripoli", "benghazi", "khartoum", "addis-abeba", "nairobi",
    "dar es-salaam", "kampala", "kinshasa", "lagos", "abuja", "accra",
    "abidjan", "dakar", "bamako", "ouagadougou", "niamey", "lome",
    "conakry", "freetown", "monrovia", "yamoussoukro", "libreville",
    "douala", "yaounde", "brazzaville", "luanda", "maputo",
    "harare", "lusaka", "lilongwe", "windhoek", "gaborone",
    "johannesburg", "le cap", "durban", "pretoria", "port elizabeth",
    "antananarivo", "port-louis", "victoria", "moroni",
    "dubai", "abu dhabi", "doha", "manama", "mascate", "kuweit",
    "riyad", "djeddah", "la mecque", "beyrouth", "amman", "damas",
    "bagdad", "bassorah", "erbil", "tehran", "ispahan", "chiraz",
    "kaboul", "islamabad", "karachi", "lahore", "faisalabad", "rawalpindi",
    "mumbai", "delhi", "bangalore", "hyderabad", "chennai", "calcutta",
    "pune", "ahmedabad", "surat", "jaipur", "lucknow", "kanpur",
    "nagpur", "indore", "thane", "bhopal", "visakhapatnam", "pattna",
    "katmandou", "dhaka", "chittagong", "rangoun", "colombo", "male",
    "bangkok", "phuket", "chiang mai", "pattaya", "ayutthaya",
    "kuala lumpur", "penang", "johor bahru", "kota kinabalu",
    "singapour", "jakarta", "surabaya", "bandung", "medan", "semarang",
    "manille", "cebu", "davao", "quezon",
    "ho chi minh ville", "hanoi", "da nang", "hue", "hoi an",
    "phnom penh", "siem reap", "vientiane", "luang prabang",
    "pekin", "shanghai", "guangzhou", "shenzhen", "chengdu", "chongqing",
    "wuhan", "tianjin", "xian", "nankin", "hangzhou", "shenyang",
    "harbin", "qingdao", "dalian", "kunming", "jinan", "zhengzhou",
    "taipei", "kaohsiung", "taichung",
    "tokyo", "osaka", "kyoto", "hiroshima", "nagoya", "sapporo",
    "fukuoka", "kobe", "yokohama", "sendai", "nara",
    "seoul", "busan", "incheon", "daegu", "daejeon", "gwangju",
    "ulaanbaatar", "almaty", "astana", "tachkent", "bichkek", "douchanbe",
    "sydney", "melbourne", "brisbane", "perth", "adélaïde", "canberra",
    "auckland", "wellington", "christchurch", "queenstown",
    "honolulu", "anchorage", "juneau", "fairbanks",
    "saint-martin", "guadeloupe", "martinique", "guyane", "reunion",
    "mayotte", "saint-barthelemy", "saint-pierre-et-miquelon",
    "tahiti", "papeete", "noumea", "wallis", "futuna",
]

TEMPLATES = [
    "meteo {} aujourd'hui",
    "meteo {} demain",
    "meteo {} ce week-end",
    "meteo {} cette semaine",
    "meteo {} en juillet",
    "temperature {} en aout",
    "previsions meteo {} 7 jours",
    "meteo {} en temps reel",
    "hotel pas cher {}",
    "meilleur hotel {}",
    "hotel 4 etoiles {}",
    "hotel avec piscine {}",
    "auberge de jeunesse {}",
    "airbnb {}",
    "location appartement {}",
    "chambre hote {}",
    "location vacances {}",
    "camping {}",
    "villa a louer {}",
    "hotel spa {}",
    "meilleur restaurant {}",
    "restaurant pas cher {}",
    "restaurant vegetarien {}",
    "restaurant vegan {}",
    "restaurant gastronomique {}",
    "brasserie {}",
    "restaurant italien {}",
    "sushi {}",
    "pizza {}",
    "burger {}",
    "restaurant halal {}",
    "petit dejeuner {}",
    "brunch {}",
    "terrasse restaurant {}",
    "restaurant vue mer {}",
    "street food {}",
    "marche alimentaire {}",
    "vol pas cher pour {}",
    "vol direct {}",
    "billet avion {}",
    "train {}",
    "bus {}",
    "location voiture {}",
    "navette aeroport {}",
    "taxi {}",
    "covoiturage {}",
    "comment aller a {}",
    "transport en commun {}",
    "metro {}",
    "tramway {}",
    "velo en libre service {}",
    "que faire a {}",
    "visiter {}",
    "incontournables {}",
    "tourisme {}",
    "activites {}",
    "musees {}",
    "galeries art {}",
    "parcs {}",
    "plages {}",
    "randonnee {}",
    "balade {}",
    "excursions depuis {}",
    "centre historique {}",
    "vieille ville {}",
    "monuments {}",
    "chateaux {}",
    "quartiers a visiter {}",
    "nightlife {}",
    "bars {}",
    "clubs {}",
    "concerts {}",
    "sortir ce soir {}",
    "vie nocturne {}",
    "discoteque {}",
    "evenements {} ce week-end",
    "agenda {} ce mois",
    "festivals {}",
    "spectacles {}",
    "theatre {}",
    "cinema {}",
    "shopping {}",
    "centres commerciaux {}",
    "marche {}",
    "brocante {}",
    "artisanat local {}",
    "souvenirs {}",
    "boutiques {}",
    "appartement a louer {}",
    "appartement a acheter {}",
    "prix immobilier {}",
    "agence immobiliere {}",
    "studio a louer {}",
    "maison a vendre {}",
    "emploi {}",
    "recrutement {}",
    "offres emploi {}",
    "travailler a {}",
    "salaire moyen {}",
    "entreprises {}",
    "freelance {}",
    "universite {}",
    "ecoles {}",
    "lycee {}",
    "formations {}",
    "campus {}",
    "etudier a {}",
    "ecole de commerce {}",
    "ecole ingenieur {}",
    "stationnement {}",
    "parking {}",
    "trafic {}",
    "embouteillages {}",
    "code postal {}",
    "plan {}",
    "carte {}",
    "distance entre paris et {}",
    "population {}",
    "histoire {}",
    "fuseau horaire {}",
    "medecin {}",
    "hopital {}",
    "pharmacie {}",
    "urgences {}",
    "clinique {}",
    "dentiste {}",
    "veterinaire {}",
    "salle de sport {}",
    "piscine {}",
    "terrain de foot {}",
    "yoga {}",
    "pilates {}",
    "coworking {}",
    "espace de travail {}",
    "cafe avec wifi {}",
    "bibliotheque {}",
    "parc naturel {}",
    "zoo {}",
    "aquarium {}",
    "parc attraction {}",
    "jardin botanique {}",
    "que voir a {} en famille",
    "week-end a {}",
    "sejour a {}",
    "visite guidee {}",
    "guide touristique {}",
    "bon plan {}",
    "itineraire {}",
    "3 jours a {}",
    "vivre a {}",
    "temoignage vie a {}",
    "securite {}",
    "quartiers dangereux {}",
    "quartiers tranquilles {}",
    "cout de la vie {}",
    "expatrie {}",
    "retraite {}",
    "demenager {}",
    "meilleure periode visiter {}",
    "quand partir a {}",
    "crue inondation {}",
    "canicule {}",
    "neige {}",
    "surf {}",
    "escalade {}",
    "ski {}",
    "vtt {}",
    "kayak {}",
    "plongee {}",
    "snorkeling {}",
    "parachutisme {}",
    "bateau {}",
    "croisiere {}",
    "gastronomie {}",
    "specialites culinaires {}",
    "vin {}",
    "biere locale {}",
    "cocktail bar {}",
    "cave a vin {}",
    "chocolaterie {}",
    "patisserie {}",
    "boulangerie {}",
    "fromagerie {}",
    "marche fermier {}",
    "produits locaux {}",
    "traiteur {}",
    "livraison repas {}",
    "spa {}",
    "massage {}",
    "bien-etre {}",
    "thermes {}",
    "thalassotherapie {}",
    "retraite bien-etre {}",
    "camping car {}",
    "aire camping car {}",
    "glamping {}",
    "lodge {}",
    "ecolodge {}",
    "maison arbre {}",
    "cabane {}",
    "gite {}",
    "ferme pedagogique {}",
    "vignoble {}",
    "cave visite {}",
    "degustation {}",
    "marche noel {}",
    "animations enfants {}",
    "atelier enfants {}",
    "aire de jeux {}",
    "parc pour enfants {}",
    "musee enfants {}",
    "ecole primaire {}",
    "creche {}",
    "garde enfants {}",
    "colonie vacances {}",
    "chien accepte {}",
    "hotel animaux {}",
    "promenade chien {}",
    "veterinaire urgence {}",
    "stade {}",
    "match {}",
    "billet match {}",
    "galerie marchande {}",
    "outlet {}",
    "librairie {}",
    "maison disques {}",
    "tatoueur {}",
    "coiffeur {}",
    "barbier {}",
    "photographe {}",
    "studio photo {}",
    "mariage {}",
    "salle mariage {}",
    "traiteur mariage {}",
    "fleuriste {}",
    "cimetiere {}",
    "mairie {}",
    "consulat {}",
    "ambassade {}",
    "office tourisme {}",
    "point info {}",
    "visas {}",
    "formalites {}",
    "assurance voyage {}",
    "pharmacie de garde {}",
    "nuit a {} pas cher",
    "dormir a {}",
    "hebergement {}",
    "routard {}",
    "avis {}",
    "tripadvisor {}",
    "note hotel {}",
]

STANDALONE = [
    "comment apprendre python en 2026",
    "meilleur langage programmation debutant",
    "tuto javascript gratuit",
    "cours html css en ligne",
    "apprendre linux commandes",
    "differrence entre python 2 et python 3",
    "comment installer docker",
    "git commandes de base",
    "meilleur editeur de code gratuit",
    "vs code vs pycharm comparatif",
    "comment creer un site web",
    "hebergement web pas cher",
    "wordpress vs wix comparatif",
    "comment faire un blog en 2026",
    "reseaux de neurones explication simple",
    "intelligence artificielle comment ca marche",
    "chatgpt vs gemini comparatif 2026",
    "meilleur vpn 2026",
    "antivirus gratuit recommande",
    "comment proteger sa vie privee en ligne",
    "navigateur internet le plus rapide",
    "extensions chrome utiles",
    "comment bloquer les pubs",
    "youtube sans pub solution",
    "comment telecharger videos youtube",
    "convertir mp4 en mp3 gratuit",
    "meilleur logiciel montage video gratuit",
    "davinci resolve tuto debutant",
    "photoshop alternative gratuite",
    "gimp tuto retouche photo",
    "meilleur smartphone 2026",
    "samsung galaxy s25 avis",
    "iphone 17 date sortie prix",
    "comparatif telephone milieu de gamme",
    "meilleure tablette android",
    "coque telephone resistant",
    "chargeur rapide universel",
    "ecouteurs sans fil moins de 100 euros",
    "airpods alternative pas chere",
    "montre connectee sport",
    "smartwatch sommeil qualite",
    "meilleur casque gamer",
    "clavier mecanique silencieux",
    "souris ergonomique bureau",
    "ecran pc 4k pas cher",
    "disque dur externe 2 to",
    "cle usb rapide 128 go",
    "routeur wifi 6 maison",
    "comment ameliorer wifi maison",
    "repeteur wifi ou mesh comparatif",
    "nas synology tuto",
    "sauvegarde automatique ordinateur",
    "comment nettoyer son pc",
    "pc qui chauffe trop solution",
    "windows 11 lent solution",
    "comment reinitialiser windows 11",
    "migrer vers linux ubuntu",
    "dualboot windows linux",
    "recette carbonara authentique",
    "recette gateau au chocolat moelleux",
    "recette tarte tatin",
    "comment faire de la brioche maison",
    "recette curry poulet facile",
    "recette ramen maison",
    "recette sushi maison",
    "recette tiramisu original",
    "recette creme brulee",
    "recette couscous traditionnel",
    "recette tajine poulet citron",
    "recette moussaka grecque",
    "comment faire du pain au levain",
    "levain pain maison comment commencer",
    "recette cookies moelleux",
    "recette crepes legeres",
    "recette quiche lorraine",
    "recette soupe miso",
    "recette smoothie banane",
    "petit dejeuner sain et rapide",
    "repas sain semaine preparation",
    "meal prep debutant",
    "regime cetogene debutant",
    "regime intermittent comment commencer",
    "calories journalieres calcul",
    "comment perdre du ventre",
    "exercice maison sans materiel",
    "programme musculation debutant",
    "comment prendre de la masse musculaire",
    "proteine apres sport combien",
    "meilleure proteine en poudre",
    "creatine comment prendre",
    "yoga debutant matin routine",
    "pilates programme semaine",
    "course a pied debutant programme",
    "comment courir sans se blesser",
    "courbatures apres sport remede",
    "etirements apres musculation",
    "sommeil comment ameliorer",
    "insomnie remede naturel",
    "melatonine efficace ou pas",
    "meditation pour dormir",
    "applications meditation gratuite",
    "stress au travail gestion",
    "burnout symptomes",
    "anxiete remede naturel",
    "psychologue ou psychiatre difference",
    "therapie en ligne avis",
    "hypnose sommeil efficace",
    "impots 2026 declaration en ligne",
    "date limite declaration impots 2026",
    "comment remplir sa declaration impots",
    "credit impot travaux maison",
    "prime energie renovation 2026",
    "aides logement 2026",
    "caf simulation aide",
    "allocations familiales montant 2026",
    "apl calcul simulation",
    "pret immobilier taux 2026",
    "simulation credit immobilier",
    "apport minimum maison",
    "investissement locatif debutant",
    "lmnp statut avantages",
    "pinel 2026 encore valable",
    "bourse investir comment commencer",
    "etf sp500 comment acheter",
    "cryptomonnaie bitcoin 2026",
    "compte epargne meilleur taux 2026",
    "livret a taux actuel",
    "assurance vie comparatif",
    "mutuelle sante comparatif",
    "complementaire sante pas chere",
    "comment resilier une assurance",
    "salaire net brut convertir",
    "prime macron 2026",
    "conge parental duree",
    "rupture conventionnelle demarches",
    "chomage calcul montant",
    "auto-entrepreneur demarches 2026",
    "micro-entreprise charges",
    "facturer en freelance",
    "apprendre la guitare debutant",
    "accord guitare facile",
    "solfege bases",
    "piano debutant tuto",
    "clavier midi pas cher",
    "logiciel composition musicale gratuit",
    "audacity tuto enregistrement",
    "photographie debutant reglages",
    "regles composition photo",
    "lightroom tuto retouche",
    "appareil photo mirrorless debutant",
    "objectif portrait prix",
    "trouver son style photo",
    "instagram algorithme 2026",
    "comment avoir plus abonnes instagram",
    "tiktok technique montage",
    "youtube monetisation comment",
    "streaming twitch debutant",
    "jeux video ps5 sortie 2026",
    "meilleur jeu ps5 2026",
    "jeux pc configuration requise",
    "steam soldes prochains",
    "epic games jeux gratuits",
    "minecraft serveur creer",
    "elden ring guide debutant",
    "baldurs gate 3 tuto",
    "jeux retro emulateur",
    "switch 2 avis",
    "jardinage debutant conseil",
    "plantes d interieur facile entretien",
    "potager balcon comment faire",
    "engrais naturel jardin",
    "compostage maison tuto",
    "permaculture principe",
    "couture debutant machine",
    "tricot apprendre",
    "broderie debutant",
    "origami facile",
    "poterie debutant cours",
    "peinture aquarelle technique",
    "dessin anatomie tuto",
    "illustration numerique ipad",
    "procreate tuto debutant",
    "3d impression filament",
    "imprimante 3d pas chere 2026",
    "arduino debutant tuto",
    "raspberry pi projet",
    "electronique debutant composants",
    "soudure electronique tuto",
    "reparation telephone ecran",
    "changer batterie telephone",
    "bricolage prise electrique",
    "installer une prise murale",
    "peindre son appartement conseil",
    "poser du carrelage soi meme",
    "monter un meuble ikea",
    "declutter maison methode",
    "rangement petit appartement",
    "deco salon tendance 2026",
    "tapis salon choix",
    "canape convertible qualite prix",
    "luminaire design pas cher",
    "plante interieur lumiere faible",
    "diffuseur huile essentielle avis",
    "purificateur air maison",
    "comment vivre plus ecologique",
    "zero dechet tuto debutant",
    "reduire plastique maison",
    "voiture electrique cout reel",
    "autonomie voiture electrique hiver",
    "borne recharge maison installation",
    "velo electrique comparatif 2026",
    "velo cargo famille",
    "trottinette electrique fiable",
    "covoiturage longue distance",
    "comment apprendre l espagnol rapidement",
    "apprendre l anglais adulte",
    "duolingo efficace ou pas",
    "apprendre le japonais",
    "dictionnaire francais anglais en ligne",
    "traduire document en ligne gratuit",
    "deepl vs google translate",
    "histoire de france resume",
    "revolution francaise causes",
    "premiere guerre mondiale resumee",
    "deuxieme guerre mondiale chronologie",
    "exoplanetes decouverte 2026",
    "trou noir explication simple",
    "james webb telescope images",
    "mission mars 2026",
    "climat rechauffement solutions",
    "energie solaire panneaux maison cout",
    "pompe a chaleur subvention 2026",
    "isolation maison aides",
    "changement chaudiere prime 2026",
    "serie netflix recommandee",
    "meilleure serie 2026",
    "film action sortie 2026",
    "film horreur liste",
    "anime a regarder",
    "manga debutant par quoi commencer",
    "livre policier recommande",
    "roman science fiction classique",
    "podcast francais recommande",
    "documentaire nature netflix",
    "sport ligue 1 classement 2026",
    "champions league resultats",
    "tour de france 2026 parcours",
    "tennis roland garros 2026",
    "formule 1 calendrier 2026",
    "jeux olympiques 2026",
    "nba playoffs 2026",
    "basket france calendrier",
    "rugby top 14 classement",
    "xv de france prochains matchs",
    "chien race familiale",
    "chat race appartement",
    "veterinaire tarif consultation",
    "alimentation chien maison",
    "chien formation debutant",
    "aquarium eau douce debutant",
    "lapin nain soin",
    "comment faire un cv en 2026",
    "lettre motivation exemple",
    "entretien embauche conseils",
    "linkedin optimiser profil",
    "reconversion professionnelle comment",
    "formation en ligne certifiante",
    "openclassrooms avis",
    "coursera diplome reconnu",
    "alternance 2026 trouver",
    "stage obligatoire trouver",
    "sante mentale ressources gratuites",
    "solitude comment gerer",
    "confiance en soi developper",
    "habitudes positives comment creer",
    "productivite matin routine",
    "pomodoro methode tuto",
    "prise de notes efficace",
    "notion tuto debutant",
    "obsidian prise notes",
    "organisation agenda",
    "comment creer une application mobile",
    "react native vs flutter comparatif",
    "swift debutant ios",
    "kotlin android tuto",
    "api rest comment ca marche",
    "json xml difference",
    "base de donnees sql debutant",
    "postgresql vs mysql comparatif",
    "mongodb tuto debutant",
    "cloud aws azure google comparatif",
    "devops kesako explication",
    "docker compose tuto",
    "kubernetes debutant",
    "cybersecurite debutant formation",
    "phishing comment reconnaitre",
    "mot de passe fort generateur",
    "gestionnaire de mots de passe",
    "vpn gratuit ou payant",
    "dark web explication",
    "blockchain explication simple",
    "nft encore utile 2026",
    "chatgpt pour travailler",
    "ia generative image gratuit",
    "stable diffusion tuto",
    "midjourney abonnement prix",
    "comment faire un podcast",
    "micro podcast qualite prix",
    "enregistrement voix off tuto",
    "youtube shorts algorithme",
    "montage video telephone",
    "capcut tuto debutant",
    "premiere pro vs davinci resolve",
    "after effects tuto motion design",
    "canva pro vaut il le coup",
    "design logo gratuit",
    "figma tuto interface",
    "ux ui design apprendre",
    "typographie conseil",
    "couleurs site web choisir",
]
