"""Recherches autonomes francaises (vie quotidienne) pour le data poisoning."""

STANDALONE = [
    "comment faire une quiche lorraine",
    "recette tiramisu facile",
    "comment faire du pain maison",
    "recette gateau au chocolat moelleux",
    "comment faire des crepes",
    "recette ratatouille traditionnelle",
    "comment faire un risotto cremeux",
    "recette soupe a l'oignon gratinee",
    "comment faire des macarons",
    "recette tarte tatin",
    "comment faire un boeuf bourguignon",
    "recette moules mariniere",
    "comment faire un gratin dauphinois",
    "recette coq au vin",
    "comment faire une mousse au chocolat",
    "recette blanquette de veau",
    "comment faire du pain au levain",
    "recette clafoutis aux cerises",
    "comment faire une tarte aux pommes",
    "recette pot au feu traditionnel",
    "comment faire des eclairs au chocolat",
    "recette canard a l'orange",
    "comment faire un fondant au chocolat",
    "recette cassoulet maison",
    "comment faire des profiteroles",
    "recette bouillabaisse",
    "comment faire une creme brulee",
    "recette lapin a la moutarde",
    "comment faire du fromage blanc maison",
    "recette tarte aux fraises",
    "comment faire du yaourt maison sans yaourtiere",
    "recette madeleines moelleuses",
    "comment faire une bechamel parfaite",
    "recette poulet roti croustillant",
    "comment faire des croissants maison",
    "recette cake au citron",
    "comment faire une sauce hollandaise",
    "recette far breton",
    "comment faire des ravioles maison",
    "recette charlotte aux fraises",
    "comment faire un gateau basque",
    "recette kouign amann",
    "comment faire du nougat maison",
    "recette quenelles de brochet",
    "comment faire des financiers",
    "recette tarte au citron meringuee",
    "comment faire un pain de campagne",
    "recette sole meuniere",
    "comment faire des tuiles aux amandes",
    "recette pissaladiere nicoise",
    "comment faire une galette des rois",
    "recette buche de noel maison",
    "comment faire du sirop de sucre",
    "recette salade nicoise authentique",
    "comment faire des gougeres",
    "recette terrine de foie gras",
    "comment faire un gateau d'anniversaire",
    "recette tapenade maison",
    "comment faire du confit de canard",
    "recette saucisson brioché",
    "comment faire une fondue savoyarde",
    "recette raclette originale",
    "comment faire un soufflet au fromage",
    "recette brandade de morue",
    "comment faire des crepes suzette",
    "recette vichyssoise froide",
    "comment faire du caramel liquide",
    "recette pain perdu avec brioche",
    "comment faire une flamiche",
    "recette andouillette a la moutarde",
    "comment faire un gratin de poireaux",
    "recette tartiflette maison",
    "comment faire du chutney maison",
    "recette pate a choux inratable",
    "comment faire des beignets de carnaval",
    "recette gateau breton",
    "comment faire une tarte flambee",
    "recette poulet a la normande",
    "comment faire du boudin blanc maison",
    "recette creme caramel maison",
    "comment calculer les calories journalieres",
    "regime sans gluten par ou commencer",
    "aliments riches en proteines naturellement",
    "pourquoi manger des fibres est important",
    "difference entre glucides simples et complexes",
    "comment reduire le sel dans l'alimentation",
    "aliments anti-inflammatoires liste complete",
    "regime mediterraneen principe de base",
    "comment se sevrer du sucre progressivement",
    "vitamines essentielles et leurs sources alimentaires",
    "pourquoi boire suffisamment d'eau chaque jour",
    "omega 3 ou les trouver dans l'alimentation",
    "comment faire un jeune intermittent",
    "aliments riches en fer pour anemie",
    "regime cetogene avantages et inconvenients",
    "comment maigrir sans se priver",
    "nutrition sportive avant et apres l'effort",
    "comment equilibrer son alimentation au quotidien",
    "superaliments vraiment utiles ou marketing",
    "comment augmenter sa consommation de legumes",
    "probiotiques bienfaits et sources naturelles",
    "comment lire une etiquette nutritionnelle",
    "alimentation pour ameliorer le cholesterol",
    "comment manger sainement avec un petit budget",
    "differences entre graisses saturees et insaturees",
    "comment stopper les grignotages compulsifs",
    "alimentation anti-acne que manger",
    "comment preparer des repas sains en avance",
    "meal prep facile pour la semaine",
    "pourquoi je mange trop le soir",
    "que manger avant une randonnee",
    "alimentation pour renforcer le systeme immunitaire",
    "comment digerer plus vite apres un repas lourd",
    "que manger quand on est fatigue",
    "symptomes carence en vitamine d",
    "comment reconnaitre une appendicite",
    "que faire contre une migraine intense",
    "symptomes de diabete de type 2",
    "comment soigner une angine sans antibiotiques",
    "que faire contre des brulures d'estomac",
    "symptomes d'une hernie discale",
    "comment soulager une sciatique naturellement",
    "que faire contre l'insomnie chronique",
    "symptomes d'une thyroide qui fonctionne mal",
    "comment soigner un rhume rapidement",
    "que faire contre un zona douloureux",
    "symptomes d'une allergie alimentaire",
    "comment reduire la tension arterielle naturellement",
    "que faire contre le syndrome du colon irritable",
    "symptomes d'une depression legere",
    "comment soigner une tendinite rapidement",
    "que faire contre les vertiges persistants",
    "symptomes d'une sinusite chronique",
    "comment soigner un eczema naturellement",
    "que faire contre le ronflement",
    "symptomes d'une carence en magnesium",
    "comment soigner une otite sans ordonnance",
    "que faire contre la constipation chronique",
    "symptomes d'un reflux gastro-oesophagien",
    "comment soulager les douleurs menstruelles",
    "que faire contre les acouphenes",
    "symptomes d'un burnout professionnel",
    "comment soigner des varices naturellement",
    "que faire contre les crampes nocturnes",
    "symptomes d'une intolerance au lactose",
    "comment traiter un psoriasis naturellement",
    "que faire contre la fatigue chronique",
    "symptomes d'une arthrose des genoux",
    "comment soigner une plaie infectee",
    "que faire contre les nausees du matin",
    "symptomes d'une crise d'anxiete",
    "comment soigner une entorse de cheville",
    "que faire contre les douleurs articulaires",
    "pourquoi j'ai toujours froid",
    "que faire contre la chute des cheveux",
    "symptomes d'une infection urinaire",
    "comment renforcer ses muscles rapidement",
    "programme musculation debutant a la maison",
    "meilleur exercice pour perdre du ventre",
    "comment commencer la course a pied",
    "yoga pour debutants quels postures",
    "comment ameliorer son endurance cardiovasculaire",
    "exercices de gainage efficaces",
    "comment se remettre au sport apres une pause",
    "natation brasses crawl differences",
    "comment eviter les courbatures apres le sport",
    "stretching efficace avant et apres sport",
    "programme hiit pour bruler des graisses",
    "comment ameliorer sa souplesse rapidement",
    "exercices pour soulager le mal de dos",
    "marche nordique bienfaits et technique",
    "comment progresser en velo de route",
    "musculation sans materiel exercices complets",
    "comment rester motive pour faire du sport",
    "pilates differences avec le yoga",
    "exercices pour les personnes agees",
    "comment reprendre le sport apres une blessure",
    "programme de course 5 km debutant",
    "exercices de respiration pour le sport",
    "comment ameliorer sa posture au bureau",
    "natation quel style pour maigrir",
    "exercices abdominaux sans se faire mal au dos",
    "comment progresser en musculation",
    "sport pendant grossesse conseils",
    "comment dormir mieux naturellement",
    "pourquoi je me reveille toujours a 3h du matin",
    "routine du soir pour bien dormir",
    "comment lutter contre le stress quotidien",
    "meditation pour debutants par ou commencer",
    "pourquoi je suis toujours fatigue le matin",
    "comment reduire l'anxiete naturellement",
    "bienfaits du bain froid le matin",
    "comment creer une routine matinale efficace",
    "pourquoi je procrastine et comment arreter",
    "comment ameliorer sa concentration",
    "techniques de relaxation efficaces",
    "comment gerer ses emotions au quotidien",
    "journaling bienfaits et comment commencer",
    "comment arreter de ruminer ses pensees",
    "bienfaits de la sieste courte",
    "comment cultiver la gratitude quotidienne",
    "pourquoi je mange mes emotions",
    "comment reprendre confiance en soi",
    "methodes de gestion du temps efficaces",
    "comment sortir d'une periode de depression legere",
    "bienfaits de la pleine conscience au quotidien",
    "comment etablir des limites saines",
    "digital detox comment s'y prendre",
    "comment se motiver quand on n'a pas envie",
    "pourquoi l'ennui peut etre benefique",
    "comment nettoyer sa maison de facon naturelle",
    "produits menagers a faire soi-meme",
    "comment enlever une tache de vin rouge",
    "desencombrer sa maison methode efficace",
    "comment organiser ses placards cuisine",
    "nettoyage printemps par ou commencer",
    "comment enlever les moisissures salle de bain",
    "astuces pour ranger un petit appartement",
    "comment laver son linge delicat",
    "nettoyage four sans produits chimiques",
    "comment organiser sa garde-robe capsule",
    "astuces pour parfumer naturellement sa maison",
    "comment repasser une chemise correctement",
    "rangement enfants jouets methode pratique",
    "comment deboucher un evier naturellement",
    "astuces pour economiser l'eau a la maison",
    "comment nettoyer des joints de carrelage noircis",
    "organisation bureau a domicile",
    "comment desodoriser un frigo naturellement",
    "astuces pour eloigner les araignees",
    "comment nettoyer un matelas",
    "rangement petite cuisine astuces",
    "comment enlever la mauvaise odeur d'une poubelle",
    "astuces pour chasser les fourmis naturellement",
    "comment nettoyer des vitres sans traces",
    "organisation cave et grenier",
    "comment plier une chemise efficacement",
    "astuces pour adoucir l'eau calcaire",
    "comment faire de la place dans un petit appartement",
    "entretien parquet bois naturellement",
    "comment arroser ses plantes en vacances",
    "quelles plantes pour debutant en jardinage",
    "comment reparer un gazon abime",
    "jardin potager debutant par ou commencer",
    "quelles fleurs planter au printemps",
    "comment faire du compost maison",
    "taille des haies quand et comment",
    "pourquoi mes plantes d'interieur jaunissent",
    "comment planter des tomates facilement",
    "plantes qui repoussent les moustiques",
    "comment faire pousser des herbes aromatiques",
    "jardinage en bac sur balcon conseils",
    "comment lutter contre les limaces naturellement",
    "quand tailler les rosiers",
    "comment faire des boutures facilement",
    "plantes d'interieur qui purifient l'air",
    "comment preparer son jardin pour l'hiver",
    "entretien orchidees pour debutants",
    "comment faire un semis de tomates",
    "pourquoi mon cactus meurt",
    "jardinage permaculture principes de base",
    "comment associer les plantes au potager",
    "taille arbres fruitiers quand",
    "comment creer un jardin naturel",
    "plantes vivaces faciles d'entretien",
    "comment detecter une fuite d'eau",
    "reparer un robinet qui goutte soi-meme",
    "comment poser du carrelage pour debutant",
    "reparer une fissure dans un mur",
    "comment installer des etageres solides",
    "peindre un mur sans traces et sans coulures",
    "comment changer un joint de robinetterie",
    "reparer une serrure bloquee",
    "comment reparer un parquet qui craque",
    "installation electrique securite de base",
    "comment poser du papier peint seul",
    "reparer une porte qui ferme mal",
    "comment enlever du vieux carrelage",
    "isolation thermique maison pas chere",
    "comment reboucher un trou dans une porte",
    "reparer un meuble en bois abime",
    "comment installer un store enrouleur",
    "decolleuse papier peint location ou achat",
    "comment changer un joint de douche",
    "reparer une fenetre qui ferme mal",
    "comment faire du macrame pour debutant",
    "tricot debutant premiers points de base",
    "comment apprendre la couture seul",
    "origami facile pour adulte",
    "comment commencer la broderie",
    "loisirs creatifs pour adultes anti-stress",
    "comment apprendre a dessiner seul",
    "poterie debutant par ou commencer",
    "comment faire du crochet facilement",
    "peinture aquarelle techniques de base",
    "comment apprendre la calligraphie",
    "scrapbooking debutant materiel necessaire",
    "apprendre la guitare acoustique seul",
    "premier accord guitare comment s'y prendre",
    "comment accorder une guitare sans accordeur",
    "tablature guitare pour debutant",
    "comment progresser rapidement a la guitare",
    "differents types de guitare lequel choisir",
    "technique fingerpicking guitare",
    "comment jouer un barre de fa",
    "apprendre a lire les partitions de guitare",
    "exercices pour souplesse des doigts guitare",
    "photographie portrait technique eclairage",
    "comment prendre de meilleures photos avec son telephone",
    "reglages manuels appareil photo debutant",
    "composition photo regles de base",
    "comment photographier la nature",
    "retouche photo logiciel gratuit",
    "photographie de nuit conseils",
    "objectif photo lequel choisir pour debutant",
    "comment ameliorer ses photos de paysage",
    "technique photo longue exposition",
    "peinture acrylique techniques debutant",
    "comment melanger les couleurs en peinture",
    "peinture huile sechage et conseils",
    "aquarelle effets techniques avancees",
    "comment peindre un portrait realiste",
    "materiel peinture debutant necessaire",
    "peche a la ligne debutant materiel",
    "comment choisir un appat pour la peche",
    "peche a la mouche technique de base",
    "quel poisson pecher selon la saison",
    "comment lancer sa ligne correctement",
    "meilleurs films de l'annee recommandations",
    "serie policiere francaise recommandee",
    "roman policier a lire absolument",
    "meilleurs livres de developpement personnel",
    "film drame historique recommande",
    "serie fantasy a regarder en ce moment",
    "roman historique francais populaire",
    "comedie francaise culte a revoir",
    "livre de cuisine francaise indispensable",
    "serie documentaire nature conseils",
    "meilleurs albums de jazz recommandes",
    "roman science-fiction classique incontournable",
    "film d'animation pour adultes",
    "serie thriller psychologique recommandee",
    "livre philosophie accessible debutant",
    "musique classique pour se concentrer",
    "roman graphique adulte recommande",
    "film etranger sous-titre a ne pas rater",
    "serie historique france recommandee",
    "livre biographie inspirante",
    "comment preparer un sac a dos pour randonnee",
    "que mettre dans sa valise pour un weekend",
    "conseils voyage longue duree preparation",
    "comment voyager avec un petit budget",
    "que faire en cas de vol bagages",
    "assurance voyage est-ce vraiment utile",
    "comment eviter le decalage horaire",
    "voyager seul premiere fois conseils",
    "comment trouver un hebergement pas cher",
    "que faire si on perd son passeport",
    "conseils pour voyager avec des enfants",
    "comment preparer un itineraire de voyage",
    "voyager en train avantages et astuces",
    "comment eviter les arnaques touristiques",
    "peur de l'avion comment la surmonter",
    "conseils pour voyager eco-responsable",
    "comment choisir entre airbnb et hotel",
    "preparer un voyage en camping",
    "comment gerer son argent en voyage",
    "conseils sante avant un grand voyage",
    "comment communiquer avec un partenaire difficile",
    "signer une relation toxique comment s'en sortir",
    "comment ameliorer la communication dans un couple",
    "conseils pour surmonter une rupture douloureuse",
    "comment reconstruire la confiance apres une trahison",
    "amitie qui s'efface comment reagir",
    "pourquoi je tombe toujours amoureux des mauvaises personnes",
    "comment poser des limites sans culpabiliser",
    "jalousie dans un couple comment gerer",
    "comment rencontrer des gens quand on est timide",
    "distance dans une relation comment y remeder",
    "comment reconnaitre quelqu'un de narcissique",
    "premiere rencontre conseils pour debutant",
    "comment reprendre contact avec quelqu'un",
    "confiance en soi dans les relations",
    "comment garder la flamme dans un couple",
    "peur de l'abandon origine et solutions",
    "comment parler de ses emotions a son partenaire",
    "relations a distance comment les faire durer",
    "comment connaitre ses propres besoins affectifs",
    "comment apprendre a un enfant a gerer sa colere",
    "activites educatives pour enfants a la maison",
    "comment encourager la lecture chez les enfants",
    "gestion des ecrans chez les enfants conseils",
    "comment parler de la mort a un enfant",
    "discipline positive principes de base",
    "comment motiver un enfant pour l'ecole",
    "activites creatives enfants 5 ans",
    "comment aider un enfant anxieux",
    "sommeil enfant routine du soir efficace",
    "comment gerer les crises de colere des tout-petits",
    "alimentation enfants selectifs que faire",
    "comment favoriser l'autonomie des enfants",
    "freres et soeurs rivalite comment la gerer",
    "comment expliquer la sexualite aux enfants",
    "enfant hyperactif signes et accompagnement",
    "comment soutenir un adolescent en difficulte",
    "relation grands-parents petits-enfants importance",
    "comment apprendre l'anglais seul efficacement",
    "methode de memorisation rapide pour etudes",
    "comment se concentrer en etudiant",
    "apprendre l'espagnol debutant par ou commencer",
    "technique de prise de notes efficace",
    "comment preparer un examen stressant",
    "apprendre une nouvelle competence rapidement",
    "methode pomodoro comment l'appliquer",
    "comment lire plus vite sans perdre la comprehension",
    "apprendre le piano seul adulte",
    "comment ameliorer son orthographe",
    "formation en ligne gratuite recommandee",
    "comment apprendre le japonais debutant",
    "technique de repetition espacee pour memorisation",
    "comment s'auto-evaluer dans ses apprentissages",
    "apprendre la guitare basse debutant",
    "comment apprendre a coder seul",
    "lecture rapide technique d'entrainement",
    "comment developper son vocabulaire",
    "apprendre a dessiner en 30 jours",
    "comment adopter un chien adulte",
    "alimentation chat sain que lui donner",
    "mon chien aboie trop que faire",
    "comment dresser un chiot les bases",
    "signes que son chat est malade",
    "quel chien choisir pour une famille",
    "comment habituer son chat au transport",
    "alimentation lapin nain que peut-il manger",
    "mon chien a peur des orages que faire",
    "soins basiques pour un nouveau chaton",
    "comment apprendre le rappel a son chien",
    "quel vaccin pour mon chien",
    "chat qui griffe les meubles solutions",
    "chien qui tire en laisse comment corriger",
    "alimentation poissons d'aquarium",
    "comment choisir la bonne taille de vetements",
    "tendances mode printemps ete",
    "comment creer un dressing capsule",
    "soin peau seche routine quotidienne",
    "comment se demaquiller correctement",
    "soins naturels pour les cheveux abimes",
    "maquillage naturel comment commencer",
    "comment choisir son fond de teint",
    "coupe de cheveux selon la forme du visage",
    "routine soin peau mixte matin et soir",
    "comment entretenir ses ongles naturellement",
    "mode durable comment s'y mettre",
    "soin contour des yeux pourquoi et comment",
    "comment eviter les frisottis",
    "parfum comment choisir selon sa personnalite",
    "histoire de la revolution francaise resumee",
    "pourquoi la guerre de 14-18 a eclate",
    "origines de la renaissance italienne",
    "histoire de l'empire romain chute",
    "pourquoi napoleon a-t-il perdu a waterloo",
    "histoire de la decolonisation en afrique",
    "revolution industrielle consequences sociales",
    "histoire de l'esclavage et de son abolition",
    "pourquoi l'empire ottoman s'est effondre",
    "histoire des droits des femmes en france",
    "premiere et deuxieme guerre mondiale differences",
    "histoire de la guerre froide resumee",
    "origine du capitalisme moderne",
    "histoire des croisades medievales",
    "comment l'imprimerie a change le monde",
    "quelle est la capitale de la mongolie",
    "quel est le pays le plus grand du monde",
    "combien de langues sont parlees dans le monde",
    "quel est le plus haut sommet du monde",
    "quelle est la religion la plus pratiquee",
    "comment fonctionne le systeme parlementaire",
    "quelle difference entre onu et otan",
    "comment est elu le president de la republique",
    "qu'est-ce que le produit interieur brut",
    "pourquoi les elections ont lieu en dimanche",
    "comment fonctionne une banque centrale",
    "quelle est la monnaie officielle du japon",
    "combien de pays en europe",
    "comment obtenir un extrait de casier judiciaire",
    "comment rediger une lettre de mise en demeure",
    "droits d'un locataire face au proprietaire",
    "comment contester une amende injuste",
    "que faire en cas de litige avec un artisan",
    "comment declarer ses impots en ligne",
    "droits du consommateur en france",
    "comment faire une declaration de sinistre",
    "que faire si son employeur ne paye pas",
    "comment obtenir un divorce a l'amiable",
    "droit de retractation achat en ligne",
    "comment redigier un testament simple",
    "que faire en cas d'accident de la route",
    "comment obtenir une reconnaissance de dette",
    "droits en cas de licenciement abusif",
    "comment faire une procuration bancaire",
    "recours en cas de refus de remboursement",
    "comment declarer un deces aux administrations",
    "que faire en cas de vol par carte bancaire",
    "comment resilier un abonnement difficile",
    "decoration de noel idees originales",
    "comment faire une buche de noel sans cuisson",
    "traditions du ramadan expliquees",
    "comment organiser un repas de noel en famille",
    "recette de la galette des rois maison",
    "traditions de paques en france",
    "comment faire un advent calendar soi-meme",
    "recette bredele alsacien noel",
    "traditions halloween origines",
    "comment organiser un reveillon du jour de l'an",
    "fete de la musique comment participer",
    "traditions de la chandeleur en france",
    "decoration de paques artisanale",
    "recette crepes pour la chandeleur",
    "traditions du carnaval en france",
    "comment celebrer yom kippur",
    "recette du colomba de paques",
    "traditions du mardi gras",
    "fete des meres idees cadeaux maison",
    "comment organiser une fete d'anniversaire surprise",
    "comment perdre du poids durablement",
    "pourquoi je reprendsdu poids apres un regime",
    "regime detox vraiment efficace ou non",
    "comment manger moins de sucre au quotidien",
    "aliments coupe-faim naturels liste",
    "comment calculer son indice de masse corporelle",
    "regime sans sel pour hypertension",
    "comment gerer les envies de sucre",
    "aliments brule-graisses vraiment efficaces",
    "regime hypocalorique comment s'y tenir",
    "pourquoi manger lentement aide a maigrir",
    "comment arreter le grignotage nocturne",
    "regime dash pour la tension arterielle",
    "comment reduire les portions sans frustration",
    "aliments a eviter absolument le soir",
    "regime vegetarien equilibre conseils",
    "comment integrer plus de legumineuses",
    "pourquoi l'eau plate est meilleure que l'eau gazeuse",
    "comment se passer du pain blanc",
    "regime anti-cholesterol que manger",
    "comment choisir un bon matelas",
    "apnee du sommeil symptomes et solutions",
    "pourquoi rever est important pour la sante",
    "comment se lever plus tot sans souffrir",
    "lumiere bleue et sommeil comment se proteger",
    "alimentation pour mieux dormir le soir",
    "comment se remettre d'une rupture amoureuse",
    "solitude choisie bienfaits",
    "comment developper son intelligence emotionnelle",
    "pourquoi certaines personnes stressent plus que d'autres",
    "comment gerer un chef toxique au travail",
    "estime de soi comment la reconstruire",
    "comment ne plus avoir peur du rejet",
    "pleine conscience exercices quotidiens",
    "comment parler en public sans stresser",
    "theorie de l'attachement comment la comprendre",
    "introversion vs extraversion differences",
    "comment mieux accepter les critiques",
    "gestion du temps techniques pratiques",
    "comment sortir de sa zone de confort",
    "psychologie de la procrastination expliquee",
    "comment ne plus chercher a plaire a tout le monde",
    "comment faire face au deuil",
    "theorie des besoins de maslow expliquee",
    "comment arreter de se comparer aux autres",
    "comment reconnaitre une manipulation affective",
    "estime de soi basse origines et solutions",
    "comment prendre de meilleures decisions",
    "pourquoi certains patrons sont mauvais leaders",
    "comment s'affirmer sans agressivite",
    "burn-out comment s'en remettre",
    "comment developper sa patience",
    "comment faire de la tarte aux quetsches",
    "recette gateau yaourt classique",
    "comment faire une sauce bechamel legere",
    "recette veloute de potiron",
    "comment faire une salade de lentilles",
    "recette tajine d'agneau aux legumes",
    "comment faire des beignets aux pommes",
    "recette pain d'epices maison",
    "comment faire un cake aux olives",
    "recette far breton traditionnel",
    "comment faire de la confiture de fraises",
    "recette crepes bretonnes originales",
    "comment faire un clafoutis aux abricots",
    "recette quiche aux poireaux",
    "comment faire du gâteau marbré",
    "recette tarte aux framboises",
    "comment faire un gratin de chou-fleur",
    "recette soupe de lentilles corail",
    "comment faire une compote de pommes",
    "recette salade de riz estivale",
    "comment faire des waffles croustillants",
    "recette pain aux noix maison",
    "comment faire un carrot cake",
    "recette zucchini farcis au four",
    "comment faire une sauce tomate maison",
    "recette poulet aux champignons",
    "comment faire du pain sans gluten",
    "recette endives au jambon gratinees",
    "comment faire des sablés viennoises",
    "recette gateau renverse a l'ananas",
    "comment faire une brioche moelleuse",
    "recette salade de pates estivale",
    "comment faire des financiers aux amandes",
    "recette gratin de courge butternut",
    "comment faire du pain pita maison",
    "recette pouding au pain",
    "comment faire de la choucroute maison",
    "recette galettes de sarrasin",
    "comment faire du fromage frais maison",
    "recette gateau sans lactose",
    "comment faire des cookies moelleux",
    "recette soupe miso japonaise simple",
    "comment faire une pizza maison croustillante",
    "recette mousse aux fruits rouges",
    "comment faire du pain de mie moelleux",
    "recette aubergines farcies",
    "comment faire des rouleaux de printemps",
    "recette flamiche aux poireaux",
    "comment faire une charlotte royale",
    "recette gateau basque traditionnel",
    "comment faire du soda maison",
    "recette soupe a la tomate maison",
    "comment faire un semifredo maison",
    "recette curry de pois chiches",
    "comment faire un tiramisu aux fraises",
    "recette gateau au miel et amandes",
    "comment faire du naan maison",
    "recette salade verte classique vinaigrette",
    "comment faire un flan parisien",
    "recette dhal de lentilles",
    "comment faire une tarte au sucre nordiste",
    "recette beignets de legumes",
    "comment faire du caramel beurre sale",
    "recette canneles bordelais",
    "comment faire une mousse de framboise",
    "recette gateau zebré facile",
    "comment faire du beurre clarifie",
    "recette chili sin carne",
    "comment faire des gaufres sans gaufrier",
    "recette riz au lait maison",
    "comment faire une terrine de legumes",
    "recette pain hamburger maison",
    "comment faire du granola maison",
    "recette creme glacee maison sans sorbetiere",
    "comment faire du pain aux cereales",
    "recette tarte bourdaloue poire",
    "comment faire une mousse au cafe",
    "recette gateau a la banane moelleux",
    "comment faire des croques monsieurs parfaits",
    "recette veloute de celeri",
    "comment faire un tartare de boeuf maison",
    "recette pave de saumon sauce citron",
    "comment faire une tarte soleil",
    "recette rillettes de sardine",
    "comment faire du beurre aromatise",
    "recette carpaccio de betterave",
    "comment faire une fondue au chocolat",
    "recette crumble aux poires",
    "comment faire du sirop de lavande",
    "recette pain grille de base",
    "comment faire des tortillas mexicaines",
    "recette lasagnes vegetariennes",
    "comment faire du vinaigre balsamique maison",
    "recette gnocchi maison sauce tomate",
    "comment faire une tarte aux noix",
    "recette soupe au pistou",
    "comment faire des tuiles chocolat",
    "recette poireaux vinaigrette",
    "comment faire une verrines facile",
    "recette gateau d'anniversaire chocolat ganache",
    "comment faire du beurre de cacahuete maison",
    "recette salade caprese originale",
    "comment faire des speculoos maison",
    "recette houmous maison facile",
    "comment faire du lait d'amande",
    "recette pate feuilletee express",
    "comment faire un cobbler aux peches",
    "recette creme de marrons maison",
    "comment faire un kugelhopf",
    "recette porridge avoine matin",
    "comment faire du tzatziki maison",
    "recette gateau renverse aux abricots",
    "comment faire des gressins italiens",
    "recette gateau pomme cannelle",
    "comment faire de la pate d'amande maison",
    "recette wrap poulet avocat",
    "comment faire de la limonade maison",
    "recette pancakes americains moelleux",
    "comment faire des bretzels maison",
    "recette velouté de patate douce",
    "comment faire un cake marbré",
    "recette muffins myrtilles",
    "comment faire une charlotte aux poires",
    "recette oeufs meurette",
    "comment faire du pain focaccia",
    "recette gateau de crepes",
    "comment faire du sirop de menthe maison",
    "recette gratin dauphinois allege",
    "comment faire des churros maison",
    "recette cake carotte orange",
    "comment faire un cheesecake sans cuisson",
    "recette daube provencale",
    "comment faire des knepfle alsaciens",
    "recette panna cotta maison",
    "comment faire du caramel sans beurre",
    "recette tarte aux prunes",
    "comment faire un punch maison",
    "recette gateau magique vanille",
    "comment faire du bouillon de legumes maison",
    "recette madeleine au citron",
    "comment faire des crepes de froment",
    "recette velouté de brocoli",
    "comment faire une fondue bourguignonne",
    "recette tarte rustique aux legumes",
    "pourquoi les plantes grasses perdent leurs feuilles",
    "comment repiquer des tomates seedlings",
    "quand semer les courgettes",
    "comment faire un bac potager sureleve",
    "engrais naturels pour le jardin",
    "comment proteger ses plantes du gel",
    "pourquoi mon rosier ne fleurit pas",
    "comment tailler un olivier en pot",
    "quand planter des bulbes de printemps",
    "comment faire de l'eau de pluie potable",
    "aromates que planter ensemble",
    "comment faire un talus de jardin stable",
    "pourquoi les feuilles de basilic noircissent",
    "comment fertiliser la terre de jardin",
    "entretien gazon automne-hiver",
    "comment faire une haie naturelle",
    "taille glycine quand et comment",
    "comment cultiver des fraises en pot",
    "quels legumes planter ensemble au potager",
    "comment designer un petit jardin",
    "entretien jardin japonais conseils",
    "comment enlever l'herbe entre les paves",
    "plante vivace pour terrain sec",
    "comment detecter la carence en fer dans une plante",
    "jardinage biologique demarrer",
    "comment faire une toiture vegetalisee",
    "comment accrocher un tableau sans faire de trous",
    "reparer une fuite sous l'evier soi-meme",
    "comment monter une armoire ikea seul",
    "changer une ampoule de faux plafond",
    "comment reparer un interrupteur defectueux",
    "poser une tringle a rideau solidement",
    "comment reboucher des vis trop grandes",
    "changer un siphon de douche",
    "comment nettoyer un systeme de ventilation",
    "installer une prise de courant supplementaire",
    "comment faire tenir un miroir lourd",
    "reparer une chaise en bois qui branche",
    "comment remplacer un robinet mitigeur",
    "installer un systeme d'alarme maison simple",
    "comment impermeabiliser des joints de salle de bain",
    "reparer un meuble laque raye",
    "comment changer un joint de wc qui fuit",
    "installer des spots led encastres",
    "comment enlever de la colle sur du carrelage",
    "reparer un escalier en bois qui grince",
    "comment installer une douche italienne",
    "nettoyage et entretien d'une machine a laver",
    "comment detartrer une bouilloire naturellement",
    "entretien climatiseur maison soi-meme",
    "comment nettoyer un canape en tissu",
    "entretien cheminee et ramonage frequence",
    "comment nettoyer des joints de douche noircis",
    "entretien robot aspirateur conseils",
    "comment se debarrasser des cafards",
    "entretien lave-vaisselle maintenance",
    "comment nettoyer un refrigerateur completement",
    "entretien chauffe-eau anode sacrificielle",
    "comment reparer une fermeture eclair bloquee",
    "entretien velo de route maintenance",
    "comment nettoyer un barbecue en fonte",
    "entretien piscine hors sol conseils",
    "comment faire partir une tache de sang",
    "entretien cuir naturellement",
    "comment nettoyer du crepi exterieur",
    "entretien terrasse bois annuel",
    "comment faire une pochette en tissu",
    "couture debutant machine quel modele",
    "comment apprendre a faire du canevas",
    "fabrication bougies maison materiaux",
    "comment faire du savon naturel",
    "creation bijoux debutant outils",
    "comment customiser un vetement soi-meme",
    "fabrication cadres photo maison",
    "comment faire une guirlande de noel",
    "peinture sur tissu technique",
    "comment faire du papier recycle maison",
    "fabrication agenda bullet journal",
    "comment restaurer un meuble ancien",
    "fabrication mobile bebe maison",
    "comment faire un herbier presse",
    "broderie anglaise technique debutant",
    "comment faire des tampons de gravure",
    "fabrication lampion papier maison",
    "comment faire des coussins decoratifs",
    "peinture sur soie technique",
    "meilleure serie policiere en ce moment",
    "documentaire a regarder absolument",
    "livre feel-good recommendé",
    "film anime japonais pour adultes",
    "roman dystopique populaire recent",
    "serie comique francaise drole",
    "meilleur livre sur la resilience",
    "film drame psychologique incontournable",
    "serie historique qualite bbc",
    "roman amoureux realiste recommande",
    "musique pour se concentrer travailler",
    "documentaire gastronomie netflix",
    "serie adaptation roman populaire",
    "meilleurs livres de voyage recits",
    "film horror psychologique sans gore",
    "chanson francaise classique incontournable",
    "roman debutant lecture facile",
    "serie policiere danoise recommandee",
    "livre sur la psychologie simple",
    "film muet classique accessible",
    "prevoir ses vacances avec peu de budget",
    "comment choisir entre camping et location",
    "voyager en famille avec enfants bas age",
    "conseils pour un premier voyage en solo",
    "que faire si son vol est annule",
    "comment preparer son estomac avant de voyager",
    "voyage en train longue distance conseils",
    "comment trouver un guide local authentique",
    "que faire quand on a peur en avion",
    "conseils pour voyager leger en avion",
    "comment se passer du roaming a l'etranger",
    "voyage camping car premiere experience",
    "conseils pour voyager avec un chien",
    "comment profiter d'un weekend court",
    "que faire en cas de maladie a l'etranger",
    "comment organiser un echange de maison",
    "voyage a velo sur route conseils",
    "que faire si on rate son train",
    "conseils pour voyager sans plastique",
    "comment reserver un billet au meilleur prix",
    "comment dire non sans se sentir coupable",
    "pourquoi certaines personnes attirent les profiteurs",
    "comment gerer un parent toxique",
    "amour de soi comment le pratiquer concrètement",
    "comment eviter les conflits familiaux",
    "comment resoudre un malentendu entre amis",
    "psychologie de la dependance affective",
    "comment arreter de s'excuser tout le temps",
    "gestion des conflits au travail",
    "comment reprendre une conversation difficile",
    "pourquoi certaines personnes mentent constamment",
    "comment depasser la peur du conflit",
    "comment se faire de nouveaux amis adulte",
    "techniques de communication non-violente",
    "comment parler a un adolescent ferme",
    "psychologie des enfants agressifs",
    "comment aider quelqu'un en depression",
    "comment gerer les personnes tres sensibles",
    "premiere rencontre virtuelle conseils",
    "comment reconnaitre une relation saine",
    "communication dans un couple mixte culturellement",
    "comment apprendre le mandarin pour debutant",
    "technique d'apprentissage des langues fluency",
    "comment passer le bac seul en candidat libre",
    "methodes d'etude scientifiquement prouvees",
    "comment ameliorer sa memoire a long terme",
    "apprendre la musique en autodidacte",
    "comment s'organiser pour ses etudes",
    "apprendre la statistique sans mathematiques complexes",
    "comment decrocher une bonne note a l'oral",
    "se former en ligne certification gratuite",
    "comment apprendre a taper plus vite au clavier",
    "cours de philosophie pour adultes",
    "comment apprendre l'astronomie seul",
    "techniques de debat efficaces",
    "comment apprendre la comptabilite de base",
    "formation aux premiers secours importance",
    "comment lire des textes academiques",
    "apprendre la psychologie cognitive base",
    "comment rediger un texte argumentatif",
    "cours de rhetorique pour parler mieux",
    "comment garder ses vetements en bon etat",
    "capsule wardrobe femme basiques",
    "entretien chaussures en cuir naturellement",
    "comment savoir sa morphologie",
    "dressing minimaliste avantages",
    "comment associer les couleurs en tenue",
    "soin pour cheveux frises naturels",
    "comment enlever une tache sur un tissu delicat",
    "mode seconde main ou trouver",
    "soins pour peau grasse acneique",
    "comment faire son propre serum visage",
    "coiffure facile quotidienne conseils",
    "comment choisir un anti-cernes adapte",
    "soins corporels naturels maison",
    "comment entretenir ses sourcils",
    "mode ethique labels a connaitre",
    "soins cheveux blancs conseils",
    "comment allonger visuellement sa silhouette",
    "soins des mains en hiver",
    "comment faire un gommage naturel maison",
    "tendances maison deco interieure",
    "rangement vetements sous-vetements methode",
    "culture generale quizz histoire france",
    "origines de la langue francaise",
    "comment fonctionne le systeme judiciaire francais",
    "origine des proverbes francais",
    "philosophie de l'absurde camus expliquee",
    "comment fonctionne la secu sociale",
    "histoire de l'impressionnisme en peinture",
    "comment fonctionne le senat",
    "origine des expressions francaises courantes",
    "mythologie grecque les 12 travaux d'hercule",
    "comment lire un tableau de peinture",
    "histoire des grandes religions resumee",
    "comment fonctionne le marche boursier",
    "origine des noms de famille francais",
    "gastronomie francaise histoire",
    "comment fonctionne la loi de finances",
    "histoire du cinema francais",
    "mythologie nordique personnages principaux",
    "comment fonctionne le droit du travail",
    "histoire de l'architecture moderne",
    "comment faire une declaration de revenus",
    "assurance habitation que couvre-t-elle",
    "comment contester une contravention",
    "droits locataires reparations qui paye",
    "comment choisir une assurance vie",
    "obligation d'entretien entre membres famille",
    "comment creer une micro-entreprise",
    "droits vis a vis de son medecin",
    "comment faire une demande d'apl",
    "que faire si son voisin fait trop de bruit",
    "droits lors d'un constat amiable accident",
    "comment rompre un contrat avant terme",
    "demande de conge parental comment faire",
    "droits en matiere de garde enfant divorce",
    "comment contester une decision administrative",
    "rsa conditions d'eligibilite",
    "droits face a un refus de credit",
    "comment signaler un accident de travail",
    "droits a la retraite age et conditions",
    "comment faire une donation simple",
    "recette soupe de poisson maison",
    "comment faire une terrine de campagne",
    "recette salade marocaine cuite",
    "comment faire du fromage de chevre maison",
    "recette quiche sans pate",
    "comment faire un tartare de legumes",
    "recette veloute d'asperges",
    "comment faire une salade waldorf",
    "recette crevettes a l'ail et persil",
    "comment faire un gratin de quinoa",
    "recette salade caeser originale",
    "comment faire du beurre de noisette",
    "recette taboulé libanais authentique",
    "comment faire une galette de sarrasin",
    "recette pain de poisson",
    "comment faire une sauce aux champignons",
    "recette tartare de thon",
    "comment faire du chou-fleur roti",
    "recette lentilles aux saucisses",
    "comment faire des falafels maison",
    "recette creme patissiere parfumee",
    "comment faire du pain de mie complet",
    "recette pommes de terre sarladaises",
    "comment faire une salade de melon",
    "recette soupe froide gaspacho",
    "comment faire un gateau sans oeuf",
    "recette tarte epinards feta",
    "comment faire une sauce ravigote",
    "recette gratin de pommes de terre saucisses",
    "comment faire des bonbons maison",
    "recette veloute de lentilles",
    "comment faire un brownie sans gluten",
    "recette galette de legumes poelees",
    "comment faire du pain aux raisins",
    "recette pate cardinale maison",
    "comment faire une chantilly maison",
    "recette gratin brocoli fromage",
    "comment faire un cake sal'e jambon olives",
    "recette poivrons farcis viande",
    "comment faire un tiramisu cafe",
    "recette salade avocat pamplemousse",
    "comment faire une tarte au fromage blanc",
    "recette papillote de saumon epinards",
    "comment faire du pain complet maison",
    "recette creme brulee fruits rouges",
    "comment faire une sauce vierge",
    "recette emince de poulet aux poivrons",
    "comment faire un crumble sale",
    "recette semoule aux raisins",
    "comment faire de la confiture de mirabelles",
    "recette pave de cabillaud en croute d'herbes",
    "comment faire un cheesecake speculoos",
    "recette betterave rotie au four",
    "comment faire une mousse a la mangue",
    "recette salade de concombre menthe",
    "comment faire des financiers pistache",
    "recette gateau amandes sans beurre",
    "comment faire une sauce andalouse",
    "recette haricots verts amandes",
    "comment faire du lait de coco chaud",
    "recette pate sucree pour tarte",
    "comment faire un gateau opera",
    "recette salade radis beurre traditionnel",
    "comment faire une bavaroise aux fruits",
    "recette asperges sauce mousseline",
    "comment faire du pain turc lavash",
    "recette fraisier gateau classique",
    "comment faire du sirop de gingembre",
    "recette salade d'oranges a la cannelle",
]
