"""Modeles de recherche francais lies aux lieux ('{}' = ville) pour le data poisoning."""

TEMPLATES = [
    # meteo
    "meteo {}",
    "meteo {} aujourd'hui",
    "meteo {} demain",
    "meteo {} ce week-end",
    "meteo {} semaine prochaine",
    "meteo {} 10 jours",
    "meteo {} 15 jours",
    "meteo {} ce soir",
    "meteo {} en janvier",
    "meteo {} en fevrier",
    "meteo {} en mars",
    "meteo {} en avril",
    "meteo {} en mai",
    "meteo {} en juin",
    "meteo {} en juillet",
    "meteo {} en aout",
    "meteo {} en septembre",
    "meteo {} en octobre",
    "meteo {} en novembre",
    "meteo {} en decembre",
    "previsions meteo {}",
    "temperature {} aujourd'hui",
    "temperature {} demain",
    "temperature {} ce week-end",
    "risque pluie {}",
    "ensoleillement {}",
    "vent {} aujourd'hui",
    "orage {} prevision",
    "neige {} prevision",
    "webcam meteo {}",
    # hebergement general
    "hotel {} pas cher",
    "meilleur hotel {}",
    "hotel {} centre ville",
    "hotel {} avec piscine",
    "hotel {} avec parking",
    "hotel {} 4 etoiles",
    "hotel {} 5 etoiles",
    "hotel {} 3 etoiles",
    "hotel {} bord de mer",
    "hotel {} vue mer",
    "hotel {} vue montagne",
    "auberge de jeunesse {}",
    "hostel {} pas cher",
    "airbnb {}",
    "location appartement {} courte duree",
    "location vacances {}",
    "camping {} pas cher",
    "camping {} avec piscine",
    "camping car {} aire de stationnement",
    "gite {} pas cher",
    "chambre hote {}",
    "bed and breakfast {}",
    "resort {}",
    "villa {} a louer",
    "appartement hotel {}",
    "logement pas cher {}",
    "hebergement {} ce week-end",
    "hebergement {} derniere minute",
    "ou dormir a {}",
    "hotel {} animaux acceptes",
    "hotel {} chien accepte",
    "hotel {} luxe",
    "hotel {} spa",
    "hotel {} vue sur mer",
    # restaurants
    "meilleur restaurant {}",
    "restaurant {} pas cher",
    "restaurant {} centre ville",
    "restaurant {} ouvert dimanche",
    "restaurant {} ouvert lundi",
    "restaurant {} vegetarien",
    "restaurant {} vegan",
    "restaurant {} petit dejeuner",
    "restaurant {} brunch",
    "restaurant {} sushi",
    "restaurant {} pizza",
    "restaurant {} burger",
    "restaurant {} italien",
    "restaurant {} asiatique",
    "restaurant {} japonais",
    "restaurant {} chinois",
    "restaurant {} indien",
    "restaurant {} thai",
    "restaurant {} mexicain",
    "restaurant {} libanais",
    "restaurant {} marocain",
    "restaurant {} africain",
    "restaurant {} grec",
    "restaurant {} espagnol",
    "restaurant {} fruits de mer",
    "restaurant {} poisson",
    "restaurant {} steak",
    "restaurant {} gastronomique",
    "restaurant {} halal",
    "restaurant {} casher",
    "restaurant {} sans gluten",
    "restaurant {} terrasse",
    "restaurant {} vue mer",
    "restaurant {} romantique",
    "restaurant {} famille",
    "restaurant {} enfants",
    "bonne adresse restaurant {}",
    "ou manger a {}",
    "que manger a {}",
    "specialites culinaires {}",
    "gastronomie locale {}",
    # cafes et bars
    "cafe {} pas cher",
    "meilleur cafe {}",
    "salon de the {}",
    "coffee shop {}",
    "cafe avec wifi {}",
    "bar {} pas cher",
    "meilleur bar {}",
    "bar {} centre ville",
    "bar {} rooftop",
    "bar {} jazz",
    "bar {} sports",
    "bar {} cocktail",
    "bar {} vin",
    "bar {} biere",
    "bar {} tapas",
    "pub {} pas cher",
    "pub {}",
    # vie nocturne
    "boite de nuit {}",
    "club {} pas cher",
    "vie nocturne {}",
    "sortir le soir a {}",
    "ou sortir a {} le vendredi",
    "ou sortir a {} le samedi",
    "soiree {} ce soir",
    "bar {} ouvert tard",
    "karaoke {}",
    "casino {}",
    # transports vers et depuis
    "vols pas chers vers {}",
    "vol {} paris",
    "vol {} lyon",
    "vol {} marseille",
    "vols depuis {}",
    "billet avion {}",
    "aeroport {}",
    "aeroport le plus proche de {}",
    "navette aeroport {}",
    "train {}",
    "billet train {}",
    "tgv {}",
    "intercites {}",
    "bus {}",
    "bus pas cher {}",
    "flixbus {}",
    "ouibus {}",
    "ferry {}",
    "traversee {}",
    "location voiture {}",
    "louer une voiture a {}",
    "taxi {}",
    "taxi aeroport {}",
    "uber {}",
    "vtc {}",
    "covoiturage {}",
    "blablacar {}",
    "aller a {} depuis paris",
    "aller a {} depuis lyon",
    "aller a {} depuis marseille",
    "comment aller a {}",
    "comment se rendre a {}",
    "distance jusqu'a {}",
    "temps de trajet pour {}",
    # transports locaux
    "metro {}",
    "bus urbain {}",
    "tramway {}",
    "transport en commun {}",
    "plan transport {}",
    "plan bus {}",
    "plan metro {}",
    "horaires bus {}",
    "horaires metro {}",
    "abonnement transport {}",
    "ticket bus {}",
    "velo libre service {}",
    "trottinette {}",
    "parking {} centre ville",
    "parking {} gratuit",
    "parking {} pas cher",
    "stationnement {}",
    "trafic {} en temps reel",
    "embouteillages {}",
    "plan de ville {}",
    "itineraire a {}",
    # tourisme et activites
    "que faire a {}",
    "que visiter a {}",
    "quoi faire a {}",
    "quoi voir a {}",
    "incontournables {}",
    "top 10 {} a visiter",
    "top attractions {}",
    "sites touristiques {}",
    "monuments {}",
    "patrimoine {}",
    "vieille ville {}",
    "centre historique {}",
    "musee {}",
    "musees gratuits {}",
    "galerie art {}",
    "exposition {}",
    "parc {}",
    "jardins {}",
    "zoo {}",
    "aquarium {}",
    "plage {}",
    "plages proches de {}",
    "randonnee {}",
    "randonnee autour de {}",
    "point de vue {}",
    "panorama {}",
    "belvedere {}",
    "montagne autour de {}",
    "lac autour de {}",
    "riviere {}",
    "foret {}",
    "parc naturel {}",
    "reserve naturelle {}",
    "parc national {}",
    "sentier {}",
    "ballade {}",
    "visite guidee {}",
    "tour a pied {}",
    "escape game {}",
    "salle de cinema {}",
    "theatre {}",
    "opera {}",
    "philharmonie {}",
    "concert {}",
    "spectacle {}",
    "parc attractions {}",
    "activites enfants {}",
    "activites plein air {}",
    "sports nautiques {}",
    "surf {}",
    "kayak {}",
    "velo {}",
    "escalade {}",
    "ski {}",
    "station de ski {}",
    "ski nautique {}",
    "golf {}",
    "piscine publique {}",
    "spa {}",
    "hammam {}",
    "sauna {}",
    # evenements
    "evenements {} ce week-end",
    "concerts {} ce week-end",
    "festivals {}",
    "festival {} ete",
    "festival {} hiver",
    "marche {} week-end",
    "marche noel {}",
    "fete locale {}",
    "foire {}",
    "salon {}",
    "exposition temporaire {}",
    "agenda {}",
    "agenda culturel {}",
    "que faire {} ce soir",
    "que faire {} ce week-end",
    "evenements {} aujourd'hui",
    "brocante {} prochain week-end",
    "vide grenier {}",
    # shopping
    "shopping {}",
    "centre commercial {}",
    "magasins {}",
    "boutiques {}",
    "marche {}",
    "marche alimentaire {}",
    "epicerie {}",
    "supermarche {}",
    "boulangerie {}",
    "boucherie {}",
    "fromagerie {}",
    "cave a vin {}",
    "souvenirs {}",
    "artisanat local {}",
    "librairie {}",
    "galerie marchande {}",
    "outlet {}",
    "soldes {}",
    "marche aux puces {}",
    "antiquaire {}",
    "brocante {}",
    "friperie {}",
    # immobilier
    "appartement a louer {}",
    "maison a louer {}",
    "appartement a acheter {}",
    "maison a acheter {}",
    "prix immobilier {}",
    "prix loyer {}",
    "loyer moyen {}",
    "agence immobiliere {}",
    "studio a louer {}",
    "colocation {}",
    "investissement immobilier {}",
    "quartier ou habiter a {}",
    "meilleur quartier {}",
    "quartier calme {}",
    "prix au m2 {}",
    # emploi et travail
    "emploi {}",
    "offre emploi {}",
    "recrutement {}",
    "travail {}",
    "stage {}",
    "alternance {}",
    "salaire moyen {}",
    "entreprises {}",
    "zone industrielle {}",
    "coworking {}",
    "espace coworking {}",
    "bureau a louer {}",
    "cafe coworking {}",
    "teletravail {}",
    # education
    "universite {}",
    "ecole superieure {}",
    "grandes ecoles {}",
    "lycee {}",
    "college {}",
    "ecole primaire {}",
    "ecole de langue {}",
    "cours de francais {}",
    "cours d'anglais {}",
    "formation {}",
    "ecole ingenieur {}",
    "faculte de medecine {}",
    "bibliotheque {}",
    # sante
    "medecin {}",
    "medecin generaliste {}",
    "medecin de garde {}",
    "hopital {}",
    "clinique {}",
    "urgences {}",
    "pharmacie {}",
    "pharmacie de garde {}",
    "dentiste {}",
    "ophtalmologue {}",
    "kinesitherapeute {}",
    "dermatologue {}",
    "gynecologie {}",
    "pediatre {}",
    "veterinaire {}",
    # sport et bien-etre
    "salle de sport {}",
    "gym {}",
    "fitness {}",
    "cours yoga {}",
    "yoga {}",
    "pilates {}",
    "piscine {}",
    "piscine couverte {}",
    "salle de musculation {}",
    "club de foot {}",
    "terrain de foot {}",
    "court de tennis {}",
    "salle de boxe {}",
    "arts martiaux {}",
    "crossfit {}",
    "centre aquatique {}",
    # vie quotidienne et services
    "poste {}",
    "mairie {}",
    "prefecture {}",
    "banque {}",
    "distributeur billet {}",
    "coiffeur {}",
    "salon coiffure {}",
    "barbier {}",
    "pressing {}",
    "laverie {}",
    "plombier {}",
    "electricien {}",
    "serrurier {}",
    "garage {}",
    "station essence {}",
    "borne recharge voiture electrique {}",
    # informations pratiques
    "population {}",
    "histoire {}",
    "plan {}",
    "code postal {}",
    "indicatif telephonique {}",
    "fuseau horaire {}",
    "altitude {}",
    "superficie {}",
    "langue parlee {}",
    "monnaie {}",
    "meteo annuelle {}",
    "meilleure periode pour visiter {}",
    "quand partir a {}",
    "quand visiter {}",
    "que mettre dans sa valise pour {}",
    "budget voyage {}",
    "cout de la vie {}",
    "indice securite {}",
    "securite {}",
    "criminalite {}",
    "quartier a eviter {}",
    "conseils voyage {}",
    "visa {}",
    # accessibilite et specifiques
    "hotel {} animaux acceptes",
    "{} avec chien",
    "voyage {} avec chien",
    "{} adapte aux enfants",
    "activites enfants {}",
    "{} accessible fauteuil roulant",
    "accessibilite {}",
    "webcam {}",
    "webcam live {}",
    "live cam {}",
    "excursion depuis {}",
    "excursion journee depuis {}",
    "escapade {}",
    "week-end {}",
    "week-end romantique {}",
    "luna de miel {}",
    "voyage scolaire {}",
    # guides et blogs
    "guide {}",
    "guide touristique {}",
    "blog voyage {}",
    "vlog {}",
    "forum {}",
    "avis {}",
    "tripadvisor {}",
    "forum voyageurs {}",
    "conseils {}",
    "itineraire {} 3 jours",
    "itineraire {} 1 semaine",
    "itineraire {} 2 jours",
    "week-end {} programme",
    "que faire {} en 1 journee",
    "que faire {} en 2 jours",
    "que faire {} en 3 jours",
    "visiter {} en 1 jour",
    "visiter {} en 2 jours",
    # gastronomie etendue
    "specialites {} a gouter",
    "marche gourmand {}",
    "vignoble {}",
    "degustation vin {}",
    "brasserie {}",
    "distillerie {}",
    "chocolatier {}",
    "patisserie {}",
    "glace {}",
    "creperie {}",
    "boulangerie {}",
    # types hebergement etendus
    "hotel romantique {}",
    "hotel design {}",
    "hotel historique {}",
    "hotel insolite {}",
    "treehouse {}",
    "yourte {}",
    "roulotte {}",
    "cabane {}",
    "glamping {}",
    "maison dhotes {}",
    "pension complete {}",
    "demi pension {}",
    # transport etendu
    "autocar {}",
    "car {} pas cher",
    "navette {}",
    "minibus {}",
    "moto taxi {}",
    "rickshaw {}",
    "tuk tuk {}",
    "bateau {}",
    "croisiere {}",
    "voilier {}",
    "helicoptere survol {}",
    "montgolfiere {}",
    # meteorologie detaillee
    "vent fort {} aujourd'hui",
    "houle {}",
    "etat de la mer {}",
    "indice uv {}",
    "qualite air {}",
    "pollution {}",
    "allergies pollen {}",
    "risque incendie {}",
    "vigilance meteo {}",
    "meteo montagne {}",
    "meteo mer {}",
    # technologie et connectivite
    "wifi {} gratuit",
    "connexion internet {}",
    "sim card {}",
    "operateur mobile {}",
    "couverture reseau {}",
    "4g 5g {}",
    # enfants et famille
    "parc enfants {}",
    "aire de jeux {}",
    "parc aquatique {}",
    "mini golf {}",
    "bowling {}",
    "cinema {}",
    "musee enfants {}",
    "activites famille {}",
    # nature et environnement
    "foret {}",
    "bois {}",
    "vallee {}",
    "gorges {}",
    "grotte {}",
    "cascade {}",
    "source thermale {}",
    "plage naturiste {}",
    "birdwatching {}",
    "observation etoiles {}",
    "astronomie {}",
    # culture et art
    "musee histoire {}",
    "musee art moderne {}",
    "musee contemporain {}",
    "musee science {}",
    "musee maritime {}",
    "musee militaire {}",
    "chateau {}",
    "abbaye {}",
    "cathedrale {}",
    "eglise {}",
    "mosquee {}",
    "synagogue {}",
    "temple {}",
    "ruins {}",
    "archeologie {}",
    "site classe {}",
    "site unesco {}",
    "patrimoine unesco {}",
    # activites sportives etendues
    "plongee {}",
    "snorkeling {}",
    "windsurf {}",
    "kitesurf {}",
    "jet ski {}",
    "parachute ascensionnel {}",
    "stand up paddle {}",
    "canoe {}",
    "rafting {}",
    "via ferrata {}",
    "parapente {}",
    "saut en parachute {}",
    "cheval {}",
    "equitation {}",
    "vtt {}",
    "trail {}",
    "marathon {}",
    "triathlon {}",
    # nocturne et detente
    "massage {}",
    "bien etre {}",
    "thalasso {}",
    "thermes {}",
    "cure thermale {}",
    "centre bien etre {}",
    "detox {}",
    "yoga retraite {}",
    "retraite meditation {}",
    # photo et social media
    "instagrammable {}",
    "photo spot {}",
    "meilleur endroit photo {}",
    "lever de soleil {}",
    "coucher de soleil {}",
    "vue panoramique {}",
    "belveder {}",
    "tour {}",
    # gastronomie detaillee
    "restaurant biologique {}",
    "restaurant local {}",
    "ferme auberge {}",
    "ferme {}",
    "marche producteurs {}",
    "produits locaux {}",
    "epicerie fine {}",
    "foie gras {}",
    "fromage {}",
    "traiteur {}",
    "plat a emporter {}",
    "livraison repas {}",
    "food truck {}",
    "street food {}",
    "marche alimentaire {}",
    # quartiers et zones
    "quartier branche {}",
    "quartier tendance {}",
    "quartier hipster {}",
    "hypercentre {}",
    "centre historique {}",
    "vieux port {}",
    "quartier artiste {}",
    "bord de mer {}",
    "bord de lac {}",
    "banlieue {}",
    "peripherie {}",
    # business et professionnel
    "salon professionnel {}",
    "congres {}",
    "conference {}",
    "coworking pas cher {}",
    "salle reunion {}",
    "hotel affaires {}",
    "hotel seminaire {}",
    "restaurant affaires {}",
    # urgences et securite
    "police {}",
    "pompiers {}",
    "ambassade {}",
    "consulat {}",
    "urgence medicale {}",
    "centre antipoison {}",
    "assistance routiere {}",
    "assurance voyage {}",
    # pratiques locales
    "pourboire {}",
    "taxe tourisme {}",
    "jours feries {}",
    "heures ouverture magasins {}",
    "fermeture hebdomadaire {}",
    "trouver billet {}",
    "billeterie {}",
    "billet entree {}",
    # recherches longue traine
    "que faire quand il pleut a {}",
    "activites gratuite {}",
    "activite gratuite {}",
    "gratuit a {}",
    "moins cher a {}",
    "voyage pas cher {}",
    "pas cher {}",
    "meilleurs coins secrets {}",
    "endroit inconnu {}",
    "perle cachee {}",
    "hors des sentiers battus {}",
    "off the beaten path {}",
    "bloggers voyage {}",
    "nomade numerique {}",
    "digital nomad {}",
    # recherches hyperspecifiques
    "halal a {}",
    "casher a {}",
    "sans gluten a {}",
    "vegan a {}",
    "vegetarien a {}",
    "lactose a {}",
    "allergie noix a {}",
    "sans alcool a {}",
    "non-fumeur a {}",
    # codes et donnees
    "code insée {}",
    "numero departement {}",
    "region {}",
    "canton {}",
    "commune {}",
    "arrondissement {}",
    # meteo supplementaire
    "temperature eau {}",
    "temperature piscine {}",
    "risque avalanche {}",
    "enneigement {}",
    "epaisseur neige {}",
    "ouverture piste ski {}",
    "conditions ski {}",
    # visite et circuit
    "circuit touristique {}",
    "tour guidé {}",
    "tour en bus {}",
    "audio guide {}",
    "carte touristique {}",
    "office tourisme {}",
    "syndicat initiative {}",
    "pass touriste {}",
    "city card {}",
    "visite privee {}",
    # hebergement atypique
    "hotel flottant {}",
    "hotel bulles {}",
    "yourte mongolienne {}",
    "nuit insolite {}",
    "lodge {}",
    "eco lodge {}",
    "ferme pedagogique {}",
    # animaux et nature
    "parc animalier {}",
    "reserve animaux {}",
    "observation dauphins {}",
    "baleine {}",
    "oiseaux {}",
    "nature {}",
    "ecotourisme {}",
    "tourisme vert {}",
    # monuments etendus
    "pont {}",
    "fontaine {}",
    "place {}",
    "statue {}",
    "fresque {}",
    "street art {}",
    "graffiti {}",
    "edifice {}",
    "batiment historique {}",
    "patrimoine architectural {}",
    # festivals et culture pop
    "festival musique {}",
    "festival film {}",
    "festival gastronomie {}",
    "festival art {}",
    "carnaval {}",
    "fete nationale {}",
    "fete de la musique {}",
    "feu artifice {}",
    # langue et communication
    "langue officielle {}",
    "langues parlees {}",
    "dialecte {}",
    "traducteur {}",
    "interpreter {}",
    # recherches saison
    "{} en ete",
    "{} en hiver",
    "{} au printemps",
    "{} en automne",
    "{} en fevrier",
    "{} en juillet",
    "{} en aout",
    "{} pendant les vacances",
    # comparatifs
    "mieux que {} pour vacances",
    "similaire a {} pas cher",
    # supplement resto
    "restaurant vue sur {}",
    "terrasse {} vue",
    "brunch {} dimanche",
    "apero {} terrasse",
    "restaurant {} midi",
    "restaurant {} soir",
    "carte menu {} restaurant",
    "reservation restaurant {}",
    # supplement hebergement
    "hotel {} dernier minute",
    "promotion hotel {}",
    "offre hotel {}",
    "hotel {} pas cher nuit",
    "nuit hotel {} pas cher",
    "camping gratuit {}",
    "camping sauvage {}",
    # supplement transport
    "location velo {}",
    "piste cyclable {}",
    "chemin de randonnee {}",
    "sentier pedestre {}",
    "GR {}",
    "tour a velo {}",
    "route velo {}",
    # supplement pratique
    "distributeur automatique {}",
    "change argent {}",
    "bureau change {}",
    "taux change {}",
    "prix taxi {}",
    "forfait transport {}",
    "navette gare {}",
    "gare {}",
    "gare routiere {}",
    "terminal {}",
    # supplement emploi
    "offres emploi {} interim",
    "offres emploi {} temps plein",
    "offres emploi {} temps partiel",
    "bourse emploi {}",
    "chomage {}",
    "pole emploi {}",
    # supplement education
    "ecole maternelle {}",
    "creche {}",
    "garderie {}",
    "centre aere {}",
    "cantine scolaire {}",
    "ecole internationale {}",
    "ecole montessori {}",
    "ecole bilingue {}",
    # supplement sante
    "medecin sans rendez vous {}",
    "radiologie {}",
    "laboratoire analyse {}",
    "hopital public {}",
    "clinique privee {}",
    "maternite {}",
    "centre de sante {}",
    "psychologue {}",
    "psychiatre {}",
    "addictologie {}",
    # supplement sport
    "stade {}",
    "complexe sportif {}",
    "salle omnisports {}",
    "club sportif {}",
    "association sportive {}",
    "marathon {}",
    "course a pied {}",
    "natation {}",
    "patinoire {}",
    # supplement vie quotidienne
    "marche du matin {}",
    "horaires mairie {}",
    "demarches administratives {}",
    "carte grise {}",
    "permis conduire {}",
    "carte nationale identite {}",
    "passeport {}",
    "notaire {}",
    "avocat {}",
    "huissier {}",
    # supplement culture
    "cinema {} seances",
    "seances cinema {} aujourd'hui",
    "theatre {} programme",
    "concert {} programme",
    "orchestre {}",
    "ballet {}",
    "danse {}",
    "exposition {} vernissage",
    "vernissage {}",
    "librairie independante {}",
    # supplement digital
    "coworking {} prix",
    "coworking {} inscription",
    "cafe wifi {} ouvert tard",
    "espace travail {}",
    # supplement alimentation
    "epicerie asiatique {}",
    "epicerie africaine {}",
    "epicerie orientale {}",
    "magasin bio {}",
    "marche bio {}",
    "magasin vrac {}",
    "zéro déchet {}",
    "fromagerie {}",
    "poissonnerie {}",
    "primeur {}",
    "maraichers {}",
    # supplement meteo granulaire
    "pluie {} semaine",
    "humidite {} aujourd'hui",
    "brouillard {} matin",
    "canicule {}",
    "froid {} nuit",
    "gel {} nuit",
    "verglas {}",
    "neige {} nuit",
    # supplement securite
    "zone rouge {}",
    "securite quartier {}",
    "taux criminalite {}",
    "arnaque touristique {}",
    "attention pickpocket {}",
    "consignes securite {}",
    # supplement tourisme durable
    "tourisme responsable {}",
    "tourisme durable {}",
    "voyage ethique {}",
    "hebergement eco {}",
    "transport vert {}",
    "bilan carbone {}",
    "compensation carbone {}",
    # supplement immobilier
    "surface moyenne appartement {}",
    "rendement locatif {}",
    "taxe fonciere {}",
    "charges copropriete {}",
    "syndic {}",
    "diagnostic immobilier {}",
    # supplement famille
    "colonie vacances {}",
    "sejour linguistique {}",
    "camp ete {}",
    "sejour sportif {}",
    "camping famille {}",
    "club enfants {}",
    # supplement gastronomie
    "cours cuisine {}",
    "atelier cuisine {}",
    "chef cuisinier {}",
    "etoile michelin {}",
    "restaurant etoile {}",
    "bib gourmand {}",
    "guide michelin {}",
    # supplement insolite
    "anecdote {}",
    "curiosite {}",
    "legende {}",
    "mythe {}",
    "fantome {}",
    "paranormal {}",
    "histoire mysterieuse {}",
    # supplement communaute
    "expatrie {}",
    "communaute francaise {}",
    "association {}",
    "benevolat {}",
    "volontariat {}",
    "groupe facebook {}",
    "forum expat {}",
    # supplement accessibilite
    "mobilite reduite {}",
    "personne agee {}",
    "senior {}",
    "retraite {}",
    "maison retraite {}",
    "ehpad {}",
    # supplement mariage et evenements
    "mariage {}",
    "salle reception {}",
    "traiteur mariage {}",
    "photographe {}",
    "videaste {}",
    "fleuriste {}",
    "anniversaire {}",
    "organisation evenement {}",
    # supplement niche
    "laser game {}",
    "paintball {}",
    "trampolines {}",
    "accrobranche {}",
    "quad {}",
    "4x4 {}",
    "buggy {}",
    "karting {}",
    "simulateur de vol {}",
    "realite virtuelle {}",
    "vr {}",
    # supplement reseaux sociaux
    "{} instagram",
    "{} tiktok",
    "{} youtube",
    "{} photos",
    "photos {} vacances",
    "belles photos {}",
    # supplement environnement
    "plage propre {}",
    "plage pollution {}",
    "qualite eau {}",
    "pollution lumineuse {}",
    "espace vert {}",
    "jardin botanique {}",
    "arboretum {}",
    # supplement retro
    "nostalgie {}",
    "{} autrefois",
    "{} histoire ancienne",
    "{} photo ancienne",
    "vestiges {}",
    "patrimoine industriel {}",
    # supplement recherche pratique
    "horaires {}",
    "adresse {}",
    "telephone {}",
    "contact {}",
    "site officiel {}",
    "mairie {} contact",
    "numero urgence {}",
    "informations pratiques {}",
    # supplement final varia
    "a propos de {}",
    "tout savoir sur {}",
    "decouvrir {}",
    "explorer {}",
    "partir a {}",
    "voyage a {}",
    "sejour a {}",
    "escapade a {}",
    "road trip {}",
    "destination {}",
    "{} vaut le detour",
    "{} ou pas",
    "avis sur {}",
    "recommandations {}",
    "tips {}",
    "astuces {}",
    "ressources {}",
    "liens utiles {}",
    "carte {}",
    "satellite {}",
    "google maps {}",
    "{} coordinates",
    "coordonnees gps {}",
    "latitude longitude {}",
    "elevation {}",
    "relief {}",
    "topographie {}",
]
