"""Liste di parole italiane per il data poisoning (vedi browser/decoy.py)."""

CITIES = [
    "roma", "milano", "napoli", "torino",
    "palermo", "genova", "bologna", "firenze",
    "bari", "catania", "venezia", "verona",
    "messina", "padova", "trieste", "taranto",
    "brescia", "prato", "parma", "modena",
    "reggio calabria", "reggio emilia", "perugia", "livorno",
    "ravenna", "cagliari", "foggia", "rimini",
    "salerno", "ferrara", "sassari", "latina",
    "giugliano in campania", "monza", "siracusa", "bergamo",
    "pescara", "forlì", "trento", "vicenza",
    "terni", "novara", "piacenza", "ancona",
    "andria", "arezzo", "udine", "cesena",
    "lecce", "pesaro", "barletta", "alessandria",
    "la spezia", "pistoia", "catanzaro", "brindisi",
    "como", "lucca", "pisa", "savona",
    "grosseto", "siena", "carrara", "massa",
    "marsala", "caserta", "benevento", "trapani",
    "caltanissetta", "agrigento", "ragusa", "enna",
    "nuoro", "oristano", "vibo valentia", "crotone",
    "cosenza", "potenza", "matera", "campobasso",
    "isernia", "l'aquila", "chieti", "teramo",
    "frosinone", "rieti", "viterbo", "tivoli",
    "civitavecchia", "sorrento", "amalfi", "positano",
    "ravello", "taormina", "cefalù", "tropea",
    "otranto", "alberobello", "trani", "vieste",
    "ostuni", "cortina d'ampezzo", "courmayeur", "madonna di campiglio",
    "sestriere", "livigno", "imola", "carpi",
    "faenza", "forli", "new york", "los angeles",
    "chicago", "houston", "miami", "san francisco",
    "seattle", "boston", "washington", "las vegas",
    "atlanta", "denver", "philadelphia", "phoenix",
    "san diego", "dallas", "austin", "portland",
    "new orleans", "nashville", "minneapolis", "detroit",
    "baltimore", "tampa", "orlando", "san jose",
    "sacramento", "salt lake city", "kansas city", "londra",
    "parigi", "berlino", "madrid", "barcelona",
    "lisbona", "amsterdam", "bruxelles", "vienna",
    "zurigo", "ginevra", "basilea", "berna",
    "losanna", "monaco di baviera", "amburgo", "francoforte",
    "colonia", "stoccarda", "dusseldorf", "lipsia",
    "dresda", "hannover", "norimberga", "stoccolma",
    "oslo", "copenaghen", "helsinki", "tallin",
    "riga", "vilnius", "varsavia", "cracovia",
    "gdansk", "praga", "brno", "bratislava",
    "budapest", "bucarest", "sofia", "belgrado",
    "zagabria", "lubiana", "sarajevo", "tirana",
    "skopje", "podgorica", "atene", "salonicco",
    "nicosia", "valletta", "la valletta", "reykjavik",
    "dublino", "cork", "edimburgo", "glasgow",
    "manchester", "birmingham", "liverpool", "leeds",
    "bristol", "cardiff", "oxford", "cambridge",
    "brighton", "porto", "siviglia", "valencia",
    "saragozza", "bilbao", "malaga", "alicante",
    "palma di maiorca", "las palmas", "tenerife", "ibiza",
    "mosca", "san pietroburgo", "ekaterinburg", "novosibirsk",
    "kazan", "sochi", "kiev", "odessa",
    "leopoli", "kharkiv", "minsk", "tbilisi",
    "erevan", "baku", "istanbul", "ankara",
    "smirne", "antalya", "bodrum", "cappadocia",
    "cairo", "alessandria d'egitto", "luxor", "sharm el-sheikh",
    "hurghada", "marrakech", "casablanca", "rabat",
    "fez", "tunisi", "algeri", "tripoli",
    "nairobi", "addis abeba", "accra", "lagos",
    "dakar", "cape town", "johannesburg", "pretoria",
    "durban", "dar es salaam", "kampala", "kigali",
    "harare", "dubai", "abu dhabi", "doha",
    "riyadh", "jeddah", "kuwait city", "muscat",
    "tel aviv", "gerusalemme", "beirut", "amman",
    "damasco", "baghdad", "teheran", "karachi",
    "lahore", "islamabad", "mumbai", "delhi",
    "bangalore", "chennai", "kolkata", "hyderabad",
    "pune", "ahmedabad", "surat", "jaipur",
    "lucknow", "kathmandu", "colombo", "dhaka",
    "yangon", "bangkok", "chiang mai", "phuket",
    "kuala lumpur", "singapore", "giacarta", "bali",
    "surabaya", "manila", "ho chi minh city", "hanoi",
    "da nang", "phnom penh", "vientiane", "tokyo",
    "osaka", "kyoto", "hiroshima", "nagoya",
    "sapporo", "fukuoka", "seul", "busan",
    "incheon", "pechino", "shanghai", "guangzhou",
    "shenzhen", "chengdu", "xi'an", "hong kong",
    "macao", "taipei", "ulan bator", "sydney",
    "melbourne", "brisbane", "perth", "adelaide",
    "auckland", "wellington", "christchurch", "suva",
    "port moresby", "toronto", "montreal", "vancouver",
    "calgary", "ottawa", "edmonton", "quebec",
    "winnipeg", "halifax", "victoria", "città del messico",
    "guadalajara", "monterrey", "cancun", "oaxaca",
    "bogota", "medellin", "cali", "cartagena",
    "lima", "cusco", "arequipa", "santiago del cile",
    "valparaiso", "buenos aires", "cordoba", "rosario",
    "san paolo", "rio de janeiro", "salvador", "brasilia",
    "fortaleza", "belo horizonte", "recife", "manaus",
    "belem", "porto alegre", "montevideo", "asuncion",
    "la paz", "sucre", "quito", "guayaquil",
    "caracas", "panama city", "san jose de costa rica", "san salvador",
    "tegucigalpa", "managua", "guatemala city", "havana",
    "santo domingo", "san juan di puerto rico", "kingston", "anchorage",
    "honolulu", "juneau", "khartoum", "abidjan",
    "bamako", "ouagadougou", "niamey", "n'djamena",
    "yaounde", "libreville", "kinshasa", "brazzaville",
    "luanda", "lusaka", "maputo", "antananarivo",
    "port louis", "moroni", "venezia mestre", "molfetta",
    "cerignola", "manfredonia", "altamura", "nola",
    "afragola", "ercolano", "portici", "pozzuoli",
    "avellino", "battipaglia", "eboli", "pagani",
    "nocera inferiore", "sassuolo", "vignola", "castelfranco emilia",
    "treviso", "rovigo", "belluno", "pordenone",
    "gorizia", "tolmezzo", "cuneo", "asti",
    "vercelli", "biella", "verbania", "aosta",
    "ivrea", "pinerolo", "chieri", "moncalieri",
    "collegno", "nichelino", "varese", "lecco",
    "sondrio", "lodi", "cremona", "mantova",
    "crema", "vigevano", "busto arsizio", "gallarate",
    "saronno", "rho", "sesto san giovanni", "cinisello balsamo",
    "cologno monzese", "desio", "seregno", "foligno",
    "spoleto", "orvieto", "città di castello", "gubbio",
    "alba", "bra", "fossano", "savigliano",
    "mondovi", "rovereto", "bolzano", "merano",
    "bressanone", "cervignano del friuli", "lanciano", "vasto",
    "sulmona", "avezzano", "termoli", "melfi",
    "lagonegro", "lamezia terme", "palmi", "locri",
    "siderno", "modica", "noto", "scicli",
    "comiso", "alghero", "olbia", "iglesias",
    "carbonia", "tortoli", "tempio pausania", "imperia",
    "sanremo", "bordighera", "ventimiglia", "alassio",
    "albenga", "chiavari", "rapallo", "santa margherita ligure",
    "portofino", "scala", "atrani", "maiori",
    "minori", "capri", "ischia", "procida",
    "ponza", "ventotene", "elba", "pantelleria",
    "lampedusa", "linosa", "ustica", "favignana",
    "lipari", "vulcano", "stromboli", "panarea",
    "filicudi", "alicudi", "porto cervo", "porto rotondo",
    "la maddalena", "santa teresa gallura", "stresa", "bellagio",
    "varenna", "bari vecchia", "nantes", "lione",
    "marsiglia", "bordeaux", "tolosa", "strasburgo",
    "nizza", "montpellier", "lille", "rennes",
    "grenoble", "lugano", "eindhoven", "rotterdam",
    "l'aia", "utrecht", "anversa", "gand",
    "liegi", "bruges", "lussemburgo", "monaco",
    "andorra", "lodz", "poznan", "wroclaw",
    "kosice", "debrecen", "pecs", "gyor",
    "cluj-napoca", "timisoara", "iasi", "constanta",
    "varna", "plovdiv", "nis", "novi sad",
    "spalato", "rijeka", "dubrovnik", "maribor",
    "tblisi", "yerevan", "almaty", "astana",
    "tashkent", "samarcanda", "kabul", "nagpur",
    "patna", "bhopal", "indore", "chittagong",
    "rangoon", "bandung", "medan", "makassar",
    "cebu", "davao", "naha", "sendai",
    "daegu", "daejeon", "wuhan", "nanjing",
    "tianjin", "chongqing", "harbin", "qingdao",
    "dalian", "kaohsiung", "tainan", "ulaanbaatar",
    "ho chi minh", "hai phong", "mandalay", "kandy",
    "pokhara", "salalah", "manama", "asmara",
    "mogadiscio", "gibuti", "conakry", "freetown",
    "monrovia", "lome", "cotonou", "porto novo",
    "douala", "bangui", "lubumbashi", "bujumbura",
    "lilongwe", "bulawayo", "windhoek", "gaborone",
    "maseru", "tananarive", "kumasi", "banjul",
    "bissau", "ndjamena", "juba", "khartum",
    "porto sudan", "dire daua", "mombasa", "kisumu",
    "entebbe", "dodoma", "zanzibar", "beira",
    "nampula", "lobito", "port elizabeth", "soweto",
    "toamasina", "limon", "san pedro sula", "leon",
    "puebla", "tijuana", "juarez", "santiago de cuba",
    "camaguey", "porto principe", "cap haitien", "santiago de los caballeros",
    "san juan", "ponce", "bridgetown", "nassau",
    "port of spain", "trujillo", "chiclayo", "barranquilla",
    "bucaramanga", "maracaibo", "cuenca", "cochabamba",
    "santa cruz", "ciudad del este", "punta del este", "mendoza",
    "concepcion", "iquitos", "sao paulo", "curitiba",
]

TEMPLATES = [
    "meteo {} oggi",
    "meteo {} domani",
    "meteo {} questo weekend",
    "previsioni meteo {} settimana",
    "temperatura {} in questo momento",
    "meteo {} prossimi 10 giorni",
    "meteo {} prossimi 7 giorni",
    "meteo {} prossimo mese",
    "cosa fare a {}",
    "cosa vedere a {}",
    "cosa visitare a {}",
    "attrazioni turistiche {}",
    "musei da visitare a {}",
    "monumenti principali {}",
    "centro storico {}",
    "piazze famose di {}",
    "chiese da visitare {}",
    "gallerie d'arte {}",
    "migliore pizza a {}",
    "migliori ristoranti {}",
    "ristoranti economici {}",
    "ristoranti romantici {}",
    "ristorante vegetariano {}",
    "ristorante vegano {}",
    "dove mangiare a {} spendendo poco",
    "street food {}",
    "migliore gelato {}",
    "colazione dove a {}",
    "brunch {}",
    "sushi {} consigliato",
    "osteria tipica {}",
    "trattoria tradizionale {}",
    "cucina locale {}",
    "specialita gastronomiche {}",
    "mercato alimentare {}",
    "hotel {} centro",
    "hotel {} economico",
    "hotel {} lusso",
    "hotel {} 4 stelle",
    "migliori hotel {}",
    "b&b {} centro storico",
    "ostello {}",
    "casa vacanze {}",
    "appartamento {} affitto breve",
    "airbnb {} consigli",
    "agriturismo vicino {}",
    "camping {}",
    "voli per {} low cost",
    "voli da roma a {}",
    "voli da milano a {}",
    "biglietti treno {}",
    "treno per {} orari",
    "autobus per {}",
    "come arrivare a {}",
    "aeroporto di {} come raggiungere il centro",
    "taxi dall'aeroporto di {}",
    "noleggio auto {}",
    "car sharing {}",
    "parcheggio {} centro",
    "trasporti pubblici {}",
    "metro {} mappa",
    "bus {} app",
    "come muoversi a {} senza auto",
    "bici elettrica {}",
    "eventi {} questo weekend",
    "eventi {} oggi",
    "concerti {} giugno 2026",
    "festival {} estate 2026",
    "mercatino {} dicembre",
    "mercatino dell'antiquariato {}",
    "fiera {} 2026",
    "cosa fare a {} di notte",
    "vita notturna {}",
    "bar {} aperitivo",
    "cocktail bar {}",
    "locali musica dal vivo {}",
    "discoteca {}",
    "pub {}",
    "caffè storici {}",
    "wine bar {}",
    "enoteca {}",
    "spettacolo teatro {}",
    "cinema {} programmazione",
    "shopping {} dove",
    "centro commerciale {}",
    "mercato {} storico",
    "outlet vicino {}",
    "negozi tipici {}",
    "artigianato locale {}",
    "souvenir {}",
    "supermercato {} 24 ore",
    "farmacia {} aperta adesso",
    "ospedale {} pronto soccorso",
    "medico di base {} come trovare",
    "palestra {} economica",
    "piscina {} pubblica",
    "parco {} jogging",
    "spiagge vicino {}",
    "spiagge più belle {}",
    "spiaggia libera {}",
    "escursioni {} a piedi",
    "trekking vicino {}",
    "natura {}",
    "parchi naturali vicino {}",
    "vista panoramica {}",
    "foto instagrammabili {}",
    "appartamento in affitto {} lungo termine",
    "affitto monolocale {} prezzi",
    "comprare casa {}",
    "quartieri migliori per vivere {}",
    "quartiere sicuro {}",
    "costo della vita {}",
    "vivere e lavorare a {}",
    "lavoro {} offerte",
    "offerte lavoro {} full time",
    "stage {} studenti",
    "università {} iscrizioni",
    "scuola di italiano {}",
    "scuola di lingue {}",
    "asilo nido {}",
    "scuola elementare {} migliore",
    "coworking {} economico",
    "bar con wifi {} lavorare",
    "biblioteca {} orari",
    "popolazione {} quanti abitanti",
    "storia di {}",
    "mappa {} scarica",
    "cap {}",
    "prefisso telefonico {}",
    "fuso orario {}",
    "lingua parlata {}",
    "moneta usata {}",
    "clima {} quando andare",
    "periodo migliore per visitare {}",
    "itinerario {} 3 giorni",
    "itinerario {} una settimana",
    "weekend a {}",
    "gita di un giorno a {}",
    "cosa fare a {} con bambini",
    "attività familiari {}",
    "parco giochi {}",
    "zoo {} o acquario",
    "museo dei bambini {}",
    "accessibilità disabili {}",
    "viaggio accessibile {}",
    "guida turistica {} gratis",
    "tour gratuito {}",
    "free walking tour {}",
    "visita guidata {}",
    "card turistica {}",
    "pass musei {}",
    "prenotare biglietti {}",
    "orari apertura attrazioni {}",
    "biglietti online {}",
    "sicurezza {} consigli",
    "zona da evitare {}",
    "assicurazione viaggio {}",
    "vaccinazioni richieste per {}",
    "visto per {}",
    "cambio valuta {}",
    "bancomat {} commissioni",
    "farmacia internazionale {}",
    "pronto soccorso {} orari",
    "consolato italiano {}",
    "ambasciata italiana {}",
    "connessione internet {} sim locale",
    "wifi gratuito {}",
    "voltaggio elettrico {}",
    "adattatore presa {}",
    "lavanderia automatica {}",
    "lavanderia a secco {}",
    "gastronomia tipica {}",
    "vino locale {}",
    "birra artigianale {}",
    "mercato settimanale {}",
    "prodotti locali {}",
    "dove comprare cibo tipico {}",
    "delivery pizza {}",
    "consegna cibo a domicilio {}",
    "ristorante aperto domenica {}",
    "ristorante aperto a ferragosto {}",
    "ristorante con terrazza {}",
    "ristorante vista mare {}",
    "ristorante panoramico {}",
    "migliore gelato artigianale {}",
    "pasticceria famosa {}",
    "forno storico {}",
    "cibo di strada {}",
    "sagra {} 2026",
    "sagra paesana vicino {}",
    "come arrivare a {} in treno da torino",
    "come arrivare a {} in aereo",
    "distanza {} da roma km",
    "distanza {} da milano",
    "quanto dista {} da napoli",
    "tempo di viaggio {} in auto",
    "autostrada per {}",
    "stazione ferroviaria {} indirizzo",
    "aeroporto {} voli nazionali",
    "porto crociere {}",
    "traghetti per {}",
    "isola vicino {}",
    "gita in barca {}",
    "noleggio barca {}",
    "surf {}",
    "diving {}",
    "kitesurf {}",
    "sci {} stazione invernale",
    "piste sci {}",
    "noleggio sci {}",
    "terme {}",
    "spa {}",
    "centri benessere {}",
    "massaggio {}",
    "yoga {}",
    "palestra 24 ore {}",
    "crossfit {}",
    "campo da tennis {}",
    "piscina olimpionica {}",
    "stadio {} partite in programma",
    "partita {} biglietti",
    "museo di storia {}",
    "museo d'arte moderna {}",
    "museo scientifico {}",
    "orto botanico {}",
    "giardini pubblici {}",
    "castello {}",
    "palazzo storico {}",
    "duomo {}",
    "basilica {}",
    "tempio antico {}",
    "sito archeologico {}",
    "borghi medievali vicino {}",
    "quartiere storico {}",
    "mercato orientale {}",
    "luna park {}",
    "bowling {}",
    "laser game {}",
    "escape room {}",
    "karaoke {}",
    "cinema all'aperto {}",
    "opera lirica {}",
    "jazz club {}",
    "jazz festival {}",
    "raduno auto d'epoca {}",
    "maratona {}",
    "gara ciclistica {}",
    "corso cucina {}",
    "lezione fotografia {}",
    "corso lingua {}",
    "laboratorio artigianale {}",
    "fattoria didattica vicino {}",
    "vendemmia {}",
    "laboratorio ceramica {}",
    "workshop pittura {}",
    "uscite subacquee {}",
    "birdwatching {}",
    "osservazione stelle {}",
    "sentieri naturalistici {}",
    "cascate vicino {}",
    "grotte {}",
    "riserva naturale {}",
    "oasi {}",
    "spiagge per cani {}",
    "dove portare i cani {}",
    "veterinario urgente {}",
    "pet hotel {}",
    "{} cosa vedere in un giorno",
    "{} guida pratica turista",
    "{} dove dormire consiglio",
    "{} trasporti dal centro",
    "{} numeri utili emergenza",
    "{} lingua ufficiale",
    "{} storia breve riassunto",
    "{} clima e temperatura media",
    "{} codice postale",
    "{} distanza dal mare",
]

STANDALONE = [
    "migliore smartphone android 2026 confronto",
    "iphone 17 vale la pena comprare",
    "macbook pro m4 recensione",
    "tablet economico per studiare 2026",
    "monitor 4k per gaming quale scegliere",
    "tastiera meccanica silenziosa consiglio",
    "mouse wireless ergonomico migliore",
    "auricolari wireless autonomia lunga 2026",
    "cuffie over ear qualita prezzo",
    "router wifi 6 casa grande",
    "smart tv 65 pollici migliore 2026",
    "soundbar economica buona qualita",
    "proiettore portatile campeggio",
    "come pulire ventola laptop",
    "ssd esterno veloce 1tb",
    "hard disk esterno 4tb backup",
    "raspberry pi 5 progetti idee",
    "arduino robot principiante",
    "stampante 3d casa prezzo",
    "come imparare python da zero",
    "corso javascript gratuito 2026",
    "differenza tra java e python",
    "linux ubuntu o fedora quale scegliere",
    "docker tutorial italiano",
    "git comandi base cheatsheet",
    "visual studio code estensioni utili",
    "come creare un sito web gratis",
    "wordpress vs webflow 2026",
    "intelligenza artificiale corso gratuito",
    "chatgpt alternativa gratuita",
    "come usare midjourney per immagini",
    "vpn migliore per privacy 2026",
    "antivirus gratuito pc windows",
    "backup automatico pc come fare",
    "velocizzare pc windows 10",
    "schermo pc oscurarsi problema",
    "connessione internet lenta cosa fare",
    "fibra ottica quanto costa al mese",
    "abbonamento streaming migliore 2026",
    "netflix o disney plus conviene di piu",
    "ricetta pasta alla carbonara originale",
    "ricetta risotto allo zafferano",
    "come fare la pasta fresca in casa",
    "ricetta pizza napoletana fatta in casa",
    "ricetta tiramisu classico",
    "ricetta panna cotta facile",
    "ricetta pane integrale lievito madre",
    "come fare il pesto alla genovese",
    "ricetta gnocchi di patate soffici",
    "ricetta lasagne alla bolognese originale",
    "come fare la creme brulee",
    "ricetta cheesecake americana",
    "biscotti al burro ricetta semplice",
    "ricetta muffin cioccolato",
    "frullato proteico post allenamento",
    "ricetta buddha bowl vegetariana",
    "come cucinare il tofu",
    "poke bowl ricetta italiana",
    "colazione proteica sana idee",
    "cosa mangiare a colazione dieta",
    "alimenti ricchi di ferro naturali",
    "vitamina d carenza sintomi",
    "omega 3 alimenti migliori",
    "come aumentare la massa muscolare naturalmente",
    "dieta mediterranea piano settimanale",
    "digiuno intermittente 16 8 come iniziare",
    "quante calorie al giorno per dimagrire",
    "come perdere peso senza soffrire",
    "palestra o corsa cosa brucia piu calorie",
    "allenamento casa senza attrezzi 30 minuti",
    "yoga mattina principianti",
    "stretching prima di dormire benefici",
    "come migliorare la postura seduto",
    "esercizi per il mal di schiena",
    "meditazione guidata italiano",
    "come dormire meglio la notte",
    "apnea del sonno cause e rimedi",
    "stress lavorativo come gestirlo",
    "ansia cosa fare senza farmaci",
    "burnout sintomi e rimedi",
    "come smettere di fumare 2026",
    "integratori naturali per energia",
    "creatina come usarla",
    "proteine del siero di latte migliori",
    "pre workout naturale ricetta",
    "come migliorare la memoria",
    "come concentrarsi meglio nello studio",
    "tecnica pomodoro studio efficace",
    "imparare l'inglese velocemente adulti",
    "app per imparare lo spagnolo gratis",
    "duolingo funziona davvero",
    "corso di tedesco online certificato",
    "come imparare il giapponese da zero",
    "libri da leggere estate 2026",
    "migliori romanzi italiani contemporanei",
    "classici letteratura italiana consigliati",
    "fantasy italiano serie consigliata",
    "thriller psicologico migliore 2026",
    "biografie interessanti da leggere",
    "libri di crescita personale davvero utili",
    "libro filosofia per principianti",
    "libri di storia italiana consigliati",
    "storia seconda guerra mondiale libri",
    "documentari netflix storia consigliati",
    "serie tv italiane migliori 2026",
    "serie tv fantascienza da vedere",
    "film horror psicologico migliore",
    "film drammatico candidato oscar 2026",
    "anime da iniziare per principianti",
    "manga consigliati adulti",
    "videogiochi pc migliori 2026",
    "giochi rpg pc open world",
    "giochi indie gratuiti steam",
    "ps5 giochi imperdibili 2026",
    "switch 2 vale la pena comprare",
    "migliore build pc gaming 2026 budget",
    "come overcloccare cpu in sicurezza",
    "gpu migliore rapporto qualita prezzo",
    "ram ddr5 quanta ne serve",
    "ssd nvme o sata differenza",
    "come assemblare un pc da zero",
    "raffreddamento liquido vs aria cpu",
    "case pc silenzioso migliore",
    "alimentatore pc quanti watt servono",
    "monitor gaming 144hz 1ms consigliato",
    "chitarra acustica principiante quale comprare",
    "come imparare la chitarra da soli",
    "corsi online chitarra classica gratuiti",
    "ukulele facile da imparare",
    "pianoforte digitale casa quale scegliere",
    "batteria elettronica appartamento silenzio",
    "come produrre musica in casa software",
    "ableton live corso italiano",
    "spotify premium vale la pena 2026",
    "fotografia ritratto consigli pratici",
    "migliore fotocamera mirrorless principiante",
    "obiettivo 50mm per streetphoto",
    "post produzione lightroom tutorial",
    "come fare belle foto col telefono",
    "gopro o action cam economica confronto",
    "drone fotografico quale comprare 2026",
    "fai da te mensole muro come fare",
    "verniciare mobili ikea tutorial",
    "come pulire le fughe del bagno",
    "trucchi per pulire casa velocemente",
    "detersivo fai da te ingredienti",
    "organizzare armadio metodo konmari",
    "domotica casa senza fili come iniziare",
    "lampadine smart compatibili alexa",
    "risparmio energetico casa consigli",
    "fotovoltaico casa costo e risparmio",
    "pompa di calore conviene 2026",
    "caldaia a condensazione manutenzione",
    "giardinaggio balcone piante facili",
    "orto sul balcone come iniziare",
    "piante da interno non tossiche gatti",
    "bonsai principianti quale scegliere",
    "compostiera casa odori come evitare",
    "api sul balcone arnie urbane",
    "auto elettrica conviene 2026 italia",
    "migliore auto elettrica range lungo",
    "colonnina ricarica casa installazione costo",
    "patente b costo totale 2026",
    "assicurazione rc auto economica",
    "bollo auto esenzione elettrica",
    "manutenzione auto fai da te base",
    "cambio gomme quando obbligatorio",
    "pneumatici invernali migliori 2026",
    "olio motore quale usare",
    "auto usata come controllare prima di comprare",
    "leasing auto conviene privati",
    "moto patente a2 migliori 2026",
    "scooter elettrico citta migliore",
    "bici elettrica pedalata assistita 2026",
    "730 precompilato come compilare",
    "tasse partita iva forfettario 2026",
    "deduzione spese mediche 730",
    "bonus ristrutturazione casa 2026",
    "superbonus stato aggiornamento 2026",
    "mutuo casa tasso fisso o variabile",
    "investire in borsa principianti",
    "etf migliori lungo termine",
    "conto deposito tassi 2026",
    "criptovalute rischi 2026",
    "bitcoin previsioni 2026",
    "pensione anticipata come funziona",
    "tfr lasciare in azienda o fondo pensione",
    "isee come fare domanda",
    "assegno unico figli importo",
    "bonus bebé requisiti 2026",
    "laurea online riconosciuta in italia",
    "universita telematica migliore 2026",
    "master online lavorare e studiare",
    "certificazione linguistica b2 come prepararsi",
    "certificazione it migliore richiesta aziende",
    "corso project management pmp",
    "linkedin ottimizzare profilo trovare lavoro",
    "curriculum vitae europeo come fare",
    "colloquio di lavoro domande tipiche",
    "come chiedere aumento stipendio",
    "smart working diritti lavoratori 2026",
    "contratto a tempo determinato proroga limiti",
    "partita iva aprire come fare 2026",
    "srl vs srls differenza vantaggi",
    "finanziamenti startup italiani 2026",
    "psicologia relazioni di coppia libro",
    "comunicazione nonviolenta esempi pratici",
    "come gestire un conflitto con un amico",
    "dipendenza affettiva come uscirne",
    "narcisismo nel partner segnali",
    "come fare nuove amicizie da adulti",
    "introversione forza non debolezza",
    "autostima bassa come migliorarla",
    "terapia cognitivo comportamentale funziona",
    "psicologo online economico 2026",
    "come organizzare il tempo meglio",
    "bullet journal come iniziare",
    "notion template produttivita",
    "obsidian vs notion quale usare",
    "seconda brain metodo zettelkasten",
    "corso astronomia amatori online",
    "telescopio principiante quale comprare",
    "eclissi solare 2026 quando dove",
    "aurora boreale quando vederla italia",
    "fisica quantistica spiegazione semplice",
    "intelligenza artificiale generale quando arriva",
    "cambiamento climatico dati aggiornati",
    "energia rinnovabile casa costi 2026",
    "riciclo plastica come funziona davvero",
    "alimentazione sostenibile consigli pratici",
    "cosa non buttare nel differenziato",
    "come ridurre impronta carbonica personale",
    "acqua del rubinetto sicura bere italia",
    "purificatore acqua domestico quale scegliere",
    "qualita aria interna casa migliorare",
    "piante purificanti aria interna",
    "corsa mattina benefici sulla salute",
    "camminare 10000 passi al giorno risultati",
    "ciclismo urbano sicurezza consigli",
    "nuoto adulti principianti come iniziare",
    "arrampicata indoor principianti cosa serve",
    "pilates differenza con yoga",
    "taekwondo adulti iniziare",
    "padel come si gioca regole",
    "running scarpe migliori 2026",
    "zaino trekking leggero quale scegliere",
    "tenda da campeggio ultraleggera",
    "sacco a pelo temperatura zero gradi",
    "borraccia termica migliore 2026",
    "viaggio zaino in spalla consigli",
    "lavorare da remoto viaggiando nomade digitale",
    "assicurazione sanitaria estero annuale",
    "passaporto italiano rinnovo quanto costa",
    "visto usa quanto tempo per ottenere",
    "esta america come fare domanda",
    "viaggio cina documenti necessari 2026",
    "come fare la valigia minimale",
    "app viaggio indispensabili 2026",
    "google maps offline come salvare",
    "traduttore offline migliore app 2026",
    "convertitore valuta app gratuita",
    "sicurezza informatica consigli base",
    "password manager quale usare gratuito",
    "autenticazione a due fattori come attivare",
    "phishing email come riconoscerlo",
    "furto identita online cosa fare",
    "gdpr diritto alla cancellazione come esercitare",
    "disdire abbonamento palestra lettera",
    "reclamo operatore telefonico come fare",
    "diritti consumatore acquisto online",
    "reso amazon tempi e modalita",
    "truffa online cosa fare denuncia",
    "codice fiscale straniero come ottenerlo",
    "residenza anagrafica cambio come fare",
    "patente straniera conversione italiana",
    "certificato di nascita dove richiederlo",
    "matrimonio civile documenti necessari",
    "divorzio consensuale costi italia",
    "testamento olografo come scriverlo",
    "eredita tasse successione italiana",
    "affitto casa diritti inquilino",
    "sfratto tempi e procedura",
    "condominio rumori orari consentiti",
    "problema umidita muri casa rimedi",
    "infiltrazione acqua tetto chi paga",
    "caldaia rotta locatario o proprietario",
    "bolletta luce come leggere",
    "offerta energia elettrica migliore 2026",
    "gas naturale prezzo 2026 andamento",
    "internet fibra migliore offerta 2026",
    "telefonia mobile migliore operatore",
    "perché il cielo è blu spiegazione",
    "come funziona un motore a scoppio",
    "differenza tra dna e rna",
    "come si forma un arcobaleno",
    "perché le foglie cambiano colore autunno",
    "come funziona la memoria umana",
    "perché si sbadigliare contagiosamente",
    "quanto dura un ciclo del sonno",
    "come funziona il sistema immunitario",
    "differenza tra virus e batterio",
    "antibiotici quando non vanno presi",
    "vaccini come funzionano spiegazione",
    "colesterolo alto cosa mangiare",
    "pressione alta rimedi naturali",
    "diabete tipo 2 prevenzione alimentazione",
    "celiachia sintomi e diagnosi",
    "intolleranza al lattosio test",
    "psoriasi cura 2026",
    "acne adulta cause e rimedi",
    "caduta capelli uomo rimedi efficaci",
    "come migliorare la vista naturalmente",
    "esercizi occhi stanco schermo",
    "colonna vertebrale esercizi mattina",
    "ginocchio dolore correndo cosa fare",
    "fascite plantare come curarla",
    "tendinite spalla rimedi casa",
    "crampi notturni gambe cause",
    "ferritina bassa sintomi e cure",
    "vitamina b12 carenza segnali",
    "magnesio quando prenderlo",
    "zinco per rafforzare le difese",
    "come aumentare la serotonina naturalmente",
    "dopamina come stimolarla senza sostanze",
    "abitudini mattutine persone di successo",
    "abitudine fare sport come instaurarla",
    "procrastinazione come smettere metodo",
    "mente wandering come controllare i pensieri",
    "journaling benefici scientifici",
    "gratitudine pratica quotidiana effetti",
    "mindfulness 5 minuti al giorno",
    "respirazione diaframmatica esercizio",
    "come costruire disciplina personale",
    "come uscire dalla zona di comfort",
    "paura del fallimento come superarla",
    "sindrome dell'impostore cosa fare",
    "perfezionismo paralisi come sbloccarsi",
    "creatività come stimolarla ogni giorno",
    "pensiero laterale esercizi pratici",
    "problem solving tecniche efficaci",
    "comunicazione assertiva esempi concreti",
    "ascolto attivo tecniche",
    "public speaking paura come gestirla",
    "parlare in pubblico corsi online",
    "storytelling aziendale tecniche base",
    "presentazione powerpoint consigli",
    "foglio excel formula media ponderata",
    "google sheets tutorial italiano",
    "notion database come creare",
    "trello vs asana quale scegliere",
    "todo list app migliore 2026",
    "calendario digitale condiviso come fare",
    "gestione email zero inbox metodo",
    "slack o teams quale usare in azienda",
    "zoom alternativa gratuita 2026",
    "google meet vs zoom confronto",
    "firma digitale come ottenerla gratis",
    "fattura elettronica come fare da solo",
    "contabilità semplificata come tenere",
    "dichiarazione redditi online guida",
    "come aprire un conto bancario online",
    "revolut o n26 quale scegliere",
    "paypal commissioni come ridurle",
    "satispay come funziona",
    "google pay sicuro usare",
    "conto corrente zero spese 2026",
    "obbligazioni vs azioni differenza",
    "pac piano accumulo capitale come fare",
    "rendita passiva idee concrete 2026",
    "crowdfunding immobiliare conviene",
    "p2p lending rischi italia",
    "criptovaluta ethereum come comprare",
    "nft cosa sono spiegazione semplice",
    "blockchain uso pratico non speculativo",
    "assicurazione vita quando farla",
    "fondo pensione integrativo migliore",
    "rottamazione cartelle 2026 istruzioni",
    "sanatoria fiscale 2026 dettagli",
]
