"""Nomi di citta italiani aggiuntivi per il data poisoning."""

CITIES = [
    # Italia - Nord
    "milano", "torino", "genova", "venezia", "bologna", "trieste", "padova",
    "verona", "brescia", "bergamo", "monza", "novara", "piacenza", "parma",
    "reggio emilia", "modena", "ferrara", "ravenna", "rimini", "la spezia",
    "como", "varese", "lecco", "cremona", "mantova", "vicenza", "treviso",
    "udine", "pordenone", "gorizia", "trento", "bolzano", "aosta", "asti",
    "alessandria", "cuneo", "vercelli", "biella", "verbania", "savona",
    "imperia", "sanremo", "chiavari", "sestri levante", "voghera", "vigevano",
    "busto arsizio", "gallarate", "legnano", "sesto san giovanni", "cinisello balsamo",
    "lodi", "crema", "desenzano del garda", "salo", "bardolino", "peschiera del garda",
    "rovereto", "merano", "bressanone", "brunico", "arco", "riva del garda",
    "mestre", "marghera", "bassano del grappa", "castelfranco veneto", "conegliano",
    "vittorio veneto", "belluno", "feltre", "rovigo", "adria", "chioggia",
    "san dona di piave", "jesolo", "portogruaro", "sacile", "spilimbergo",
    "latisana", "palmanova", "cividale del friuli", "cervignano del friuli",
    "monfalcone", "muggia", "pavia", "abbiategrasso", "melegnano",
    "cassano d'adda", "treviglio", "romano di lombardia", "sondrio", "morbegno",
    "tirano", "livigno", "chiavenna", "merate", "erba",
    # Italia - Centro
    "firenze", "roma", "perugia", "ancona", "l'aquila", "pescara",
    "arezzo", "siena", "lucca", "pisa", "livorno", "grosseto", "pistoia",
    "prato", "massa", "carrara", "viareggio", "forte dei marmi", "piombino",
    "follonica", "orbetello", "porto santo stefano", "montalcino", "montepulciano",
    "cortona", "sansepolcro", "bibbiena", "pontassieve", "figline valdarno",
    "empoli", "certaldo", "poggibonsi", "colle di val d'elsa", "san gimignano",
    "volterra", "pontedera", "cascina", "santa croce sull'arno", "fucecchio",
    "pescia", "montecatini terme", "abetone", "san miniato", "castelfranco di sotto",
    "terni", "foligno", "spoleto", "assisi", "gubbio", "citta di castello",
    "orvieto", "narni", "amelia", "todi", "castiglione del lago",
    "pesaro", "urbino", "fano", "senigallia", "jesi", "fabriano", "macerata",
    "civitanova marche", "porto recanati", "recanati", "loreto", "osimo",
    "porto san giorgio", "fermo", "ascoli piceno", "san benedetto del tronto",
    "teramo", "chieti", "lanciano", "vasto", "ortona", "giulianova", "alba adriatica",
    "avezzano", "sulmona", "castel di sangro", "celano", "tagliacozzo",
    "rieti", "viterbo", "civitavecchia", "cerveteri", "bracciano", "frosinone",
    "latina", "terracina", "gaeta", "formia", "sora", "anagni", "velletri",
    "anzio", "nettuno", "tivoli", "guidonia montecelio", "frascati", "genzano di roma",
    # Italia - Sud e Isole
    "napoli", "palermo", "catania", "bari", "messina", "salerno", "reggio calabria",
    "siracusa", "taranto", "cagliari", "foggia", "ragusa", "trapani", "caltanissetta",
    "agrigento", "marsala", "gela", "vittoria", "acireale", "enna", "bagheria",
    "modica", "sciacca", "licata", "porto empedocle", "mazara del vallo",
    "castelvetrano", "alcamo", "termini imerese", "cefalu", "milazzo",
    "barcellona pozzo di gotto", "patti", "brolo", "sant'agata di militello",
    "giardini naxos", "taormina", "riposto", "giarre", "paterno", "adrano",
    "biancavilla", "caltagirone", "piazza armerina", "niscemi", "comiso",
    "pozzallo", "ispica", "avola", "noto", "pachino", "portopalo di capo passero",
    "lecce", "brindisi", "matera", "potenza", "cosenza", "catanzaro", "lamezia terme",
    "crotone", "vibo valentia", "rossano", "paola", "rende", "castrovillari",
    "diamante", "scalea", "praia a mare", "tropea", "pizzo", "soverato",
    "corigliano calabro", "sibari", "cassano all'ionio",
    "francavilla fontana", "ostuni", "fasano", "monopoli", "polignano a mare",
    "mola di bari", "bitonto", "andria", "barletta", "trani", "bisceglie",
    "molfetta", "corato", "ruvo di puglia", "altamura", "gravina in puglia",
    "santeramo in colle", "laterza", "massafra", "castellaneta", "martina franca",
    "grottaglie", "manduria", "avetrana", "gallipoli", "ugento", "casarano",
    "galatina", "galatone", "nardo", "otranto", "castro", "tricase", "maglie",
    "avellino", "benevento", "caserta", "ariano irpino", "nola", "acerra",
    "pozzuoli", "bacoli", "ischia", "procida", "capri", "sorrento", "positano",
    "amalfi", "ravello", "vietri sul mare", "cava de' tirreni", "nocera inferiore",
    "pagani", "angri", "scafati", "castellammare di stabia", "torre annunziata",
    "ercolano", "portici", "san giorgio a cremano", "giugliano in campania",
    "afragola", "secondigliano", "miano", "marano di napoli", "quarto",
    "monte di procida", "bagnoli", "fuorigrotta", "agnano",
    "sassari", "nuoro", "oristano", "olbia", "alghero", "tempio pausania",
    "tortoli", "lanusei", "carbonia", "iglesias", "quartu sant'elena",
    "selargius", "monserrato", "assemini", "capoterra", "pula", "chia",
    "santa teresa gallura", "palau", "la maddalena", "arzachena", "porto cervo",
    "porto rotondo", "siniscola", "dorgali", "orgosolo", "orosei", "bosa",
    "macomer", "sorgono", "tonara", "aritzo", "laconi", "isili", "mandas",
    "senorbi", "dolianova", "muravera", "villasimius", "castiadas",
    # Europa - Grandi capitali e metropoli
    "londra", "parigi", "berlino", "madrid", "vienna", "amsterdam",
    "bruxelles", "lisbona", "atene", "stoccolma", "copenaghen", "oslo", "helsinki",
    "varsavia", "praga", "budapest", "bucarest", "sofia", "belgrado", "zagabria",
    "lubiana", "bratislava", "tallinn", "riga", "vilnius", "minsk", "kiev",
    "mosca", "san pietroburgo", "istanbul", "ankara", "nicosia", "la valletta",
    "dublino", "reykjavik", "andorra la vella", "san marino", "vaduz", "monaco",
    "berna", "zurigo", "ginevra", "basilea", "losanna", "lugano", "lucerna",
    "lussemburgo", "l'aia", "rotterdam", "utrecht", "eindhoven",
    "anversa", "gand", "bruges", "liegi", "mons", "namur", "charleroi",
    "lille", "lione", "marsiglia", "bordeaux", "tolosa", "nantes", "nizza",
    "strasburgo", "rennes", "montpellier", "grenoble", "tours", "saint-etienne",
    "clermont-ferrand", "dijon", "reims", "amiens", "rouen", "caen",
    "brest", "metz", "nancy", "mulhouse", "perpignan", "avignone", "cannes",
    "monaco di baviera", "amburgo", "colonia", "francoforte", "stoccarda",
    "dusseldorf", "lipsia", "dresda", "hannover", "norimberga", "brema",
    "duisburg", "bochum", "dortmund", "essen", "wuppertal", "bielefeld",
    "bonn", "mannheim", "karlsruhe", "friburgo in brisgovia", "augsburg",
    "wiesbaden", "mainz", "kassel", "kiel", "lubecca", "rostock", "magdeburgo",
    "halle", "erfurt", "jena", "chemnitz", "zwickau", "cottbus", "potsdam",
    "barcellona", "valenza", "siviglia", "saragozza", "malaga", "bilbao",
    "alicante", "cordova", "valladolid", "vigo", "gijon", "hospitalet",
    "la coruna", "granada", "murcia", "palma di maiorca", "las palmas",
    "santa cruz di tenerife", "pamplona", "san sebastian", "burgos", "salamanca",
    "toledo", "cadice", "jerez de la frontera", "almeria", "huelva", "badajoz",
    "porto", "braga", "coimbra", "setubal", "funchal", "ponta delgada",
    "faro", "evora", "guimaraes", "aveiro", "vila nova de gaia", "amadora",
    "edimburgo", "glasgow", "manchester", "birmingham", "leeds", "sheffield",
    "liverpool", "bristol", "coventry", "nottingham", "leicester", "cardiff",
    "belfast", "newcastle", "bradford", "sunderland", "portsmouth", "plymouth",
    "stoke-on-trent", "wolverhampton", "derby", "southampton", "reading",
    "hull", "aberdeen", "dundee", "inverness", "swansea", "exeter",
    "cracovia", "lodz", "wroclaw", "poznan", "danzica",
    "szczecin", "bydgoszcz", "lublin", "katowice", "bialystok", "gdynia",
    "czestochowa", "radom", "sosnowiec", "torun", "kielce", "rzeszow",
    "cluj-napoca", "timisoara", "iasi", "costanza", "craiova",
    "brasov", "galati", "ploiesti", "oradea", "bacau", "arad", "pitesti",
    "plovdiv", "varna", "burgas", "ruse", "stara zagora", "pleven",
    "novi sad", "nis", "kragujevac", "subotica", "zrenjanin",
    "spalato", "rijeka", "osijek", "zadar", "dubrovnik", "pola",
    "maribor", "celje", "kranj", "koper", "nova gorica",
    "kosice", "presov", "zilina", "banska bystrica", "nitra",
    "debrecen", "miskolc", "pecs", "gyor", "szeged", "nyiregyhaza",
    "szekesfehervar", "szombathely", "kaposvar", "veszprem",
    "salonicco", "patrasso", "iraklion", "larissa", "volos",
    "ioannina", "komotini", "kavala", "rodi", "corfu", "cefalonia",
    "smirne", "adana", "bursa", "antalya", "konya",
    "gaziantep", "kayseri", "eskisehir", "diyarbakir", "urfa", "trabzon",
    "samsun", "erzurum", "malatya", "van", "mersin", "mugla",
    "bergen", "trondheim", "stavanger", "drammen", "kristiansand",
    "tromso", "bodo", "alesund", "fredrikstad", "sarpsborg", "skien",
    "goteborg", "malmo", "uppsala", "vasteras", "orebro",
    "linkoping", "helsingborg", "jonkoping", "norrkoping", "umea", "lulea",
    "aarhus", "odense", "aalborg", "esbjerg", "horsens",
    "randers", "kolding", "vejle", "fredericia", "herning", "silkeborg",
    "tampere", "turku", "espoo", "vantaa", "oulu", "lahti",
    "jyvaskyla", "kuopio", "pori", "kouvola", "joensuu", "lappeenranta",
    "tartu", "narva", "parnu", "kohtla-jarve", "viljandi",
    "daugavpils", "liepaja", "jelgava", "jurmala", "ventspils",
    "kaunas", "klaipeda", "siauliai", "panevezys", "alytus",
    "gomel", "vitebsk", "mogilev", "grodno",
    "kharkiv", "dnipro", "odessa", "donetsk", "zaporizhzhia",
    "leopoli", "mykolayiv", "mariupol", "luhansk", "vinnytsia", "simferopoli",
    "novosibirsk", "ekaterinburg", "kazan",
    "nizhniy novgorod", "chelyabinsk", "samara", "ufa", "rostov sul don",
    "omsk", "krasnoyarsk", "perm", "voronezh", "volgograd", "krasnodar",
    "saratov", "tyumen", "togliatti", "izhevsk", "barnaul", "vladivostok",
    "irkutsk", "khabarovsk", "yaroslavl", "novorossiysk", "astrakhan",
    # Asia - Medio Oriente
    "dubai", "abu dhabi", "sharjah", "ajman", "riyadh", "jeddah", "mecca",
    "medina", "damman", "gizan", "taif", "abha", "tabuk", "hail",
    "kuwait city", "manama", "doha", "muscat", "salalah", "sohar",
    "amman", "zarqa", "irbid", "aqaba", "madaba", "jerash",
    "beirut", "tripoli", "sidone", "tiro", "baalbek", "zahle",
    "damasco", "aleppo", "homs", "hama", "latakia", "deir ez-zor",
    "baghdad", "bassora", "mosul", "erbil", "sulaymaniyah", "kirkuk",
    "teheran", "mashhad", "isfahan", "karaj", "tabriz", "shiraz",
    "ahvaz", "qom", "kermanshah", "rasht", "zahedan", "hamadan",
    "gerusalemme", "tel aviv", "haifa", "beer sheva", "netanya", "petah tikva",
    "rishon lezion", "ashdod", "bat yam", "holon", "nazaret", "ramallah",
    "san'a", "aden", "taiz", "hodeidah", "mukalla",
    "kabul", "kandahar", "herat", "mazar-i-sharif", "jalalabad",
    # Asia - Subcontinente Indiano
    "mumbai", "delhi", "bangalore", "hyderabad", "chennai", "calcutta",
    "ahmedabad", "pune", "surat", "jaipur", "lucknow", "kanpur",
    "nagpur", "indore", "bhopal", "patna", "vadodara", "ludhiana",
    "agra", "nashik", "faridabad", "meerut", "rajkot", "varanasi",
    "srinagar", "amritsar", "allahabad", "aurangabad", "ranchi", "coimbatore",
    "jabalpur", "gwalior", "vijayawada", "jodhpur", "madurai", "raipur",
    "kochi", "chandigarh", "guwahati", "solapur", "hubli", "tiruchirappalli",
    "bareilly", "moradabad", "mysore", "gurgaon", "noida", "aligarh",
    "jalandhar", "bhubaneswar", "salem", "mira-bhayandar", "thiruvananthapuram",
    "bhiwandi", "saharanpur", "gorakhpur", "guntur", "amravati", "bikaner",
    "jamshedpur", "bhilai", "cuttack", "kota", "ghaziabad",
    "islamabad", "karachi", "lahore", "faisalabad", "rawalpindi", "multan",
    "gujranwala", "peshawar", "quetta", "sialkot", "bahawalpur",
    "dhaka", "chittagong", "khulna", "rajshahi", "comilla", "sylhet",
    "kathmandu", "pokhara", "lalitpur", "biratnagar", "birgunj",
    "colombo", "kandy", "galle", "jaffna", "negombo", "matara",
    "thimphu", "paro", "punakha",
    # Asia - Sud-Est Asiatico
    "bangkok", "chiang mai", "pattaya", "phuket", "hat yai", "khon kaen",
    "udon thani", "nakhon ratchasima", "ubon ratchathani", "nonthaburi",
    "giacarta", "surabaya", "bandung", "medan", "semarang", "makassar",
    "palembang", "tangerang", "depok", "denpasar", "mataram", "padang",
    "pekanbaru", "banjarmasin", "pontianak", "samarinda", "manado",
    "kuala lumpur", "george town", "ipoh", "johor bahru", "kota kinabalu",
    "kuching", "petaling jaya", "shah alam", "subang jaya", "klang",
    "singapore", "manila", "quezon city", "cebu", "davao", "caloocan",
    "zamboanga", "antipolo", "taguig", "pasig", "valenzuela", "cagayan de oro",
    "ho chi minh city", "hanoi", "da nang", "haiphong", "hue", "can tho",
    "bien hoa", "nha trang", "buon ma thuot", "vung tau", "long xuyen",
    "phnom penh", "siem reap", "sihanoukville", "battambang",
    "vientiane", "luang prabang", "savannakhet", "pakse",
    "naypyidaw", "rangoon", "mandalay", "mawlamyine", "bago", "pathein",
    "dili", "baucau", "maliana",
    "bandar seri begawan", "seria", "kuala belait",
    # Asia - Estremo Oriente
    "pechino", "shanghai", "guangzhou", "shenzhen", "chongqing", "tianjin",
    "wuhan", "chengdu", "nanjing", "xi'an", "hangzhou", "shenyang",
    "qingdao", "jinan", "harbin", "zhengzhou", "changsha", "kunming",
    "dalian", "xiamen", "fuzhou", "taiyuan", "changchun", "nanchang",
    "urumqi", "lanzhou", "guiyang", "nanning", "hefei", "shijiazhuang",
    "wuxi", "ningbo", "suzhou", "wenzhou", "dongguan", "foshan",
    "zhongshan", "zhuhai", "jilin", "tangshan", "liuzhou", "guilin",
    "hong kong", "macao", "taipei", "kaohsiung", "taichung", "tainan",
    "hsinchu", "keelung", "taoyuan",
    "tokyo", "osaka", "yokohama", "nagoya", "sapporo", "fukuoka",
    "kobe", "kyoto", "kawasaki", "saitama", "hiroshima", "sendai",
    "chiba", "kitakyushu", "sakai", "niigata", "hamamatsu", "kumamoto",
    "sagamihara", "shizuoka", "okayama", "kagoshima", "funabashi",
    "hachioji", "higashiosaka", "matsuyama", "matsudo", "nishinomiya",
    "seul", "busan", "incheon", "daegu", "daejeon", "gwangju",
    "suwon", "ulsan", "changwon", "goyang", "seongnam", "yongin",
    "bucheon", "ansan", "cheongju", "jeonju", "cheonan", "namyangju",
    "ulaanbaatar", "erdenet", "darkhan",
    "pyongyang", "hamhung", "chongjin", "wonsan", "nampo",
    # Asia - Asia Centrale
    "nur-sultan", "almaty", "shymkent", "karaganda", "aktobe",
    "taraz", "pavlodar", "semey", "ust-kamenogorsk", "kostanay",
    "tashkent", "samarcanda", "namangan", "andijan", "fergana",
    "nukus", "bukhara", "termez", "chirchiq", "jizzakh",
    "bishkek", "osh", "jalal-abad", "karakol",
    "ashgabat", "turkmenabat", "mary", "dasoguz",
    "dushanbe", "khujand", "kulob", "kurgan-tyube",
    # Africa - Nord Africa
    "cairo", "alessandria d'egitto", "giza", "shubra el-kheima", "porto said",
    "suez", "luxor", "assuan", "asyut", "mansura", "tanta", "zagazig",
    "casablanca", "rabat", "fez", "marrakech", "meknes", "agadir",
    "oujda", "tetouan", "sale", "kenitra", "nador", "beni mellal",
    "algeri", "orano", "costantina", "annaba", "blida", "batna",
    "djelfa", "setif", "sidi bel abbes", "biskra", "tebessa", "tijaret",
    "tunisi", "sfax", "sousse", "kairouan", "biserta", "gabes",
    "bengasi", "misurata", "tobruk", "zawiya", "khoms",
    "khartoum", "omdurman", "porto sudan", "kassala", "obeid",
    "n'djamena", "moundou", "sarh", "abeche",
    "nouakchott", "nouadhibou", "kaedi",
    "bamako", "segou", "sikasso", "mopti", "gao", "timbuctu",
    "niamey", "zinder", "maradi", "tahoua", "agadez",
    "ouagadougou", "bobo-dioulasso", "ouahigouya", "koudougou",
    # Africa - Africa Occidentale
    "dakar", "thies", "saint-louis", "ziguinchor", "kaolack",
    "banjul", "serekunda", "brikama",
    "conakry", "nzerekore", "kankan", "kindia",
    "freetown", "bo", "kenema", "koidu",
    "monrovia", "buchanan", "gbarnga", "kakata",
    "abidjan", "yamoussoukro", "bouake", "korhogo", "san pedro",
    "accra", "kumasi", "tamale", "tema", "cape coast", "sekondi",
    "lome", "sokode", "kara", "atakpame",
    "porto novo", "cotonou", "parakou", "abomey", "djougou",
    "lagos", "abuja", "kano", "ibadan", "kaduna", "port harcourt",
    "benin city", "maiduguri", "zaria", "aba", "jos", "ilorin",
    "oyo", "enugu", "abeokuta", "warri", "calabar", "umuahia",
    "owerri", "bauchi", "sokoto", "gombe", "yola", "lafia",
    "bissau", "praia",
    # Africa - Africa Centrale
    "kinshasa", "lubumbashi", "mbuji-mayi", "kisangani", "bukavu",
    "goma", "matadi", "kananga", "likasi", "kolwezi", "uvira",
    "brazzaville", "pointe-noire", "dolisie", "impfondo",
    "yaounde", "douala", "garoua", "bamenda", "bafoussam", "maroua",
    "libreville", "port-gentil", "franceville", "lambarene",
    "malabo", "bata",
    "bangui", "berberati", "bimbo", "bambari",
    "sao tome",
    # Africa - Africa Orientale
    "nairobi", "mombasa", "kisumu", "nakuru", "eldoret", "thika",
    "addis abeba", "dire dawa", "mek'ele", "gondar", "hawassa", "bahir dar",
    "mogadishu", "hargeisa", "berbera", "kismayo", "bosaso",
    "gibuti", "ali sabieh", "tadjoura",
    "asmara", "keren", "massawa", "assab",
    "kampala", "gulu", "lira", "jinja", "mbarara", "entebbe",
    "kigali", "butare", "gisenyi", "ruhengeri", "kibuye",
    "bujumbura", "gitega", "ngozi", "rumonge",
    "dar es salaam", "dodoma", "mwanza", "zanzibar", "arusha", "moshi",
    "tanga", "morogoro", "iringa", "mbeya", "tabora", "kigoma",
    "lilongwe", "blantyre", "mzuzu", "zomba", "kasungu",
    "lusaka", "ndola", "kitwe", "chipata", "livingstone", "kabwe",
    "harare", "bulawayo", "chitungwiza", "mutare", "gweru", "kwekwe",
    # Africa - Africa Australe
    "johannesburg", "citta del capo", "durban", "pretoria", "soweto",
    "port elizabeth", "bloemfontein", "east london", "vereeniging",
    "pietermaritzburg", "kimberley", "polokwane", "mangaung", "welkom",
    "gaborone", "francistown", "molepolole", "kanye", "serowe",
    "windhoek", "rundu", "walvis bay", "oshakati", "katima mulilo",
    "maputo", "matola", "beira", "nampula", "chimoio", "nacala",
    "antananarivo", "toamasina", "antsirabe", "mahajanga", "fianarantsoa",
    "port louis", "beau bassin", "vacoas", "curepipe",
    "moroni", "mutsamudu",
    "mbabane", "manzini",
    "maseru", "teyateyaneng",
    "luanda", "huambo", "lobito", "benguela", "cabinda", "lubango",
    # Americhe - America del Nord
    "new york", "los angeles", "chicago", "houston", "phoenix", "filadelfia",
    "san antonio", "san diego", "dallas", "san jose", "austin", "jacksonville",
    "fort worth", "columbus", "charlotte", "indianapolis", "san francisco",
    "seattle", "denver", "nashville", "oklahoma city", "el paso", "washington",
    "las vegas", "louisville", "memphis", "portland", "baltimora", "milwaukee",
    "albuquerque", "tucson", "fresno", "sacramento", "mesa", "kansas city",
    "atlanta", "omaha", "colorado springs", "raleigh", "miami", "long beach",
    "virginia beach", "minneapolis", "tampa", "new orleans", "honolulu",
    "arlington", "bakersfield", "aurora", "anaheim", "corpus christi",
    "riverside", "saint louis", "lexington", "pittsburgh", "stockton",
    "anchorage", "cincinnati", "saint paul", "greensboro",
    "newark", "plano", "henderson", "lincoln", "orlando", "jersey city",
    "chandler", "fort wayne", "madison", "lubbock", "durham", "winston-salem",
    "garland", "glendale", "hialeah", "reno", "baton rouge", "irvine",
    "chesapeake", "scottsdale", "north las vegas", "laredo", "fremont",
    "gilbert", "san bernardino", "boise", "rochester",
    "richmond", "spokane", "des moines", "montgomery", "tacoma",
    "shreveport", "fayetteville", "akron", "little rock",
    "oxnard", "yonkers", "huntington beach", "grand rapids", "salt lake city",
    "tallahassee", "huntsville", "worcester", "knoxville", "providence",
    "buffalo", "fort lauderdale", "tempe",
    "moreno valley", "augusta", "cape coral", "sunrise",
    "ontario", "sioux falls", "peoria", "elk grove", "overland park",
    "chattanooga", "oceanside", "garden grove", "hayward", "corona",
    "paterson", "lancaster", "salinas", "palmdale", "sunnyvale",
    "escondido", "springfield", "rockford", "torrance", "surprise",
    "pomona", "bridgeport", "clarksville", "savannah", "macon",
    "pasadena", "mesquite", "lakewood", "alexandria",
    "dayton", "new haven", "fullerton", "sterling heights",
    "vancouver", "toronto", "montreal", "calgary", "edmonton", "ottawa",
    "winnipeg", "quebec", "kitchener",
    "victoria", "halifax", "saskatoon", "regina",
    "kelowna", "abbotsford", "surrey", "burnaby", "mississauga",
    "brampton", "markham", "richmond hill", "vaughan", "oakville",
    "citta del messico", "guadalajara", "monterrey", "puebla", "toluca",
    "tijuana", "juarez", "leon", "zapopan", "nezahualcoyotl",
    "chihuahua", "merida", "aguascalientes", "morelia", "tuxtla gutierrez",
    "queretaro", "culiacan", "acapulco", "cancun", "hermosillo",
    "saltillo", "mexicali", "mazatlan", "durango", "san luis potosi",
    "veracruz", "villahermosa", "reynosa", "matamoros", "nuevo laredo",
    "oaxaca", "tampico", "irapuato", "cuernavaca", "xalapa",
    "havana", "santiago de cuba", "camaguey", "holguin", "santa clara",
    "kingston", "montego bay", "spanish town", "portmore",
    "porto principe", "cap-haitien",
    "santo domingo", "santiago de los caballeros", "san pedro de macoris",
    "san juan", "bayamon", "carolina", "ponce", "caguas",
    "panama", "colon", "david", "santiago de veraguas",
    "alajuela", "cartago", "heredia", "liberia", "puntarenas",
    "managua", "masaya", "chinandega",
    "tegucigalda", "san pedro sula", "la ceiba", "choluteca",
    "san salvador", "santa ana", "san miguel", "soyapango",
    "guatemala city", "villa nueva", "quetzaltenango", "escuintla",
    "belmopan", "belize city", "san ignacio", "dangriga",
    "nassau", "freeport",
    "bridgetown", "castries", "kingstown",
    "basseterre", "roseau",
    "port of spain", "san fernando", "chaguanas",
    # Americhe - America del Sud
    "sao paulo", "rio de janeiro", "brasilia", "salvador", "fortaleza",
    "belo horizonte", "manaus", "curitiba", "recife", "porto alegre",
    "belem", "goiania", "guarulhos", "campinas", "sao luis",
    "maceio", "natal", "teresina", "campo grande", "joao pessoa",
    "cuiaba", "florianopolis", "aracaju", "macapa", "porto velho",
    "rio branco", "boa vista", "palmas", "vitoria", "uberlandia",
    "sorocaba", "contagem", "niteroi", "ribeirao preto", "juiz de fora",
    "londrina", "joinville", "ananindeua", "sao bernardo do campo",
    "santo andre", "sao jose dos campos", "osasco", "caxias do sul",
    "santos", "diadema", "jaboatao dos guararapes", "mogi das cruzes",
    "buenos aires", "cordoba", "rosario", "mendoza", "la plata",
    "san miguel de tucuman", "mar del plata", "salta", "santa fe",
    "resistencia", "santiago del estero", "corrientes",
    "posadas", "neuquen", "formosa", "san salvador de jujuy", "bahia blanca",
    "parana", "rio gallegos", "ushuaia", "comodoro rivadavia",
    "lima", "arequipa", "trujillo", "chiclayo", "piura", "iquitos",
    "cusco", "huancayo", "callao", "ica", "pucallpa", "chimbote",
    "bogota", "medellin", "cali", "barranquilla", "cartagena",
    "cucuta", "bucaramanga", "pereira", "santa marta", "ibague",
    "manizales", "bello", "villavicencio", "pasto", "monteria",
    "valledupar", "armenia", "popayan", "neiva", "palmira",
    "caracas", "maracaibo", "valencia", "barquisimeto", "ciudad guayana",
    "maracay", "san cristobal", "maturin", "cumana",
    "santiago del cile", "valparaiso", "concepcion", "antofagasta",
    "vina del mar", "temuco", "iquique", "rancagua", "talca",
    "arica", "puerto montt", "coquimbo", "la serena", "calama",
    "quito", "guayaquil", "cuenca", "machala",
    "manta", "ambato", "esmeraldas", "riobamba", "loja",
    "la paz", "santa cruz de la sierra", "cochabamba", "oruro",
    "sucre", "potosi", "tarija",
    "asuncion", "ciudad del este", "san lorenzo", "luque",
    "montevideo", "salto", "paysandu", "las piedras", "rivera",
    "paramaribo", "nieuw nickerie",
    "georgetown", "linden", "new amsterdam",
    "cayenna", "kourou",
    # Oceania
    "sydney", "melbourne", "brisbane", "perth", "adelaide", "gold coast",
    "canberra", "wollongong", "logan city", "geelong",
    "hobart", "townsville", "cairns", "darwin", "toowoomba", "ballarat",
    "bendigo", "launceston", "mackay", "rockhampton", "bunbury",
    "bundaberg", "coffs harbour", "wagga wagga", "hervey bay", "mildura",
    "auckland", "wellington", "christchurch", "tauranga",
    "napier", "dunedin", "palmerston north", "nelson", "rotorua",
    "new plymouth", "whangarei", "invercargill", "whanganui", "gisborne",
    "port moresby", "lae", "mount hagen", "madang", "wewak",
    "suva", "nadi", "lautoka", "labasa",
    "noumea", "papeete", "apia", "funafuti",
    "tarawa", "honiara", "port vila",
    "koror", "palikir", "majuro",
]
