"""Modelli di ricerca italiani legati a luoghi ('{}' = citta) per il data poisoning."""

TEMPLATES = [
    # meteo
    "meteo {}",
    "meteo {} oggi",
    "meteo {} domani",
    "meteo {} questo weekend",
    "meteo {} prossima settimana",
    "meteo {} 10 giorni",
    "meteo {} 15 giorni",
    "meteo {} luglio",
    "meteo {} agosto",
    "meteo {} settembre",
    "meteo {} ottobre",
    "meteo {} novembre",
    "meteo {} dicembre",
    "meteo {} gennaio",
    "meteo {} febbraio",
    "meteo {} marzo",
    "meteo {} aprile",
    "meteo {} maggio",
    "meteo {} giugno",
    "previsioni meteo {}",
    "previsioni meteo {} domani",
    "previsioni meteo {} weekend",
    "temperatura {} oggi",
    "temperatura {} agosto",
    "clima {} in estate",
    "clima {} in inverno",
    "clima {} ad aprile",
    "clima {} a luglio",
    "pioggia {} questa settimana",
    "neve {} dicembre",
    "quando arriva la neve a {}",
    "allerta meteo {}",
    "umidità {} oggi",
    "vento {} oggi",
    "webcam meteo {}",
    # hotel e alloggi
    "hotel {} economici",
    "hotel {} centro",
    "hotel {} 4 stelle",
    "hotel {} 5 stelle",
    "hotel {} vicino alla stazione",
    "hotel {} vicino all'aeroporto",
    "hotel {} con piscina",
    "hotel {} con spa",
    "hotel {} ammette cani",
    "hotel {} pet friendly",
    "hotel {} per famiglie",
    "hotel {} romantico",
    "hotel {} con vista mare",
    "hotel {} con colazione inclusa",
    "migliori hotel {}",
    "ostello {}",
    "ostelli economici {}",
    "bed and breakfast {}",
    "b&b {}",
    "appartamento vacanza {}",
    "airbnb {}",
    "casa vacanze {}",
    "affitto breve {}",
    "agriturismo vicino {}",
    "agriturismo {}",
    "campeggio {}",
    "camping {}",
    "glamping {}",
    "alloggio economico {}",
    "alberghi {}",
    "resort {}",
    "villa affitto {}",
    "locanda {}",
    "motel {}",
    "alloggio a {} per una notte",
    "dove dormire a {}",
    "dormire a {} low cost",
    # ristoranti
    "migliori ristoranti {}",
    "ristoranti {} economici",
    "ristoranti {} vicino a me",
    "ristorante italiano {}",
    "ristorante pesce {}",
    "ristorante carne {}",
    "ristorante pizza {}",
    "miglior pizza {}",
    "pizzeria {}",
    "ristorante vegetariano {}",
    "ristorante vegano {}",
    "ristorante senza glutine {}",
    "ristorante halal {}",
    "ristorante kosher {}",
    "ristorante giapponese {}",
    "ristorante sushi {}",
    "ristorante cinese {}",
    "ristorante indiano {}",
    "ristorante messicano {}",
    "ristorante greco {}",
    "ristorante turco {}",
    "ristorante thai {}",
    "ristorante asiatico {}",
    "ristorante sudamericano {}",
    "ristorante argentino {}",
    "ristorante hamburger {}",
    "ristorante fusion {}",
    "ristorante gourmet {}",
    "ristorante stellato {}",
    "osteria {}",
    "trattoria {}",
    "taverna {}",
    "wine bar {}",
    "enoteca {}",
    "colazione {} dove",
    "miglior colazione {}",
    "brunch {}",
    "aperitivo {}",
    "buffet {}",
    "street food {}",
    "cibo di strada {}",
    "mercato gastronomico {}",
    "dove mangiare a {}",
    "dove mangiare a {} bene e poco",
    "gelato {} migliore",
    "gelateria {}",
    "pasticceria {}",
    "panetteria {}",
    "bakery {}",
    "rosticceria {}",
    "piadineria {}",
    "kebab {}",
    "fast food {}",
    # bar e vita notturna
    "bar {} centro",
    "caffè {} storico",
    "miglior caffè {}",
    "cocktail bar {}",
    "bar aperitivo {}",
    "pub {}",
    "birreria {}",
    "craft beer {}",
    "discoteca {}",
    "nightclub {}",
    "vita notturna {}",
    "locali notturni {}",
    "lounge bar {}",
    "rooftop bar {}",
    "spritz {}",
    "happy hour {}",
    "dove bere a {}",
    "karaoke {}",
    "live music {}",
    "jazz club {}",
    # voli
    "voli per {}",
    "voli da {} a roma",
    "voli da {} a milano",
    "voli da {} a londra",
    "voli da {} a parigi",
    "voli da {} a barcellona",
    "voli da {} a new york",
    "voli da roma a {}",
    "voli da milano a {}",
    "voli low cost per {}",
    "voli economici {}",
    "voli diretti {}",
    "aeroporto di {} come arrivare",
    "aeroporto {} trasporti",
    "aeroporto {} parcheggio",
    "aeroporto {} taxi",
    "aeroporto {} bus",
    "biglietti aerei {}",
    "voli last minute {}",
    "charter {}",
    "compagnie aeree {}",
    # treni
    "treno per {}",
    "treno da {} a napoli",
    "treno da {} a firenze",
    "treno da {} a venezia",
    "treno da {} a torino",
    "treno da {} a bologna",
    "treno da {} a palermo",
    "treno da {} a bari",
    "orari treni {}",
    "stazione ferroviaria {}",
    "stazione {} come raggiungere",
    "trenitalia {}",
    "italo treno {}",
    "frecciarossa {}",
    "intercity {}",
    "regionale {}",
    "biglietti treno {}",
    "prezzo treno {} roma",
    "treno alta velocita {}",
    # bus
    "autobus per {}",
    "pullman {}",
    "flixbus {}",
    "marino bus {}",
    "autolinee {}",
    "orari autobus {}",
    "stazione autobus {}",
    "bus notturno {}",
    "navetta {}",
    "shuttle {}",
    # traghetti
    "traghetto per {}",
    "traghetto da {} a sardegna",
    "traghetto da {} a sicilia",
    "traghetto da {} a corsica",
    "orari traghetti {}",
    "porto di {} traghetti",
    "biglietti traghetto {}",
    "navi {}",
    "compagnie traghetti {}",
    # trasporto locale
    "metro {}",
    "metropolitana {} linee",
    "tram {}",
    "autobus urbano {}",
    "trasporti pubblici {}",
    "abbonamento trasporti {}",
    "taxi {}",
    "noleggio auto {}",
    "autonoleggio {}",
    "noleggio moto {}",
    "noleggio scooter {}",
    "noleggio bici {}",
    "bike sharing {}",
    "monopattino {}",
    "uber {}",
    "parcheggio {}",
    "parcheggio gratuito {}",
    "ztl {}",
    "traffico {} oggi",
    "come spostarsi a {}",
    "come arrivare a {}",
    "come arrivare a {} in treno",
    "come arrivare a {} in aereo",
    "come arrivare a {} in auto",
    # cosa vedere e fare
    "cosa vedere a {}",
    "cosa fare a {}",
    "cosa visitare a {}",
    "attrazioni turistiche {}",
    "luoghi di interesse {}",
    "punti panoramici {}",
    "centro storico {}",
    "musei {}",
    "museo {}",
    "galleria d'arte {}",
    "gallerie {}",
    "arte {}",
    "monumenti {}",
    "chiese {}",
    "cattedrale {}",
    "basilica {}",
    "duomo {}",
    "castello {}",
    "fortezza {}",
    "palazzo {}",
    "palazzo storico {}",
    "villa storica {}",
    "fontana {}",
    "piazza principale {}",
    "piazze {}",
    "porto {}",
    "lungomare {}",
    "spiagge {}",
    "spiagge libere {}",
    "lido {}",
    "stabilimento balneare {}",
    "snorkeling {}",
    "immersioni {}",
    "surf {}",
    "escursioni {}",
    "trekking {}",
    "sentieri {}",
    "sentiero natura {}",
    "parco nazionale {}",
    "parco naturale {}",
    "parco {}",
    "riserva naturale {}",
    "lago {}",
    "cascata {}",
    "grotta {}",
    "grotte {}",
    "vulcano {}",
    "montagna {}",
    "sci {}",
    "impianti sciistici {}",
    "comprensori sciistici {}",
    "zoo {}",
    "acquario {}",
    "parco avventura {}",
    "parco divertimenti {}",
    "escape room {}",
    "bowling {}",
    "cinema {}",
    "teatro {}",
    "opera {}",
    "concerto {}",
    "festival {}",
    "eventi {} questo weekend",
    "eventi {} questa settimana",
    "eventi {} oggi",
    "cosa fare a {} di sera",
    "cosa fare a {} con bambini",
    "cosa fare a {} con la famiglia",
    "cosa fare a {} con il cane",
    "cosa fare a {} in un giorno",
    "cosa fare a {} in due giorni",
    "itinerario {}",
    "itinerario 3 giorni {}",
    "visita guidata {}",
    "tour {}",
    "tour guidato {}",
    "tour privato {}",
    "gita a {}",
    "gita giornaliera a {}",
    "gite da {}",
    "escursione da {} a",
    "day trip {}",
    "tour in barca {}",
    "crociera {}",
    "tramonto a {}",
    "alba a {}",
    "panorama {}",
    "belvedere {}",
    "foto {}",
    "instagram spot {}",
    "luoghi fotografici {}",
    # eventi specifici
    "concerti {} 2025",
    "concerti {} 2026",
    "festival musicale {}",
    "sagra {}",
    "fiera {}",
    "mercatino di natale {}",
    "capodanno {}",
    "carnevale {}",
    "palio {}",
    "fuochi d'artificio {}",
    "manifestazioni {}",
    "mostre {}",
    "mostra d'arte {}",
    "esposizione {}",
    "teatro {} programma",
    "cinema {} programmazione",
    "spettacoli {}",
    "musica live {}",
    "street festival {}",
    # shopping
    "shopping {}",
    "centro commerciale {}",
    "centri commerciali {}",
    "negozi {}",
    "mercato {}",
    "mercatino {}",
    "mercatino vintage {}",
    "mercatino dell'usato {}",
    "mercato delle pulci {}",
    "souvenir {}",
    "dove comprare souvenir {}",
    "prodotti tipici {}",
    "artigianato {}",
    "outlet {}",
    "boutique {}",
    "high street {}",
    "libreria {}",
    "librerie {}",
    "farmacia {}",
    "supermercato {}",
    "market {}",
    "fruttivendolo {}",
    # immobili e affitti
    "appartamento in affitto {}",
    "affitto {}",
    "affitti {}",
    "prezzi affitti {}",
    "affitto monolocale {}",
    "affitto bilocale {}",
    "affitto trilocale {}",
    "affitto stanza {}",
    "stanza in affitto {}",
    "appartamento {} acquisto",
    "comprare casa {}",
    "prezzi immobili {}",
    "mutuo {}",
    "case in vendita {}",
    "villetta {}",
    "investimento immobiliare {}",
    "agenzia immobiliare {}",
    "portale immobili {}",
    "affitto lungo termine {}",
    "affitto breve termine {}",
    "costo vita {}",
    "costo della vita {}",
    "quanto costa vivere a {}",
    "vivere a {}",
    "trasferirti a {}",
    "trasferirsi a {} pro e contro",
    # lavoro e economia
    "lavoro {}",
    "offerte di lavoro {}",
    "trovare lavoro {}",
    "lavoro part time {}",
    "lavoro stagionale {}",
    "stipendio medio {}",
    "salario medio {}",
    "aziende {}",
    "industria {}",
    "economia {}",
    "disoccupazione {}",
    "stage {}",
    "tirocinio {}",
    "lavoro da remoto {}",
    "coworking {}",
    "spazio coworking {}",
    "ufficio condiviso {}",
    # istruzione
    "universita {}",
    "universita di {} corsi",
    "facolta {}",
    "college {}",
    "scuole {}",
    "scuola di lingue {}",
    "corsi di italiano {}",
    "corsi di inglese {}",
    "asilo nido {}",
    "scuola primaria {}",
    "liceo {}",
    "istituto tecnico {}",
    "master {}",
    "dottorato {}",
    "istruzione {}",
    "studenti {}",
    "vita universitaria {}",
    # salute e benessere
    "ospedale {}",
    "ospedali {}",
    "pronto soccorso {}",
    "medico {}",
    "medico di base {}",
    "pediatra {}",
    "dentista {}",
    "ortodontista {}",
    "farmacia {} aperta",
    "farmacia notturna {}",
    "clinica privata {}",
    "poliambulatorio {}",
    "oculista {}",
    "dermatologo {}",
    "ginecologo {}",
    "fisioterapista {}",
    "psicologo {}",
    "ambulanza {}",
    # sport e fitness
    "palestra {}",
    "palestre {}",
    "palestra low cost {}",
    "yoga {}",
    "pilates {}",
    "crossfit {}",
    "piscina {}",
    "piscina pubblica {}",
    "centro sportivo {}",
    "campo da tennis {}",
    "padel {}",
    "calcio {}",
    "stadio {}",
    "basket {}",
    "running {}",
    "pista ciclabile {}",
    "percorso running {}",
    "sport acquatici {}",
    "canottaggio {}",
    "vela {}",
    "kitesurf {}",
    "parapendio {}",
    "arrampicata {}",
    "palestra arrampicata {}",
    "trail running {}",
    "maratona {}",
    # tecnologia e connettivita
    "wifi gratuito {}",
    "bar con wifi {}",
    "coworking wifi {}",
    "internet {}",
    "assistenza tecnica {}",
    "apple store {}",
    "negozio informatica {}",
    # accessibilita e inclusivita
    "ammette cani {}",
    "pet friendly {}",
    "adatto bambini {}",
    "accessibile sedia a rotelle {}",
    "disabili {}",
    "spiagge attrezzate {}",
    "strutture accessibili {}",
    "bambini {}",
    "neonati {}",
    "giochi bambini {}",
    "asilo {}",
    "sitter {}",
    # sicurezza
    "sicurezza {}",
    "criminalita {}",
    "quartieri sicuri {}",
    "quartieri da evitare {}",
    "polizia {}",
    "emergenze {}",
    "carabinieri {}",
    # informazioni generali
    "{} storia",
    "{} origini",
    "{} wikipedia",
    "{} popolazione",
    "{} abitanti",
    "{} cap",
    "{} codice postale",
    "{} prefisso telefonico",
    "{} mappa",
    "{} mappa centro",
    "{} comune",
    "{} regione",
    "{} provincia",
    "{} altitudine",
    "{} coordinate",
    "{} fuso orario",
    "{} lingua",
    "{} valuta",
    "{} informazioni generali",
    "quando visitare {}",
    "periodo migliore per visitare {}",
    "migliore stagione {}",
    "quanti giorni a {}",
    "budget viaggio {}",
    "viaggio {} quanto costa",
    "vacanza {} economica",
    "vacanze a {}",
    "turismo {}",
    "guida turistica {}",
    "guida {}",
    "{} turismo",
    # webcam e live
    "webcam {} live",
    "webcam {}",
    "live cam {}",
    "diretta {}",
    "{} in diretta",
    "foto {} oggi",
    # ambasciata e burocrazia
    "ambasciata italiana {}",
    "consolato {}",
    "visto per {}",
    "permesso soggiorno {}",
    "documenti {}",
    "burocrazia {}",
    # natura e ambiente
    "parco botanico {}",
    "oasi naturalistica {}",
    "riserva ornitologica {}",
    "birdwatching {}",
    "flora e fauna {}",
    "inquinamento {}",
    "qualita dell'aria {}",
    "indice uv {}",
    "tramonto {} orario",
    "alba {} orario",
    # quartieri e zone
    "quartieri {}",
    "quartiere {} dove dormire",
    "zona {} migliore",
    "dove alloggiare {}",
    "dove stare a {}",
    "centro di {}",
    "periferia {}",
    "dintorni {}",
    "vicino a {}",
    "nei pressi di {}",
    # cibo e prodotti locali
    "cucina tipica {}",
    "piatti tipici {}",
    "specialita locali {}",
    "vino {}",
    "cantina {}",
    "degustazione vini {}",
    "birra artigianale {}",
    "formaggi {}",
    "salumi {}",
    "prodotti locali {}",
    "mercato alimentare {}",
    "fattoria {}",
    "km zero {}",
    "ristorante tipico {}",
    "ricette {}",
    "cucina locale {}",
    # bambini e famiglie
    "parco giochi {}",
    "luna park {}",
    "musei bambini {}",
    "fattoria didattica {}",
    "laboratorio bambini {}",
    "teatrino {}",
    "piscina bambini {}",
    "spiaggia bambini {}",
    "vacanza famiglia {}",
    "hotel family {}",
    # romantico e coppia
    "weekend romantico {}",
    "cosa fare a {} in coppia",
    "ristorante romantico {}",
    "hotel romantico {}",
    "spa coppia {}",
    "proposta matrimonio {}",
    "luna di miele {}",
    # budget e risparmio
    "gratis {}",
    "cosa fare gratis a {}",
    "ingresso gratuito {}",
    "musei gratis {}",
    "attrazioni gratuite {}",
    "tour gratis {}",
    "low cost {}",
    "risparmio {}",
    "spendere poco a {}",
    # spiritualita e cultura
    "chiesa {}",
    "tempio {}",
    "moschea {}",
    "sinagoga {}",
    "luoghi sacri {}",
    "religione {}",
    "cultura {}",
    "tradizioni {}",
    "folklore {}",
    "dialetto {}",
    "lingua locale {}",
    # numeri utili
    "numeri utili {}",
    "emergenza {}",
    "pompieri {}",
    "pronto soccorso {} telefono",
    "polizia {} numero",
    "guardia medica {}",
    # tecnologia smart city
    "smart city {}",
    "app {}",
    "app turistica {}",
    "mappa app {}",
    # servizi
    "lavanderia {}",
    "lavanderia automatica {}",
    "corriere {}",
    "posta {}",
    "banca {}",
    "bancomat {}",
    "ufficio postale {}",
    "notaio {}",
    "avvocato {}",
    "commercialista {}",
    # spicciolo
    "ristorante aperto domenica {}",
    "ristorante aperto lunedi {}",
    "ristorante aperto a ferragosto {}",
    "negozi aperti domenica {}",
    "orari negozi {}",
    "cosa e aperto a {}",
    "happy hour {} orari",
    "mercato {} orari",
    "museo {} orari",
    "biglietti {}",
    "prenotazione {}",
    "prenotare {}",
    "prezzi {}",
    "quanto costa {}",
    "costo ingresso {}",
    "truffa turistica {}",
    "scam {}",
    "consigli {}",
    "consigli per visitare {}",
    "errori da evitare {}",
    "cosa non fare a {}",
    "etichetta {}",
    "galateo {}",
    "mance {}",
    "contrattare {}",
    # lingue e internazionale
    "parlano inglese a {}",
    "lingua ufficiale {}",
    "traduttore {}",
    "frasario {}",
    "espressioni utili {}",
    # stagioni e clima aggiuntive
    "piove a {} in ottobre",
    "fa caldo a {} in agosto",
    "temperature medie {}",
    "stagione secca {}",
    "stagione delle piogge {}",
    # varianti frasi con citta alla fine
    "cosa vedere {}",
    "cosa fare {}",
    "dove mangiare {}",
    "dove dormire {}",
    "dove bere {}",
    "dove ballare {}",
    "dove fare shopping {}",
    "musei gratuiti {}",
    "spiagge più belle {}",
    "ristoranti consigliati {}",
    "hotel consigliati {}",
    "ostelli consigliati {}",
    "escursioni consigliate {}",
    "tour consigliati {}",
    "eventi {}",
    "festival locale {}",
    "nightlife {}",
    "divertimento {}",
    "tempo libero {}",
    "svago {}",
    "relax {}",
    "benessere {}",
    "spa {}",
    "terme {}",
    "centro benessere {}",
    "massaggio {}",
    "bellezza {}",
    "parrucchiere {}",
    "barbiere {}",
    "tatuaggi {}",
    "mercato vintage {}",
    "antiquariato {}",
    "galleria commerciale {}",
    "factory outlet {}",
    "saldi {}",
    "prezzi bassi {}",
    "dove comprare {}",
    "dove trovare {}",
    "quanto costa vivere {}",
    "qualita della vita {}",
    "indice di vivibilita {}",
    "classifica citta {}",
    "migliore citta {}",
    "pro e contro {}",
    "recensioni {}",
    "opinioni {}",
    "forum {}",
    "blog {}",
    "vlog {}",
    "youtube {}",
    "tiktok video {}",
    "instagram {}",
    "galleria foto {}",
    "immagini {}",
    "video {}",
    "documentario {}",
    "film girato a {}",
    "serie tv {}",
    "libri su {}",
    "romanzi ambientati a {}",
    "storia di {}",
    "leggende {}",
    "miti {}",
    "curiosita {}",
    "fatti interessanti {}",
    "record {}",
    "statistiche {}",
    "dati {}",
    "economia locale {}",
    "pil {}",
    "pil pro capite {}",
    "occupazione {}",
    "settore turistico {}",
    "industria locale {}",
    "artigianato locale {}",
    "fiera commerciale {}",
    "esposizione internazionale {}",
    "congresso {}",
    "conferenza {}",
    "hotel per congressi {}",
    "centro congressi {}",
    "sede eventi {}",
    "sala riunioni {}",
    # varianti con preposizioni
    "a {} cosa visitare",
    "a {} dove mangiare",
    "a {} cosa fare la sera",
    "a {} hotel migliori",
    "a {} ristoranti migliori",
    "a {} spiagge migliori",
    "a {} musei migliori",
    "a {} come arrivare",
    "a {} come spostarsi",
    "a {} trasporti",
    "a {} sicurezza",
    "a {} costo della vita",
    "da {} gite",
    "da {} escursioni di un giorno",
    "da {} cosa si vede in giro",
    "da {} treno",
    "da {} aereo",
    "da {} bus",
    "vicino a {} cosa vedere",
    "vicino a {} spiagge",
    "vicino a {} montagna",
    "vicino a {} lago",
    "vicino a {} agriturismo",
    "vicino a {} parco naturale",
    "vicino a {} ristoranti",
    "per {} voli economici",
    "per {} treni",
    "per {} pullman",
    "in {} cosa fare",
    "in {} dove dormire",
    "in {} vita notturna",
    "in {} coworking",
    "in {} lavoro",
    "in {} universita",
    # varianti temporali extra
    "{} agosto 2025",
    "{} estate 2025",
    "{} natale 2025",
    "{} pasqua 2026",
    "{} luglio 2026",
    "{} agosto 2026",
    "{} estate 2026",
    "{} inverno 2025",
    "{} inverno 2026",
    "{} primavera 2026",
    # mix di intenti aggiuntivi
    "{} app turistica",
    "{} mappa interattiva",
    "{} guida pdf",
    "{} guida offline",
    "{} itinerario una settimana",
    "{} itinerario due settimane",
    "{} itinerario un mese",
    "{} budget giornaliero",
    "{} spese medie turista",
    "{} assicurazione viaggio",
    "{} vaccinazioni",
    "{} fuso orario differenza",
    "{} orario solare",
    "{} moneta locale",
    "{} tasso di cambio",
    "{} sim card",
    "{} internet mobile",
    "{} roaming",
    "{} presa elettrica",
    "{} tensione elettrica",
    "{} acqua potabile",
    "{} tap water sicuro",
    "{} allergie alimentari",
    "{} intolleranze",
    "{} cibo senza lattosio",
    "{} ristorante celiaci",
    "{} farmacia di turno",
    "{} guardia medica",
    "{} numero emergenza",
    "{} consulato italiano",
    "{} ambasciata",
    "{} permesso di soggiorno",
    "{} visto turistico",
    "{} ingresso gratuito under 18",
    "{} sconto studenti",
    "{} carta giovani",
    "{} tourist card",
    "{} city pass",
    "{} pass musei",
    "{} biglietto cumulativo",
    "{} audioguida",
    "{} guida turistica umana",
    "{} tour in italiano",
    "{} tour in inglese",
    "{} visita virtuale",
    "{} museo virtuale",
    "{} google street view",
    "{} foto satellitare",
    "{} vista aerea",
    "{} drone",
    "{} patrimonio unesco",
    "{} sito patrimonio mondiale",
    "{} architettura",
    "{} architettura rinascimentale",
    "{} architettura barocca",
    "{} architettura moderna",
    "{} street art",
    "{} graffiti",
    "{} murales",
    "{} arte contemporanea",
    "{} design",
    "{} moda",
    "{} shopping lusso",
    "{} shopping di lusso",
    "{} fashion week",
    "{} design district",
    "{} libreria piu bella",
    "{} mercatino antiquariato",
    "{} collezionismo",
    "{} numismatica",
    "{} filatelia",
    "{} fumetti",
    "{} videogiochi",
    "{} gaming",
    "{} lan party",
    "{} hackathon",
    "{} startup",
    "{} incubatore",
    "{} innovazione",
    "{} tech hub",
    "{} comunita italiana",
    "{} italiani all'estero",
    "{} expat",
    "{} comunita internazionale",
    "{} lingua straniera",
    "{} corso lingua",
    "{} scambio linguistico",
    "{} tandem linguistico",
    "{} volontariato",
    "{} ong",
    "{} associazioni locali",
    "{} eventi culturali",
    "{} centro culturale",
    "{} biblioteca",
    "{} biblioteca pubblica",
    "{} mediateca",
    "{} sala studio",
    "{} dove studiare",
    "{} caffè studiare",
    "{} bar tranquillo",
    "{} posto silenzioso",
    "{} parco per rilassarsi",
    "{} verde urbano",
    "{} giardino pubblico",
    "{} orto botanico",
    "{} area cani",
    "{} dog park",
    "{} veterinario",
    "{} toelettatura cani",
    "{} pensione cani",
    "{} cibo animali",
    "{} negozio animali",
    "{} rifugio animali",
    "{} gatto",
    "{} gatti randagi",
    "{} colonie feline",
    # ulteriori
    "volo piu economico per {}",
    "quando e il periodo migliore per andare a {}",
    "quante ore di volo per {}",
    "distanza da roma a {}",
    "distanza da milano a {}",
    "distanza da napoli a {}",
    "distanza da firenze a {}",
    "distanza da venezia a {}",
    "distanza da torino a {}",
    "distanza km {}",
    "tempo in auto per {}",
    "autostrada per {}",
    "pedaggi autostrada {}",
    "strade {}",
    "mappa stradale {}",
    "navigatore {}",
    "google maps {}",
    "directions {}",
    "percorso {}",
    "itinerario stradale {}",
    "mappa metro {}",
    "linee bus {}",
    "fermata bus {}",
    "fermata metro {}",
    "orari metro {}",
    "notte bianca {}",
    "sagra locale {}",
    "tradizione locale {}",
    "festa patronale {}",
    "santo patrono {}",
    "carnevale di {} date",
    "ferragosto {}",
    "eventi ferragosto {}",
    "cosa fare a {} a ferragosto",
    "new year {} eventi",
    "countdown capodanno {}",
    "estate in citta {}",
    "estate a {}",
    "inverno a {}",
    "primavera a {}",
    "autunno a {}",
    "foglie autunno {}",
    "colori autunno {}",
    "natura {}",
    "paesaggio {}",
    "panorama da {}",
    "vista {}",
    "tramonto {}",
    "alba {}",
    "notte stellata {}",
    "inquinamento luminoso {}",
    "osservatorio astronomico {}",
    "stelle {}",
    "telescopio {}",
    "astrofotografia {}",
    "meteor shower {}",
    "eclissi {}",
    "luna piena {}",
    "aurora boreale vicino {}",
    "fenomeni naturali {}",
    "terremoto {}",
    "rischio sismico {}",
    "alluvione {}",
    "rischio idrogeologico {}",
    "protezione civile {}",
    "piano emergenza {}",
    "spiagge nudiste {}",
    "spiagge naturiste {}",
    "spiagge gay friendly {}",
    "lgbtq {}",
    "pride {}",
    "community lgbtq {}",
    "locali gay {}",
    "sauna {}",
    "benessere e spa {}",
    "terme romane {}",
    "bagni storici {}",
    "hammam {}",
    "spa luxury {}",
    "spa economica {}",
    "massaggio ayurvedico {}",
    "meditazione {}",
    "centro meditazione {}",
    "ritiro yoga {}",
    "reiki {}",
    "medicina alternativa {}",
    "erboristeria {}",
    "mercato biologico {}",
    "prodotti bio {}",
    "cibo vegano {}",
    "locale vegano {}",
    "ristorante raw food {}",
    "veganismo {}",
    "vegetarianismo {}",
    "fruttarismo {}",
    "zero waste {}",
    "sostenibilita {}",
    "ecologia {}",
    "mobilita sostenibile {}",
    "bici elettrica {}",
    "auto elettrica {}",
    "colonnine ricarica {}",
    "pannelli solari {}",
    "energia rinnovabile {}",
    "economia circolare {}",
    "raccolta differenziata {}",
    "riciclaggio {}",
    "plastica free {}",
    "spiagge pulite {}",
    "ambiente {}",
    "green {}",
    "turismo responsabile {}",
    "turismo sostenibile {}",
    "ecoturismo {}",
    "agriturismo sostenibile {}",
    "fattoria biologica {}",
    "slow food {}",
    "presidi slow food {}",
    "cibo di qualita {}",
    "trattoria tipica {}",
    "cucina della nonna {}",
    "ricette tradizionali {}",
    "corso cucina {}",
    "lezione cucina {}",
    "food tour {}",
    "wine tour {}",
    "cheese tour {}",
    "degustazione olio {}",
    "oliveto {}",
    "oleificio {}",
    "produzione vino {}",
    "vigna {}",
    "vendemmia {}",
    "birrificio {}",
    "distilleria {}",
    "liquori locali {}",
    "amaro {}",
    "grappa {}",
    "limoncello {}",
    "digestivo {}",
    "aperitivo tradizionale {}",
    "aperol spritz {}",
    "negroni {}",
    "cocktail tipico {}",
    "bar storico {}",
    "caffe storico {}",
    "gelateria artigianale {}",
    "yogurteria {}",
    "cremeria {}",
    "cioccolateria {}",
    "confetteria {}",
    "dolci tipici {}",
    "torta locale {}",
    "biscotti tipici {}",
    "panificio artigianale {}",
    "pane tipico {}",
    "pizza al taglio {}",
    "trancio pizza {}",
    "friggitoria {}",
    "arancini {}",
    "supplì {}",
    "crocchette {}",
    "cuoppo {}",
    "puccia {}",
    "focaccia {}",
    "bruschetta {}",
    "antipasto {}",
    "primo piatto {}",
    "secondo piatto {}",
    "contorno {}",
    "dessert {}",
    "menu fisso {}",
    "menu turistico {}",
    "pranzo economico {}",
    "cena economica {}",
    "ristorante aperto a pranzo {}",
    "ristorante aperto a cena {}",
    "ristorante apertura continua {}",
    "cucina fino a tardi {}",
    "ristorante h24 {}",
    "ristorante 24 ore {}",
    "delivery {}",
    "consegna a domicilio {}",
    "just eat {}",
    "glovo {}",
    "deliveroo {}",
    "uber eats {}",
    "take away {}",
    "asporto {}",
    "lunch box {}",
    "pausa pranzo {}",
    "mensa {}",
    "refettorio {}",
    "banchetto {}",
    "catering {}",
    "buffet matrimonio {}",
    "location matrimonio {}",
    "cerimonia matrimonio {}",
    "chiesa matrimonio {}",
    "municipio {}",
    "ufficio anagrafe {}",
    "ufficio elettorale {}",
    "ufficio tributi {}",
    "ufficio tecnico {}",
    "comune di {} contatti",
    "sindaco {}",
    "assessorato {}",
    "bando {}",
    "gara appalto {}",
    "iter burocratico {}",
    "modulo {}",
    "certificato {}",
    "stato civile {}",
    "residenza {}",
    "domicilio {}",
    "trasferimento residenza {}",
    "iscrizione anagrafe {}",
    "codice fiscale {}",
    "carta d'identita {}",
    "passaporto {}",
    "patente {}",
    "motorizzazione {}",
    "revisione auto {}",
    "bollo auto {}",
    "assicurazione auto {}",
    "rc auto {}",
    "incidente stradale {}",
    "multa {}",
    "autovelox {}",
    "telecamere traffico {}",
    "videosorveglianza {}",
    "sicurezza stradale {}",
    "incidentalita {}",
    "strade pericolose {}",
    "lavori stradali {}",
    "cantiere {}",
    "chiusura strade {}",
    "deviazione {}",
    "viabilita {}",
    "previsioni traffico {}",
    "code autostrada {}",
    "traffico intenso {}",
    "ora di punta {}",
    "rush hour {}",
    "traffico {}",
    "traffico {} in tempo reale",
    "traffico {} mappa",
    "waze {}",
    "tomtom {}",
    "google maps traffico {}",
    "parcheggio {} strisce blu",
    "parcheggio {} tariffe",
    "parcheggio {} gratuito",
    "parcheggio {} coperto",
    "parcheggio {} multipiano",
    "garage {}",
    "rimessa {}",
    "deposito bagagli {}",
    "left luggage {}",
    "locker {}",
    "armadietti {}",
    "portineria {}",
    "reception {}",
    "concierge {}",
    "front desk {}",
    "check in {}",
    "check out {}",
    "late check out {}",
    "early check in {}",
    "half board {}",
    "mezza pensione {}",
    "pensione completa {}",
    "all inclusive {}",
    "tutto incluso {}",
    "resort all inclusive {}",
    "tour crociera {}",
    "nave da crociera {}",
    "porto crociere {}",
    "escursione nave {}",
    "scalo crociera {}",
    "crociera nel mediterraneo {}",
    "crociera partenza {}",
    "barca a vela {}",
    "yacht {}",
    "noleggio yacht {}",
    "charter nautico {}",
    "giro in barca {}",
    "escursione in barca {}",
    "kayak {}",
    "canoa {}",
    "rafting {}",
    "torrentismo {}",
    "speleologia {}",
    "alpinismo {}",
    "via ferrata {}",
    "ciaspole {}",
    "sci di fondo {}",
    "sci alpino {}",
    "snowboard {}",
    "freeride {}",
    "piste da sci {}",
    "impianti di risalita {}",
    "seggiovia {}",
    "funivia {}",
    "cabinovia {}",
    "ski pass {}",
    "scuola sci {}",
    "noleggio sci {}",
    "rifugio alpino {}",
    "bivacco {}",
    "capanna {}",
    "rifugio {}",
    "sentiero alpino {}",
    "alta via {}",
    "cammino {}",
    "pellegrinaggio {}",
    "cammino di santiago da {}",
    "via francigena {}",
    "via appia {}",
    "percorso storico {}",
    "itinerario storico {}",
    "percorso naturalistico {}",
    "oasi wwf {}",
    "lipu {}",
    "legambiente {}",
    "area marina protetta {}",
    "fondo marino {}",
    "barriera corallina {}",
    "subacquea {}",
    "diving center {}",
    "snorkeling attrezzatura {}",
    "surf school {}",
    "windsurf {}",
    "kitesurfing {}",
    "wakeboard {}",
    "sci nautico {}",
    "moto d'acqua {}",
    "gommone {}",
    "giro in gommone {}",
    "spiaggia privata {}",
    "spiaggia pubblica {}",
    "spiaggia bandiera blu {}",
    "qualita acqua {}",
    "mare pulito {}",
    "bandiera blu {}",
    "bolkestein {}",
    "concessione balneare {}",
    "ombrellone affitto {}",
    "lettino affitto {}",
    "chiosco spiaggia {}",
    "bar spiaggia {}",
    "cocktail spiaggia {}",
    "tramonto spiaggia {}",
    "spiaggia notturna {}",
    "spiagge rocks {}",
    "calette {}",
    "caletta nascosta {}",
    "spiaggia solitaria {}",
    "spiaggia affollata {}",
    "parcheggio spiaggia {}",
    "docce spiaggia {}",
    "spiaggia attrezzata {}",
    "spiaggia vip {}",
    "beach club {}",
    "beach party {}",
    "rave {}",
    "festival spiaggia {}",
    "concerto spiaggia {}",
    "cinema all'aperto {}",
    "teatro all'aperto {}",
    "arena {}",
    "anfiteatro {}",
    "anfiteatro romano {}",
    "arena romana {}",
    "scavi archeologici {}",
    "sito archeologico {}",
    "reperti {}",
    "archeologia {}",
    "museo archeologico {}",
    "museo civico {}",
    "museo storico {}",
    "museo di arte moderna {}",
    "museo di arte contemporanea {}",
    "museo scientifico {}",
    "museo naturale {}",
    "museo navale {}",
    "museo militare {}",
    "museo della guerra {}",
    "museo del risorgimento {}",
    "museo della resistenza {}",
    "museo dell'olocausto {}",
    "memoriale {}",
    "cimitero storico {}",
    "cimitero monumentale {}",
    "cripta {}",
    "catacombe {}",
    "mausoleo {}",
    "tomba {}",
    "sepolcro {}",
    "sarcofago {}",
    "reliquie {}",
    "cappella {}",
    "oratorio {}",
    "monastero {}",
    "abbazia {}",
    "convento {}",
    "eremo {}",
    "santuario {}",
    "meta pellegrinaggio {}",
    "madonna {}",
    "miracoli {}",
    "grotta sacra {}",
    "processione {}",
    "festa religiosa {}",
    "celebrazione {}",
    "messa {}",
    "funzione religiosa {}",
    "religioni {}",
    "confessioni {}",
    "minoranze religiose {}",
    "moschee {}",
    "centro islamico {}",
    "comunita ebraica {}",
    "comunita ortodossa {}",
    "cattolicesimo {}",
    "protestantesimo {}",
    "buddismo {}",
    "hinduismo {}",
    "induismo {}",
    "sincretismo {}",
    "multiculturalismo {}",
    "diversita culturale {}",
    "immigrazione {}",
    "integrazione {}",
    "quartiere etnico {}",
    "chinatown {}",
    "little italy {}",
    "quartiere arabo {}",
    "mercato arabo {}",
    "bazar {}",
    "souk {}",
    "mercato orientale {}",
    "cucina etnica {}",
    "ristorante etnico {}",
    "cibo etnico {}",
    "spezie {}",
    "spezieria {}",
    "erbe aromatiche {}",
    "mercato delle erbe {}",
    "piante medicinali {}",
    "erboristeria tradizionale {}",
    "medicina tradizionale {}",
    "shiatsu {}",
    "agopuntura {}",
    "naturopatia {}",
    "omeopatia {}",
    "benessere olistico {}",
    "mindfulness {}",
    "centro reiki {}",
    "cristalloterapia {}",
    "new age {}",
    "librerias esoterica {}",
    "negozio esoterico {}",
    "cartomante {}",
    "lettura dei tarocchi {}",
    "astrologia {}",
    "oroscopo {}",
    "numerologia {}",
    "feng shui {}",
    "vastu shastra {}",
    "architettura sostenibile {}",
    "bioarchitettura {}",
    "case passive {}",
    "case in legno {}",
    "architettura bioclimatica {}",
    "edilizia verde {}",
    "green building {}",
    "certificazione leed {}",
    "riqualificazione urbana {}",
    "rigenerazione urbana {}",
    "sviluppo urbano {}",
    "piano regolatore {}",
    "urbanistica {}",
    "gentrification {}",
    "periferie {}",
    "borghi {}",
    "borghi piu belli {}",
    "borgo medievale {}",
    "borgo storico {}",
    "caratteristico {}",
    "pittoresco {}",
    "autentico {}",
    "genuino {}",
    "tipico {}",
    "tradizionale {}",
    "artigiano {}",
    "bottega artigianale {}",
    "liutaio {}",
    "ceramista {}",
    "scultore {}",
    "pittore {}",
    "atelier {}",
    "studio d'artista {}",
    "open studio {}",
    "mostra artista {}",
    "galleria indipendente {}",
    "arte di strada {}",
    "installazione {}",
    "performance {}",
    "happening {}",
    "teatro sperimentale {}",
    "teatro di prosa {}",
    "compagnia teatrale {}",
    "festival teatro {}",
    "festival cinema {}",
    "cinema d'essai {}",
    "filmclub {}",
    "videoteca {}",
    "cineforum {}",
    "rassegna cinematografica {}",
    "proiezione {}",
    "anteprima film {}",
    "regista {}",
    "attore {}",
    "troupe {}",
    "set cinematografico {}",
    "luogo del film {}",
    "location film {}",
    "turismo cinematografico {}",
    "movie tourism {}",
    "fan location {}",
    "manga {}",
    "anime {}",
    "cosplay {}",
    "convention {}",
    "comic con {}",
    "giochi da tavolo {}",
    "ludoteca {}",
    "sala giochi {}",
    "videogiochi {}",
    "gaming center {}",
    "vr experience {}",
    "realta virtuale {}",
    "realta aumentata {}",
    "museo digitale {}",
    "arte digitale {}",
    "nft {}",
    "metaverso {}",
    "tecnologia {}",
    "innovazione digitale {}",
    "startup innovazione {}",
    "incubatore startup {}",
    "acceleratore {}",
    "venture capital {}",
    "angel investor {}",
    "crowdfunding {}",
    "fintech {}",
    "blockchain {}",
    "criptovalute {}",
    "bitcoin {}",
    "ethereum {}",
    "defi {}",
    "web3 {}",
    "intelligenza artificiale {}",
    "ai {}",
    "machine learning {}",
    "robotica {}",
    "automazione {}",
    "industria 4.0 {}",
    "fabbrica intelligente {}",
    "manifattura additiva {}",
    "stampa 3d {}",
    "prototipazione {}",
    "fab lab {}",
    "makerspace {}",
    "hacker space {}",
    "open source {}",
    "community tecnologica {}",
    "incontro tech {}",
    "meetup {}",
    "conferenza tech {}",
    "summit {}",
    "barcamp {}",
    "unconference {}",
    "workshop {}",
    "seminario {}",
    "corso online {}",
    "mooc {}",
    "formazione professionale {}",
    "aggiornamento professionale {}",
    "master professionale {}",
    "certificazione professionale {}",
    "coaching {}",
    "mentoring {}",
    "networking {}",
    "business networking {}",
    "camera di commercio {}",
    "associazione imprenditori {}",
    "confindustria {}",
    "confcommercio {}",
    "sindacato {}",
    "ordine professionale {}",
    "albo professionale {}",
    "avvocati {}",
    "medici {}",
    "ingegneri {}",
    "architetti {}",
    "commercialisti {}",
    "notai {}",
    "psicologi {}",
    "giornalisti {}",
    "giornale locale {}",
    "quotidiano {}",
    "notizie {}",
    "news {}",
    "radio locale {}",
    "televisione locale {}",
    "emittente locale {}",
    "blog locale {}",
    "podcast {}",
    "influencer {}",
    "creator {}",
    "youtuber {}",
    "streamer {}",
    "twitch {}",
    "social media {}",
    "facebook {}",
    "twitter {}",
    "tiktok {}",
    "{} mappa turistica",
    "{} come ci si orienta",
    "{} cosa comprare",
    "{} regali tipici",
    "{} prodotti da portare a casa",
    "{} prenotazione online",
    "{} biglietto online",
    "{} acquisto online",
    "{} app ufficiale",
    "{} sito ufficiale turismo",
    "{} ufficio turismo",
    "{} iat",
    "{} pro loco",
    "{} associazione turistica",
    "{} centro informazioni",
    "{} punto informazioni",
    "{} help desk",
    "{} info point",
    "{} tourist office",
    "{} visitor center",
    "{} welcome center",
    "{} accoglienza turistica",
    "{} servizi ai turisti",
    "{} assistenza turisti",
    "{} polizia turistica",
    "{} vigili",
    "{} polizia municipale",
    "{} guardie",
    "{} pattuglia",
    "{} telecamere sicurezza",
    "{} sicurezza evento",
    "{} steward",
    "{} croce rossa",
    "{} ambulanza",
    "{} elisoccorso",
    "{} eliporto",
    "{} elicottero",
    "{} soccorso alpino",
    "{} corpo nazionale soccorso alpino",
    "{} speleosoccorso",
    "{} guardia costiera",
    "{} capitaneria di porto",
    "{} porto turistico",
    "{} marina",
    "{} darsena",
    "{} ormeggio",
    "{} noleggio gommone",
    "{} noleggio motore",
    "{} diving",
    "{} centro diving",
    "{} snorkeling tour",
    "{} tour marino",
    "{} osservazione cetacei",
    "{} avvistamento delfini",
    "{} avvistamento balene",
    "{} birdwatching tour",
    "{} safari fotografico",
    "{} astroturismo",
    "{} dark sky",
    "{} parco astronomico",
    "{} osservazione stelle",
    "{} planetario",
    "{} museo scienza",
    "{} museo tecnologia",
    "{} museo ferroviario",
    "{} museo automobilistico",
    "{} museo motori",
    "{} museo aeronatuica",
    "{} museo spazio",
    "{} museo sport",
    "{} museo calcio",
    "{} stadio visita",
    "{} tour stadio",
    "{} museo squadra",
    "{} fan shop",
    "{} store ufficiale",
    "{} merchandising",
    "{} gadget",
    "{} abbigliamento sportivo",
    "{} articoli sportivi",
    "{} negozio sportivo",
    "{} attrezzatura outdoor",
    "{} attrezzatura montagna",
    "{} attrezzatura sci",
    "{} noleggio attrezzatura",
    "{} assistenza attrezzatura",
    "{} riparazione bici",
    "{} officina bici",
    "{} riparazione moto",
    "{} officina moto",
    "{} riparazione auto",
    "{} meccanico",
    "{} carrozzeria",
    "{} autolavaggio",
    "{} benzinaia",
    "{} distributore carburante",
    "{} stazione di servizio",
    "{} area di servizio",
    "{} autogrill",
    "{} bar autostrada",
    "{} ristorante autostrada",
    "{} hotel autostrada",
    "{} motel autostrada",
    "{} casello autostradale",
    "{} pedaggio",
    "{} tutor autostradale",
    "{} telecamere autovelox",
    "{} autovelox fisso",
    "{} limite velocita",
    "{} segnaletica",
    "{} segnali stradali",
    "{} codice della strada",
    "{} regole stradali",
    "{} educazione stradale",
    "{} scuola guida",
    "{} autoscuola",
    "{} patente b",
    "{} patente a",
    "{} patente am",
    "{} patente nautica",
    "{} brevetto subacqueo",
    "{} certificato",
    "{} esame",
    "{} test",
    "{} quiz",
    "{} simulazione esame",
    "{} ripasso",
    "{} studio",
    "{} materiale didattico",
    "{} libri scolastici",
    "{} libreria scolastica",
    "{} cartolibreria",
    "{} cartoleria",
    "{} cancelleria",
    "{} ufficio stampa",
    "{} stampa digitale",
    "{} copisteria",
    "{} tipografia",
    "{} grafica",
    "{} web design",
    "{} sviluppo web",
    "{} marketing",
    "{} comunicazione",
    "{} agenzia comunicazione",
    "{} agenzia marketing",
    "{} agenzia viaggi",
    "{} tour operator",
    "{} pacchetto vacanza",
    "{} offerta viaggio",
    "{} promozione turistica",
    "{} sconto hotel",
    "{} offerta hotel",
    "hotel offerta speciale {}",
    "{} promo",
    "{} coupon",
    "{} voucher",
    "{} gift card",
    "{} regalo",
    "{} esperienza regalo",
    "{} cofanetto regalo",
    "{} smartbox",
    "{} bybox",
    "{} emozione3",
    "{} groupon",
    "{} sconti",
    "{} promo estate",
    "{} offerta estate",
    "{} vacanze scontate",
    "{} vacanza last minute",
    "{} last minute",
    "{} early booking",
    "{} prenotazione anticipata",
    "{} sconto prenotazione",
    "{} cancellazione gratuita",
    "{} rimborso",
    "{} assicurazione annullamento",
    "{} travel insurance",
    "{} covid policy",
    "{} flexible booking",
    "{} change booking",
    "{} modifica prenotazione",
    "{} disdetta",
    "{} cancellazione",
    "{} review",
    "{} recensione hotel",
    "{} tripadvisor",
    "{} booking",
    "{} expedia",
    "{} hotels.com",
    "{} hostelworld",
    "{} airbnb",
    "{} vrbo",
    "{} homeaway",
    "{} trivago",
    "{} kayak",
    "{} skyscanner",
    "{} google flights",
    "{} google hotels",
    "{} google maps ristoranti",
    "{} yelp",
    "{} thefork",
    "{} opentable",
    "{} zomato",
    "{} deliveroo",
    "{} glovo",
    "{} just eat",
    "{} uber eats",
    "{} getir",
    "{} gorillas",
    "{} glovoapp",
    "ordinare cibo a {}",
    "{} spesa online",
    "{} supermercato online",
    "{} fresco e bello",
    "{} amazon fresh",
    "{} consegna fresca",
    "{} paniere biologico",
    "{} csa agricoltura",
    "{} gruppo di acquisto",
    "{} gas gruppo acquisto solidale",
    "{} mercato contadino",
    "{} farmers market",
    "{} mercato biologico",
    "{} fiera biologica",
    "{} sagra biologica",
    "sagra del vino {}",
    "sagra del pesce {}",
    "sagra della polenta {}",
    "sagra del fungo {}",
    "sagra del tartufo {}",
    "{} tartufo",
    "{} fungo porcino",
    "{} produzione truffe",
    "{} cerca tartufi",
    "{} caccia al tartufo",
    "{} fioritura",
    "{} floreal",
    "{} parco fiorito",
    "{} giardino fiorito",
    "{} lavanda",
    "{} campi di lavanda",
    "{} girasoli",
    "{} tulipani",
    "{} ciliegio in fiore",
    "{} hanami",
    "{} primavera",
    "{} spring",
    "{} fiore",
    "{} flora",
    "{} fauna",
    "{} wildlife",
    "{} natura incontaminata",
    "{} selvaggio",
    "{} wilderness",
    "{} parco wilderness",
    "{} zona di silenzio",
    "{} silenzio",
    "{} relax natura",
    "{} forest bathing",
    "{} shinrin yoku",
    "{} bagno nel bosco",
    "{} terapia forestale",
    "{} terapia della natura",
    "{} ecoterapia",
    "{} green therapy",
    "mental health {}",
    "{} salute mentale",
    "{} benessere psicologico",
    "{} supporto psicologico",
    "{} sportello ascolto",
    "{} help line",
    "{} casa delle associazioni",
    "{} centro di aggregazione",
    "{} spazio giovani",
    "{} centro giovani",
    "{} oratorio",
    "{} parrocchia",
    "{} comunita",
    "{} vita comunitaria",
    "{} quartiere solidale",
    "{} reti di solidarieta",
    "{} mutuo aiuto",
    "{} banca del tempo",
    "{} time bank",
    "{} scambio competenze",
    "{} sharing economy",
    "{} economia della condivisione",
    "{} baratto",
    "{} scambio",
    "{} dono",
    "{} regalo gratis",
    "{} mercato del dono",
    "{} free shop",
    "{} bookcrossing",
    "{} panchine dei libri",
    "{} casette dei libri",
    "{} little free library",
    "{} lettura",
    "{} club del libro",
    "{} circolo letterario",
    "{} festival letteratura",
    "{} fiera del libro",
    "{} presentazione libro",
    "{} firma autografi",
    "{} reading",
    "{} poetry slam",
    "{} spoken word",
    "{} open mic",
    "{} karaoke bar",
    "{} piano bar",
    "{} bossa nova",
    "{} tango",
    "{} salsa",
    "{} danza",
    "{} scuola di danza",
    "{} ballo",
    "{} discoteca anni 80",
    "{} revival",
    "{} retro",
    "{} vintage",
    "{} moda vintage",
    "{} stile vintage",
    "{} hipster",
    "{} trend",
    "{} fashion",
    "{} moda locale",
    "{} stilista",
    "{} sarto",
    "{} sartoria",
    "{} atelier moda",
    "{} show room",
    "{} sample sale",
    "{} vendita privata",
    "{} stock abbigliamento",
    "{} abbigliamento economico",
    "{} second hand",
    "{} usato",
    "{} vintage shop",
    "{} thrift store",
    "{} friperie",
    "{} vintage market",
    "{} mercatino usato abiti",
    "{} scambio abiti",
    "{} noleggio abiti",
    "{} costume carnevale",
    "{} travestimento",
    "{} cosplay shop",
    "{} negozio giocattoli",
    "{} giocattoli",
    "{} bambole",
    "{} action figure",
    "{} modellismo",
    "{} radiocomandati",
    "{} droni",
    "{} fotografia droni",
    "{} drone photography",
    "{} fotografia aerea",
    "{} riprese aeree",
    "{} video marketing",
    "{} video produzione",
    "{} casa di produzione",
    "{} studio video",
    "{} studio fotografico",
    "{} fotografo",
    "{} fotografo professionista",
    "{} fotografo matrimonio",
    "{} fotografo ritratti",
    "{} fotografo paesaggi",
    "{} fotografo reportage",
    "{} fotografo moda",
    "{} fotografo cibo",
    "{} food photography",
    "{} lifestyle photography",
    "{} portrait photography",
    "{} street photography",
    "{} fotografia notturna",
    "{} night photography",
    "{} astrophotography",
    "{} macro photography",
    "{} underwater photography",
    "{} scuola fotografia",
    "{} corso fotografia",
    "{} workshop fotografia",
    "{} attrezzatura fotografica",
    "{} negozio fotografia",
    "{} stampa foto",
    "{} laboratorio fotografico",
    "{} sviluppo pellicola",
    "{} analogico",
    "{} lomografia",
    "{} polaroid",
    "{} istantanea",
    "{} foto ricordo",
    "{} cartolina",
    "{} cartoline vintage",
    "{} collezionismo cartoline",
    "{} francobolli",
    "{} collezionismo francobolli",
    "{} monete",
    "{} collezionismo monete",
    "{} banconote",
    "{} collezionismo banconote",
    "{} gioielli",
    "{} gioielleria",
    "{} oreficeria",
    "{} argenteria",
    "{} orologeria",
    "{} orologi",
    "{} orologi vintage",
    "{} collezionismo orologi",
    "{} antiquariato orologi",
    "{} libri antichi",
    "{} mappe antiche",
    "{} stampe antiche",
    "{} arte antica",
    "{} pittura antica",
    "{} scultura antica",
    "{} arredo antico",
    "{} mobili antichi",
    "{} restauro mobili",
    "{} restauro quadri",
    "{} restauro sculture",
    "{} restauro conservativo",
    "{} beni culturali",
    "{} tutela beni culturali",
    "{} soprintendenza",
    "{} mibact",
    "{} ministero cultura",
    "{} fondazione",
    "{} fondazione culturale",
    "{} mecenate",
    "{} sponsor culturale",
    "{} crowdfunding culturale",
    "{} art bonus",
    "{} adotta un monumento",
    "{} volunteering culturale",
    "{} volontariato culturale",
    "{} guide volontarie",
    "{} amici del museo",
    "{} associazione culturale",
    "{} circolo culturale",
    "{} cinecircolo",
    "{} cineforum locale",
    "{} cinema storico",
    "{} teatro storico",
    "{} opera lirica",
    "{} lirica",
    "{} concerto lirico",
    "{} concerto sinfonico",
    "{} orchestra",
    "{} filarmonico",
    "{} banda musicale",
    "{} coro",
    "{} gospel",
    "{} canto gregoriano",
    "{} musica sacra",
    "{} chiesa musica",
    "{} organo",
    "{} concerto d'organo",
    "{} festival musica sacra",
    "{} festival musica classica",
    "{} festival jazz",
    "{} festival blues",
    "{} festival rock",
    "{} festival pop",
    "{} festival indie",
    "{} festival elettronica",
    "{} festival techno",
    "{} rave party",
    "{} festival outdoor",
    "{} open air",
    "{} arena open air",
    "{} festival gratuito",
    "{} ingresso libero",
    "{} concerti gratuiti",
    "{} musica gratis",
    "{} concerto gratuito",
    "{} free concert",
    "{} free festival",
    "{} piazza concerti",
    "{} summer festival",
    "{} winter festival",
    "{} capodanno in piazza",
    "{} notte bianca musica",
    "{} musica in piazza",
    "{} banda in piazza",
    "{} processione musicale",
    "{} tarantella",
    "{} pizzica",
    "{} tarantismo",
    "{} musica popolare",
    "{} folk music",
    "{} musica tradizionale",
    "{} strumenti tradizionali",
    "{} liutai famosi",
    "{} fabbricazione strumenti",
    "{} conservatorio",
    "{} scuola musica",
    "{} lezioni musica",
    "{} lezioni chitarra",
    "{} lezioni pianoforte",
    "{} lezioni violino",
    "{} lezioni canto",
    "{} sala prove",
    "{} studio di registrazione",
    "{} recording studio",
    "{} produzione musicale",
    "{} dj",
    "{} dj set",
    "{} dj resident",
    "{} club dj",
    "{} musica elettronica",
    "{} house music",
    "{} techno club",
    "{} underground",
    "{} after party",
    "{} after hours",
    "{} sunrise party",
    "{} beach party musica",
    "{} boat party",
    "{} party in barca",
    "{} crociera festa",
    "{} gala",
    "{} evento gala",
    "{} charity event",
    "{} asta beneficenza",
    "{} raccolta fondi",
    "{} eventi beneficenza",
    "{} npo",
    "{} ong locale",
    "{} onlus",
    "{} terzo settore",
    "{} welfare",
    "{} assistenza sociale",
    "{} servizi sociali",
    "{} casa rifugio",
    "{} centro accoglienza",
    "{} mensa poveri",
    "{} banco alimentare",
    "{} food bank",
    "{} emporio solidale",
    "{} emporio della solidarieta",
    "{} dono cibo",
    "{} cucina comunitaria",
    "{} communal kitchen",
    "{} food sharing",
    "{} too good to go",
    "{} sprecato meno",
    "{} antispreco",
    "{} lotta spreco alimentare",
    "{} surplus alimentare",
    "{} donazione cibo",
    "{} raccolte alimentari",
    "{} raccolta abbigliamento",
    "{} centri raccolta",
    "{} centri di riuso",
    "{} riuso creativo",
    "{} upcycling",
    "{} diy",
    "{} fai da te",
    "{} laboratorio fai da te",
    "{} materiali riciclati",
    "{} arte riciclata",
    "{} trash art",
    "{} eco art",
    "{} murales ecologici",
    "{} giardini verticali",
    "{} verde verticale",
    "{} tetti verdi",
    "{} orti urbani",
    "{} orto condiviso",
    "{} community garden",
    "{} giardino comunitario",
    "{} fattoria urbana",
    "{} urban farming",
    "{} apicoltura urbana",
    "{} api in citta",
    "{} miele urbano",
    "{} alveare",
    "{} compostaggio",
    "{} compost urbano",
    "{} energia solare",
    "{} pannelli fotovoltaici",
    "{} comunita energetica",
    "{} cooperative",
    "{} cooperativa locale",
    "{} mutualismo",
    "{} economia solidale",
    "{} commercio equo",
    "{} fair trade",
    "{} negozio equosolidale",
    "{} bottega equosolidale",
    "{} prodotti artigianali locali",
    "prodotti made in {}",
    "{} produzione locale",
    "{} marchio locale",
    "{} dop igp",
    "{} denominazione origine",
    "{} indicazione geografica",
    "{} patrimonio gastronomico",
    "cucina tipica di {}",
    "ricetta tradizionale di {}",
]
